### ISSUE TITLE
FAE settings are not saved successfully on the backend server. There are always missed settings

### ISSUE THREAD

**Issue by ustunsoz** [facebookincubator/Facebook-For-OpenCart#100]
Trying yo install Facebook ads extension more than 100 times and always getting same error on opencart side. 

> 2019-02-09 8:59:26 - Updating FAE settings - facebook_dia_setting_id
2019-02-09 8:59:26 - Updating FAE settings - facebook_pixel_id,facebook_pixel_use_pii
2019-02-09 8:59:26 - Complete - Updating FAE settings
2019-02-09 8:59:26 - Complete - Updating FAE settings
2019-02-09 9:00:17 - Updating FAE settings - facebook_page_id,facebook_messenger_activated,facebook_jssdk_version
2019-02-09 9:00:17 - Complete - Updating FAE settings
2019-02-09 9:01:15 - Failure - no catalog, page or access token, dashboard module
2019-02-09 9:04:31 - Get Sample product feed
2019-02-09 9:04:33 - Complete - Get Sample product feed
2019-02-09 9:04:37 - Failure - no catalog, page or access token, get initial product sync status

See error screen as: [https://getirgel.com/screen.JPG](url)

**Comment by shue249** [comment]
@ustunsoz Thank you for the feedback. May I understand what is your web store URL?

**Comment by shue249** [comment]
Possible duplicate as https://github.com/facebookincubator/Facebook-For-OpenCart/issues/91

**Comment by ustunsoz** [comment]
> @ustunsoz Thank you for the feedback. May I understand what is your web store URL?

getirgel.com

**Comment by ustunsoz** [comment]
![screen1](https://user-images.githubusercontent.com/33930051/52523148-390baf00-2c9f-11e9-8ce6-1032ebff8c31.JPG)

it is not sam issue as #91

**Comment by ustunsoz** [comment]
During Facebook extension setup process, it is creating a catalog under assets > catalogs.
But when it receives error, it is deleting catalog and failing.

I am trying manually creating a new catalog and assigning all necessary permission. also deleting such catalog during setup process

**Comment by ustunsoz** [comment]
Setup process ending with below message 
![image](https://user-images.githubusercontent.com/33930051/52523513-301cdc80-2ca3-11e9-84e1-d4f42764856b.png)

**Comment by shue249** [comment]
@ustunsoz Thank you for the feedback. Can I check on 3 things for you.

1. Can you capture again a latest screenshot of Facebook Ads Extension module and share here again.

2. Can you check if you have disabled the theme cache for OpenCart 3? We found that there are no pixels added to your website.
![image](https://user-images.githubusercontent.com/11957585/52608973-9cbbf500-2eb6-11e9-8fcf-321769e01dac.png)

3. Are you using any VPN for your internet connection?

**Comment by ustunsoz** [comment]
1. I have deleted the settings and reprocess the module but this time it is not finished with success:
![image](https://user-images.githubusercontent.com/33930051/52632569-fdf1c180-2ed2-11e9-84a3-491d169ea142.png)
![image](https://user-images.githubusercontent.com/33930051/52632608-15c94580-2ed3-11e9-9f39-87c78aea7be0.png)

2. The heme cache was on, according to your instruction I have disabled before the process
3. I am not using any VPN connection

**Comment by ustunsoz** [comment]
I am selecting the pixel properly during setup, but it is not ending with success
![image](https://user-images.githubusercontent.com/33930051/52633190-b1a78100-2ed4-11e9-867f-3197749f77ef.png)

**Comment by ustunsoz** [comment]
The latest log file recorded as follow:
2019-02-12 11:49:13 - Updating FAE settings - facebook_page_id,facebook_page_token
2019-02-12 11:49:13 - Complete - Updating FAE settings
2019-02-12 11:49:16 - Sync all products using feed
2019-02-12 11:49:16 - Failure - no catalog, page or access token, sync all products using feed
2019-02-12 11:50:12 - Deleting FAE settings
2019-02-12 11:50:12 - Complete - Deleting FAE settings
2019-02-12 11:50:14 - Clear all Facebook products
2019-02-12 11:50:14 - Complete - Clear all Facebook products

**Comment by sirericg** [comment]
I am experiencing the same issue. Did you find a solution.

**Comment by shue249** [comment]
@ustunsoz We require more information from you in order for us to continue to investigate further. Can you reach to us at ads_extension_opencart@fb.com so that we can reach to you privately?

**Comment by shue249** [comment]
@sirericg We see that you have created a separate ticket. Let us follow up from there. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/104

**Comment by shue249** [comment]
@ustunsoz Will you also be able to provide us your webstore URL?

**Comment by shue249** [comment]
@ustunsoz We have taken this offline and you have resolved this issue by re-installing your OpenCart website. We will be closing out this issue.
