### ISSUE TITLE
facebook module not automaticaly synced my product to my facebook catalog /shop

### ISSUE THREAD

**Issue by robteeshirtguy** [facebookincubator/Facebook-For-OpenCart#101]
facebook module not automatically synced my product to my facebook catalogue/shop my site is opencart 2.3.0.2 journal 3 themes new them
faceook module Plugin Version: 2.1.3
the facebook module does automatically sync my product when i first installed it but about 1 week after it been installed it does update the catalogue/shop on facebook
should i try unstalling the module from scratch again ??

**Comment by shue249** [comment]
@robteeshirtguy Thank you for your feedback. There are 2 things I like to understand.

1. Can you share how are you making changes to your product on OpenCart (adding new products, editing existing products and deleting products)? Are you using OpenCart's default product management module or a 3rd party extension to manage products?

2. Will you be able do the below test to verify if the product integration is working properly on your OpenCart site?
a. Create a new product on OpenCart. Check if this product is also created on Facebook catalog.
![image](https://user-images.githubusercontent.com/11957585/52607835-b3f8e380-2eb2-11e9-9dd4-0e6e834e2a5f.png)

b. Make some edits to that new product created, eg changing the description or price. Check if the changes is also reflected on Facebook catalog (you will need to refresh the Facebook catalog page).
![image](https://user-images.githubusercontent.com/11957585/52607909-fe7a6000-2eb2-11e9-97d8-2e3acb1d25f5.png)

c. Delete away that new product. Check if the product has been removed from Facebook catalog (you will need to refresh the Facebook catalog page and search for the product).
![image](https://user-images.githubusercontent.com/11957585/52607961-40a3a180-2eb3-11e9-8b29-f1a43ac7ed99.png)

d. Check the Facebook Ads Extension log file. Verify that the tests we did was recorded as success on the log file.
![image](https://user-images.githubusercontent.com/11957585/52608021-8f513b80-2eb3-11e9-9113-90314142b779.png)

**Comment by robteeshirtguy** [comment]
here what my server tech are saying as i tryed that and still having problems 
ooking into this whilst it's having this problem, it seems that the website is accepting requests but it's holding open the database query along with the php request for the user and simply not outputting any data for the user. This seems like it's going to be a problem with the facebook extension with the way it's pulling and pushing the data

**Comment by robteeshirtguy** [comment]
when i click to resynic site i finding my server Of Processes
147 / 150 (98%)

**Comment by shue249** [comment]
@robteeshirtguy We have released a new version of the plugin - 2.1.10. We greatly improved the performance of the Resync products feature in Facebook Business Extension module. You can use this function to re-sync your products from Opencart to facebook catalog. The catalog will remain the same.

We will be closing out the ticket, feel free to reach to us if you have any further questions.
