### ISSUE TITLE
[OC 2.3.0.2] Extension does not load

### ISSUE THREAD

**Issue by am786** [facebookincubator/Facebook-For-OpenCart#102]
After installing Facebook and going to the module, it does not load. Receiving an error. https://prnt.sc/mjtdov

**Comment by shue249** [comment]
@am786 Thank you for your feedback. Can you look at this post and see if the solution helps you - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/77

**Comment by shue249** [comment]
@am786 We will proceed to close off this ticket first, feel free to reach to us if you have any further questions.
