### ISSUE TITLE
Https links are malicious 

### ISSUE THREAD

**Issue by prosenjeet123** [facebookincubator/Facebook-For-OpenCart#103]
It was working fine and i was doing advertising as well but suddenly it stopped working and started throwing errors in catalog , attaching screenshot of the errors and help me to sort this out.
https://prnt.sc/mk1fh5
https://prnt.sc/mk1fvc
https://prnt.sc/mk1g7f

**Comment by shue249** [comment]
@prosenjeet123 Thank you for the feedback. Currently your website URL is marked as malicious by Facebook. You can reach to the Facebook team at https://www.facebook.com/help/contact/571927962827151 and share with them context on your website and request for them to review your website URL again.

We will close off this issue for now, but pls feel free to reach to us if you have any further questions.
