### ISSUE TITLE
Only worked on first time setup! 

### ISSUE THREAD

**Issue by sameersb** [facebookincubator/Facebook-For-OpenCart#105]
After installing and setting up facebook ads extension, it automatically created the catalog of all the products properly. But then onwards, it did not resynced the products automatically (We update products with export/import extension). If I assume it does not resync when products updated with export/import extension, it should at-least import and update the products again when I click "Fetch Now" button manually. But on clicking "Fetch Now" button, it never update the products and the worst thing is that, my store get completely hanged and for hours I can not do anything with my store down for hours (I cant even access admin area). Then I have to deactivate all my Facebook Ads for hours. Please guide me how I can resync all the products in one-go without store downtime as it worked first time. I can daily once resync all the products manually. 
Thanks in advance!

**Comment by shue249** [comment]
@sameersb Thank you for the feedback. Our plugin does not support integration with 3rd party product management modules, and most likely that is why the product changes from the export/import extension did not sync to Facebook catalog. 

Our plugin integrates with the OpenCart default product management module. For more details you can check on this post https://github.com/facebookincubator/Facebook-For-OpenCart/issues/101

We are looking into enhancing the plugin to better support on product updates. We will keep you informed once we have any updates.

**Comment by sameersb** [comment]
Thanks for the reply.
But there is one more important issue in my comment. So I am repeating that part of the comment.
On clicking "Fetch Now" button, it never update the products and the worst thing is that, my store get completely hanged and for hours I can not do anything with my store down for hours (I cant even access admin area). Then I have to deactivate all my Facebook Ads for hours. Please guide me how I can resync all the products in one-go without store downtime as it worked first time. I can daily once resync all the products manually.

**Comment by shue249** [comment]
@sameersb Thanks for the feedback and apologies for missing out on the "Fetch Now" button. Can you provide us a screenshots of which is the Fetch Now button that you are referring to.

**Comment by sameersb** [comment]
![facebookadsextension](https://user-images.githubusercontent.com/40753234/52898756-c1da9b80-3207-11e9-81c2-c2372dda8c5d.png)
The screenshot is attached.... This window opens on clicking "Manage Settings" button

**Comment by sameersb** [comment]
Finally it worked with "Resync Products to Facebook" button. Thanks for your support.
