### ISSUE TITLE
Purchase pixel event not fired with guest checkout

### ISSUE THREAD

**Issue by sameersb** [facebookincubator/Facebook-For-OpenCart#107]
Purchase pixel event is fired properly when customer registers and makes a purchase. But it does not fire purchase pixel event if any customer makes a purchase with "Guest Checkout" i.e. without registering.

**Comment by shue249** [comment]
@sameersb Thank you for your feedback. 

Can you share with us your webstore URL?

**Comment by shue249** [comment]
@sameersb We have tested on our sites and the Purchase pixel is fired for "Guest Checkout". 

Can I understand if you are using any 3rd party extensions for checkout.

![image](https://user-images.githubusercontent.com/11957585/53280354-0f00c500-3754-11e9-991b-e3a399dafd5e.png)

**Comment by shue249** [comment]
@sameersb Like to follow up on this. Are you still having problems with the guest checkout on your webstore? Are you using any 3rd party extensions?

**Comment by shue249** [comment]
@sameersb We will be closing out this ticket, feel free to reach to us if you have any further questions.
