### ISSUE TITLE
facebook pixel in opencart

### ISSUE THREAD

**Issue by wichystar** [facebookincubator/Facebook-For-OpenCart#111]
Hi I install facebook ads extension and  say this  

There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.

my version of opencart  is Version 3.0.3.1

my site is   http://www.ofertas.coolwatches.website/

**Comment by shue249** [comment]
@wichystar Thank you for your feedback. Can we understand how many products do you have on your webstore?

We will like to also inform you that we are still in the progress of testing the compatibility of our plugin with version 3.0.3.1.

**Comment by shue249** [comment]
@wichystar We have released a new version of the plugin, 2.1.5, which you can obtain from OpenCart marketplace or our github. https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.5

We will be closing out this ticket, pls feel free to reach to us if you have any further questions
