### ISSUE TITLE
Messenger plugin - it is not displayed on website

### ISSUE THREAD

**Issue by HelgiSikoRa** [facebookincubator/Facebook-For-OpenCart#112]
I've just installed module. Pixel and product sinc working well but i faced issue with messenger plugin - it is not displayed on website. I enabled plugin in this module and also tried placing the generated code on business page after the opening <body> tag but no one case doesn't work. 
website: sweater.in.ua
CMS version 2.3.0.2

**Comment by shue249** [comment]
@HelgiSikoRa 
We have released a latest version of the plugin, v2.1.4 and can be downloaded from OpenCart marketplace or our github. The new version will resolve your issue with the Messenger chat plugin.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.4

We will close out this ticket for now, but pls do reach to us if you still have any further questions or issues.
