### ISSUE TITLE
Rights problem? 

### ISSUE THREAD

**Issue by zigi00x** [facebookincubator/Facebook-For-OpenCart#114]
Hello, i have a problem with the rights when installing the fb module everything is going to be fine, then I click on facebook dashboardwill list this error ↓, the privileges I have all the files set at 770 uninstall install did not help, is there any other solution? My e-shop is  i have renamed admin folder. oc version 3.0.2.0 error log is empty

Facebook Ads Extension
There are problems with the installation of the Facebook Ads Extension.

We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders.

Give read+write+execute permissions to the admin, catalog and system folders and their child folders on your OpenCart web server. Our plugin will need these permissions to copy over some new files to your web server.

**Comment by zigi00x** [comment]
![vystrizek](https://user-images.githubusercontent.com/1354349/53497324-392feb00-3aa4-11e9-8ba0-fee9c2c0c71c.PNG)
![vystrizek1](https://user-images.githubusercontent.com/1354349/53497333-3c2adb80-3aa4-11e9-847d-a099d61707bb.PNG)

**Comment by shue249** [comment]
@zigi00x Thanks for the feedback. Here are some suggestions.
1. Can you check the folder permissions for the OpenCart root folder (public_html), as well as the admin, catalog and system folders. What are the folder permissions? 
2. Can you also try to give the folders 775 permission
3. We have a similar issue reported by other user here - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/60

**Comment by zigi00x** [comment]
Hi, i try it but nothing work, I can give you FTp access data and we can look at it together.

**Comment by zigi00x** [comment]
![vystrizek2](https://user-images.githubusercontent.com/1354349/53563338-0c3b1100-3b54-11e9-86db-85441b856779.PNG)
![vystrizek](https://user-images.githubusercontent.com/1354349/53563332-034a3f80-3b54-11e9-9104-eda9f1dc2495.PNG)

**Comment by shue249** [comment]
@zigi00x We have 2 follow up suggestions.
1. Unzip the plugin file. From the unzipped folder copy the contents of the admin, catalog and system folders into your OpenCart web folder.

2. Check if the files that are copied over have execute options.

**Comment by zigi00x** [comment]
I got the problem by reinstalling the opencart..

**Comment by shue249** [comment]
@zigi00x Thank you for the feedback. Can I understand that you have solved the problem and the plugin is now working properly for you.

**Comment by zigi00x** [comment]
Yes the problem has been solved and the plugin works fantastically :)

**Comment by shue249** [comment]
@zigi00x Great to know that the plugin works for you. Feel free to reach to us if you have any further questions. We will be closing out this issue.
