### ISSUE TITLE
Facebook pixel is not firing

### ISSUE THREAD

**Issue by SergejsRo** [facebookincubator/Facebook-For-OpenCart#115]
Hi,

After installing new version of FB for opencart, pixel is not firing anywhere on site.
However, product are updated to FB catalogue.
Please help find the solution.
Opencart version 2.2.0.0
site: www.vaveritesgiftshop.eu
www.voverytesbutkelis.lt uses old version, and there pixel fires, but seems it not working properly.

**Comment by nichinu** [comment]
Same with me... the last purchase event was around 10 days ago. So may be it happened after last update. I am using opencart 3.0.2 and Journal 3 theme.

**Comment by SergejsRo** [comment]
Tried to switch different themes and default theme, all is the same.

**Comment by nichinu** [comment]
yeah.. it was working fine before the last update...

**Comment by nichinu** [comment]
pixel is only firing for "view content" and "pageview"

**Comment by shue249** [comment]
@SergejsRo Thank you for your feedback. We have a few questions.
1. What is the plugin version?
2. Can you share the log file from Facebook Ads Extension?
![image](https://user-images.githubusercontent.com/11957585/54079456-be729580-4317-11e9-9a3d-c4f6dd4a6e79.png)


To provide more context. We find that the pixel code is correctly injected on your website by the plugin, but there is no pixel id attached. We want to verify if the Facebook Ads Extension settings is correct.

**Comment by shue249** [comment]
@nichinu Can you share your website, plugin version number and the log file?

**Comment by nichinu** [comment]
www.ComicSense.xyz, i have the latest plugin 2.1.5 and have attached the log file.
I will also try the older plugin as suggested by you in the other thread and let you know.
[ComicSense.xyz_2019-03-10_04-29-54_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2949063/ComicSense.xyz_2019-03-10_04-29-54_facebook_ads_extension.log)

**Comment by nichinu** [comment]
After reinstalling the earlier version 2.1.3 its working properly. all the events are firing now.

**Comment by SergejsRo** [comment]
Now I installed again 2.1.5 version and no fires on www.vaveritesgiftshop.eu
[Vaverites Gift Shop_2019-03-10_10-31-39_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2949224/Vaverites.Gift.Shop_2019-03-10_10-31-39_facebook_ads_extension.log)

Same situation is with www.voverytesbutikelis.lt just now there is older plugin version 2.1.2

**Comment by SergejsRo** [comment]
@shue249  At www.voverytesbutikelis.lt it fires only on main page and checkout/success with plugin version 2.1.2

**Comment by shue249** [comment]
@nichinu Your case of pixel not firing may be different from @SergejsRo . Can we ask for you to create a separate ticket so we follow up accordingly.

**Comment by nichinu** [comment]
Sure

**Comment by shue249** [comment]
@SergejsRo Are you using any SEO plugin?

**Comment by SergejsRo** [comment]
@shue249 no, I am using only default opencart seo urls

**Comment by Emwestside** [comment]
@shue249 kindly assist pixels are also not firing. Thanks

**Comment by shue249** [comment]
@Emwestside As you have created a separate ticket https://github.com/facebookincubator/Facebook-For-OpenCart/issues/120, lets follow up your issue there instead of diluting this thread.

**Comment by Emwestside** [comment]
Ok. Thanks

**Comment by shue249** [comment]
@SergejsRo Can you try to install back the earlier version of the plugin 2.1.3 and see if the pixels are able to be fired.

https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3

**Comment by SergejsRo** [comment]
I tried install it previously, pixels work only on main page, success, 
special.
NOT in categories or product pages.

**Comment by SergejsRo** [comment]
@shue249 any info?

**Comment by SergejsRo** [comment]
@shue249 with version 2.1.5 in admin panel I am getting message: The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token. 
but there is no "update token" inside.
And on extension i get "Bad request"

**Comment by shue249** [comment]
@SergejsRo We have seen this from another user but we are unable to reproduce this on our dev environment - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/122. 

Will you be able to check on your webserver error log files and share any insights with us?

**Comment by SergejsRo** [comment]
@shue249 Can you tell me, how to disable pixel on my site, but leave working product import to FB catalog in this extension? As it only tries to load without pixel ID.

**Comment by shue249** [comment]
@SergejsRo Our plugin bundles the pixel and catalog sync together.

There are 2 issues that are faced by you
1. Pixel not firing correctly - we are still working on this to understand the root cause.

2. Bad request faced - are you still facing this problem?

**Comment by SergejsRo** [comment]
At the present I use another extension.
With your extension all is the same.

**Comment by shue249** [comment]
@SergejsRo We think we have found the root of the problem. Will you be able to share a file with us so that we can double confirm our hypothesis. The file is /system/engine/front.php on your webserver.

![image](https://user-images.githubusercontent.com/11957585/55445157-bac8dc00-556e-11e9-8828-36e85ecd5890.png)

**Comment by SergejsRo** [comment]
Hi,

here is the file.

**Comment by shue249** [comment]
@SergejsRo I am unable to see the file. Can you try to attach the file to here again?

**Comment by SergejsRo** [comment]
@shue249 Seems it was not attached from email.
Here again.

[front.php.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3039482/front.php.zip)

**Comment by SergejsRo** [comment]
@shue249 Any news?

**Comment by shue249** [comment]
@SergejsRo Thanks for the file. This is what we have suspected. I believe this file is changed on your side by the Journal plugin and it differs from the original OpenCart file, resulting in some incompatibilty  issues to detect the location to insert in the pixel code.

We will be working on a fix and to make it more robust to be able to handle more of such edge cases. We will keep you posted as soon as the new version is ready

**Comment by SergejsRo** [comment]
@shue249 Ok, waiting for new version

**Comment by SergejsRo** [comment]
@shue249 Tried to install older extension version, 2.0.3, it shows "Bad Request", but in the frontend I see pixel fires on addToCart, Purchase, PageView

**Comment by SergejsRo** [comment]
@shue249 can you tell, when will be new release with fix?

**Comment by shue249** [comment]
@SergejsRo We are targeting to roll out the new release within these 2 weeks.

**Comment by shue249** [comment]
@SergejsRo , we have just released a version 2.1.6 which will we hope to solve the pixel firing issue on your system.

Can you upgrade the plugin to the latest version and see if all the pages are now firing pixel, eg product details page, product category, shopping cart, check out and payment. Pls let us know the status on your website.

**Comment by SergejsRo** [comment]
@shue Thank you for info about new release.
Seems pixel fires everywhere: addtocart, category, pageview, purchase, viewcontent, search
Only not fires on checkout "initiatecheckout", but it is probably as our checkout path is onepagecheckout/checkout
Where can I modify it to make work?

Also I see error of catalog sync, however, new catalog has been created in FB business.
Adding print screen and file from system (/admin/controller/extension/facebookadsextension.php) as you asked at another issue.
![catalog sync](https://user-images.githubusercontent.com/48356144/56354787-51d39c00-61dd-11e9-8631-dcb4781f418b.png)
[facebookadsextension.php.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3093927/facebookadsextension.php.zip)

**Comment by shue249** [comment]
@SergejsRo Thank you for the feedback on the catalog sync error. We are working to resolve this issue now. Feel free to leave a comment on https://github.com/facebookincubator/Facebook-For-OpenCart/issues/144 so that we can notice you when the issue is solved.

As for the checkout path, this is the place where you can make the changes https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L147

However, I like to caution on 2 things
1. As our plugin is built based on the default opencart codes, it is highly recommended for you to test out if it is compatible with onecheckout.
2. When you upgrade to a new version subsequently, you will need to make those changes again on your webserver.

We will close off this ticket for now, but feel free to reach to us if you have any questions.
