### ISSUE TITLE
Rename admin folder

### ISSUE THREAD

**Issue by zigi00x** [facebookincubator/Facebook-For-OpenCart#117]
Hello i renamed admin folder and get some errors, so extension not work properly, where i find settings to change way to the new renamed admin folder?? Sorry for my english...

**Comment by shue249** [comment]
@zigi00x We have some guidelines on how to do this in our install_guide. You may want to refer here https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#pre-requisites-prior-to-installing-the-plugin

**Comment by shue249** [comment]
@zigi00x We will close out this ticket, feel free to reach to us if you have any further questions.
