### ISSUE TITLE
facebook ads extension error opencart 3.0.2.0

### ISSUE THREAD

**Issue by lcfigo** [facebookincubator/Facebook-For-OpenCart#119]
Warning: Use of undefined constant INITIAL_PRODUCT_SYNC_EXCEPTION_MESSAGE - assumed 'INITIAL_PRODUCT_SYNC_EXCEPTION_MESSAGE' (this will throw an Error in a future version of PHP) in /home/kog89pdba7qu/public_html/admin/controller/extension/facebookproducttrait.php on line 219

facebooks ads extension works well but always show this error in the panel admin.
more than 18000 products, can any one help me？

**Comment by shue249** [comment]
@lcfigo We have a latest version of the plugin, v2.1.5, which fixes this problem. Can you remove and install this latest version and see if it helps you to solve the problem. https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.5

Also, we suspect the catalog sync may not be completed successfully. In this case, can you delete away the existing Facebook Ads Extension settings and redo the setup again.
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md

**Comment by shue249** [comment]
@lcfigo We will close off this ticket, but pls feel free to create another ticket if you have further questions.

**Comment by lcfigo** [comment]
> @lcfigo We will close off this ticket, but pls feel free to create another ticket if you have further questions.

Thx, If I update the new version, the data still exist？
