### ISSUE TITLE
Dynamic Value

### ISSUE THREAD

**Issue by ryanstacey** [facebookincubator/Facebook-For-OpenCart#121]
Does the extension get the dynamic value of the products / transactions etc?

**Comment by shue249** [comment]
@ryanstacey Yes, we are pulling the value of the products and transactions and putting them on the pixel firing. If you install pixelhelper, you can inspect the parameters of the pixel fired.

![image](https://user-images.githubusercontent.com/11957585/54483959-a2cb3a00-4897-11e9-93a7-1305bc09334a.png)
![image](https://user-images.githubusercontent.com/11957585/54483970-de660400-4897-11e9-8175-c9632cf02e12.png)

We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.
