### ISSUE TITLE
Images are not showing in facebook page shop section

### ISSUE THREAD

**Issue by hammadrahman** [facebookincubator/Facebook-For-OpenCart#124]
Only 4-5 images are showing.
https://www.facebook.com/pg/AL-Modest-344372056403579/shop/?ref=page_internal

**Comment by shue249** [comment]
@hammadrahman We are checking on this now. Pls give us some time to work this out

**Comment by shue249** [comment]
@hammadrahman We have resolved the issue. The images are now loaded. We will close out this ticket, feel free to reach to us if you have any further questions/
