### ISSUE TITLE
After installing new version of FB for opencart, pixel is not firing anywhere on site

### ISSUE THREAD

**Issue by cccelil** [facebookincubator/Facebook-For-OpenCart#125]
After installing new version of FB for opencart, pixel is not firing anywhere on site.
However, products are updated to FB catalog.
Please help find the solution.
Opencart version 2.3.0.2
Now use other module for pıxel
When stop module that now use 
Not showed any pıxel

**Comment by shue249** [comment]
@cccelil Thank you for your feedback. Can you try to install back the earlier version 2.1.3 and see if the pixel is now firing correctly. 

https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3

**Comment by shue249** [comment]
@cccelil We think we have found the root of the problem. Will you be able to share a file with us so that we can double confirm our hypothesis. The file is /system/engine/front.php on your webserver.

![image](https://user-images.githubusercontent.com/11957585/55445157-bac8dc00-556e-11e9-8828-36e85ecd5890.png)

**Comment by shue249** [comment]
@cccelil  , we have just released a version 2.1.6 which will we hope to solve the pixel firing issue on your system.

Can you upgrade the plugin to the latest version and see if all the pages are now firing pixel, eg product details page, product category, shopping cart, check out and payment. Pls let us know the status on your website.

**Comment by shue249** [comment]
@cccelil.  We will be closing out this ticket. Feel free to reach to us if you have any further questions.
