### ISSUE TITLE
Ajax Best Checkout pixel not working 

### ISSUE THREAD

**Issue by Merih06** [facebookincubator/Facebook-For-OpenCart#126]
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=20736

pixel code does not work on payment page..

does not seem iniatecheckout...

**Comment by shue249** [comment]
@Merih06 Our plugin currently supports only the OpenCart default checkout and does not support 3rd party checkout plugins.

If you have development resources, we can suggest for you to modify our plugin codes to extend for this 3rd party checkout plugin. A starting point for you will be:
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L96

**Comment by shue249** [comment]
We will be closing out this issue, but feel free to reach to us if you have any other questions.
