### ISSUE TITLE
Facebook Catalog Feed Not working

### ISSUE THREAD

**Issue by DORMETA** [facebookincubator/Facebook-For-OpenCart#127]
Hi,

I've installed on OC 2.3.0.2 the latest version of v.2.1.5 and the only issue is the Facebook Catalog and Shop the feed uploaded just about 657 products out of almost 980. I tried to resynchronize and redo the steps in settings/setul panel but not working. 
Not having the full catalog creates problems for remarketing...

Best regards,

**Comment by DORMETA** [comment]
https://dormeta.ro

**Comment by shue249** [comment]
@DORMETA I am seeing 857 products on your catalog.

![image](https://user-images.githubusercontent.com/11957585/54960315-012ea180-4f97-11e9-8c9a-0e3f9b537817.png)

**Comment by DORMETA** [comment]
![issue](https://user-images.githubusercontent.com/48640019/55107104-24616a00-50d9-11e9-888d-fa902b2896d8.jpg)
There is a diference between products in shop and in catalog!

**Comment by shue249** [comment]
@DORMETA One thing you can try is to re-do the Facebook Ads Extension setup and see if the product count is correct. https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

**Comment by shue249** [comment]
@DORMETA Is the res-setup working for you?

**Comment by DORMETA** [comment]
Hi,
I am reticent about doing that. I believe it may affect my ads!
Regards,


Trimis din Yahoo Mail pe Android 
 
  Pe lun., apr. 8, 2019 la 19:05, shue249<notifications@github.com> a scris:   
@DORMETA Is the res-setup working for you?

**Comment by shue249** [comment]
@DORMETA We need to work on improving the resync feature for the plugin, so that you can re-update all the products gracefully. We will inform you soonest when we have any updates.

**Comment by shue249** [comment]
@DORMETA We have released a new version of the plugin - 2.1.10. We improved the performance of the Resync products feature in Facebook Business Extension module. You can use this function to re-sync your products from Opencart to facebook catalog. The catalog will remain the same.

We will be closing out the ticket, feel free to reach to us if you have any further questions.
