### ISSUE TITLE
Different Currencies at front and admin-sites

### ISSUE THREAD

**Issue by vlad3609** [facebookincubator/Facebook-For-OpenCart#129]
Dear Devs,

My store uses a currency fix module, that allows me to input prices in admin in USD and output them in a local currency (smith like this: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=19640). 

Hence, as in some modules happens, all the goods are output in USD values and codes & not in the local currency. 
Could you please advice me on where should I modify your code, so the goods would be imported in my local currency?

Best regards,
Vlad

**Comment by vlad3609** [comment]
Alright, I managed to change the currency code.

Now the module understands my real currency, however it does not multiply it:

Example: 
[admin side in the shop]
Product A costs 5$

[customer side in the shop]
It would cost 50 local bucks (exchange rate is 10 lb per dollar)

[Facebook store]
The product costs 5 local bucks, so there is no multiplication. 

Where should I look up for the multiplication?

**Comment by shue249** [comment]
@vlad3609 This is where you can key in the exchange rate (multiplication).
![image](https://user-images.githubusercontent.com/11957585/54750470-bd444100-4c12-11e9-8c57-d5a8fde00c33.png)

**Comment by vlad3609** [comment]
Thank you. It would work in a default version. In my case I had to make a custom request to DB and then multiply currency.

**Comment by shue249** [comment]
@vlad3609 Can I understand if this means that you have solved the currency problem?

**Comment by shue249** [comment]
@vlad3609 We will be closing this request, feel free to reach to us if you have further questions.
