### ISSUE TITLE
Fail to upload products to catalog

### ISSUE THREAD

**Issue by suresh4949** [facebookincubator/Facebook-For-OpenCart#13]
I can't see to add any products using pixel . it shows I have products in the inventory but when I re-sync, it won't do anything and I can't see my products . how do I go about this

**Comment by suresh4949** [comment]
I don't think you need my id for that

**Comment by suresh4949** [comment]
645756245760425

**Comment by suresh4949** [comment]
anyways this is the store id

**Comment by shue249** [comment]
Thank you for your feedback.

With the store id, we will be able to double check the catalog from our side to see if the products are intact. 

In any case, you will be able to also check this your self.
1. On the Facebook Ads Extension, click on Manage Settings. A popup dialog will appear
2. Click on Products and the link to see your products on Facebook
![image](https://user-images.githubusercontent.com/11957585/41807684-36e26274-7687-11e8-8c35-fba990b2ca17.png)

To better understand how we are syncing your store products to facebook, you can refer to this post on the OpenCart plugin marketplace. https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336#comment-input-box&member_token=UQgcBZRAIBSKQYbBY1fTl4Z373pFngvy

![image](https://user-images.githubusercontent.com/11957585/41807696-703ffd4c-7687-11e8-8333-58fe929ec05e.png)

**Comment by shue249** [comment]
I did a check on your store ID, seems that there is some problem with your initial product sync. Can you send to us a copy of your log file at ads_extension_opencart@fb.com, for us to better troubleshoot the problem? Also, how many products do you have on your store?

![image](https://user-images.githubusercontent.com/11957585/41807717-e2fed3c6-7687-11e8-8f0c-8df25f2c9652.png)

**Comment by suresh4949** [comment]
I have send it in

**Comment by shue249** [comment]
Thank you! We have received this. We are also seeing this same problem across 1 other merchant. We are still checking onto this problem to better understand this. Let us get back to you soonest once we identified the problem.

**Comment by suresh4949** [comment]
hi. any updates on this matters

**Comment by shue249** [comment]
Thank you for your feedback. We are still working on figuring out the problem. Pls bear with us while we work on this.

**Comment by suresh4949** [comment]
hi. Shue249 I got this error today. hope this might help 
2018-07-02 17:05:12 - PHP Warning:  require_once(C:/inetpub/wwwroot/opencart/catalog//controller/extension/facebookproducttrait.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\opencart\admin\controller\extension\facebookproduct.php on line 8
2018-07-02 17:05:29 - PHP Warning:  require_once(C:/inetpub/wwwroot/opencart/catalog//controller/extension/facebookproducttrait.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\opencart\admin\controller\extension\facebookproduct.php on line 8
2018-07-02 17:05:33 - PHP Warning:  require_once(C:/inetpub/wwwroot/opencart/catalog//controller/extension/facebookproducttrait.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\opencart\admin\controller\extension\facebookproduct.php on line 8

**Comment by shue249** [comment]
@suresh4949 Thank you for your feedback. We have a latest version of the plugin, version 2.0.2, which will fix the problem on the errors. Can you take a look to see if it helps you.

Also, I am wondering if you are still facing problem for your catalog sync?

**Comment by suresh4949** [comment]
Where can I get the latest version of the installer ?

**Comment by suresh4949** [comment]
the facebook ads module is no longer in opencart marketplace. so how can I download the latest version to fix this error and ensure me to be able to upload my data for ads

**Comment by shue249** [comment]
@suresh4949 Like to get back to you on this issue. Are you able to get the latest version v2.0.2 of our plugin and if the checkout problem is resolved for you?

**Comment by suresh4949** [comment]
hi.. no as your module screws up my website. I even got errors on success pages and payment system also all got issue . because of your module. best of yet. its your module and you guys should fix it. instead of asking people to join the forum and fix things. I don't mind paying $20 and above for a module that works and the support is able to fix the errors . but unfortunately . you guys aren't able to do any of that. I won't install that screwed up module . I have fixed my site after removing those files and etc . which cause a major crash . sorry to say that your module is a fail product. and your support is also a failed support. most developers which are new . give the module out for free  and yet the support is superb . and once they are good . they start to charge. and we don't mind paying for it. but they don't ask us to go thru like this . where you wait for the rainbow to come out during a sunny day . .. seriously I am not happy with your module at all.

**Comment by suresh4949** [comment]
im running a live site. and I can't effort for this miracle waits to happen. thats why I do not wish to get your module . thanks for nothing

**Comment by shue249** [comment]
@suresh4949 Thank you for your feedback. We sincerely want to help you and your business be successful and we are working hard on this. We understand the pain that you been going through and we really thank you for your patience with us. 

We understand that the checkout problem is due to a new version of our plugin which is upgraded to support for OpenCart v3. As there are many differences between OpenCart v2 and v3, we are working hard to ensure the support is as smooth as possible. 

At the same time, there was some administrative issues with our Opencart account, which causes our plugin to disappear on the marketplace and we are still resolving this with the Opencart admin now.

The plugin version 2.0.2 should be solving the earlier problem on your checkout page. If you are still getting errors, it could be due to some other conflicts with other plugins, as we have other merchants using our plugin and their checkout is successful.

If you are keen to still give the version 2.0.2 a try and feedback to us the exact error, we will support you as much as we can. I also understand your time and energy constraint if you do not wish to continue this.

**Comment by shue249** [comment]
Closing this as our plugin is not compatible with @suresh4949 system. We welcome reopening this issue and go deeper to work out the incompatible issues.
