### ISSUE TITLE
Messenger is not displayed

### ISSUE THREAD

**Issue by missbow** [facebookincubator/Facebook-For-OpenCart#130]
I've installed the Facebook Ads Extension. Pixel and product work as expected but I am facing an issue with the messenger plugin, it is not displayed on website. 

- I have enabled plugin (by following the instructions https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md), but it doesn't work.

- Latest Version of the extension is installed (https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336).

- website: missbow.gr
- OpenCart version 3.0.2.0
- Theme: Journal v 2.16.8

Thanks you.

**Comment by shue249** [comment]
@missbow Can I understand if the extension is still installed on your website?

**Comment by missbow** [comment]
Yes it is installed :) 
![image](https://user-images.githubusercontent.com/34458043/54978517-45c33880-4fa9-11e9-867e-04c7bb5c2b6d.png)

**Comment by shue249** [comment]
@missbow We looked at your website but found that the codes for firing pixel is not inserted. And it is the same case for the messenger chat plugin. 

![image](https://user-images.githubusercontent.com/11957585/55301214-0182dd00-546e-11e9-8ed3-ab6de5480733.png)
![image](https://user-images.githubusercontent.com/11957585/55301250-30994e80-546e-11e9-974a-e2853984b109.png)



3 things that you can check.
1. Can you disable the OpenCart theme cache - https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm

2. Can you click on Refresh modifications again. Then check if the pixel is firing and you can see the messenger chat plugin. https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw

3. If the above 2 still does not work, can you try to change the UI theme back to OpenCart's default UI theme and see if it works.

**Comment by shue249** [comment]
@missbow Like to check if the above solutions are working for you.

**Comment by missbow** [comment]
Hello Shue,

Where do I have to put this code?

Thank you :)

**Comment by shue249** [comment]
@missbow You do not need to put any code. What you need to do are these following 2 steps:
1. Can you disable the OpenCart theme cache - https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm

2. Can you click on Refresh modifications again. Then check if the pixel is firing and you can see the messenger chat plugin. https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw

**Comment by shue249** [comment]
@missbow We debugged with another user where their website is also not showing the messenger chat plugin. Can you take a look at this comment and see if you have made any edits to the footer template via the editor. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/167#issuecomment-493733468

**Comment by shue249** [comment]
@missbow We found that the messenger chat plugin is now working correctly on your website.

![image](https://user-images.githubusercontent.com/11957585/58013002-4bac4480-7b28-11e9-848b-f4c3dba09388.png)

However, the pixels are not fired on the website. Can I know what is the version of our plugin that you are using.

**Comment by shue249** [comment]
@missbow  We will be closing out this ticket. Feel free to reach to us if you have any further questions.

**Comment by cgonzalez-p** [comment]
@missbow entro a su web y no aparece la burbuja del chat de messenger ¿La quitaron? 
Εισάγω τον ιστότοπό σας και δεν εμφανίζεται η φούσκα συνομιλίας του αγγελιοφόρου. Καταργήθηκε;
