### ISSUE TITLE
Catalogs Product Website Links

### ISSUE THREAD

**Issue by ryanstacey** [facebookincubator/Facebook-For-OpenCart#131]
When the extension uploads the products from opencart it uses a generic product id link rather then pulling the seo url.
This creates an issue when analysing data in google analytics/facebook as now you not only have your seo urls but you have product id urls. So you dont get the correct data for a page all together.
I know you can edit each for the products links within facebook but this is an issue when you have a lot of products...I have 500.

Url facebook uses for catalog ads:
<img width="957" alt="Screenshot 2019-03-20 at 2 44 20 pm" src="https://user-images.githubusercontent.com/44474887/54693630-e1bef100-4b1e-11e9-88de-6e3bc0584d50.png">

Actual url of the product used throughout the website
<img width="1013" alt="Screenshot 2019-03-20 at 2 45 16 pm" src="https://user-images.githubusercontent.com/44474887/54693638-e388b480-4b1e-11e9-997d-1d0b6adf359e.png">

**Comment by shue249** [comment]
@ryanstacey We have evaluated the performance of generating the SEO URL and decided not to pursue with this feature as it will impose a performance degradation when doing the initial product sync.

We have described the details in this reply and also the action steps needed to make the changes yourself if you have development resources. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/51#issuecomment-467407263

We will close off this ticket as wontfix.
