### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by smart81bg** [facebookincubator/Facebook-For-OpenCart#133]
How can I control the output language>

**Comment by shue249** [comment]
@smart81bg Can you explain more on your use case. Are you referring to using multi languages in the product catalog?

**Comment by Henry17888** [comment]
My website was made in multi-language: Chinese and English, and English is the default language. When I check my shop on Facebook, the language is Chinese, how could I use English as my Facebook shop default language?
Thanks in advance

P.S the facebook shop: https://www.facebook.com/pg/AbohodIndustrialCOLTD/shop/?ref=page_internal

**Comment by shue249** [comment]
@Henry17888 Can you share with us screenshots of how you setup the products on your OpenCart server? Specifically, we like to see how did you configure the multi language for the products. You can share with us 1 product example.

**Comment by Henry17888** [comment]
@shue249 may I have your email? then I will send the screenshots to you. Thx

**Comment by shue249** [comment]
@Henry17888 Sure, you can reach to us at ads_extension_opencart@fb.com

**Comment by Henry17888** [comment]
Got it.

**Comment by miaosun** [comment]
Is there an update on this? I'm having the exact same problem.

**Comment by Henry17888** [comment]
I have submitted the screenshots yesterday. Once it solved, I will let you know.

**Comment by Henry17888** [comment]
@miaosun I solved this problem. 
Firstly, [Delete the existing settings for Facebook for OpenCart](https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL) 
Secondly, [Uninstall the plugin ](https://drive.google.com/open?id=12dX2wYTcE3Y7Wf-ZBD_6X4EAZU2L-8vp)
Thirdly, I deleted the local Chinese language in my web administration
Then, reinstall and set the plugin as the guide. You will find your facebook shop is in your default language.
Finally, reinstall your local language.

P.s above links are the official video guides

-----------------------------
While this still has a problem. You need to re-edit products descriptions. 
Just pray don't have so many products on the website now. :)
gl, hf

**Comment by miaosun** [comment]
Hi @Henry17888 , thank you for your information, but what you suggested seems to me a temporary workaround, not a proper solution. 

Can you try what happens if you create few new products and then sync them again to Facebook, will they still be in Chinese?

I also sent an email to @shue249 yesterday, let's hope a fix is coming soon :)

**Comment by miaosun** [comment]
@Henry17888, I made the test and after doing "Resync Products to Facebook", all the products we synced before with the language we want will be replaced with Chinese infos...

@shue249 can we have an ETA for the fix, please?

**Comment by shue249** [comment]
We are still looking into this. Pls give us some time to identify the problem and think of a solution. Will update this post soonest once we have any updates.

**Comment by Henry17888** [comment]
@miaosun, I uploaded a new product on my website yesterday, then I Resync products to Facebook. When I check the new product on Facebook shop, the language is the local Chinese language. So sad :(
@shue249 Take your time. Thanks for your kindly help on this issue.

**Comment by shue249** [comment]
@Henry17888 , @miaosun 
Our update is taking longer than expected. In the meantime, if you wish to control the language and have developer resources, you can consider making these 2 changes on the plugin file directly in your webserver. These are the 2 places to change.

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/model/extension/facebookproduct.php#L96

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/model/extension/facebookproduct.php#L205

The current behavior is that we are using the language from the default configuration to sync to Facebook. The change required is to replace and put in the exact id of the language that you wish to use (instead of that from the configuration).

**Comment by yao-tx** [comment]
Hi @Henry17888 @miaosun 

The extension should be taking your default language set in admin (Language option under System -> Settings -> 'Edit' for your store -> 'Local' tab, **NOT** the Administrative Language). If your default language is already set to English, the exported products should be in English. 

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336) or from [GitHub Latest Release](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/latest). 

We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow one of the following:
* Quick installation guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart)
* Detailed step-by-step guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
