### ISSUE TITLE
admin folder is changed

### ISSUE THREAD

**Issue by mohet786** [facebookincubator/Facebook-For-OpenCart#135]
I have followed all the steps in installing the extension, but always getting the same error:

"We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders."

I have given 777 permission to public_html folder already and the issue persists.

Waiting for some help on this, as i am stuck since last 3 days.

Regards,
Mohit

**Comment by shue249** [comment]
@mohet786 Can you try to give the permission recursively to all the child folders under public_html.

**Comment by mohet786** [comment]
Hello,

Thank you for your response. I have tried that already. But no luck. Is
there any other way?

By the way, I have changed the folder name of admin to something else. Will
that cause any issues ??

Regards,
Mohit

**Comment by shue249** [comment]
@mohet786 Yes, that is probably the cause of why the plugin fail to work, as we build the plugin based on the admin folder name.

Can you take a look at these instructions and make the changes on the plugin files.
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#pre-requisites-prior-to-installing-the-plugin

**Comment by duncanbbd** [comment]
we have the same problem,  the admin folder name is different,
we cannot get into admin to uninstall the plugin, what is best way to recover so we can try and install again.
thanks brian

Warning: require_once(/home/abc/public_html/adminxxx/../admin/controller/extension/facebookproducttrait.php): failed to open stream: No such file or directory in /home/abc/public_html/adminxx/controller/extension/facebookproduct.php on line 8

**Comment by shue249** [comment]
@duncanbbd Brian, I want to check if you are able to access your admin panel on OpenCart. If you are still able to access it, then all's good for now.

We are looking to see how we can simplify the installation for users who have renamed the admin folder. We will keep you updated soonest

**Comment by duncanbbd** [comment]
Hi

YES I got access to it by modifying the files you suggested.

I guess it would be good to determine the base admin folder somehow and 
use that.

On another topic, I'm always concerned when people tell users to set 
folder permissions to 777  (becuase I'm sure some people don't set back 
to correct permissions)

Is it not possible that you use an FTP script to upload files into the 
correct folder ?  (I have my own CMS) and I upload files to the specific 
folder using FTP  and they don't need to worry about folder/file permissions

thanks for getting back to me

Brian



___________________________________

e: brian@fife.co.uk
w: https://2mx.co.uk
w: https://eazy-site.co.uk - Content Management System
m: 0794 641 5312

**Comment by shue249** [comment]
@duncanbbd I am glad that you got it working.

Rather than 777, one way is to set as 775 or 755 permission for better security access.

We decided to go with OpenCart's default ocmod system because it is the most user friendly. There could have other users who are not savvy enough to use FTP scripts. Another alternative will be using vqmod approach, to copy and paste in the unzipped files into the webserver, and we are working on providing the vqmod solution now.

**Comment by mohet786** [comment]
Thank you for replying @shue249 I tried making changes in each file of the extension and replacing the original path of the installation with the one with the link to my renamed admin panel name, ie, current path says /admin/... and i replaced "admin" with the renamed name of my admin folder, but still no luck.

what can be the alternative now? Please suggest...

**Comment by mohet786** [comment]
Hello Brian, any luck ?

**Comment by yao-tx** [comment]
Hi @mohet786 

Hi @rod2k 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The latest version of the FBE plugin (version 4.0.0 and above) doesn't require additional configurations if you have a custom admin folder name as it utilises the default OpenCart Extension Installer feature to install the plugin. Unless you are manually uploading the files onto your web server to install the plugin, you shouldn't encounter any problems with custom admin folder names.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
