### ISSUE TITLE
Product Update Error (Access token invalid)

### ISSUE THREAD

**Issue by Merih06** [facebookincubator/Facebook-For-OpenCart#136]
2019-04-04 13:27:35 - Get Sample product feed
2019-04-04 13:27:35 - Complete - Get Sample product feed
2019-04-04 13:27:35 - Invalid access token when querying FB page
2019-04-04 13:27:35 - Error with getting the initial product sync status The Facebook access token is invalid. Please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.

**Comment by shue249** [comment]
@Merih06 Thank you for the feedback. Can you share with us a screenshot of how the Facebook Ads Extension module screen looks like from your OpenCart admin panel

**Comment by shue249** [comment]
@Merih06  We are putting a fix soon. In the meantime, can you follow this post to see if it works for you. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142#issuecomment-482908951

**Comment by shue249** [comment]
@Merih06, we have just released a version 2.1.6 which will solve the "error" or "Bad request" error message, allowing you to update the token and without the need to run any codes on the console. Please update to the latest version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.6

However, if you still encounter the "Invalid access token" even after updating the token, pls comment in this ticket https://github.com/facebookincubator/Facebook-For-OpenCart/issues/144 and we will follow up there.

Closing off this ticket for now.
