### ISSUE TITLE
Problems with installation (Access token invalid)

### ISSUE THREAD

**Issue by Anders1982** [facebookincubator/Facebook-For-OpenCart#137]
I've installed the Facebook Ads extension on my OpenCart store and everything works fine, except an error message. I use version 3.0.2.0. This error message appears on the admin front and the text "error" appears when I enter the Facebook Ads extension:

There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.

Best regards
Anders

**Comment by shue249** [comment]
@Anders1982 Thank you for the feedback. We are looking into this issue now. We will keep u updated soonest.

**Comment by shue249** [comment]
@Anders1982 Can you share with us a screenshot of the Facebook Ads Extension on your admin panel.

**Comment by shue249** [comment]
@Anders1982 We are putting a fix soon. In the meantime, can you follow this post to see if it works for you. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142#issuecomment-482908951

**Comment by shue249** [comment]
@Anders1982, we have just released a version 2.1.6 which will solve the "error" or "Bad request" error message, allowing you to update the token and without the need to run any codes on the console. Please update to the latest version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.6 

However, if you still encounter the "Invalid access token" even after updating the token, pls comment in this ticket https://github.com/facebookincubator/Facebook-For-OpenCart/issues/144 and we will follow up there.

Closing off this ticket for now.
