### ISSUE TITLE
Problem with catalogues

### ISSUE THREAD

**Issue by Shrimp1234** [facebookincubator/Facebook-For-OpenCart#138]
Hi there
Im having problem from the last 3 weeks, my catalogue in fb lost some of its features. This is the automated catalogue created via the "facebook ads extension". version 2.1.3.  My open cart vers is  2.3.0.2. Old catalogues created via spreadsheets are all ok, but it is pain in the ass. Attaching 2 files for preview

**Comment by shue249** [comment]
@Shrimp1234 Thank you for the feedback.
The features you mentioned were disabled intentionally for Facebook Ads Extension catalogs, as the plugin is be able to handle all the product syncs.

Can I understand what are the reasons you need these features for your Facebook Ads Extension catalog?

**Comment by Shrimp1234** [comment]
shue249, thanks for the reply. I need this so i can run dynamic ads without creating inner catalogues, with exact products. It saves a lot of time. You can easy control which products to be shown or not. For example i create dynmic ad with entire catalogue 1.1k products, i deactivate delivery on 700 so i can have active only 400. During promoting period for example 1 month i keep changing products, because some got out of stock and you dont need to promote them while they are not available, or some are already available. Activate delivery and deactivate delivery is a big time work saver

**Comment by shue249** [comment]
@Shrimp1234 To activate the products based on conditions, the recommended way to do it is via product sets. You can set in various filters to your product set to control the products to be shown.

https://www.facebook.com/business/help/620275848114281

**Comment by shue249** [comment]
@Shrimp1234 We will be closing out this ticket. Pls feel free to reach to us if you have any further questions.
