### ISSUE TITLE
cant remove fb ads plugin,told error,opencart 3.0.2.0

### ISSUE THREAD

**Issue by yingqingzhou** [facebookincubator/Facebook-For-OpenCart#139]
There was an error. It could be a temporary problem and we are working to solve it as soon as possible. Try again later.

**Comment by shue249** [comment]
@yingqingzhou Can you share with us a screenshot of how the problem looks like.

**Comment by yingqingzhou** [comment]
shue249 <notifications@github.com> 于 2019年4月10日周三 12:00写道：

**Comment by shue249** [comment]
@yingqingzhou Can you put the screenshot here as we cannot see the image from your previous reply.

**Comment by yingqingzhou** [comment]
*It was already resolved, thank you very much!*

shue249 <notifications@github.com> 于2019年4月16日周二 下午3:48写道：

**Comment by shue249** [comment]
Great, feel free to reach to us if you have any further questions.
