### ISSUE TITLE
Hello. Has the extension stopped working?

### ISSUE THREAD

**Issue by BarlPro** [facebookincubator/Facebook-For-OpenCart#143]
My log file
[Интернет-магазин_2019-04-13_17-58-22_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3076355/-._2019-04-13_17-58-22_facebook_ads_extension.log)

**Comment by shue249** [comment]
Duplicate issue, going to track this here https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142
