### ISSUE TITLE
My admin dashboard page doesn't open after installing v2.1.5

### ISSUE THREAD

**Issue by alengeere** [facebookincubator/Facebook-For-OpenCart#145]
Hi. I previously use old version but today i tried installing v2.1.5. First i uninstall old version, refresh extensions, upload ocmod.zip successfully, and refresh extensions again.

After that, my admin dashboard page gone. I can enter other pages from panel, extensions, layouts etc. but dashboard page doesn't work. i get "connection timeout" message from server after waiting.

When i delete cookieconsent.min.js or facebook_pixel.js file from catalog/view/javascript/facebook/ folder, my dashboard page start working. Also i get a warning message upside the page about facebook extension, it's normal.

I also tried to reinstall several times but it didn't helped.

Could you please help me about installing v2.1.5? What's the problem? I use opencart v 2.1.0.1

Thanks.

**Comment by shue249** [comment]
@alengeere Are you able to access your web server (eg apache) error log file and see if there's any error message logged there.

Can you also share with us a screenshot of the warning message.

This is weird as the admin dashboard does not access the cookieconsent.min.js or facebook_pixel.js files.

**Comment by alengeere** [comment]
When i had problems, facebook, instagram and whatsapp were working very slowly in Turkey. Later in the day, they started working properly, and my problem was spontaneously improved. Thank you for your quick reply. It works fine now.
