### ISSUE TITLE
after installed the newer version fb openccart 2.1.6 , getting an error on AD SETUP tab .

### ISSUE THREAD

**Issue by hassni1** [facebookincubator/Facebook-For-OpenCart#146]
Catalog Can't Be Synced
A system error is preventing your catalog from syncing. You can still get website visitors and track sales, and we'll notify you when your catalog is ready to sync.

**Comment by maxdmtrv** [comment]
I'm getting the same error after updating to version 2.1.6. I've tried deleting OCMOD and system caches but it didn't help.

I'm running the module on Opencart 2.3.

**Comment by shue249** [comment]
@hassni1 , @maxdmtrv We are looking into this issue now. To help with easier tracking, we will close off this ticket and consolidate the tracking on this https://github.com/facebookincubator/Facebook-For-OpenCart/issues/148
