### ISSUE TITLE
Products are not uploaded to catalog due to invalid access token

### ISSUE THREAD

**Issue by Elected0406** [facebookincubator/Facebook-For-OpenCart#147]
pixel identifier on the site and on facebook are not the same, can I register the identifier in the code of the plugin and set it to the site again
![pixel](https://user-images.githubusercontent.com/20260940/56297888-dec51980-6139-11e9-8afe-51c2f317f07c.png)

**Comment by shue249** [comment]
@Elected0406 What is your website URL?

**Comment by Elected0406** [comment]
@shue249 https://lavlis.com.ua

**Comment by shue249** [comment]
@Elected0406 We can see that your website is firing for the pixel id that ends with 2157. Is this what you want to achieve?

![image](https://user-images.githubusercontent.com/11957585/56329533-8c760e00-61b6-11e9-8fb5-d69cb7092457.png)

**Comment by Elected0406** [comment]
@shue249 I thought ID mismatch caused Catalog sync error but it still not working
![123](https://user-images.githubusercontent.com/20260940/56342309-4e7de780-61c0-11e9-86d4-24b60d1634a0.png)
[Lavlis_2019-04-18_09-25-44_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3093111/Lavlis_2019-04-18_09-25-44_facebook_ads_extension.log)

**Comment by shue249** [comment]
@Elected0406 We have fixed the message on the Catalog Cant's be Synced.

Are you still getting any errors on the Facebook Ads Extension module screen?

**Comment by shue249** [comment]
@Elected0406 We will be closing out this ticket. Please refer  to this post for more details. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/144#issuecomment-489399216
