### ISSUE TITLE
Catalog Can't Be Synced

### ISSUE THREAD

**Issue by zigi00x** [facebookincubator/Facebook-For-OpenCart#150]
Catalog Can't Be Synced
After update facebook extension i get this error A system error is preventing your catalog from syncing. You can still get website visitors and track sales, and we'll notify you when your catalog is ready to sync.

**Comment by itshaman** [comment]
![image](https://user-images.githubusercontent.com/16690535/56352994-17680000-61d9-11e9-8531-1b6d9c747c68.png)
Have a same troble. Update extension to 2.1.6

**Comment by hongyiu** [comment]
i have the same problem

**Comment by shue249** [comment]
Thanks to everyone for your feedback! We are looking into this issue now. For now, in order to streamline the error tracking, we will be consolidating all these cases into this thread https://github.com/facebookincubator/Facebook-For-OpenCart/issues/148, and we will be closing off this.
