### ISSUE TITLE
two pixels and duplicate conversion

### ISSUE THREAD

**Issue by anasnemer** [facebookincubator/Facebook-For-OpenCart#151]
Hi

thank you all for your efforts

Kindly help me with this issue

i have on my website two pixels and duplicate conversion as per below pic

i am trying to solve it by delete one pixel but i cant

i install the pixel by plugin 

![Annotation 2019-04-19 191903](https://user-images.githubusercontent.com/49791430/56433310-1e763780-62d9-11e9-93f7-97734d44993b.jpg)

**Comment by shue249** [comment]
@anasnemer We looked at your website. There is already a pixel code embedded in your website that you need to remove. You may need to see if you need to modify your opencart website codes manually or this is from a 3rd party plugin that you need to disable.

![image](https://user-images.githubusercontent.com/11957585/56454064-17553500-637e-11e9-9312-3146ab2d4895.png)

Unfortunately, we are unable to do anything from our end. We will be closing out this ticket, feel free to reach out if you have any further questions.
