### ISSUE TITLE
Special price on Products

### ISSUE THREAD

**Issue by JakubSVK** [facebookincubator/Facebook-For-OpenCart#154]
Hello, 
we have in Opencart 3.0.2.0 special price for wholesale customers. Not for default customers.

If we are using plugin, we have a wholesale price on Facebook store catalog.

It is possible to change or hide special price ? 

Thank you

**Comment by zigi00x** [comment]
site?

**Comment by JakubSVK** [comment]
https://www.project-f.sk

**Comment by shue249** [comment]
@JakubSVK 
1. Can you share more details on how do you setup the wholesale price for the customers. Any screenshots will be super helpful for us
2. Can you explain how do you expect the price to be like. We want to understand what is the mismatch/gap between your expectation and what the plugin is doing now.

This is based on my understanding, pls feel free to let me know if my understanding is wrong.
1. we do not have a customer segments, ie Facebook is unable to differentiate between a default customer and wholesale customer
2. the plugin is using the Opencart product special price as discounts which will be applied to all customers

If you wish to disable the special price to be using for all customers, you can change this line in the plugin file to be false on your webserver. Then, try to re-setup the Facebook Ads Extension settings again; by deleting away the existing settings and re-do the settings. Do take note that if you wish to do this, you need to make sure to amend the code for subsequent version upgrades of the plugin.

`$product_specials = false;`

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/v2.1.6/upload/system/library/facebookproductformatter.php#L186

**Comment by shue249** [comment]
Duplicate issue as https://github.com/facebookincubator/Facebook-For-OpenCart/issues/16

**Comment by normdouglas** [comment]
> @JakubSVK
> 
> 1. Can you share more details on how do you setup the wholesale price for the customers. Any screenshots will be super helpful for us
> 2. Can you explain how do you expect the price to be like. We want to understand what is the mismatch/gap between your expectation and what the plugin is doing now.
> 
> This is based on my understanding, pls feel free to let me know if my understanding is wrong.
> 
> 1. we do not have a customer segments, ie Facebook is unable to differentiate between a default customer and wholesale customer
> 2. the plugin is using the Opencart product special price as discounts which will be applied to all customers
> 
> If you wish to disable the special price to be using for all customers, you can change this line in the plugin file to be false on your webserver. Then, try to re-setup the Facebook Ads Extension settings again; by deleting away the existing settings and re-do the settings. Do take note that if you wish to do this, you need to make sure to amend the code for subsequent version upgrades of the plugin.
> 
> `$product_specials = false;`
> 
> https://github.com/facebookincubator/Facebook-For-OpenCart/blob/v2.1.6/upload/system/library/facebookproductformatter.php#L186

Can you please clarify this > "Then, try to re-setup the Facebook Ads Extension settings again; by deleting away the existing settings and re-do the settings"

**Comment by shue249** [comment]
@JakubSVK  We have released a latest 2.1.11 version of the plugin which provides you an option to choose to sync the special price as discount or to disable the syncing of special price.

If you like to sync for 1 special customer group id price for ALL the products, you can consider making the modifications directly on the plugin files on your webserver. The code pointer will be at - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/v2.1.11/upload/system/library/facebookproductformatter.php#L227

However, it will not be possible if you are looking to sync the entire customer group structure from OpenCart to Facebook, as Facebook does not have the structure of customer group.

Will be closing out this ticket. Feel free to reach to us if you have further questions.
