### ISSUE TITLE
facebook shopping trying to get it to work on multimerch marketplace

### ISSUE THREAD

**Issue by robteeshirtguy** [facebookincubator/Facebook-For-OpenCart#157]
hi know i need to hook a link up to multimerch marketplace seller product submit button but what link do link to it from the facebook module so it add the product to facebook shopping as at min the only time it add them is if i go in to opencart admin and click on a product in product and then click save

**Comment by shue249** [comment]
@robteeshirtguy Can you explain more on "multimerch marketplace seller". Is this a default feature of OpenCart or is this an additional 3rd party plugin?

Currently, our plugin is already creating and showing the products on facebook page shop and the link from facebook page shop is to your product details page on your store website

**Comment by robteeshirtguy** [comment]
yes it a 3rd party module https://multimerch.com/ why turn opencart 2 into a full marketplace (multiseller platform) all the product as still add to opencart product section but throw the database as far as i understand as the seller have there own sections on the site what i needing to know is how does the facebook module know when you add a product normaly in opencart is it a line of code on the save button if so what that line of code

**Comment by shue249** [comment]
@robteeshirtguy Thanks for the context. Here are the code modifications that we made to the default OpenCart module to handle product changes.

Adding new products:
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L205

Editing existing products:
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L240

Deleting existing products:
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L274

For the specific controller, this will be the file that you need to look at. Specifically.
Adding and editing products:
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L274

Deleting products:
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookproduct.php#L422

**Comment by shue249** [comment]
@robteeshirtguy We will be closing out this ticket, feel free to reach to us if you have any further questions.
