### ISSUE TITLE
Suggestion to improve on the access token by replacing with own token

### ISSUE THREAD

**Issue by adias** [facebookincubator/Facebook-For-OpenCart#161]
@shue249 you have a bug here, not fixed at latest version !

You are passing the wrong token, you are passing the opencart token instead of the facebook token.

admin/controller/extensions/facebookadsextension.php
line 303
line: 307

-------------------

Hello, 
i think i resolve the error...

admin/controller/extensions/facebookadsextension.php
line 303: 
: $this->session->data['token'];
to
: 'MY-TOKEN';

line: 307
return 'user_token=' . $this->getToken() . '&token=' . $this->getToken();
to
return 'user_token=' . $this->getToken() . '&token=MY-TOKEN';

The message error disappear and, i dont know but im thinkin its working now, 
im waiting ... the products sync...

![okok](https://user-images.githubusercontent.com/1707013/56614077-7c16c680-65ee-11e9-801b-02eba8a13c36.jpg)

_Originally posted by @adias in https://github.com/facebookincubator/Facebook-For-OpenCart/issues/144#issuecomment-485965474_

**Comment by shue249** [comment]
@adias Thank you for your suggestion.

The plugin is already taking care of generating a set of access token that you can use for the catalog sync. The code pointers are as follow:

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/view/javascript/facebook/dia.js#L175

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/view/javascript/facebook/dia.js#L72

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookadsextension.php#L310

We will be closing out this ticket. Let us know if you have any further questions.
