### ISSUE TITLE
Error when saving product Unsupported post request. Warning: Encountered problem updating product(s) to Facebook. Please retry again. Check the error log file for more details

### ISSUE THREAD

**Issue by dyslexicdrakness** [facebookincubator/Facebook-For-OpenCart#163]
These error suddenly started happening on all stores...

Running version of OC 2.3.0.2 and Facebook Ads Extension version 2.1.6

The log shows something like this:

Sync for product 155
2019-05-08 17:34:52 - Failure update product 155 / 2268647409861605 on Facebook {"message":"Unsupported post request.","type":"GraphMethodException","code":100,"fbtrace_id":"BqBxuNT1KJ7"}
2019-05-08 17:34:53 - {"success":true}
2019-05-08 17:34:53 - Complete - Sync for product 155
2019-05-08 17:37:18 - Get Sample product feed
2019-05-08 17:37:18 - Complete - Get Sample product feed
2019-05-08 17:49:34 - Sync for product 264
2019-05-08 17:49:35 - Failure update product 264 / 2035309749930779 on Facebook {"message":"Unsupported post request.","type":"GraphMethodException","code":100,"fbtrace_id":"Ho8D2uVA1Ot"}
2019-05-08 17:49:35 - {"success":true}
2019-05-08 17:49:35 - Complete - Sync for product 264

**Comment by shue249** [comment]
@dyslexicdrakness Let us take a look at the errors.

**Comment by dyslexicdrakness** [comment]
They are all production sites and last time I updated the extension I had to delete settings and reconfigure which needless to say caused a lot of issues for my clients who had campaigns running and had already organized the fb catalog into categories...

Do you think going from 2.1.6 to 2.1.8 will unsync the catalog?

I'm attaching the log file for one of the sites but I suppose they will all show similar behaviour.

![image](https://user-images.githubusercontent.com/7231700/57540800-cd22fc00-730a-11e9-822e-a741356c7c1b.png)

[Meat Shop_2019-05-10_15-57-44_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3167263/Meat.Shop_2019-05-10_15-57-44_facebook_ads_extension.log)

**Comment by shue249** [comment]
@dyslexicdrakness 

1. Updating the plugin to latest version does not require you to delete away the existing settings. The plugin update is only copying over the updated plugin files to your webserver. There is no need to re-do the Facebook Business extension setup again.

2. You can safely update the plugin from 2.0.3 to current 2.1.8

3. How are the products managed? Are your clients using the default Opencart product management module? Or are they using a 3rd party product management module?

**Comment by dyslexicdrakness** [comment]
1. cool

2. i'm on 2.3.0.2 version of opencart. The facebook extension is 2.1.6, do you still think the upgrade will fix it?

3. default

**Comment by shue249** [comment]
@dyslexicdrakness 

I want to follow up with you on this case. It is weird, but we are unable to identify the root cause of the errors from your clients based on the error messages.

1. Are you able to check on their log if those error messages are still occuring?
2. Are they getting any message saying that their access tokens are invalid

**Comment by dyslexicdrakness** [comment]
Hello!

I would like to report that this issue resolved itself somehow :S

cheers!

**Comment by Quickdealmagazine** [comment]
Good afternoon, I have opencards 2.3.0.2, there was a version of Facebook 2.0.1. Now I'm trying to update facebook from github to 3.0.1 and gives an error, I cleaned the cache, deleted the mod, and re-installed. Tell me please, what is the problem? initially when saving the product, I started to get an error - Warning: Encountered problem updating product (s) to Facebook. Please try again. Check the error log file for more details. on this and decided to update the version!
![23](https://user-images.githubusercontent.com/68055281/87575246-4c168000-c6d8-11ea-9aa1-3280e01b27b1.jpg)
