### ISSUE TITLE
Sales end should not be inclusive and ends sales is not considering in the timezone locale

### ISSUE THREAD

**Issue by dyslexicdrakness** [facebookincubator/Facebook-For-OpenCart#165]
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/8d5d217bda1d6e9f185444b3cd5388e7026a86fd/upload/system/library/facebookproductformatter.php#L210

I'm new to github community and culture so not sure how to contribute...

I got a report from a client that the sales were not syncing properly. Upon doing some test and reviewing the code I believe this line:

          : $product_special['date_end'] . self::MAX_TIME;

Should be changed to:

          : $product_special['date_end'] . self::MIN_TIME;

Open cart sales are set like this:
![ocimage](http://docs.opencart.com/image/catalog-product-discount.png)

No time for start or end. The default OC query to check for specials is:

(SELECT price FROM " . DB_PREFIX . "product_special ps WHERE ps.product_id = p.product_id AND ps.customer_group_id = '" . (int)$this->config->get('config_customer_group_id') . "' AND ((ps.date_start = '0000-00-00' OR ps.date_start < NOW()) AND (ps.date_end = '0000-00-00' OR ps.date_end > NOW())) ORDER BY ps.priority ASC, ps.price ASC LIMIT 1) AS special

I believe this causes a sale configured form 1/1/19 through 15/1/19 to end "effectively" at 15/1/19 0:00:00 am so basically its setup from 1/1/19 through 1/14/19 EOD.

Cheers!

**Comment by shue249** [comment]
@dyslexicdrakness Thank you for your feedback. We believe the culprit is on the locale of the MAX_TIME. 

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L67

The MAX_TIME is already set at 23:59, but the locale is set to be at GMT time and should have considered in the locale time zone instead.

Let us work out a fix for this.

**Comment by dyslexicdrakness** [comment]
If the locale is not being taken into account then that's another bug.

I still believe it should be MIN_TIME, or alternatively {end date - 1 day} MAX_TIME.

**Comment by shue249** [comment]
@dyslexicdrakness Thank you for the great feedback. You are right that the end date is the date where the sales must end. We will make the changes accordingly.

**Comment by shue249** [comment]
@dyslexicdrakness We have addressed the sales end date on version 2.1.9. You will still need to edit-save the products so that the discount dates will be correctly updated on FB side.

We will be closing out this ticket, feel free to reach to us if you have any more questions.
