### ISSUE TITLE
Error when removing connections for page with existing page shop connected

### ISSUE THREAD

**Issue by HWDonald** [facebookincubator/Facebook-For-OpenCart#166]
Trying to get FB for OpenCart to connect but it says I'm already connected.  When I click to remove existing connection I get Sorry, something went wrong. This might be a temporary issue and we're working to get it fixed as soon as we can. Please try again later.  How do I fix this?

**Comment by shue249** [comment]
@HWDonald  Thank you for the feedback.

Can you share a screenshot of how the error message looks like, so we ca better understand where is the point of failure.

**Comment by HWDonald** [comment]
![1](https://user-images.githubusercontent.com/50535273/57582603-c1fbd780-7494-11e9-8f3e-3e88655d9ac6.jpg)
![2](https://user-images.githubusercontent.com/50535273/57582604-c6c08b80-7494-11e9-8851-b532b211587e.jpg)

**Comment by shue249** [comment]
Duplicate error faced when trying to delete away the settings - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/158#issuecomment-491619629

**Comment by HWDonald** [comment]
I have read through that thread and another that was linked to it, I can't get to Advanced Setting through the module, that isn't an option.  I have the latest module installed 2.1.8, all the correct files are where they should be with read/write access as it should be.  I had an opencart website that was running for a while, and then I closed it down but I kep the FB page.  I have recently gone back to having a website (fresh install, all new, etc) so there shouldn't be any connections to this new page.  I have deleted FB developer account and FB Business account.  I then opened another FB Business account for that page.  Still unable to get that old connection gone and connect this new store.  I really don't want to have to make a new FB page if I don't have to.  What is my next step.

**Comment by shue249** [comment]
@HWDonald Thank you for your feedback. We are working to resolve this problem now. We will update you soonest once we have resolved the issue.

**Comment by HWDonald** [comment]
I don't know if this is going to help any but I downloaded the log file.  It has product numbers that don't even exist in my current opencart website.  They may have existed in the old site that I deleted.  I have gone through FB Business Manager and deleted everything I could.  There were no apps and only 1 pixel.  I went through FB Developer, nothing there either.  


[Black Goat Soap Co._2019-05-14_01-01-31_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3175409/Black.Goat.Soap.Co._2019-05-14_01-01-31_facebook_ads_extension.log)

**Comment by shue249** [comment]
@HWDonald Thank you for the feedback. We will suggest a clean restart (ie delete away old settings and restart again) will be the best approach. We are actively looking into the problem on our side and we will keep you updated soonest!

**Comment by shue249** [comment]
@HWDonald We have done up a fix on the issue that you are facing with the deletion of the settings. Can you try to delete away the settings again and let us know if it works.

**Comment by khrizzcristian** [comment]
Hello. Please let us know when you will fix the issue from "remove existing connection". I get that error also and I'm not able to setup the extension. Thank you

**Comment by shue249** [comment]
@khrizzcristian Can you share a screenshot of where you are getting the error so that we can better troubleshoot. Thanks

**Comment by khrizzcristian** [comment]
Same error as here: https://github.com/facebookincubator/Facebook-For-OpenCart/issues/166#issuecomment-491594029

When i try to remove the existing connection I receive that message and error 500 in console on dia.js ... if I try to ignore that and finish the setup, I receive again error 500 and nothing happens.

**Comment by shue249** [comment]
@HWDonald , @khrizzcristian We have released a fix that should be able to allow you to delete away the existing connections for page with page shop. Can you try to do that on your OpenCart website and let us know how it goes.

If it is still not working for you, we will need to contact you offline to request for additional help to troubleshoot.

**Comment by khrizzcristian** [comment]
Thank you. I will download the extension and if i have any trouble i'll write to you

**Comment by khrizzcristian** [comment]
Still doesn't work... But i see on opencart that is still v2.1.8

**Comment by khrizzcristian** [comment]
I get errors when i try to remove the existing connection, not when i try to delete settings...

**Comment by adibtradelink** [comment]
Facebook Ads Extension Sorry, something went wrong
how to fix it and connect to my page ?

**Comment by shue249** [comment]
@HWDonald , @khrizzcristian , @adibtradelink We have landed some fixes to resolve the problem when trying to remove existing connection for Page Shop. Can you try to remove away the existing connection on your OpenCart website and see if it works.

**Comment by khrizzcristian** [comment]
It's working :D :D Thanks a lot !

**Comment by adibtradelink** [comment]
Its work now thanks

**Comment by shue249** [comment]
Thanks to all for the feedback. We will be closing out this ticket, feel free to reach to us if you have any further questions.

**Comment by khrizzcristian** [comment]
After the upgrade to 2.1.9 I don't have any pixel in page. Did you removed this in the latest version?

**Comment by shue249** [comment]
@khrizzcristian Can you look at this comment and share on the same thread - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/183#issuecomment-497688460
