### ISSUE TITLE
Link from Facebook shop catalogue back to product on website is not working

### ISSUE THREAD

**Issue by atra1329** [facebookincubator/Facebook-For-OpenCart#168]
Hi 
We have installed  the module on opencart version 2.0.1.1 And all appears to be working fine However and are getting an incorrect link to our product on our website eg:

index.php?route=product%252Fproduct&product_id=53

this link gives a page not found error on our website.

The correct link syntax should be:
index.php?route=product/product&product_id=53

thanks for your help

**Comment by byron0920** [comment]
My version 3.0 also has this problem, which has not been solved.

**Comment by shue249** [comment]
@atra1329 , @byron0920 This is the case of rewrite rules on your webserver. We have provided a solution to resolve this that you need to apply on your webserver.

https://github.com/facebookincubator/Facebook-For-OpenCart/issues/113#issuecomment-467328263

**Comment by byron0920** [comment]
Hello, we have two websites; one is normal, the other is wrong; and the data we read is Catalog and Link.


Another normal website


shbqiu09@163.com
 
From: shue249
Date: 2019-05-13 12:44
To: facebookincubator/Facebook-For-OpenCart
CC: byron0920; Mention
Subject: Re: [facebookincubator/Facebook-For-OpenCart] Link from Facebook shop catalogue back to product on website is not working (#168)
@atra1329 , @byron0920 This is the case of rewrite rules on your webserver. We have provided a solution to resolve this that you need to apply on your webserver.
#113 (comment)

**Comment by byron0920** [comment]
Need FTP or?

**Comment by atra1329** [comment]
We have just added the NE parameter to our rewrite rules in the htaccess file but we are still not getting  the / in our link url

**Comment by atra1329** [comment]
Sorry there is a change we are getting now:
 %2F with the NE parameter in place of: / 
before it was set we were getting:
 %252F insted of the: /

thanks for your help

**Comment by atra1329** [comment]
It still doesn't change %2F with the NE parameter in place of: / but the links now work and are not getting the page not found error anymore. thanks

**Comment by shue249** [comment]
To give more context. We are not changing the URL link, but it is changing on how your web server handles the URL rewrite rule to handle the character encoding due to %2F.
