### ISSUE TITLE
Special Price Customer Group ID

### ISSUE THREAD

**Issue by Schwannn** [facebookincubator/Facebook-For-OpenCart#169]
Opencart has the option to create many spacial prices for different Customer Group IDs, but the facebook extension only synchs one customer group special price.
How can the spacial price customer group ID be defined for this app when synching ?

**Comment by shue249** [comment]
@Schwannn Thank you for the feedback.

Unfortunately, Facebook does not have the structure of customer groups, hence this feature is not able to be ported completely and we only sync 1 special price as the discount.

If you like to disable the discount completely on facebook, you can look to manually edit the codes of the plugin on your webserver. This post will be able to help you - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/16#issuecomment-487334001

**Comment by tomeda** [comment]
How can I choose which customer group id price to be selected. I want to only sync 1 special price as the discount but to be able to choose which customer group id to be selected. Because now I have two customer group id's, one is default from which special prices must be pulled, however discounted price in facebook are not from the default group.

**Comment by tomeda** [comment]
Please check the screenshot http://tinyurl.com/y425lkcp

**Comment by shue249** [comment]
@Schwannn, @tomeda  We have released a latest 2.1.11 version of the plugin which provides you an option to choose to sync the special price as discount or to disable the syncing of special price. 

If you like to sync for 1 special customer group id price for ALL the products, you can consider making the modifications directly on the plugin files on your webserver. The code pointer will be at - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/v2.1.11/upload/system/library/facebookproductformatter.php#L227

However, it will not be possible if you are looking to sync the entire customer group structure from OpenCart to Facebook, as Facebook does not have the structure of customer group.

Will be closing out this ticket. Feel free to reach to us if you have further questions.
