### ISSUE TITLE
Hard coded language strings

### ISSUE THREAD

**Issue by osworx** [facebookincubator/Facebook-For-OpenCart#171]
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/8d5d217bda1d6e9f185444b3cd5388e7026a86fd/install.xml#L383
Please remove those hard coded strings into a own, seperate language file and add here that language file and assign the vars instead.
thx.

**Comment by shue249** [comment]
@osworx Thank you for the feedback! Let us put it as a fix for upcoming versions.

**Comment by shue249** [comment]
@osworx We have addressed this on version 2.1.9. Will be closing out this ticket. Feel free to reach to us if you have any further questions.
