### ISSUE TITLE
Delete setting of the extension caused ads error

### ISSUE THREAD

**Issue by i3kevin** [facebookincubator/Facebook-For-OpenCart#174]
If I delete the settings here, will the product catalog on Facebook also being deleted as well?

![temp1](https://user-images.githubusercontent.com/45218158/57927257-10b7d000-78e0-11e9-8e4d-ae3d341c51f8.jpeg)

Yesterday I encountered some error and I was trying to troubleshoot by deleting the setting of this extension. After I re-connected back my page by the extension, all of my Facebook ads display error and stopped. "cannot find catalog"

![temp2](https://user-images.githubusercontent.com/45218158/57927516-d3077700-78e0-11e9-8b07-aee566a2ca2d.jpg)

There is no way I could solve this because the whole catalog just disappear? And there is no option for me to choose the new catalog to continue the dynamic ads. I was using Ads manager to place the ads not the extension in Opencart.

**Comment by shue249** [comment]
@i3kevin Thank you for your feedback.

Unfortunately, deleting away the Facebook Ads Extension settings will delete away the catalog and when you re-setup again, a new catalog will be created.

In this case, I am afraid that the best way for you now will be to stop the existing ads and setup a new set of ads again. We are truly sorry for the sub-optimal experience and we will take in this feedback to see how we can better improve the experience of the extension by informing users that deletion of the settings will cause disruption to existing ads.

We will close out this ticket for now, feel free to reach out to us if you have any further questions.
