### ISSUE TITLE
There are problems with the installation of the Facebook Ads Extension.

### ISSUE THREAD

**Issue by mahmoudelgharabawy** [facebookincubator/Facebook-For-OpenCart#176]
please i need help to solve this problem.
after install facebook extension show this error 
the error message :
There are problems with the installation of the Facebook Ads Extension.

We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders.

Please uninstall and reinstall the Facebook Ads Extension after correcting the above 1 step
Click here for details on the plugin installation.

what a solution for this problem >> thanks a lot

**Comment by shue249** [comment]
@mahmoudelgharabawy 

1. Did you rename the admin folder to some other name?

2. Can you check if you have given 775 access to the OpenCart folders?

**Comment by engasix** [comment]
@shue249 I am facing the same problem, I checked the OpenCart folder permissions are 755 and I didn't change the name of admin folder.

**Comment by engasix** [comment]
My OpenCart version is 3.0.2.0 and extenstion version is 2.1.8

**Comment by shue249** [comment]
@engasix Can you give the OpenCart folder permissions 775 recursively. Some of the files of the plugin was not able to be copied over correctly.

**Comment by shue249** [comment]
@mahmoudelgharabawy , @engasix Are you able to resolve the problem on your OpenCart webserver?

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have any further questions.
