### ISSUE TITLE
@haxcop We are glad that this works out for you.

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#178]
@haxcop We are glad that this works out for you.

@squarelabindia Can you let us know if the fix works for you.

_Originally posted by @shue249 in https://github.com/facebookincubator/Facebook-For-OpenCart/issues/160#issuecomment-493642218_

**Comment by shue249** [comment]
@KonstantinGOT Let's follow up with your error at https://github.com/facebookincubator/Facebook-For-OpenCart/issues/177. Will be closing out this ticket
