### ISSUE TITLE
Facebook Ads Extension Sorry, something went wrong. 

### ISSUE THREAD

**Issue by Aleksandr111111111** [facebookincubator/Facebook-For-OpenCart#179]
Hi
There is a problem when updating the module.
The module is installed everything is fine.
There is a problem with linking to the facebook store page.
facebook can not break \ terminate existing connection with the module of the previous version.
Currently installing (Facebook Ads Extension
Latest version: 2.1.8), previous module (Facebook Ads Extension
Latest version: 2.1.5) version of OpenCart © 2009-2019
Version 2.3.0.2

I choose the Facebook store page with which I want to link the module
https://drive.google.com/open?id=1_17EnjQXKxF9TXtuhTW8AXTQpPlsmLwf

But, in front of the desired store page, Tooltip is visible.
https://drive.google.com/open?id=1sAYYvhg7sftOpZHYMEXnwldqfCrTqHib

I still choose the right page, I need to break the existing connection to the site OpenCart
https://drive.google.com/open?id=14ClzwQur6KlHwfoOzMK_r4j0y3P26CII

I break an existing connection with OpenCart
https://drive.google.com/open?id=1IkekZgWG9LwseXY8Big8pPC252Im5tvP

See messageт (Sorry, something went wrong. This might be a temporary issue and we're working to get it fixed as soon as we can. Please try again later.)
https://drive.google.com/open?id=1Zfq-GY2Dy1sd75q7kahEU-bHaqxNszSp

after that, the process does not end and I cannot connect to the Facebook page I need

P.S.
With any other store page (made a test store in the same account) or even another store, the site \ module is connected with another account without problems, just cannot connect to this store.
https://www.facebook.com/Italian-top-shop-1140422989314988/

**Comment by Aleksandr111111111** [comment]
help

**Comment by Aleksandr111111111** [comment]
Before installing the module, all facebook files from the database were deleted.

**Comment by shue249** [comment]
Duplicate issue as https://github.com/facebookincubator/Facebook-For-OpenCart/issues/166

@Aleksandr111111111 We are looking into this now. Give us some time and we will update you soonest.

**Comment by Aleksandr111111111** [comment]
Thank you very much , everything works fine)))))
