### ISSUE TITLE
catalog products doesn't fully show in shop front

### ISSUE THREAD

**Issue by wegee-us** [facebookincubator/Facebook-For-OpenCart#180]
Hi, we have a problem with our another fun page, that is feed by facebook Pixel. It's feed successfully and import products to facebook catalog automatically when people visit the product page, but we don't know why it only shows 2 products in shop front page, actually we have more than 20 products in catalog.
![20190528162706](https://user-images.githubusercontent.com/50933832/58519555-08c22080-8169-11e9-89da-e0587be39416.png)
![20190528162646](https://user-images.githubusercontent.com/50933832/58519557-0bbd1100-8169-11e9-8dfb-34e83e1adac9.png)

**Comment by shue249** [comment]
@wegee-us 
1. Is this website also using the OpenCart plugin?
2. If yes, when was the setup done?

You can also readup on the approach that our plugin is syncing the catalog - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

To your earlier question on long time to resync the products. Based on your 1200 products, I will say it will take roughly 1 hour to complete the sync. It is on our roadmap to improve the re-sync mechanism.

**Comment by wegee-us** [comment]
@shue249 
Hi,
this is another fun page without OpenCart plugin, but using facebook Pixel to sync the product, and products are successfully added to the catalog, but not showing in shop front. we tried to contact facebook to figure out why it happens, but we can't reach them. 

for the earlier question about long time to resync 1200 products, does it cause my website down? because my website is down when resync those products.

**Comment by shue249** [comment]
For FB page shop, there is tighter review process on the products, so it could be that the products failed the review. Have you tried to recreate/repopulate the catalog and see if it solves the problem?

On the topic of 1200 products, yes - our current mechanism does lock down the webserver during the sync as the CPU resources are used to do the sync via API. We are currently looking at improving this process.

**Comment by wegee-us** [comment]
@shue249 
actually we tried to delete the catalog and shop front both, but it happens the same, and it always shows only that 2 products even recreate it. it looks like some facebook cache on it. can you check it for me? our fun page is https://www.facebook.com/pg/WBuy.us/shop/?rt=28

**Comment by wegee-us** [comment]
@shue249 Hi, can you help us out with this issue? our shop front keep only showing 3 or 5 products. but we have a lot products in catalog.

**Comment by wegee-us** [comment]
@shue249 Hi, our website is high customized, even we clean the cache, it still not shows up again. but the old version is ok. so it should be some problem to add it to header. this is our website, you can take look. 
wegee.us

**Comment by wegee-us** [comment]
and i did reinstall couple times, and also clean the setting from database.

**Comment by wegee-us** [comment]
sorry, i sent to wrong issue ticket...

**Comment by shue249** [comment]
@wegee-us Want to check in with you again, are you still facing problems on this?

**Comment by wegee-us** [comment]
@shue249 yes, still have this problem. the products are not fully show in front shop page
https://www.facebook.com/pg/WBuy.us/shop/?rid=1057257881079291&rt=6

**Comment by shue249** [comment]
@wegee-us Apologies for dropping the ball on this. We looked at the Facebook page again and found there are close to 120 products. Are you able to successfully load in the products?

**Comment by wegee-us** [comment]
@shue249 hi, i think it's working fine now. Thanks

**Comment by shue249** [comment]
@wegee-us Will be closing out this ticket, feel free to reach to us if you have any further questions.
