### ISSUE TITLE
"Manage Settings" shows more products in the inventory then the button "See your products on Facebook"

### ISSUE THREAD

**Issue by xseon** [facebookincubator/Facebook-For-OpenCart#181]
When I click Manage Settings from OC admin panel and the popup loads I see that we have 119 products in the inventory but when I click to see them - the link "See your products on Facebook" -  there are 62 products only. 
Why is that difference?

**Comment by shue249** [comment]
@xseon There could be products which are filtered away that does not meet our privacy review. Can you share with me what is the catalog id.

**Comment by xseon** [comment]
Catalog ID: 694867194241019
Facebook Store ID: 310158102942380

I don't see existing Product Data Sources. Could it be related to that
issue?

And one more thing about the dataflow: if I install a GDPR module which
will prevent any cookie from being set before a consent is givven and thus
the pixel probably won't send any events, will the advertising and
remarketing data continue to be accurate?

Dim

На чт, 30.05.2019 г. в 17:32 ч. shue249 <notifications@github.com> написа:

**Comment by shue249** [comment]
@xseon We found that the initial catalog sync may not have completed successfully when you perform the setup. Can you download the plugin log file and share the log file with us.

![image](https://user-images.githubusercontent.com/11957585/58738010-76ef3780-8436-11e9-897c-e7d294a8e785.png)

**Comment by shue249** [comment]
@xseon We suggest for you to Delete away your existing Facebook Ads Extension settings and redo the setup again. https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

We will be closing out this ticket, feel free to reach to us if you have any further questions.
