### ISSUE TITLE
after install when click extension tab showing blank screen only

### ISSUE THREAD

**Issue by whitesnow91** [facebookincubator/Facebook-For-OpenCart#182]
hi, i install and refresh modification for fb ads extension , all seem work correctly, but when i check tab on the admin side bar , it show blank screen only. when i check error log it seem no error and checked my php error log on server also seem no error .... i wonder what the problem and finding solution to solve it, hope that community at here can help me out , thank you

**Comment by shue249** [comment]
@whitesnow91 Can you share a screenshot of how it looks like?

**Comment by whitesnow91** [comment]
it only show blankscreen when i click the extension tab 
![Screenshot_1](https://user-images.githubusercontent.com/51204211/58642950-e11db480-8330-11e9-8fb2-c73bb2790592.png)

**Comment by shue249** [comment]
@whitesnow91 This is really weird and first time I came across this. Will you be able to double check again on the error log on your webserver. Also, can you open up javascript console on your chrome and inspect if there are any errors.

**Comment by whitesnow91** [comment]
no error showing on javascrip console also...

**Comment by shue249** [comment]
@whitesnow91 Can you verify if this file is on your webserver.
![image](https://user-images.githubusercontent.com/11957585/58737920-0516ee00-8436-11e9-9176-d0841d54d34e.png)

**Comment by shue249** [comment]
@whitesnow91 Unfortunately, we are unable to resolve this error on your webserver. You may want to check if this is due to some other 3rd party extensions that you have installed on your OpenCart.

We will be closing out this ticket, feel free to reach to us if you have any further questions.
