### ISSUE TITLE
Missing CompleteRegistration Currency and Value Parameters

### ISSUE THREAD

**Issue by i3kevin** [facebookincubator/Facebook-For-OpenCart#184]
I found a new bug when I updated to version2.1.9.

![image](https://user-images.githubusercontent.com/45218158/58754621-049a5800-8507-11e9-8385-149fe35581e1.png)
![image](https://user-images.githubusercontent.com/45218158/58754625-1da30900-8507-11e9-99ee-c17c2038041b.png)

**Comment by shue249** [comment]
@i3kevin Thank you for the feedback. This issue does not come from our plugin but from our pixel diagnostics dashboard. We will flow the feedback to our product teams.

We will be closing out this ticket, feel free to reach to us if you have any further questions.

**Comment by ArtemHoi** [comment]
Hello. I have the same problem, did you find the solution?
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/39946799/89410644-cb71ff00-d72c-11ea-8510-294d450ef844.png)
