### ISSUE TITLE
There is an error making API calls using the access token - When you change facebook account

### ISSUE THREAD

**Issue by pao2pao16** [facebookincubator/Facebook-For-OpenCart#185]
Hi,

Sorry for creating a new issue while there is already a closed issue regarding this one.
But I dont think that this is resolved.

I am always getting this message

"There is an error making API calls using the access token. The error encountered is "Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.".
To update your access token, please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token"

And I have found out that this happens when I change facebook account to maintain a different opencart with a different facebook page account, using the same browser session.

Hope you can check it out
Thanks

**Comment by shue249** [comment]
@pao2pao16 We are aware of this behavior and this is intended. Let us check into your use case and get back to you

**Comment by shue249** [comment]
@pao2pao16 

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

We will be closing out this ticket, feel free to reach to us on this ticket if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302
