### ISSUE TITLE
"Get Started" button is missing

### ISSUE THREAD

**Issue by svremeto** [facebookincubator/Facebook-For-OpenCart#186]
@shue249  Ive tried to upgrade the facebook extension of our old site as it was version 1. Ive upgraded as its shown in the video but i was facing the same error as in the new website (which we already fixed it).

So i replaced this file https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookadsextension.php

After that i clicked Empty Cache and Hard Reload.

Nothing changed. After that i`ve tried this command as you advice:
delete from setting where code = 'facebook';

But received error https://prnt.sc/nvaznc

and after that tried this command as you advice:
SELECT * FROM oc_setting WHERE code = 'facebook';
DELETE FROM oc_setting WHERE code = 'facebook';
I received this response: http://prntscr.com/nw9txl

After that clicked Admin/Modifications/Refresh and again Empty Cache and Hard Reload.

After that i see this: http://prntscr.com/nw9to9

Could you please advice? Thank you!

**Comment by svremeto** [comment]
Here is the javascript console to see if there are any errors when I access the Facebook Ads Extension module screen. http://prntscr.com/nww2gz

**Comment by shue249** [comment]
@svremeto There is a file, dia.js, which is not updated to latest version on your webserver. Can you try try to copy that file manually from the plugin zip package into your webserver. (you will need to unzip the zip package)

In additional, can you also check your webserver if the right permissions are given - 775 for the admin catalog and system folder. There could be other files which are not updated correctly.

**Comment by svremeto** [comment]
@shue249 Permission set correctly, file replaced, Modifications/Refresh, Empty Cache and Hard Reload but still the same.

**Comment by shue249** [comment]
@svremeto We released a new version of the plugin, 2.1.10. Can you try out this version on your OpenCart and see if it solves the problem of missing "Get Started" button.

**Comment by svremeto** [comment]
Fixed, Thank you!

**Comment by shue249** [comment]
Great! Will be closing out this ticket, feel free to reach to us if you have any further questions.
