### ISSUE TITLE
Pixel events do not fire

### ISSUE THREAD

**Issue by Gadzhev** [facebookincubator/Facebook-For-OpenCart#187]
I recently updated the Facebook for OpenCart extension because of the token update issue. Today I checked again and it seems the pixel is not firing again. Updated the module to latest version 2.1.9 and the issue still persist. I've cleared the cache of the theme and refreshed Modifications couple of times after doing changes. Still nothing.

Would appreciate some help since the ads are running for 8 days without any data. Website URL is https://www.cooolcheap.com

**Comment by shue249** [comment]
@Gadzhev Can you look at this comment and share your details - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/183#issuecomment-497688460

**Comment by Gadzhev** [comment]
@shue249 there's no such file on under system/storage/modification. I only have index.html in that directory.

**Comment by shue249** [comment]
Can you check to see
1. Have you refresh modifications - https://drive.google.com/drive/folders/1b3jBHIfi5dnwcsWr1aIGIBKVwXDrMH2g

2. Have you disabled both caches and refresh - https://drive.google.com/drive/folders/1b3jBHIfi5dnwcsWr1aIGIBKVwXDrMH2g

**Comment by shue249** [comment]
@Gadzhev I re-updated the links, can you try to access them again

**Comment by Gadzhev** [comment]
Thanks @shue249 I refreshed modifications and disabled cache and refreshed it. Pixel Helper still shows "No pixels found"

**Comment by shue249** [comment]
@Gadzhev Can you take a look at the modifications folder and see if you have the router.php file. If so, can you share that file here

**Comment by shue249** [comment]
@Gadzhev We have just released a version 2.1.10 of the plugin, which attempts to solve your pixel problem. Can you try out this update and let us know if the issue is resolved.

**Comment by Gadzhev** [comment]
@shue249 installed the new version and it works correctly now. Thank you very much for your time and help!
