### ISSUE TITLE
SYNC not working - Products missing from catalog - Initiate Checkout Event no fire + Error Mesage!

### ISSUE THREAD

**Issue by DORMETA** [facebookincubator/Facebook-For-OpenCart#190]
Hi, 

1. This problem persists regardless the updates.
In Admin/business facebook extension/ Manage / My products the count is 915 and in Business Facebook Manager  CATALOG there are only 619.
Is there any solution? Is there a feed URL that I can use to manually set the SYNC?
The SYNC is not working
![No sync](https://user-images.githubusercontent.com/48640019/58997014-3fe89f80-8803-11e9-91ff-ce8fe37a9471.jpg)

2. And the Initiate Checkout event is does not fire!

![initiate](https://user-images.githubusercontent.com/48640019/58997179-0e240880-8804-11e9-87b5-da653b753b8b.jpg)

3. Error Message encountered - I have the last update

![Error](https://user-images.githubusercontent.com/48640019/58998001-7fb18600-8807-11e9-9e46-f9471864e464.jpg)

Best regards,

**Comment by shue249** [comment]
@DORMETA 

1. You can use the "Resync products" feature to sync up the catalog. You can also read up more on our mechanism to sync products - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog
![image](https://user-images.githubusercontent.com/11957585/59011346-40743c80-87e9-11e9-9fbd-3f62c1244fee.png)

2. To see your products count/list, use the Products link
![image](https://user-images.githubusercontent.com/11957585/59011562-f63f8b00-87e9-11e9-8c05-d438a4d01dde.png)

3. For the checkout, we see that you are using a 3rd party checkout module. However, we support only OpenCart default checkout and do not support 3rd party checkout modules. If you have development capability, you can edit the codes on your webserver and test to see if our plugin is able to work out of the box. The code change you need to make is here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L158

**Comment by DORMETA** [comment]
Hi,
1. Regarding the ReSynck Products to Facebook I don't have the button available.
It;s stuck in loading mode. I've left the page open for more than 2 hours ans it's still the same:
![resync](https://user-images.githubusercontent.com/48640019/59125406-eac79d80-896a-11e9-85c8-b89b363269ae.jpg)

2. Also I have this message:

![message](https://user-images.githubusercontent.com/48640019/59125515-3aa66480-896b-11e9-801f-b69a0086bcf6.jpg)

Best regards!

**Comment by shue249** [comment]
@DORMETA 
1. Can you download the log file from our plugin and share the log file with us

2. To resolve the error message on access token, can you do follow these steps - https://drive.google.com/open?id=18koOQZmV3ra6wMsjsaWUPDuYZR_phl3J

**Comment by DORMETA** [comment]
Hi,
This is the log file:
[DORMETA_2019-06-10_08-07-56_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3270691/DORMETA_2019-06-10_08-07-56_facebook_ads_extension.log)
 And this is the window with Advanced Options:
![Advanced option page](https://user-images.githubusercontent.com/48640019/59174231-38a1f880-8b59-11e9-931d-40ab082274c1.jpg)

Regards!

**Comment by shue249** [comment]
@DORMETA Are you currently running any FB ads involving product catalog sales (dynamic ads)?

**Comment by DORMETA** [comment]
Hi,
I used a new PC and thing's look exactly the same.
Yes I have a dynamic add for remarketing in use connected  to product catalog sales

**Comment by shue249** [comment]
@DORMETA 

Thanks for the feedback. Based on your feedback, I will like to meet these 2 goals
1. Solve the access token issue on your setup
2. Solve the "loading" message on your setup so that the "Resync products" button is available

Once we solve for item 2, you can trigger a resync so that your latest product status can be synced over to Facebook catalog.

Can you share with us a screenshot of how the module page with the javascript console enabled.

![image](https://user-images.githubusercontent.com/11957585/59643241-78d92a80-919a-11e9-93c2-cb306b29c5e8.png)

**Comment by shue249** [comment]
@DORMETA 

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

Feel free to reach to us on this ticket if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302

**Comment by shue249** [comment]
We will be closing out this ticket, feel free to reach to us if you have further questions.
