### ISSUE TITLE
Update token option still not showing

### ISSUE THREAD

**Issue by dyslexicdrakness** [facebookincubator/Facebook-For-OpenCart#191]
Hey @shue249 !

I'm having trouble with most clients where the access token has been invalidate showing this message on the admin:

> There is an error making API calls using the access token. The error encountered is "Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.".
> To update your access token, please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.

The problem is that when you go to advanced there is no option to update token! We have also tried to resync without success...

On the facebook page where you refresh the token we do see this error:

aEkFhWwOX_F.js:53 ErrorUtils caught an error: "Could not find element "u_0_e" from module "__elem_20081362_0_0"". Subsequent errors won't be logged; see https://fburl.com/debugjs.
b	@	aEkFhWwOX_F.js:53
reportNormalizedError	@	aEkFhWwOX_F.js:55
applyWithGuard	@	aEkFhWwOX_F.js:56
d	@	aEkFhWwOX_F.js:56
A	@	aEkFhWwOX_F.js:38
y	@	aEkFhWwOX_F.js:38
H	@	aEkFhWwOX_F.js:38
c.$12	@	aEkFhWwOX_F.js:125
applyWithGuard	@	aEkFhWwOX_F.js:56
applyWithGuard	@	aEkFhWwOX_F.js:57
c.$11	@	aEkFhWwOX_F.js:125
(anonymous)	@	aEkFhWwOX_F.js:125
k	@	aEkFhWwOX_F.js:125
c.$5	@	aEkFhWwOX_F.js:125
c.handle	@	aEkFhWwOX_F.js:125
c.handlePartial	@	aEkFhWwOX_F.js:125
c._displayPagelet	@	aEkFhWwOX_F.js:195
c._displayPageletHandler	@	aEkFhWwOX_F.js:195
(anonymous)	@	aEkFhWwOX_F.js:195
applyWithGuard	@	aEkFhWwOX_F.js:56
applyWithGuard	@	aEkFhWwOX_F.js:57
c.$6	@	aEkFhWwOX_F.js:58
c.satisfyPersistentDependency	@	aEkFhWwOX_F.js:58
c.$6	@	aEkFhWwOX_F.js:71
a.$6	@	aEkFhWwOX_F.js:71
c.inform	@	aEkFhWwOX_F.js:71
a.inform	@	aEkFhWwOX_F.js:71
c._beginPhase	@	aEkFhWwOX_F.js:195
c._tryRenderingNextPhase	@	aEkFhWwOX_F.js:195
c._nextPhase	@	aEkFhWwOX_F.js:195
c._onPhaseDisplayEnd	@	aEkFhWwOX_F.js:195
(anonymous)	@	aEkFhWwOX_F.js:195
applyWithGuard	@	aEkFhWwOX_F.js:56
applyWithGuard	@	aEkFhWwOX_F.js:57
c.$6	@	aEkFhWwOX_F.js:58
c.satisfyPersistentDependency	@	aEkFhWwOX_F.js:58
c.$6	@	aEkFhWwOX_F.js:71
a.$6	@	aEkFhWwOX_F.js:71
c.inform	@	aEkFhWwOX_F.js:71
a.inform	@	aEkFhWwOX_F.js:71
c._displayPagelet	@	aEkFhWwOX_F.js:195
c._displayPageletHandler	@	aEkFhWwOX_F.js:195
(anonymous)	@	aEkFhWwOX_F.js:195
applyWithGuard	@	aEkFhWwOX_F.js:56
applyWithGuard	@	aEkFhWwOX_F.js:57
c.$6	@	aEkFhWwOX_F.js:58
c.satisfyPersistentDependency	@	aEkFhWwOX_F.js:58
c.$6	@	aEkFhWwOX_F.js:71
a.$6	@	aEkFhWwOX_F.js:71
c.inform	@	aEkFhWwOX_F.js:71
a.inform	@	aEkFhWwOX_F.js:71
(anonymous)	@	aEkFhWwOX_F.js:195
applyWithGuard	@	aEkFhWwOX_F.js:56
applyWithGuard	@	aEkFhWwOX_F.js:57
c.$6	@	aEkFhWwOX_F.js:58
c.satisfyPersistentDependency	@	aEkFhWwOX_F.js:58
(anonymous)	@	aEkFhWwOX_F.js:111
done	@	aEkFhWwOX_F.js:111
f	@	aEkFhWwOX_F.js:111
(anonymous)	@	aEkFhWwOX_F.js:111
I.guard.propagationType	@	aEkFhWwOX_F.js:297
applyWithGuard	@	aEkFhWwOX_F.js:56
applyWithGuard	@	aEkFhWwOX_F.js:57
n	@	aEkFhWwOX_F.js:297
load (async)		
R	@	aEkFhWwOX_F.js:111
P	@	aEkFhWwOX_F.js:111
U	@	aEkFhWwOX_F.js:111
(anonymous)	@	aEkFhWwOX_F.js:111
V	@	aEkFhWwOX_F.js:111
loadResources	@	aEkFhWwOX_F.js:111
o	@	aEkFhWwOX_F.js:195
(anonymous)	@	aEkFhWwOX_F.js:195
applyWithGuard	@	aEkFhWwOX_F.js:56
d	@	aEkFhWwOX_F.js:56
(anonymous)	@	dia?origin=https%3A%…2336002546621840:37
applyWithGuard	@	aEkFhWwOX_F.js:56
applyWithGuard	@	aEkFhWwOX_F.js:57
n	@	aEkFhWwOX_F.js:297
(anonymous)	@	dia?origin=https%3A%…2336002546621840:37

[Tecno Mundo_2019-06-10_18-54-24_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3273386/Tecno.Mundo_2019-06-10_18-54-24_facebook_ads_extension.log)

**Comment by DORMETA** [comment]
Hi,
Subsequent errors won't be logged; see https://fburl.com/debugjs. -->> the page no longer exists.
What can I do to fix my problem?
There is an error making API calls using the access token. The error encountered is "Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.".
To update your access token, please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
Regards

**Comment by shue249** [comment]
@dyslexicdrakness , @DORMETA 

If the update token option is not shown up, the other way is for you to manually fix this - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142#issuecomment-482908951

**Comment by shue249** [comment]
@dyslexicdrakness , @DORMETA . Were you able to update your access token?

**Comment by dyslexicdrakness** [comment]
Hey @shue249 sorry for the delay, I had trouble coordinating with affected clients a remote session to try it. It worked!

I might do a mod to insert a button with some kind of warning CLICK TO UPDATE TOKEN ONLY IF NEEDED.

Cheers!
