### ISSUE TITLE
Issue how cookies are showing up after istaling plug in.

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#192]
Hello i have a issue that cookies is showing up in a very strange way. Please see screenshot.
how to take it out?
![Screen Shot 2019-06-11 at 14 37 39](https://user-images.githubusercontent.com/50840258/59309918-b0efe300-8c59-11e9-92b4-05d25ae4bd11.png)

**Comment by shue249** [comment]
@KonstantinGOT You can disable the cookie bar here https://drive.google.com/open?id=1cdzTmI9pIqKx2olKku0-bjH1XMPEKcbn

**Comment by guilhermeojs** [comment]
> @KonstantinGOT You can disable the cookie bar here https://drive.google.com/open?id=1cdzTmI9pIqKx2olKku0-bjH1XMPEKcbn

Is it possible to disable it on mobile version as well? I've disabled it, it is not showing on the desktop anymore but it still shows on mobile version of the website

![cookiepolicy](https://user-images.githubusercontent.com/20118742/59379100-317f1400-8d2c-11e9-8b4f-6f1f17138fb1.png)

**Comment by shue249** [comment]
@KonstantinGOT I see from another thread that you can disable the web cookie but not the cookie on mobile. I will be closing this thread and replying to you on the other thread.
