### ISSUE TITLE
Pixel doesn't recognize the Checkout and the Registration page

### ISSUE THREAD

**Issue by svremeto** [facebookincubator/Facebook-For-OpenCart#195]
Hello!

Pixel doesn't recognize the Checkout and the Registration page. It shows them as View Page Action.

**Comment by shue249** [comment]
@svremeto What is the URL of your Checkout and Registration page? Are you using any custom 3rd party plugins that uses a different URL from OpenCart's default URL for checkout and registration?

**Comment by svremeto** [comment]
@shue249 Hello! My checkout URL is:
index.php?route=quickcheckout/checkout
and the registration URL is the same as its a module and the customer can make registration on the same page. http://prntscr.com/o3sqhd
Could you help me to fix it?

**Comment by shue249** [comment]
@svremeto You are using a 3rd party checkout module and we are unable to support the 3rd party module. If you have developer resources, this is the code where you may want to try changing to see if it works - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L158

For the creation of new user account on the checkout screen, we will look into this. However, as you are using a 3rd party checkout module, you may not be able to receive our subsequent changes.

**Comment by svremeto** [comment]
I have some developer skills but i`m not sure that i understand you. Let me see if i understand - I should make changes in this file and thats how the pixel will start recognizing the 3rd party checkout as a Checkout Action?
Do I understand you correctly?

**Comment by shue249** [comment]
@svremeto That is correct. You need to make changes to our plugin file, as our files are reading all the URL route path to decide if we should fire the pixel. If you look at the code line, we are reading the path "checkout/checkout" and you need to change it to "quickcheckout/checkout" for your 3rd party module.

However, 2 things you need to be aware of:
1. It is highly recommended for you to test out on a test server before doing this on actual live server. Because the 3rd party plugin may not be compatible with the rest of our module codes. And if you encounter problems, you need to debug and fix the problem.

2. You need to ensure that this custom change is applied on subsequent plugin versions when you do the upgrade.

**Comment by svremeto** [comment]
@shue249 Thank you for your recommendations. I am not sure that I can test it on a test server. I have a test website but it has no pixel for it. Also, I know nothing about the debug. 
Can I just make a backup ( i do it everything if I make some changes) 
then do the change in the code, 
then check it if it's working 
and if it's not to run the back up of the files and database also?

**Comment by shue249** [comment]
@svremeto Yes you can do that too.

**Comment by svremeto** [comment]
@shue249 Thank you very much for your help! I think i`ve fixed it! 
http://prntscr.com/o8yu2i
Is that enough proof for me that everything it's working correctly and there is no "hidden causes"?

Also, i found that when we had an order, the order wasn`t counted in the business analytics. Do you know what could cause this?

Thank you very much again!

**Comment by shue249** [comment]
@svremeto The screenshot on InitiateCheckout looks right.

We are not sure what is the cause of the order not counted in business analytics, as there could be too many factors affecting this. The best is to test out on a dummy website by installing each external plugin at a time to determine where the failure could be.

**Comment by yao-tx** [comment]
Hi @svremeto 

If you are using a 3rd party checkout page or registration page, the Pixel Events will not be able to fire correctly. Modifications to the FBE plugin will have to be made to accommodate custom pages.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
