### ISSUE TITLE
Help needed with setup

### ISSUE THREAD

**Issue by TamamFam** [facebookincubator/Facebook-For-OpenCart#196]
Hi, Im trying to install this extension on my opencart 3.03.2

But after installing all looks fine but i get many times error that i need to remove extension and install again. Tried many times diffrent ways . 

When i check with Facebook pixel helper there is no pixel found on my website.

I have themeburn pavilion theme....

Any solutions?

Have look at https://www.kinderschoenenoutletamsterdam.nl

Thank you

**Comment by kfaer** [comment]
same issue, is this extension compatible with OC 3.03.2?
permission did not work

**Comment by shue249** [comment]
@TamamFam , @kfaer 

We have yet to test out the plugin with 3.0.3.2. Also, we are wondering if you have seen the installation steps listed here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md

If you are facing permission error, you will need to "install" the module or to give the access permissions manually to your user groups.

**Comment by shue249** [comment]
@TamamFam Can you also share a screenshot of what is your error.

**Comment by TamamFam** [comment]
![image](https://user-images.githubusercontent.com/14175851/60106854-2c778700-9766-11e9-8397-2587273f194b.png)

No only says error.....

**Comment by shue249** [comment]
@TamamFam Apologies for the delayed reply.

From your error log, it seems that the products are not uploaded successfully to FB on the initial sync. Can you follow this steps to reset your Facebook Business Extension Settings - https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

Also how many products do you have in your OpenCart website?

**Comment by shue249** [comment]
Closing out this ticket for now. Pls feel free to reach to us if you have any further questions.
