### ISSUE TITLE
The plugin can't be set up because your currency ( egp ) is not supported.

### ISSUE THREAD

**Issue by vaguemind** [facebookincubator/Facebook-For-OpenCart#197]
hello , i installed the plugin and when to set it up and connect with facebook pixels that message appears: 

The plugin can't be set up because your currency ( egp ) is not supported. Learn more about supported currencies.

could you help me

**Comment by shue249** [comment]
@vaguemind We need the currency code to be all upper case. Can you make the changes below. Then launch the setup for Facebook Business Extension again.

![image](https://user-images.githubusercontent.com/11957585/60060641-22cd2f80-9724-11e9-94a8-6c66ba1bb4a4.png)

![image](https://user-images.githubusercontent.com/11957585/60060676-5a3bdc00-9724-11e9-9f6c-b7bd51c70dd5.png)

**Comment by shue249** [comment]
Closing off this issue. Feel free to reach to us if you have any further questions.
