### ISSUE TITLE
Param image_url is not a valid 

### ISSUE THREAD

**Issue by dieg15** [facebookincubator/Facebook-For-OpenCart#198]
I got this error in all my products when trying to import them to my facebook page:

2019-06-24 10:17:09 - Failure update product 140007 / 1957135794391815 on Facebook {"message":"(#100) Param image_url is not a valid URI.","type":"OAuthException","code":100,"fbtrace_id":"BmxMHuxH0k3"}

Thanks in advance!

**Comment by shue249** [comment]
@dieg15 Can you share what is the image url that you are using for the product?

**Comment by shue249** [comment]
@dieg15 We are closing out this ticket for now. Feel free to reach to us if you have any further questions.

**Comment by debora-maciel** [comment]
Hey, im with the same problem. Can u help me?

**Comment by yao-tx** [comment]
Hi @Trxuxv 

Please open a support ticket with us at marketinsg.zendesk.com so that our technical support team can assist you with it. Thank you.
