### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by guilhermeojs** [facebookincubator/Facebook-For-OpenCart#199]
Hi! Yesterday I had a critical issue regarding the Facebook Ads Extension. I think It happened after the last update and It took a while to impact it because of the cache.

![Untitled](https://user-images.githubusercontent.com/20118742/60107354-2caf5c80-973d-11e9-9faf-49ec30e5d1b4.png)

The website and also the admin page went offline with this fatal error. After I've disabled the Facebook Ads Extension and cleaned the cache it went back online.

It is something with this part of the code:

`<file path="system/engine/router.php">
    <operation>

      
      <search><![CDATA[public function __construct($registry]]></search>
      <add position="before"><![CDATA[
        private function runAction($actionName) {
          // added in defensive checks to ensure the
          // controller class is available and accessible
          try {
            if (is_file(
              DIR_APPLICATION . '/controller/' . $actionName . '.php')) {
              $facebookAction = new Action($actionName);
              $facebookAction->execute($this->registry);
            }
          } catch (Exception $e) {
            error_log($e->getMessage());
          }
        }
      ]]></add>
    </operation>
</file>
`

I had to disable it completely from my website in order to fix the issue. Anyone else with the same issue? I haven't done any changes on my website that could cause the problem.

**Comment by shue249** [comment]
@guilhermeojs This post has the fix - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/189

What you need to do is to remove all versions of our plugin from your system and Refresh modifications. Then install only the latest version and Refresh modifications.

Will be closing out this ticket, feel free to reach to us if you have any questions.
