### ISSUE TITLE
Fatal error: Cannot redeclare Front::runAction() after updating to version 2.1.10 plugin

### ISSUE THREAD

**Issue by OjuA1** [facebookincubator/Facebook-For-OpenCart#200]
Hello,

Please help if you can. I attempted to updated my plugin by uploading the ocmod zip to my opencart admin. I was in the process of refreshing my modification when I got this error message pointing me to line 30 in my front.php. When I try to access my opencart admin, the error displays same as when I try to access the site .

Any solutions please?

Thank you.

**Comment by shue249** [comment]
@OjuA1 Can you look at this post https://github.com/facebookincubator/Facebook-For-OpenCart/issues/189, it will solve your problem

**Comment by shue249** [comment]
Will be closing out this ticket. Feel free to reach to us if you have any further questions.

**Comment by OjuA1** [comment]
Thank you shue249. The errors were slightly different as mine pointed to the front.php file but the same method solved it nonetheless. Thanks again
