### ISSUE TITLE
Unable to remove dir as the directory is not empty

### ISSUE THREAD

**Issue by lipmycar** [facebookincubator/Facebook-For-OpenCart#201]
Hello Support team,

When I try to install the latest version of the extension I get this error:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<b>Warning</b>: rmdir(/home/lipmycar/public_html/admin//../admin/controller/extension/module/): Directory not empty in <b>/home/lipmycar/public_html/system/upload/temp-6843914e16d340dfa0dc8c648ec0a336/install.php</b> on line <b>110</b>[]
![facebook ext issue](https://user-images.githubusercontent.com/40515131/60326299-0f270080-9992-11e9-8839-f57378a04e12.png)

**Comment by shue249** [comment]
@lipmycar Thank you for the feedback. Let us look into this.

**Comment by lipmycar** [comment]
Do you have any ideas what can cause this issue? 
Unfortunately I am not able to use the latest version of the extension.

**Comment by shue249** [comment]
@lipmycar Apologies for the delay. 
1. Can we understand what is the version of your OpenCart? Is the version 2.0.3.1?
2. If the version is 2.0.3.1, do you have folder "admin/controller/extension/module" on the webserver? If so, can we understand why do you need this folder?

**Comment by shue249** [comment]
@lipmycar We have released a latest 2.1.11 version of the plugin which fixes this problem. 

Will be closing out this ticket. Feel free to reach to us if you have further questions.
