### ISSUE TITLE
Opencart error Cannot redeclare modification()

### ISSUE THREAD

**Issue by jamaakurtlar** [facebookincubator/Facebook-For-OpenCart#203]
I installed mod 

facebookadsextension.ocmod

 and it will not allow me access to my Extensions -> Modifications section so that I can uninstall the mod. I receive this error when I attempt to go to "Modifications":
Fatal error: Cannot redeclare Router::runAction() in /home/domain/storage/modification/system/engine/router.php on line 39

the problem is this extension already install in my opencart 
i need to remove it manually because i can't access to my admin area 
thank you for your help

**Comment by shue249** [comment]
@jamaakurtlar Thank you for the feedback. Can you look at this post for the solution - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/189

We will be closing out this ticket, but feel free to comment on the same post if you have any further questions.

**Comment by jamaakurtlar** [comment]
work for me , thank you shue249  :)
