### ISSUE TITLE
Facebook ads extension 2.1.10 Opencart Version 3.0.2.0   sync failure 

### ISSUE THREAD

**Issue by HasanMadni1** [facebookincubator/Facebook-For-OpenCart#204]
Keep showing the error mention below event delete the and restart the setup many time 
Facebook plugin version and Opencart version are mention in  subject
i have also attached the logged for better understand please help us with this issue 

We have around 10,000 product on our server enable 

[Log File.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3353439/Log.File.log)

**Error occur on dashboard**
" There is an error with Facebook Business Extension setup. Click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.
The sync failure of your products to Facebook may be because of the large number of products on your system (We detected 6835 products). Please refer to our FAQ section on "Syncing of OpenCart products to Facebook catalog" for more details."

**Comment by shue249** [comment]
@HasanMadni1 After looking through the log file, we see that you have restarted the setup several times. There are indeed some times where the setup failed, but there are also other occasions where the setup is successful.

Can you try to delete the settings and restart the setup again and share the log file.

**Comment by HasanMadni1** [comment]
Hi Dear,

Thanks for the prompt response.
Yes we have tried the plugin before now yesterday install the plugin and setup the thing from scratch  just before writing this email delete and restarted the setup once again as you told that it happen for few times sharing the logs after the restart the setup please have a look and let me know.



Thanks & Regards
Hasan Madni

________________________________

**Comment by shue249** [comment]
@HasanMadni1 Do you have the latest log file after you restart the setup?

**Comment by HasanMadni1** [comment]
Hi

Please find attached logs after restart.

Thanks & Regards
Hasan Madni
________________________________

**Comment by shue249** [comment]
@HasanMadni1 You will need to put the attached file on github website instead of replying to the email, as the reply from email will not add the attachments.

**Comment by HasanMadni1** [comment]
Noted I will do the same by today

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HasanMadni1** [comment]
Hi Please find attached logs after restart
[ShopAlArab.Com_2019-07-06_06-29-53_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3364472/ShopAlArab.Com_2019-07-06_06-29-53_facebook_ads_extension.log)

**Comment by shue249** [comment]
@HasanMadni1 From the last restart, the product catalog sync has been successful. However, there are some new errors coming from the access token due to the need to verify the authenticity of your account. To solve this problem, can you access facebook.com and follow the required authenticity steps.

**Comment by HasanMadni1** [comment]
Hi Today once again the error started i have attached logs for your reference.

[ShopAlArab.Com_2019-07-09_07-26-36_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3371903/ShopAlArab.Com_2019-07-09_07-26-36_facebook_ads_extension.log)

**Comment by HasanMadni1** [comment]
> Hi Today once again the error started i have attached logs for your reference.
> 
> [ShopAlArab.Com_2019-07-09_07-26-36_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3371903/ShopAlArab.Com_2019-07-09_07-26-36_facebook_ads_extension.log)

Hello please check this logs you answered for the previous.

**Comment by HasanMadni1** [comment]
> @HasanMadni1 From the last restart, the product catalog sync has been successful. However, there are some new errors coming from the access token due to the need to verify the authenticity of your account. To solve this problem, can you access facebook.com and follow the required authenticity steps.

Please answer for the new attachment.

**Comment by HasanMadni1** [comment]
Hello still waiting for the feedback 2 days has been passed

**Comment by shue249** [comment]
@HasanMadni1 If you looked at the log file, you can see that the setup is successful and the product sync are successful on 8th Jul. However, it seems that you have have went to delete and restart the setup again and then the setup was incomplete.

Can I suggest for you to delete and restart the setup again. And then you can make 1 product edit and check the log file. If you see success message, then the setup is complete.
![image](https://user-images.githubusercontent.com/11957585/61034130-46b49480-a3f7-11e9-9ca6-541d83afdae0.png)

**Comment by HasanMadni1** [comment]
Hi I have restarted once again just now also sharing the log after the fresh restart
most of the time when i have restarted after 2 days will get the same error
please find attached screen shot for your reference including the logs
[ShopAlArab.Com_2019-07-11_10-00-44_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3381414/ShopAlArab.Com_2019-07-11_10-00-44_facebook_ads_extension.log)
![Get Started](https://user-images.githubusercontent.com/52482009/61042065-86be4c00-a3e4-11e9-9fb5-deec7d33c84e.jpg)
![Successful](https://user-images.githubusercontent.com/52482009/61042067-86be4c00-a3e4-11e9-81b3-d26850597cc6.jpg)
![Sync](https://user-images.githubusercontent.com/52482009/61042068-8756e280-a3e4-11e9-9bc6-c30c40150f27.jpg)

**Comment by shue249** [comment]
@HasanMadni1 After the last restart, do you still get any error on the catalog sync?

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach out if you have any further questions.
