### ISSUE TITLE
photos are not uploaded

### ISSUE THREAD

**Issue by Kucenkov** [facebookincubator/Facebook-For-OpenCart#205]
photos are not uploaded
Opencart ocStore 2.3.0.2.3
Plugin Version: 2.1.10

<img width="1640" alt="Снимок экрана 2019-07-03 в 21 36 27" src="https://user-images.githubusercontent.com/24460483/60616692-bcf33e80-9dda-11e9-8b89-86e20dec9b18.png">

**Comment by shue249** [comment]
@Kucenkov Thank you for the feedback. It may take some time for our crawlers to retrieve the photos and store them on FB side. I did a check and found that the product images are now available.

![image](https://user-images.githubusercontent.com/11957585/60631617-e2139b80-9e32-11e9-81e7-069431c13c4c.png)

Will be closing out this ticket. Feel free to reach to us if you have any further questions.
