### ISSUE TITLE
Website blocked or error ? Why is it blocked? 

### ISSUE THREAD

**Issue by nymphaclothing** [facebookincubator/Facebook-For-OpenCart#206]
Everything went fine for our nymphaclothing.com online store, except yesterday when all of our products cannot be tagged anymore in Instagram, it seems that the feed is seen with 219 products but the product list wont show. The link nymphaclothing.com in instagram bio wont work, also messages in facebook says :
Your message couldn't be shared, because this link goes against our Community Standards.

We dont know what we did wrong, we filed numerous complains but nobody is giving any reasons or explanation, either on Instagram or Facebook. Our business is going down after years with investing and good collaboration. This is so frustrating, to know that any random report can cause this, if this is what happened.... Can you please help us or tell us any quick way to analyze our situation? Where should we address ? Thank you

<img width="1049" alt="Screenshot 2019-07-04 at 08 50 35" src="https://user-images.githubusercontent.com/52521975/60642527-e5aa2100-9e38-11e9-95b1-33f9be8c4fcd.png">
<img width="1129" alt="Screenshot 2019-07-03 at 20 13 54" src="https://user-images.githubusercontent.com/52521975/60642528-e5aa2100-9e38-11e9-9acc-ef29618eff6d.png">
<img width="1097" alt="Screenshot 2019-07-03 at 13 52 11" src="https://user-images.githubusercontent.com/52521975/60642529-e642b780-9e38-11e9-884a-d8cc03911664.png">

**Comment by nymphaclothing** [comment]
Also we attach the error log of Facebook Ads Extension 
[SHOP A DEAL SRL_2019-07-04_05-52-50_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3357848/SHOP.A.DEAL.SRL_2019-07-04_05-52-50_facebook_ads_extension.log)

**Comment by shue249** [comment]
@nymphaclothing We have feedback this to our internal teams. Will get back to you soonest if they have any updates.

**Comment by nymphaclothing** [comment]
Hello,


Any news regarding our request? This is an urgent situation, our business is suffering a lot each day. We did our part of being loyal to your services in the last years (17.000 usd spent in Ads in the last 2 years) and now Facebook is keeping us in a waiting list that might ruin our years of hard work...


Can you speed up the process in any way and flag our request please?



Multumesc,
Razvan Stroescu
0766.511.681


________________________________

**Comment by shue249** [comment]
@nymphaclothing Thanks for following up. We just heard back from our internal team. They have helped to resolve this issue. Can you check if this problem still exists.

**Comment by nymphaclothing** [comment]
Thank you for your help !


Can you please ask what was the problem ? It will be a great deal for us to avoid this in the future...it was automatic error or it was something that we did ?


Respectfully,


Multumesc,
Razvan Stroescu
0766.511.681


________________________________

**Comment by shue249** [comment]
@nymphaclothing Unfortunately I do not have a reply on this as our internal teams did not share out the reason. You can reach to us here if this happens in future and we can get our internal teams to help take a look.

**Comment by nymphaclothing** [comment]
Hello,

@shue249 
I am getting back to you as the problem is now back again. Can you help me again with this and notify the internal team as you helped me before?

**Comment by nymphaclothing** [comment]
@shue249 

Hello again after years, 
Can you please help me on other issue regarding ad accounts that were hacked and facebook pages that were stolen?
I started case ID 1033734540815062 but this is taking days and they are asking for legal notary documents and other stuff that can take a lot of time. Meanwhile hackers are running ads. Can you help me on speeding up the process ?
