### ISSUE TITLE
The catalog is not updating and in instagram can see 2 catalogs 

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#209]
Have 2 problems
1) have a duplicate catalog that i only see in Instagram app but not in FB 
2) the catalog is not updating from the webpage even if i do it manually

**Comment by shue249** [comment]
1. For the issue on duplicate catalogs, will you be able to provide us both the catalog ids

2. For the problem where the catalog is not updated. Can you share with us your log file for the Facebook business extension plugin. Also are you making the product changes using the default Opencart product management module or are you using a 3rd party product management module.

**Comment by KonstantinGOT** [comment]
1) is there other way? i don't see it in fb and in Instagram the number is not full
2) here
[satorisanshop.ru_2019-07-11_05-44-31_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3380033/satorisanshop.ru_2019-07-11_05-44-31_facebook_ads_extension.log)

**Comment by KonstantinGOT** [comment]
@shue249 any update

**Comment by shue249** [comment]
@KonstantinGOT 
1. What is the URL for the catalog on FB and Instagram?

2. The log file shows that the updates are done correctly. Can you share where are the areas of mis match?

**Comment by KonstantinGOT** [comment]
2) but it shows the last update was on Last successful update : Tue May 28, 2019 12:56am
quite far away from now. @shue249

**Comment by shue249** [comment]
@KonstantinGOT The last update information shown on the catalog is shown due to the initial feed upload from the sync. 

Will you be able to share any mis-match shown on the catalog?

**Comment by shue249** [comment]
Will be closing out this ticket. Feel free to reach to us if you have further questions.
