### ISSUE TITLE
Providing support for PHP 5.3

### ISSUE THREAD

**Issue by 2728384** [facebookincubator/Facebook-For-OpenCart#21]
Hi,i got 2 problem after installed it in the OC-2.2.0.0.
The installed is success and i did refresh after the installed.
And the plugin's version is 2.0.2.

Here's the error message after i want to click the extension▼
Fatal error: Using $this when not in object context in /home/vitaorga/public_html/shoponline/admin/controller/extension/facebookadsextension.php on line 484

And another error message show up on my website▼
Notice: Use of undefined constant JSON_PRETTY_PRINT - assumed 'JSON_PRETTY_PRINT' in /home/vitaorga/public_html/shoponline/system/storage/modification/catalog/controller/common/header.php on line 34Notice: Use of undefined constant JSON_PRETTY_PRINT - assumed 'JSON_PRETTY_PRINT' in /home/vitaorga/public_html/shoponline/system/storage/modification/catalog/controller/common/header.php on line 38

When the error show up, all  function of product in Backstage are crashed, i need to delete the plugin to make  my O.C system work again.

**Comment by shue249** [comment]
Thank you for the feedback! Let us look into this.

**Comment by shue249** [comment]
@2728384 Can I understand 
1. what is the version of PHP used on your server
2. what is the server you are using, eg OS, version

**Comment by 2728384** [comment]
php-5.3 
os- centos 6

**Comment by shue249** [comment]
@2728384 Thanks for the feedback! The problem you are encountering is due to the PHP requirement, as we did not support for 5.3. Based on OpenCart's requirement, we are catering for PHP 5.4 and higher - http://docs.opencart.com/en-gb/requirements/

Will you be able to upgrade your php to 5.4 or higher?

**Comment by 2728384** [comment]
I have installed some other plugin. (Ajax Quick Checkout .....) Everything works good.
Upgrade php version may cause some other errors, so it's not my first choice.
Do you have another way to fix it???

**Comment by shue249** [comment]
We can consider it as an enhancement subsequently but not in the immediate timeline. We can share with you when it is ready soonest.

**Comment by EsmondTan** [comment]
We will not be able to support PHP 5.3 unfortunately since that version is no longer maintained and the Facebook PHP SDK has external dependencies.
