### ISSUE TITLE
Undefined class constant 'FACEBOOK_CUSTOMIZATION_GREETING_TEXT_CODE' 

### ISSUE THREAD

**Issue by priyorockz** [facebookincubator/Facebook-For-OpenCart#211]
Page (store front) breaks after updating to 2.1.10. It gives the following message.

> Fatal error: Uncaught Error: Undefined class constant 'FACEBOOK_CUSTOMIZATION_GREETING_TEXT_CODE' in /home/xxxxxx/public_html/vqmod/vqcache/vq2-system_storage_modification_catalog_controller_common_header.php:18 Stack trace: #0 /home/xxxxxx/public_html/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(44): ControllerCommonHeader->index(Array) #1 /home/xxxxx/public_html/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php(32): Action->execute(Object(Registry), Array) #2 /home/xxxxx/public_html/vqmod/vqcache/vq2-system_storage_modification_catalog_controller_common_home.php(107): Loader->controller('common/header') #3 /home/xxxxx/public_html/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(44): ControllerCommonHome->index() #4 /home/xxxxxxx/public_html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #5 /home/xxxxxx/public_html/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(44): ControllerStartupR in /home/xxxxxx/public_html/vqmod/vqcache/vq2-system_storage_modification_catalog_controller_common_header.php on line 18

**Comment by shue249** [comment]
@priyorockz Can you check if your system folder on your webserver is writable. We have a latest version of the facebookcommonutils.php file and I believe that this file is not updated correctly on your webserver. For more context, this is the code line you should be seeing on the same file on your webserver - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookcommonutils.php#L100

As a guidance, we suggest to give 775 permission to admin, catalog and system folders.

**Comment by c0s7y** [comment]
![facebook admin2](https://user-images.githubusercontent.com/52632609/61381034-20896b80-a8b3-11e9-95b9-687d4dacb2af.jpg)
after update facebookcommonutils.php

**Comment by shue249** [comment]
Closing out this ticket. Feel free to reach to us if you have further questions!
