### ISSUE TITLE
1 Add to cart Fired for 2 times?

### ISSUE THREAD

**Issue by i3kevin** [facebookincubator/Facebook-For-OpenCart#212]
When I add one product to cart, there is a double record for 'Add to Cart' Pixel.

The difference between the two records are Parameters: (5) and Parameters: (6)
What do these Parameters mean?

![image](https://user-images.githubusercontent.com/45218158/61083111-8a41e980-a45d-11e9-8283-6dceefec0d43.png)

**Comment by shue249** [comment]
@i3kevin The second AddToCart is the event fired from our plugin (we included in the num_items parameters). 

I am not sure what is the actual reason for the first AddToCart event, I can suggest for you to look if you have implemented any pixel firings manually or using other 3rd party plugins. If you are doing so, you need to remove these pixel firings.

In terms of double firing for AddToCart, this is fine. However, I will encourage you to look at Purchase events.

I will be closing out this ticket, but feel free to reach to us if you have further questions.
