### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by guilhermeojs** [facebookincubator/Facebook-For-OpenCart#213]
Hi there.

I've been having a fatal error that happens for around 10 minutes and then it comes back to normal. The last fatal error I had on my store was due the extension.

Any idea if this is related?

Fatal error: Cannot access property Composer\Autoload\ClassLoader::$prefixLengthsPsr4 in /home/mystore/storage/vendor/composer/autoload_static.php on line 131

**Comment by shue249** [comment]
@guilhermeojs This is the first time we see this error. Perhaps we can monitor this more further and see if it still happens later on.

**Comment by shue249** [comment]
@guilhermeojs We will be closing off this issue. Feel free to reach to us if you have further questions
