### ISSUE TITLE
Opencart 2.0.2.0 'missing database tables'

### ISSUE THREAD

**Issue by Steve-Regal** [facebookincubator/Facebook-For-OpenCart#214]
Hi, 

using Opencart 2.0.2.0, running Journal 2 theme. Have set the permissions to '775' on the required file paths, but am still getting the following issue:

We have detected these missing database tables for Facebook Ads Extension. Please give the CREATE privilege for your database user.
oc_facebook_product

I have refreshed the cache, I have uninstalled and re-installed, but still can not get passed this issue. 

Any ideas?

**Comment by shue249** [comment]
@Steve-Regal The error is on the permission level of your database user. You need to give the CREATE permission to the user as we need the permission to create a new database.

**Comment by Steve-Regal** [comment]
Hi, all database permissions are all set to 775 which is read, write and execute for Owner and Group

**Comment by shue249** [comment]
@Steve-Regal You have mixed up file permission with database permission. For database permission you need to set it  from the MYSQL database side.

**Comment by Steve-Regal** [comment]
okay I will take a look now thanks, will update shortly

**Comment by Steve-Regal** [comment]
hi, have also checked and the database permissions are all set to create

**Comment by shue249** [comment]
@Steve-Regal Can you also check if the database permission has ALTER table permissions

**Comment by Steve-Regal** [comment]
Hi, yes all permissions are ticked.

Best Regards,
Steve Brown
*_______________________________*
Office Phone: +44 (0) 2380 55 86 36
<https://mailtrack.io/trace/link/ccdba879a375d4959cb92afd20e9f719f55c4448?url=http%3A%2F%2Fwww.regalautosport.com%2Fshop&userId=4267568&signature=db7f3ebd9eaf4838>Online
Shop
<https://mailtrack.io/trace/link/426646615f21daadccad1fcdf410420854a048d1?url=http%3A%2F%2Fwww.regalautosport.com%2Fshop&userId=4267568&signature=5d138e85130e8507>
-
Instant Finance Available
Facebook
<https://mailtrack.io/trace/link/225fd21bd0c3c5177039080bd64a96f1765c305c?url=http%3A%2F%2Fwww.facebook.com%2Fregalautosport&userId=4267568&signature=bb61eb3a23e03996>
 | Twitter
<https://mailtrack.io/trace/link/9583f2bb97b67dde17cc3bb21e138788cf5e0093?url=http%3A%2F%2Fwww.twitter.com%2Fregalautosport&userId=4267568&signature=b567a9338e4d49e5>
 | Instagram
<https://mailtrack.io/trace/link/a58927469afb3666c6a5872543fd7ee414bb414b?url=http%3A%2F%2Fwww.instagram.com%2Fregalautosport&userId=4267568&signature=7e85c0f012e24e6c>
 | Blog
<https://mailtrack.io/trace/link/1cd1982be0caab0de49c26aa82febfa3a9de1545?url=http%3A%2F%2Fwww.regalautosport.com%2Fblog&userId=4267568&signature=997025735cde092d>
Monday through Friday 0830hrs – 1730hrs
72-82 Belgrave Road, Southampton, SO17 3AN, UK
<https://mailtrack.io/trace/link/3a4b0d18f04c01e08c523260dce69a5257a8133c?url=https%3A%2F%2Fwww.google.co.uk%2Fmaps%2Fplace%2FRegal%2BAutosport%2F%4050.930744%2C-1.3837%2C17z%2Fdata%3D!3m1!4b1!4m2!3m1!1s0x487473e5838a39f7%3A0xe0a5ca9b19678845&userId=4267568&signature=df59c8296a3892ed>

Regal Autosport (International)l Limited Email Legal Disclaimer: E-mails
and any attachments sent by Regal Autosport (International)l Limited are
intended for the named addressee(s) only, or person authorised to receive
them on their behalf. The content should be treated as confidential and the
recipient may not disclose the message or any attachment to anyone else without
authorisation. Unauthorised use, copying or disclosure may be unlawful.  If
any transmission is received in error please notify the sender immediately
and delete the message from your e-mail system. Any view expressed by the
sender of the message or any attachment may be personal and may not
represent the view held by Regal Autosport (International)l Limited.
All electronic
transmissions to and from Regal Autosport (International)l Limited,
may be monitored
and are scanned for viruses and content. E-mails containing viruses
will be deleted
without notification. Whilst we maintain virus checks on inbound
e-mails we accept
no liability for viruses or for any loss or damage arising from the use  of
any outgoing messages or other material introduced to outgoing messages.

**Comment by shue249** [comment]
Can you try to remove away our plugin and re-install the plugin again and see if it works.

**Comment by shue249** [comment]
@Steve-Regal Like to check in again to see if you are still encountering any further problems.

**Comment by Steve-Regal** [comment]
Thanks for the follow up, we had some issue's with the database so i need
to take another look at it now thats resolved. I will be in touch if i
require more assistance

Best Regards,
Steve Brown
*_______________________________*
Office Phone: +44 (0) 2380 55 86 36
<https://mailtrack.io/trace/link/03c04ff0e79d8549526a65d4382e713e16b60c06?url=http%3A%2F%2Fwww.regalautosport.com%2Fshop&userId=4267568&signature=9dbd9c6dc3fad177>Online
Shop
<https://mailtrack.io/trace/link/e4bddddcc7e32b9f3b6dd146fb5f5f8053f69f96?url=http%3A%2F%2Fwww.regalautosport.com%2Fshop&userId=4267568&signature=0b0af39f641b4a24>
-
Instant Finance Available
Facebook
<https://mailtrack.io/trace/link/211d6f059611e1570fce836099277a7e3d983150?url=http%3A%2F%2Fwww.facebook.com%2Fregalautosport&userId=4267568&signature=569d4b9d0a06bc99>
 | Twitter
<https://mailtrack.io/trace/link/1781ea46287cb9e7189d5fa3fffc25485cea2c79?url=http%3A%2F%2Fwww.twitter.com%2Fregalautosport&userId=4267568&signature=7cbedabeea1049d5>
 | Instagram
<https://mailtrack.io/trace/link/a8d6f36ddca4dbe64bff92cc33f216c6be1b4202?url=http%3A%2F%2Fwww.instagram.com%2Fregalautosport&userId=4267568&signature=201d7182f0421308>
 | Blog
<https://mailtrack.io/trace/link/df8ec4f6f5cf2ebce0cac9aa0799d70ca0ef4834?url=http%3A%2F%2Fwww.regalautosport.com%2Fblog&userId=4267568&signature=18f578992c84f7af>
Monday through Friday 0830hrs – 1730hrs
72-82 Belgrave Road, Southampton, SO17 3AN, UK
<https://mailtrack.io/trace/link/a596401547ce371e59a92746ef59d5fdcd076446?url=https%3A%2F%2Fwww.google.co.uk%2Fmaps%2Fplace%2FRegal%2BAutosport%2F%4050.930744%2C-1.3837%2C17z%2Fdata%3D!3m1!4b1!4m2!3m1!1s0x487473e5838a39f7%3A0xe0a5ca9b19678845&userId=4267568&signature=99460bb7ad3ebb6d>

Regal Autosport (International)l Limited Email Legal Disclaimer: E-mails
and any attachments sent by Regal Autosport (International)l Limited are
intended for the named addressee(s) only, or person authorised to receive
them on their behalf. The content should be treated as confidential and the
recipient may not disclose the message or any attachment to anyone else without
authorisation. Unauthorised use, copying or disclosure may be unlawful.  If
any transmission is received in error please notify the sender immediately
and delete the message from your e-mail system. Any view expressed by the
sender of the message or any attachment may be personal and may not
represent the view held by Regal Autosport (International)l Limited.
All electronic
transmissions to and from Regal Autosport (International)l Limited,
may be monitored
and are scanned for viruses and content. E-mails containing viruses
will be deleted
without notification. Whilst we maintain virus checks on inbound
e-mails we accept
no liability for viruses or for any loss or damage arising from the use  of
any outgoing messages or other material introduced to outgoing messages.

**Comment by shue249** [comment]
Closing this for now. Feel free to reach to us if you have further questions.

**Comment by Steve-Regal** [comment]
Hi,

All permissions are ticked, and all files have RWX permission but i am
still getting the same error message. Have installed - removed and
reinstalled and the issue persists.

Do you have any other suggestions?

Best Regards,
Steve Brown
*_______________________________*
Office Phone: +44 (0) 2380 55 86 36
<https://mailtrack.io/trace/link/7c8b8d9e278990f01db3c4c6e62dc9d9d356996d?url=http%3A%2F%2Fwww.regalautosport.com%2Fshop&userId=4267568&signature=1e8db62a6f918272>Online
Shop
<https://mailtrack.io/trace/link/7c8b8d9e278990f01db3c4c6e62dc9d9d356996d?url=http%3A%2F%2Fwww.regalautosport.com%2Fshop&userId=4267568&signature=1e8db62a6f918272>
-
Instant Finance Available
Facebook
<https://mailtrack.io/trace/link/9987f8bcf754397c928f8d1504d0132113d80ee9?url=http%3A%2F%2Fwww.facebook.com%2Fregalautosport&userId=4267568&signature=ceda8992c87e795f>
 | Twitter
<https://mailtrack.io/trace/link/8e32863730d7ee0502603884ffc45c9d8b577532?url=http%3A%2F%2Fwww.twitter.com%2Fregalautosport&userId=4267568&signature=5a0de7fa52b21bfd>
 | Instagram
<https://mailtrack.io/trace/link/cef6869584e4f83520740f1809e996a61afab637?url=http%3A%2F%2Fwww.instagram.com%2Fregalautosport&userId=4267568&signature=192a987552d9f561>
 | Blog
<https://mailtrack.io/trace/link/361ed81d433c64ba320a07eda5dd87f31077122b?url=http%3A%2F%2Fwww.regalautosport.com%2Fblog&userId=4267568&signature=31ee780406efb7a3>
Monday through Friday 0830hrs – 1730hrs
72-82 Belgrave Road, Southampton, SO17 3AN, UK
<https://mailtrack.io/trace/link/b8398d8c65552751e66989410e6fecae661b397b?url=https%3A%2F%2Fwww.google.co.uk%2Fmaps%2Fplace%2FRegal%2BAutosport%2F%4050.930744%2C-1.3837%2C17z%2Fdata%3D!3m1!4b1!4m2!3m1!1s0x487473e5838a39f7%3A0xe0a5ca9b19678845&userId=4267568&signature=8402286c6fc25446>

Regal Autosport (International)l Limited Email Legal Disclaimer: E-mails
and any attachments sent by Regal Autosport (International)l Limited are
intended for the named addressee(s) only, or person authorised to receive
them on their behalf. The content should be treated as confidential and the
recipient may not disclose the message or any attachment to anyone else without
authorisation. Unauthorised use, copying or disclosure may be unlawful.  If
any transmission is received in error please notify the sender immediately
and delete the message from your e-mail system. Any view expressed by the
sender of the message or any attachment may be personal and may not
represent the view held by Regal Autosport (International)l Limited.
All electronic
transmissions to and from Regal Autosport (International)l Limited,
may be monitored
and are scanned for viruses and content. E-mails containing viruses
will be deleted
without notification. Whilst we maintain virus checks on inbound
e-mails we accept
no liability for viruses or for any loss or damage arising from the use  of
any outgoing messages or other material introduced to outgoing messages.

**Comment by shue249** [comment]
@Steve-Regal Can you check on your database if you have this table and all 3 columns.

![image](https://user-images.githubusercontent.com/11957585/62770319-6067fb00-bacd-11e9-9aad-ed0ab5b89849.png)
