### ISSUE TITLE
Image not linked to the product is appearing in the catalog

### ISSUE THREAD

**Issue by pablomarttiins** [facebookincubator/Facebook-For-OpenCart#215]
After updating to the latest version of the plugin (2.1.10), on the Facebook catalogs page, in all my products, a gray background image appears, which is not of my products, follow image:

![1 - Imagens Não carregadas](https://user-images.githubusercontent.com/24293232/61379882-c79fe000-a87e-11e9-863a-86e08a3d041b.jpg)

And when I click on some product in the catalog, the first image remains that of gray background, follows image:

![2 - Imagem fundo cinza](https://user-images.githubusercontent.com/24293232/61380131-34b37580-a87f-11e9-872a-514fa5133c82.jpg)

By inspecting the element of the image above, I could see that it is coming from Facebook, follow image:

![3 - Link Imagem](https://user-images.githubusercontent.com/24293232/61380381-a4296500-a87f-11e9-89ad-1522a82c7f2d.jpg)

OpenCart Version: 2.3.0.2
Facebook Plugin Version: 2.1.10

Thanks in advance!

**Comment by shue249** [comment]
@pablomarttiins What is your catalog id?

**Comment by pablomarttiins** [comment]
Follow the print and catalog code:

Code: 2068210886629485

Image:

![4 - Código de catalogo](https://user-images.githubusercontent.com/24293232/61383659-7cd59680-a885-11e9-91ca-7c66dcb211b0.jpg)

**Comment by shue249** [comment]
@pablomarttiins We checked and found the catalog to be deleted. Is the catalog id correct?

**Comment by shue249** [comment]
@pablomarttiins Are you still facing any problems with the image on the new catalog?

**Comment by shue249** [comment]
Closing out this ticket. Feel free to reach to us if you have further questions.
