### ISSUE TITLE
How do you run ads from the Synced products?

### ISSUE THREAD

**Issue by TyrannosaurHex** [facebookincubator/Facebook-For-OpenCart#216]
Not sure if this is the correct place to ask this, but shouldn't there be an option to add the products in Facebook shop while creating a New Ad? How do I do this?

**Comment by shue249** [comment]
@TyrannosaurHex 
1. For running Facebook Dynamic ads, I can suggest for you to look at this document - https://www.facebook.com/business/ads/dynamic-ads

2. For adding of new products to Facebook shop and Facebook product catalog, the information can be found here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

We will be closing out this ticket. Feel free to reach to us if you have any further questions.
