### ISSUE TITLE
Showing product without tax

### ISSUE THREAD

**Issue by prismatix** [facebookincubator/Facebook-For-OpenCart#217]
Hi,

The prices are showing with no tax on facebook shop. The option "Show products with tax" is enabled on my shop backoffice. I'm using opencart 2.1.0.2

Anyone experienced this? Is there anything I can do to fix this?

Thanks in advance

**Comment by shue249** [comment]
@prismatix 

1. We are applying the product tax based on the tax class selected for the product. Can you check if the tax class is setup accordingly.
![image](https://user-images.githubusercontent.com/11957585/61609577-20a9b280-ac89-11e9-820c-30449c816305.png)

2. If this logic does not work for you, and if you have development resources, you can make the changes to the plugin code. The logic for setting the product price is here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L159

3. After making the changes, you will need to do a Resync of all the products on your website to Facebook through the Resync button on the Facebook Business Extension module.

**Comment by shue249** [comment]
@prismatix Are you still having any questions or issues with the product tax?

**Comment by shue249** [comment]
Closing this ticket. Feel free to reach to us if you have further questions.
