### ISSUE TITLE
Enable page shop after installation

### ISSUE THREAD

**Issue by PetrBren** [facebookincubator/Facebook-For-OpenCart#218]
Hello. During the installation process, in the section "Your products" I didn't toggle Page shop.

Is there a way to enable this later? I can't see it anywhere in the settings. The section "Your products" only offers an option to load the products.

edit: the OC versions is 2.3.0.2
Plugin Version: 2.1.10

**Comment by shue249** [comment]
@PetrBren There is no way to enable this later. If you wish to enable page shop later, the only way is to Delete away the existing settings which will trigger a new re-setup and you can enable page shop.

I will be closing off this ticket. Feel free to reach out to us if you have further questions.
