### ISSUE TITLE
Load products stuck on step 1 - creating source file

### ISSUE THREAD

**Issue by PetrBren** [facebookincubator/Facebook-For-OpenCart#219]
Hello. In the administration, under the section "Your products" when I choose Load, it seems to be loading forever and a bubble tooltip says "Products are importing: step 1 - creating source file". (Last succesfull update was two hours ago I don't recall doing any changes in server configuration since.) The OC versions is 2.3.0.2.

edit: in fact I changed the permissions from 770 to 777 because of another extension, but that shouldn't be a problem as 777 is more permissive than 770, right?
Plugin Version: 2.1.10

**Comment by shue249** [comment]
@PetrBren Do you see any red error messages displayed on the plugin module? If not, things should be working fine. You can verify this on the log file and see if there are any error message reported out.

You can read more on how we sync products from your website to Facebook - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog. The successful update you saw was the initial product sync using the feed file.

**Comment by shue249** [comment]
@PetrBren Any updates from your side, are you still encountering this error?

**Comment by shue249** [comment]
Will be closing out this ticket. Feel free to reach to us if you have further questions.
