### ISSUE TITLE
using http://freegeoip.net/

### ISSUE THREAD

**Issue by zavaruev** [facebookincubator/Facebook-For-OpenCart#22]
http://freegeoip.net/ had changed (https://github.com/apilayer/freegeoip#readme), so some modifications needed. Now extension raising error:
"The service[0] (//freegeoip.net/json/?callback={callback}) responded with the following error Error: Error [UNKNOWN]: Invalid response (SyntaxError: Unexpected end of JSON input)
    at o (cookieconsent.min.js:25)
    at Object.callback (cookieconsent.min.js:25)
    at e.runServiceCallback (cookieconsent.min.js:25)
    at cookieconsent.min.js:25
    at cookieconsent.min.js:25"

**Comment by shue249** [comment]
@zavaruev Thank you for your feedback! We have recently released a new version of our plugin - version 2.0.3 which addressed this problem. You can download the plugin either from OpenCart or from our release page here on github.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
