### ISSUE TITLE
Access token error keeps showing and the "Update token" button is not available.

### ISSUE THREAD

**Issue by harrysrevis** [facebookincubator/Facebook-For-OpenCart#221]
For the last few days after installing the Facebook Business Extension, after some time i get an error about updating the access token. 

What can i do to solve this? I had some products tagged and since i had to remove the broken versions and reinstall the new ones all my product tags have been removed and that messed up the whole situation. 

Any ideas? Thanks..

**Comment by RuDee-BG** [comment]
The button is in the setting of the extension, but when i click to get new token, facebook locks my FB account, then i have to change my password, and then again i have to reset the token and thing goes forever... please fix this...

**Comment by shue249** [comment]
@harrysrevis and @RuDee-BG Did you log out from Facebook account on your web browser?

**Comment by RuDee-BG** [comment]
> 
> 
> @harrysrevis and @RuDee-BG Did you log out from Facebook account on your web browser?

I don't log out, i just get new token, then when refreshing FB my account become locked, then i have to go throu some steps to verify my account, and then again i get error in opencart plugin

**Comment by RuDee-BG** [comment]
Do i have to log out first then get new token, then login again?

**Comment by harrysrevis** [comment]
@shue249 I didn't log out! Should i do this first? Moreover (since @RuDee-BG mentioned it) i had the same problem too with account lock down. I usually come up with this notification that someone tried to access my account and it should be locked in order to verify it first. 

I thought that someone tried to access my account but after seeing the problem mentioned i figured it out that it might be the extension that causes the problem!"

Any ideas?

**Comment by shue249** [comment]
@harrysrevis, @RuDee-BG You should not need to log out and you need to stay logged in.

Want to double confirm again, are you still getting this problem right now?

**Comment by RuDee-BG** [comment]
Let me check it out, i did leave the error message in OP admin panel for several days, cause i was tired changing FB password...

**Comment by harrysrevis** [comment]
@shue249 Let me check it please!

**Comment by harrysrevis** [comment]
@shue249 I deleted and reinstalled the pixel. I still don't have an "Update token" button appear but i will check if there will be any errors in the following 1-2 days!

**Comment by shue249** [comment]
Will be closing out this ticket. Feel free to reach to us if you have further questions.
