### ISSUE TITLE
error with Facebook Ads Extension setup

### ISSUE THREAD

**Issue by ivklau** [facebookincubator/Facebook-For-OpenCart#222]
There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.
The sync failure of your products to Facebook may be because of the large number of products on your system (We detected 168147 products).

Can help me?
OpenCart Version 3.0.3.1

And how can i set pixels for Facebook?

**Comment by shue249** [comment]
@ivklau Can you look into this FAQ section to see if it helps you - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

**Comment by shue249** [comment]
Will be closing out this ticket. Feel free to reach to us if you have further questions.
