### ISSUE TITLE
Can't sync products-Error with getting the initial product sync status

### ISSUE THREAD

**Issue by stefansxxl** [facebookincubator/Facebook-For-OpenCart#223]
Hi there, yesterday i upgraded my version to 2.1.10. Can't sync products, I attach the log file. Some error messages are displayed in Opencart.

**Error when querying FB page - Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.

Error**

The first error message disappears when I log into my facebook account. 
I can't be constantly logged on because I have another account, I don't care where it appears, I care that I can't sync my products. Do you have something to suggest?

[StefansXXL_2019-07-31_11-30-54_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3450619/StefansXXL_2019-07-31_11-30-54_facebook_ads_extension.log)

**Comment by shue249** [comment]
We are looking into a long term change to address this issue as well as to provide maximum security for the plugin users. For now, the suggested solution is to stay log into the facebook account.

Side note: same issue as reported here - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/185

**Comment by shue249** [comment]
@stefansxxl  

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

We will be closing out this ticket, feel free to reach to us on this ticket if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302
