### ISSUE TITLE
Problem with facebook store I can't manage

### ISSUE THREAD

**Issue by zigi00x** [facebookincubator/Facebook-For-OpenCart#224]
![image](https://user-images.githubusercontent.com/1354349/62387825-ffd03f80-b55b-11e9-8ed9-beafc33f3e2b.png)

Hello, I deleted a Facebook page I would create a new one and add it to the opencart stores, unfortunately I can't manage the stores in manage settings but i get error

**Comment by shue249** [comment]
@zigi00x Can you try to access the Manage Settings again to see if the Facebook Business Extension page loads for you.

**Comment by shue249** [comment]
Closing this ticket. Feel free to reach to us if you have further questions.
