### ISSUE TITLE
Got an error of product syncyng

### ISSUE THREAD

**Issue by snussik** [facebookincubator/Facebook-For-OpenCart#225]
I've made initial setup twice, but both times I see the error message. In log file of plugin there is no any criminal.

is 27k of products 2much? If so, how can I configure the plugin to extract some categories?

[Магазин строительных, хозяйственных товаров и крепежа - Частное предприятие «ГЕНХАНТ»_2019-08-04_16-02-28_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3465069/-._2019-08-04_16-02-28_facebook_ads_extension.log)

<img width="1155" alt="Screen Shot 2019-08-04 at 19 06 32" src="https://user-images.githubusercontent.com/16715490/62426273-3f796180-b6eb-11e9-9d30-16b38263c1f0.png">

**Comment by shue249** [comment]
@snussik 

You can refer to this FAQ on possible ways on how to resolve the large catalog problem - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

Another way is for you to set products which are not in use to Disabled status. These products will not be synced to Facebook and it will reduce the amount of products to be synced.
https://drive.google.com/open?id=1cKfe_oIX9Hbvcuqop4-Zxsgeyk3rZa_J

We will be closing out this ticket. Feel free to reach to us if you have further questions.
