### ISSUE TITLE
About low volume product synchronization

### ISSUE THREAD

**Issue by txwbaliever** [facebookincubator/Facebook-For-OpenCart#226]
I successfully installed this extension, but it was stuck in the step of checking the product upload status. I checked it with the pixel assistant. The code was inserted, but no events were triggered. My product was less than 100. I reloaded it. Still the same, the card is in the check upload status, and then an error is reported. When I first installed it, it was good. Later, the website was blacked out by facebook. I built a new site and it has never been successful since then, no matter if I use the new number. I want to know where the reason is.

**Comment by shue249** [comment]
@txwbaliever 

1. Can you share the screenshots of where the error on the product upload is. For context, you may want to read up on our FAQ on how we sync up the product catalog - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

2. What is the store website URL where the plugin is installed? We like to verify the pixel firing

**Comment by txwbaliever** [comment]
I can send my example website to you, the error is exactly the same, and because the plugin has been checking the product upload status, the background login will become very stuck, until the status check fails for a while, then continue to log in, screenshot I also posted on the attachment, the website http://demo.wujiangyun.com, the background is http://demo.wujiangyun.com/admin, the account number: demo, password: demo, you can help me find the problem. Thank you.


------------------ 原始邮件 ------------------
发件人: "shue249"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 中午11:28
收件人: "facebookincubator/Facebook-For-OpenCart"<Facebook-For-OpenCart@noreply.github.com>;
抄送: "叶孤橙"<624720432@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [facebookincubator/Facebook-For-OpenCart] About low volumeproduct synchronization (#226)




@txwbaliever
  
 
Can you share the screenshots of where the error on the product upload is. For context, you may want to read up on our FAQ on how we sync up the product catalog - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog
 
 
 
What is the store website URL where the plugin is installed? We like to verify the pixel firing

**Comment by txwbaliever** [comment]
Do you have any feedback?

**Comment by shue249** [comment]
@txwbaliever Can you share the log file from our plugin?

![image](https://user-images.githubusercontent.com/11957585/62769931-8fca3800-bacc-11e9-9b82-978fb743dc04.png)

**Comment by txwbaliever** [comment]
我可以下载日志，我发给你我的最后一个日志。


------------------ 原始邮件 ------------------
发件人: "shue249"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 下午5:40
收件人：  “facebookincubator / Facebook-For-OpenCart”<Facebook-For-OpenCart@noreply.github.com>;
抄送: "叶孤橙"<624720432@qq.com>;"Mention"<mention@noreply.github.com>;
主题：  Re：[facebookincubator / Facebook-For-OpenCart]关于低容量产品同步（＃226）




@txwbaliever你能从我们的插件共享日志文件吗？
 

 
- 
你收到这个是因为你被提到了。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by txwbaliever** [comment]
I want to ask if your problem has been solved? I haven't received your reply for a long time.




------------------ 原始邮件 ------------------
发件人: "shue249"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 中午11:28
收件人：  “facebookincubator / Facebook-For-OpenCart”<Facebook-For-OpenCart@noreply.github.com>;
抄送: "叶孤橙"<624720432@qq.com>;"Mention"<mention@noreply.github.com>;
主题：  Re：[facebookincubator / Facebook-For-OpenCart]关于低容量产品同步（＃226）




@txwbaliever
  
 
您能否分享产品上传错误的屏幕截图。有关上下文，您可能需要阅读我们的常见问题解答，了解我们如何同步产品目录 - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart -products到Facebook的目录
 
 
 
安装插件的商店网站URL是什么？我们想验证像素点火
 
   
- 
你收到这个是因为你被提到了。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by shue249** [comment]
@txwbaliever Can you attach the log file directly to the github ticket instead of replying from email, as attachments sent out from the email will not be sent to us.

**Comment by txwbaliever** [comment]
This is the log of my last failure. What documents do you need?
[中轴精工_2019-08-06_02-15-54_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3494926/_2019-08-06_02-15-54_facebook_ads_extension.log)

**Comment by shue249** [comment]
@txwbaliever After looking at the log file, the last part of the log shows that the required settings are all successfully populated on your system. Are you still encountering any errors on updating the product details?

Can you do this:
1. Trigger a product save - search for any product, edit and click on save. The product update to Facebook will be triggered and the results logged.
2. Re-download the log file. We want to inspect the log file to see the status of the product update to Facebook catalog.

**Comment by txwbaliever** [comment]
I added 5 items, but the background is still stuck in the display to check the product upload status. I will send you screenshots and error logs.
![微信图片_20190814175319](https://user-images.githubusercontent.com/50563174/63012377-b4ebeb80-bebc-11e9-8601-87807d68247f.png)
![微信图片_20190814175329](https://user-images.githubusercontent.com/50563174/63012382-b6b5af00-bebc-11e9-8af6-935811c8e0d5.png)
[Demo Store_2019-08-14_09-52-24_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3500811/Demo.Store_2019-08-14_09-52-24_facebook_ads_extension.log)

**Comment by txwbaliever** [comment]
What is the cause of this? I really need this plugin urgently.

**Comment by shue249** [comment]
@txwbaliever We looked through your log file, but we were not able to replicate the error on our side. The failure happens on the part when our plugin tries to create the Facebook feed for the initial catalog sync, and the error message returned is just null.

![image](https://user-images.githubusercontent.com/11957585/63235170-086a8a80-c26b-11e9-9941-d9d747f2dfc4.png)

What is the Facebook Page that you are using during the Facebook Business Extension setup? Will you be able to test with a new Facebook page?

**Comment by shue249** [comment]
Closing out this ticket. Feel free to reach to us if you have further questions.
