### ISSUE TITLE
trying to install 

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#227]
Trying to install the extension but it keep saying wrong file format @shue249

**Comment by shue249** [comment]
@KonstantinGOT Can you check these 2 links below:

1. https://drive.google.com/open?id=1NH0yR9X6C49M_CMGtuh2qvNoX_iMuIp-

2. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/62

**Comment by shue249** [comment]
Closing this ticket. Feel free to reach to us if you have further questions.
