### ISSUE TITLE
Error when setting up because currency (TWD) is not supported

### ISSUE THREAD

**Issue by AngelicaLinLin** [facebookincubator/Facebook-For-OpenCart#228]
Hello, When I try to go through the installation process and connect my Facebook pixel, this error appears: 

The plugin can't be set up because your currency (TWD) is not supported. 

I saw the other thread that addresses this error, I've made the adjustments but I am still getting this error.

Here are screenshots of my setup. 
<img width="1118" alt="Screen Shot 2019-08-15 at 9 51 45 AM" src="https://user-images.githubusercontent.com/37519961/63111680-12c31680-bf43-11e9-9103-68f9ec8cdbb5.png">
<img width="1077" alt="Screen Shot 2019-08-15 at 9 51 05 AM" src="https://user-images.githubusercontent.com/37519961/63111689-16569d80-bf43-11e9-802c-837b678c2326.png">

Thanks for the help!

**Comment by shue249** [comment]
@AngelicaLinLin Can you try the Facebook Business Extension setup again and see if the error still happens. If so, can you share a screenshot of the error.

**Comment by shue249** [comment]
Closing this ticket. Feel free to reach to us if you have further questions.
