### ISSUE TITLE
GeoIP issues...http://freegeoip.net/shutdown

### ISSUE THREAD

**Issue by hrm143** [facebookincubator/Facebook-For-OpenCart#23]
API provided by freegeoIP not working..it is now throwing out Errors on my website becuz of this

**Comment by shue249** [comment]
@hrm143 Thank you for your feedback! We have recently released a new version of our plugin - version 2.0.3 which addressed this problem. You can download the plugin either from OpenCart or from our release page here on github.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
