### ISSUE TITLE
Extension Is Creating Suspicious Activity for Facebook?...

### ISSUE THREAD

**Issue by ryanstacey** [facebookincubator/Facebook-For-OpenCart#230]
Recently Facebook has been locking my account every week for 'suspicious activity' and making me change my password. The issue is I'm extremely safe online and it's not saying that someone has logged in from XYZ location or that XYZ device has logged in.

It's not someone 'trying' to login, it's someone successfully logging in and therefore creating suspicious. The only thing I can think is that this extension is constantly connected to my facebook and every time I change my password and have to re-login to open cart and update the token, it then has access again.

I don't know if anyone else is having this issue but this is the only realistic source I can think its coming from.

**Comment by shue249** [comment]
@ryanstacey Thank you for the feedback. We are now working on backend changes to solve this problem entirely. We will keep you posted when we have any latest updates soonest.

**Comment by dyslexicdrakness** [comment]
Hello! I have at least 1 of my clients experiencing the same issue... He's unable to say that the IP/source/app is safe and is forced to change password and then resync and so on...

**Comment by dyslexicdrakness** [comment]
@shue249 any news?

@ryanstacey is it still happening to you?

**Comment by shue249** [comment]
@ryanstacey , @dyslexicdrakness  

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

We will be closing out this ticket, feel free to reach to us on this ticket if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302
