### ISSUE TITLE
Facebook Ads Extension error - "Sorry, something went wrong"

### ISSUE THREAD

**Issue by dkunal01** [facebookincubator/Facebook-For-OpenCart#231]
I have been trying to integrate facebook ads extension in opencart but I am getting this error message "Something went Wrong" whenever i click on 'Manage Settings'.

I tried removing and re-installing the extension but the error still persists.

I have also manually deleted all the files related to this extension and re-installed with the updated version but still the error exists.

Note: My previous FB page was working fine but now i have changed to a new page and this error occurs.

Opencart Version 2.3.0.2
Facebook Ads Extension Version: 2.1.10

How can you help me?

**Comment by shue249** [comment]
@dkunal01 

1. Will you be able to check again if this problem remains.

2. If the problem exists, do you have any existing catalog sales ads running which is using the catalog from the plugin? If not, you can manually remove away the plugin settings from the database. You can follow the steps here - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/177#issuecomment-495930585

**Comment by shue249** [comment]
Closing this ticket. Feel free to reach to us if you have further questions.
