### ISSUE TITLE
I deleted my Facebook store.Help please

### ISSUE THREAD

**Issue by mrtektr** [facebookincubator/Facebook-For-OpenCart#232]
I deleted my Facebook page and store, opencart tan old store id how do I delete, or change?

thank you.
good work

**Comment by shue249** [comment]
Are you able to still access the Manage settings of the plugin and remove the existing settings to re-setup again? You can follow the steps here - https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

**Comment by mrtektr** [comment]
the advanced settings tab does not appear, ie it does not.
opencarttan store id database how to delete.

Thank you

**Comment by shue249** [comment]
@mrtektr Can you look at this post to see if it helps. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/177#issuecomment-495930585. You will need ability to connect to your database

**Comment by mrtektr** [comment]
Nasıl telaffuz edildiğini öğrenin
Can we make visual expression?
code: Where is Facebook?
thank you.

**Comment by mrtektr** [comment]
Can we make visual expression?
code: Where is Facebook?
thank you.

**Comment by mrtektr** [comment]
delete from setting where code = 'facebook';
code is running error.
How can I fix.
![hata](https://user-images.githubusercontent.com/46427050/63634107-8effdd00-c65a-11e9-830e-735d4f422a46.jpg)

Thank you

**Comment by shue249** [comment]
@mrtektr When you setup OpenCart, did you change the database prefix, as the default prefix is "oc_".

You can try to run this SQL command - 

DELETE FROM oc_setting WHERE code = 'facebook';

**Comment by shue249** [comment]
Closing this ticket. Feel free to reach to us if you have further questions.
