### ISSUE TITLE
chat messenger no está en mi página

### ISSUE THREAD

**Issue by cgonzalez-p** [facebookincubator/Facebook-For-OpenCart#234]
Hola. Instalé y configuré plugin y todo parece ok. Agregué la función disponible "chat de messenger" pero en mi web no aparece la busbuja https://canaldeventasdigitalescgp.com/ , ni en mi página de producto https://canaldeventasdigitalescgp.com/index.php?route=product/product&path=59_66&product_id= 60 ¿Cómo soluciono? :(

**Comment by shue249** [comment]
@cgonzalez-p Have you followed the installation and setup steps here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation? We looked through your website and could not find both the pixel and messenger chat plugin.

**Comment by cgonzalez-p** [comment]
Volví a revisar y confirmado seguimiento pasos. La extensión aparece en el menú, configuración plugin ok y función disponible de chat ok. Catálogo sincronizado con tienda página de negocio ¿Qué puede estar sucediendo?
![image](https://user-images.githubusercontent.com/54340494/63662351-ca49fb00-c783-11e9-8ea8-7360e361ecd7.png)

**Comment by msincar2** [comment]
isterseniz yardımcı olabiliri  ingilizcem iyi değil translate kullanırız

26 Ağu 2019 Pts 06:05 tarihinde cgonzalez-p <notifications@github.com> şunu
yazdı:

**Comment by cgonzalez-p** [comment]
Merhaba. Eklentiyi yükledim ve yapılandırdım ve her şey yolunda görünüyor. Kullanılabilir "mesajlaşma sohbeti" işlevini ekledim, ancak https://canaldeventasdigitalescgp.com/ web sitemde veya ürün sayfamda https://canaldeventasdigitalescgp.com/index.php?route=product/product&path= 59_66 & product_id = 60 Nasıl çözerim? :(

**Comment by cgonzalez-p** [comment]
Gözden geçirmek için geri döndüm ve takip adımları onayladım. Uzantı menüde, eklenti yapılandırması tamam ve sohbet işlevi tamam görünür. Mağaza iş sayfasıyla senkronize edilmiş katalog ¿Ne oluyor?

**Comment by shue249** [comment]
@cgonzalez-p Can you check the 2 suggestions on this post and see if it helps you.
https://github.com/facebookincubator/Facebook-For-OpenCart/issues/235#issuecomment-524798402

**Comment by shue249** [comment]
@cgonzalez-p Is the suggestions helping you on the Messenger chat plugin?

**Comment by cgonzalez-p** [comment]
No :(  sigo probando todo lo que encuentro en la literatura y no detecto qué corregir.

**Comment by cgonzalez-p** [comment]
> @ cgonzalez-p ¿Ha seguido los pasos de instalación y configuración aquí: https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation ? Revisamos su sitio web y no pudimos encontrar el complemento de chat de píxeles y mensajería.

![image](https://user-images.githubusercontent.com/54340494/64205769-6055e380-ce5e-11e9-97b5-5b7a018aea24.png)
Sigo sin solucionar que la burbuja no aparezca :(

**Comment by shue249** [comment]
@cgonzalez-p Can you try to remove the current plugin and install in an earlier version of 2.1.8. Then do a refresh and see if the messenger chat appears - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.8

**Comment by cgonzalez-p** [comment]
@shue249 estoy revisando detalladamente heater y footer y si no soluciono prueba con esta última indicación. pronto reporto resultados =)

**Comment by cgonzalez-p** [comment]
@shue249 perfecto!!!! gracias =) Funcionando caché, pixel, catálogo, burbuja de chat. ¿Estoy perdiéndome de algo al estar dos versiones atrás del plugin?

**Comment by shue249** [comment]
@cgonzalez-p We made a change in version 2.1.9 which moves the messenger chat plugin from footer to header. However this is the change which also makes it unsuitable for your setup.

We are now looking on improving to make the chat plugin even more robust so that it can suit your case.

For now, pls use 2.1.8 first and once we have the new version ready, you can upgrade it.

**Comment by shue249** [comment]
@cgonzalez-p We have released a new version of the plugin 2.1.11, which should have solved your problem for the messenger chat plugin. Can you try the new version and let us know if it works.

**Comment by shue249** [comment]
Will be closing out this request. Feel free to reach to us if you have further questions
