### ISSUE TITLE
Pixel not firing

### ISSUE THREAD

**Issue by burockwoo** [facebookincubator/Facebook-For-OpenCart#235]
I was write manually facebook pixel code with analytic extension.
But same pixel wasn't true.Than i remove this and i set facebook ads extencion.
Page see catalog but pixel not firing.
Please help me. Thank you for your support now.
<img width="1277" alt="Ekran Resmi 2019-08-25 16 22 30" src="https://user-images.githubusercontent.com/54508454/63653483-ff4f5100-c775-11e9-9a31-1f3dc3805bb3.png">

**Comment by shue249** [comment]
We have a latest version, 2.1.10 - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.10

Can you delete away the existing 2.1.3 version from your Opencart and then install the 2.1.10 version. Ensure that you have disabled the theme and SASS cache. Finally you can verify if the pixel is fired correctly. https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm

**Comment by burockwoo** [comment]
Hi sir, again. facebook_pixel_2_1_10.js it doesn't include this file. I thing it is the problem.

// we are storing all the pixel data in the fbevents parameters
      // this fbevents will be sent over to the header.php
      // which will then be sent to the header.tpl as $data to be
      // fired as FB pixel events via javascript

Js file is not loading homepage.

**Comment by shue249** [comment]
What is your website URL?

**Comment by burockwoo** [comment]
www.gotham.com.tr

**Comment by shue249** [comment]
I checked on your website and found that the pixel firing is correct. Can you check if your theme and SASS cache are disabled - https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm

![image](https://user-images.githubusercontent.com/11957585/63658877-aff23a80-c7e0-11e9-88f6-f4cabb0973fd.png)

**Comment by Aeeneas** [comment]
Hi, i have a similar problem.
Pixel Helper don't see pixels on the site
https://statuetts.ru/
But fb business manager linked with pixel in installation

**Comment by Aeeneas** [comment]
Plagin Messendger also doesn't work

**Comment by burockwoo** [comment]
It doesn’t work. I add pixel to header.tple with manually.
So you can see my pixel.
Ads extension doesn’t add pixel to header.tpl than i add manually.


26 Ağu 2019 Pzt, saat 04:49 tarihinde Larin Maxim <notifications@github.com>
şunu yazdı:

**Comment by shue249** [comment]
@burockwoo can you remove the manual codes, so that we can debug and troubleshoot.

@burockwoo and @Aeeneas 
1. Can you check if you have disabled the theme and SASS cache
2. Can you check if you have made modifications to the header and footer via the Design -> Theme editor? If so, can you remove those modifications?
![image](https://user-images.githubusercontent.com/11957585/63682309-33844980-c82a-11e9-9781-bedc763ea40d.png)

**Comment by testingCitytech** [comment]
I have installed the extension successfully download from `https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336` this link and I have using Opencart 2.0.3.1
![Page Not Found!](https://user-images.githubusercontent.com/54580411/63860855-7891b280-c9c7-11e9-8c6d-dc2b4803cf1e.png)
![Modifications (1)](https://user-images.githubusercontent.com/54580411/63861024-bdb5e480-c9c7-11e9-8cdb-487dcfac45e7.png)

**Comment by shue249** [comment]
@burockwoo  and @Aeeneas Are you able to resolve your problems?

**Comment by burockwoo** [comment]
Hey.
I solve my problem to different way. I guess because my special theme.But its fine now working.
But i change my facebook password because facebook want this because secretiy reason.
Than i have this problem -> 
There is an error making API calls using the access token. The error encountered is "Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.".
To update your access token, please click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Update token.

https://github.com/facebookincubator/Facebook-For-OpenCart/issues/159 <https://github.com/facebookincubator/Facebook-For-OpenCart/issues/159> I look at this but i don’t solve my problem. Please help me.Thank you from now.

**Comment by burockwoo** [comment]
I solved.
https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142 <https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142>
Thank to this page.

**Comment by cgonzalez-p** [comment]
@burockwoo entro a tu web https://gotham.com.tr/index.php?route=product/category&path=59
 y no veo la burbuja del chat ¿La quitaron?
Web sitene giriyorum ve ben sohbet balonunu göremiyorum

**Comment by burockwoo** [comment]
yeah that's right.
because i dont want it.

**Comment by shue249** [comment]
Thank you all for the feedback. We will close off this ticket based on the original problem where the pixel is not firing. Feel free to reach to us if you have further questions.
