### ISSUE TITLE
Error in facebookeventparameters.php

### ISSUE THREAD

**Issue by nijones05** [facebookincubator/Facebook-For-OpenCart#236]
I have an error that keeps appearing

PHP Warning:  A non-numeric value encountered in /catalog/controller/extension/facebookeventparameters.php on line 399

I'm not sure which line that is or how to fix it.
Any help would be appreciated.

Thanks

**Comment by shue249** [comment]
@nijones05 Apologies for this late reply. What is the version of the plugin you are using? We have a latest version 2.1.11, can you try to use this version and see if you are still getting this error.

**Comment by nijones05** [comment]
Hi, Thanks but i no longer use opencart so this issue no longer applies.

Regards

Nic

**Comment by shue249** [comment]
Will be closing out this request. Feel free to reach to us if you have further questions
