### ISSUE TITLE
Does This work with 3.0.3.2

### ISSUE THREAD

**Issue by Ashon95** [facebookincubator/Facebook-For-OpenCart#237]
Does This work with 3.0.3.2

**Comment by shue249** [comment]
Duplicated https://github.com/facebookincubator/Facebook-For-OpenCart/issues/202

**Comment by shue249** [comment]
Hi there, we have verified that you can use the current 2.1.10 version of our plugin on OC version 3.0.3.2.

We will be closing out this ticket for now.
