### ISSUE TITLE
Facebook Ads Extension Not Working for Opencart 2.0.3.1

### ISSUE THREAD

**Issue by testingCitytech** [facebookincubator/Facebook-For-OpenCart#238]
I have installed the extension successfully but I could not access Product, Dashboard page from admin panel please see the screenshot.

Showing this error

> Fatal error: Class 'FacebookGraphAPIError' not found in C:\xampp\htdocs\msseduction\system\modification\admin\controller\common\dashboard.php on line 33

I have using Opencart 2.0.3.1

![Modifications (1)](https://user-images.githubusercontent.com/54580411/63862404-230ad500-c9ca-11e9-887c-5498abfe0ee1.png)
![Page Not Found!](https://user-images.githubusercontent.com/54580411/63862417-29994c80-c9ca-11e9-9b99-96dfb0ac7157.png)

**Comment by shue249** [comment]
1. What is the plugin version you are using? Our latest version is 2.1.10
2. Can you check if the file FacebookGraphAPIError.php exists in this folder on your webserver - system/library

**Comment by testingCitytech** [comment]
I installed the version 2.1.6 and fetch the same problem. after uninstall and re-install your latest version 2.1.10 Please Check out the screenshot above. but I'm facing same problems again.

and I am trying to install your plugin V-2.1.10 in Opencart 3 it's successfully installed and working fine.

But I need to install in Opencart Version 2.0.3.1

I cannot find out `FacebookGraphAPIError.php` file in system/library folder

installed both of version plugin.
![Modifications (1)](https://user-images.githubusercontent.com/54580411/63913299-50e52d80-ca4d-11e9-9e2c-2b0b178ce960.png)

**Comment by shue249** [comment]
@testingCitytech Can you ensure that you have given read+write folder access to the admin, catalog and system folders for your opencart webserver. The problem with missing files is because of lack of write folder permission to copy the files from the plugin zip to your webserver.

**Comment by testingCitytech** [comment]
I have customized the Opencart folder structure, I saw that the folder structure are not the same I think that's the problem.

My Folder Structure 
`i have renamed the folder admin to other_side `
Please see the screenshot of my Opencart folder structure

![Untitled-crop](https://user-images.githubusercontent.com/54580411/64104296-9c6f4280-cd91-11e9-8b83-cb68a9e08efc.jpg)

And this is your Extension folder structure
Please see the screenshot

![Untitled-crop-2](https://user-images.githubusercontent.com/54580411/64104946-e3116c80-cd92-11e9-8334-5ccf43899eee.jpg)

> The basic difference here is that the folders in my module are out of the extension folder and Your module folder exist in the extension folder.

If you can help me in any way, I can solve it.

**Comment by testingCitytech** [comment]
yes, it is working I have modified the code for my Opencart folder structure.
Thank you.

**Comment by tksir** [comment]
testingCitytech, can you please help me on something?

**Comment by testingCitytech** [comment]
> testingCitytech, can you please help me on something?

Yes How can I help you ?

**Comment by tksir** [comment]
testingCitytech, my case is that fb chat box is not shown on my web site home. Why is that?

**Comment by testingCitytech** [comment]
I have no idea about FB chat, This is the Facebook Ads Extension issue.

**Comment by shue249** [comment]
@tksir Let us follow up with your problem on this issue https://github.com/facebookincubator/Facebook-For-OpenCart/issues/242
