### ISSUE TITLE
Support for OC Multi Store

### ISSUE THREAD

**Issue by foshdafosh** [facebookincubator/Facebook-For-OpenCart#241]
I can't seem to get this working on a multi store installation, it looks like this isn't supported yet.
Do you have plans to implement this?

**Comment by shue249** [comment]
Thanks for the feedback. We are aware of this issue, it is not on the immediate roadmap yet as we are working through other issues now

Similar issue - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/71

**Comment by foshdafosh** [comment]
Thanks for letting me know, I'll subscribe to the similar issue.
