### ISSUE TITLE
Facebook Chat Option not shown on website

### ISSUE THREAD

**Issue by tksir** [facebookincubator/Facebook-For-OpenCart#242]
I did all the things according to instructions. Of course, I am really happy with all the other things except for the chat option is now shown on my fb page. https://119sldeals.com/ This is my website. Please let me know what to do.

**Comment by tksir** [comment]
https://119sldeals.com/

**Comment by shue249** [comment]
@tksir Is the plugin still installed on your website?

**Comment by tksir** [comment]
@shue249, Yes shue249.

**Comment by tksir** [comment]
Yes, I still have it.

**Comment by tksir** [comment]
@shue249 , please let me know why the fb chat option is now show on my website home.

**Comment by shue249** [comment]
@tksir We checked on your website and found that both pixels and the messenger chat plugin are not available. Here are few things you can check:

1. Did you click on the Refresh button? View this screenshot - https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw

2. Are you on OpenCart 3.x? If so, here are 2 things you can try
    a. Disable the theme and SASS cache. View this screenshot - https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm

    b. Check that you did not edit the header design template - https://drive.google.com/open?id=1066BSKAqjKegzw-5oKuvtZuzu_PzkRZT

3. If the above 2 steps do not work, can you re-install the plugin (delete, install and refresh) and share the install log file and modified template file with us. 
![image](https://user-images.githubusercontent.com/11957585/64231178-75477b00-cf21-11e9-828f-44fbed13f446.png)

![image](https://user-images.githubusercontent.com/11957585/64231285-bf306100-cf21-11e9-9f1b-bf5347073243.png)

**Comment by tksir** [comment]
Shue249, thanks for the update. I worked it out.
