### ISSUE TITLE
An error occurred after merging the home page.

### ISSUE THREAD

**Issue by oyzbmmmm** [facebookincubator/Facebook-For-OpenCart#243]
![1567417943(1)](https://user-images.githubusercontent.com/54800056/64106279-7013f000-cdaa-11e9-9218-f1ce42384586.jpg)
An error occurred after merging the home page.

**Comment by shue249** [comment]
@oyzbmmmm 

1. Can you share more details on what do you mean by "merging the home page"

2. For this problem, you will need to reset the settings on the installation. Can you follow the steps here to see if you can delete away the settings data. Do note that your settings table could be oc_setting (depending on what is the database prefix you used)

**Comment by oyzbmmmm** [comment]
1: I had two Facebook homepages before, and then I merged them.
The homepage I keep is not open cart bound.

2: Show the steps for delete settting data pls,

**Comment by shue249** [comment]
@oyzbmmmm Apologies, missed out the steps link. Here is it https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142#issuecomment-482908951

**Comment by shue249** [comment]
@oyzbmmmm Apologies for missing the link. Here you go - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/177#issuecomment-495930585

**Comment by oyzbmmmm** [comment]
OK. IT'S WORK 

Thanks

**Comment by shue249** [comment]
We will be closing this ticket. Feel free to reach to us if you have further questions.
