### ISSUE TITLE
HTTP 500 error

### ISSUE THREAD

**Issue by doviis** [facebookincubator/Facebook-For-OpenCart#245]
Hello,
I am using OC 3.02, Journal v2 theme. I have installed Facebook extension from Opencart marketplace, however it did not work normally so I decided to delete it. Now I am getting HTTP 500 errors while accessing my website. What should I do to solve the problem?

Errors:
`Wed Sep 04 06:46:37.567892 2019] [:error] [pid 1190] [client] PHP Fatal error:  Uncaught Error: Class 'FacebookCommonUtils' not found in /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_catalog_controller_common_header.php:92\nStack trace:\n#0 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_action.php(79): ControllerCommonHeader->index(Array)\n#1 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_loader.php(51): Action->execute(Object(Registry), Array)\n#2 /var/www/storage/modification/catalog/controller/common/home.php(52): Loader->controller('common/header')\n#3 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_action.php(79): ControllerCommonHome->index()\n#4 /var/www/html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry))\n#5 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_action.php(79): ControllerStartupRouter->index()\n#6 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_router.php(150): Action->execute(Object(Registry) in /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_catalog_controller_common_header.php on line 92
[Wed Sep 04 06:46:47.654941 2019] [:error] [pid 580] [client ] PHP Fatal error:  Uncaught Error: Class 'FacebookGraphAPIError' not found in /var/www/storage/modification/admin/controller/common/dashboard.php:33\nStack trace:\n#0 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_action.php(79): ControllerCommonDashboard->index()\n#1 /var/www/html/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array)\n#2 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_action.php(79): ControllerStartupRouter->index()\n#3 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_router.php(150): Action->execute(Object(Registry))\n#4 /var/www/html/vqmod/vqcache/vq2-_var_www_storage_modification_system_engine_router.php(139): Router->execute(Object(Action))\n#5 /var/www/html/system/framework.php(168): Router->dispatch(Object(Action), Object(Action))\n#6 /var/www/html/vqmod/vqcache/vq2-system_startup.php(104): require_once('/var/www/html/s...')\n#7 /var/www/html/admin/index.php(23): start('admin')\n#8 {main}\n  thrown in /var/www/storage/modification/admin/controller/common/dashboard.php on line 33, referer: https://mywebsite.com/admin
`

Tried to delete VQMOD cache, but every time it creates new files so I need to find problem somewhere else.
Thanks

**Comment by shue249** [comment]
@doviis Have you refresh the extension modifications? It is needed after every changes to the modules. See this screenshot - https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw

**Comment by shue249** [comment]
Closing out this ticket. Feel free to reach to us if you have further questions.
