### ISSUE TITLE
pleas help me.

### ISSUE THREAD

**Issue by altruismbike** [facebookincubator/Facebook-For-OpenCart#247]
My product can't sync to Facebook store.
Always prompt the following error message.
![777777777777777](https://user-images.githubusercontent.com/35982450/64361986-3cea8e80-d040-11e9-9294-a050ec10d669.JPG)
please help us.Thanks

There is an error making API calls using the access token. The error encountered is "".
To update your access token, please click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Update token.

**Comment by shue249** [comment]
Hi there!

Can you check this screenshot and see if the steps help you - https://drive.google.com/open?id=18koOQZmV3ra6wMsjsaWUPDuYZR_phl3J

**Comment by altruismbike** [comment]
Hi，No work.
Thanks

**Comment by shue249** [comment]
@altruismbike Can you share more context on the failure, and where it failed to work.

**Comment by palangiux** [comment]
what have to do with this ocmod file now?

**Comment by palangiux** [comment]
doesnt help this ocmod

**Comment by shue249** [comment]
@palangiux We have replied to you on your ticket, can you take a look and see if it works.

**Comment by shue249** [comment]
Closing out this ticket. Feel free to reach to us if you have further questions.
