### ISSUE TITLE
Facebook messenger plugin

### ISSUE THREAD

**Issue by regko** [facebookincubator/Facebook-For-OpenCart#248]
I've installed the Facebook Ads Extension. Pixel and product work as expected but I am facing an issue with the messenger plugin, it is not displayed on website. I've followed the instruction that I found from Github, cleaning all the caches but still no luck.

Opencart version: 3.0.2.0

Website: praesto.xyz

**Comment by shue249** [comment]
@regko Can you try to remove away the current plugin and install the 2.1.8 version of the plugin. We made a change in v2.1.9 and moved the chat plugin codes from footer to header and this may be the case. We want to see if the chat plugin is shown up in v2.1.8 on your website.

https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.8

**Comment by shue249** [comment]
@regko We checked on your website and found that the pixel is also not shown. We suspect this is to do with the header file not changed.

Can you check if you have made any changes to the header design template and if so, can you delete away the modifications (see screenshot) https://drive.google.com/open?id=1066BSKAqjKegzw-5oKuvtZuzu_PzkRZT

**Comment by regko** [comment]
@shue249 it's working now, after removing the header design template. Thanks for your help!!
