### ISSUE TITLE
Error Token - Security Problems

### ISSUE THREAD

**Issue by reginamor** [facebookincubator/Facebook-For-OpenCart#249]
I have a problem with this extension.
Even 2 o 3 days, facebook block my account because detect that i made a insecure login.
So i have to change the password, update the token 2 o 3 times per week on my 3 webs
This problem starts with the last oficial update of the extensión.

How can i fix it? 
I don't have more passwords on mi head XD

**Comment by shue249** [comment]
Thanks for the feedback. We are working hard on this case now, but it involves more work than expected. We will update you once we have the update soonest.

Similar case reported https://github.com/facebookincubator/Facebook-For-OpenCart/issues/230

**Comment by dyslexicdrakness** [comment]
Hey @shue249 ! I'm sorry to keep nagging you on this but my clients are asking for an update, do you have a time frame for the fix on this?

**Comment by shue249** [comment]
@reginamor , @dyslexicdrakness  

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

We will be closing out this ticket, feel free to reach to us on this ticket if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302
