### ISSUE TITLE
Facebook Ads

### ISSUE THREAD

**Issue by travveler65** [facebookincubator/Facebook-For-OpenCart#250]
Hello,
I've activated FB Ads in Opencart 2.3 and have now no access to admin panel.
Can someone help?

**Comment by shue249** [comment]
@travveler65 Did you upgrade the old plugin to the latest version? If so, can you check this post if the solution works for you.

If it doesnt work, can you share more details on what is the error you are seeing on the admin panel and the error logs from your webserver.

**Comment by shue249** [comment]
@travveler65 Missed out the link earlier - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/189

**Comment by shue249** [comment]
@travveler65 Are you still facing problem with the plugin?

**Comment by shue249** [comment]
Closing out this ticket, feel free to reach to us if you have further questions.
