### ISSUE TITLE
Facebook-For-OpenCart  - type of product Category

### ISSUE THREAD

**Issue by vgidok** [facebookincubator/Facebook-For-OpenCart#251]

**Comment by vgidok** [comment]
Hello.
Opencard version 2.3.0.2.3
The Facebook-For-OpenCart module has been installed successfully. The catalog was successfully added to the facebook store.
The product information on the "Category" is and pulls up with sub categories of the second level of the online store.
But in the product information, "type of product" is empty, but should pull up the main category ID from the online store !!!
Can you fix this problem?
thank.

**Comment by vgidok** [comment]
There is still a small problem with the yellow triangle in the Facebook Pixel Helper add-on.

---AddToCart

WARNINGS
The value for 'currency' is not formatted correctly. We were expecting a currency code without currency symbol (e.g. "USD").Learn more
CUSTOM PARAMETERS SENT
content_type: product
content_ids: ["2996"]
value: 71
num_items: 1
content_name: Show
currency: UAH
EVENT INFO
URL Called: Show
Load Time: 29.26 ms
Pixel Location: Show
Matched Products: 2996,2996

**Comment by vgidok** [comment]
established Facebook for OpenCart v2.1.10

**Comment by shue249** [comment]
@vgidok 

1. For the product side, we are syncing to the category field. 
![image](https://user-images.githubusercontent.com/11957585/66395959-3c606180-ea0b-11e9-9ee5-99732a876ea7.png)

2. For the pixel firing, is this still an issue on your website? We tested the UAH currency and did not receive the warning sign on pixel helper.

**Comment by vgidok** [comment]
It turned out that the default USD was in the ADS Manager settings. Changed on UAH the problem is gone.

**Comment by vgidok** [comment]
Good afternoon.
Will there be further improvements to this add-on?
1. Type of category?
2. Auto update Access Token when changing the password to Facebook. (since you have to go to the admin panel of the online store each time to manually update the Access Token)

I enclose the photo in a letter.
Thank.



@vgidok

For the product side, we are syncing to the category field.


For the pixel firing, is this still an issue on your website? We tested the UAH currency and did not receive the warning sign on pixel helper.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



-- 
С уважением,
 vgidok                          mailto:vgidok@ukr.net

**Comment by shue249** [comment]
@vgidok  Thanks for the feedback
1. For the category field, we have to put it as a enhancement but we do not have resources to work on this now. If you have development resources, you can consider making the changes yourself. The code pointer will be here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L87

2. We are working now to solve the access token issue by replacing the entire catalog sync mechanism, where this is our main focus now. We will update you soonest when this is fixed.

**Comment by shue249** [comment]
@vgidok  

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

We will be closing out this ticket, feel free to reach to us on this ticket if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302
