### ISSUE TITLE
manage settings

### ISSUE THREAD

**Issue by palangiux** [facebookincubator/Facebook-For-OpenCart#254]
want update token but cant enter manage settings in my admin panel page not found please help me

**Comment by palangiux** [comment]
![facebook](https://user-images.githubusercontent.com/55613475/65368617-2cdfcb00-dc4c-11e9-8c8d-2e62b56e53f2.png)

**Comment by palangiux** [comment]
![facebook1](https://user-images.githubusercontent.com/55613475/65368624-3c5f1400-dc4c-11e9-895c-5c43ce90a6dd.png)

**Comment by palangiux** [comment]
Any ideas please

**Comment by shue249** [comment]
@palangiux Do you have any ad blocker or VPN installed? If so, can you try to disable them?

**Comment by palangiux** [comment]
Dobt have any blocker or vpn

Sent from Yahoo Mail on Android 
 
  On pr, rugs. 23, 2019 at 2:38, shue249<notifications@github.com> wrote:   
@palangiux Do you have any ad blocker or VPN installed? If so, can you try to disable them?

**Comment by palangiux** [comment]
How to do fresh restart of the plugin?

**Comment by palangiux** [comment]
> @palangiux
> 
> 1. Do you have any ad blocker or VPN installed? If so, can you try to disable them?
> 2. Do you have the Facebook page that you used in the setup? Is the page still there, have you deleted it away?
> 3. If the above 2 does not work, can we understand if you have already run ads for the catalog created? If not, we can consider doing a fresh restart of the plugin.

could youexplain more clear how to deal with option 2? How to check is this deleted or not?

**Comment by shue249** [comment]
@palangiux Do you still remember which is the page that you used for the setup? If so, you can go to Facebook and try to search for it. Or you can also go to the list of pages you manage/own and look for that page.

For a fresh restart of the plugin, you can follow the steps here - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/177#issuecomment-495930585

**Comment by shue249** [comment]
@palangiux Have you tried to do the fresh restart of the plugin?

**Comment by shue249** [comment]
@palangiux We will be closing out this ticket. Feel free to reach to us if you have further questions.
