### ISSUE TITLE
Stuck after installation

### ISSUE THREAD

**Issue by GBud80** [facebookincubator/Facebook-For-OpenCart#255]
After installing the extension on open cart Version 2.1.0.2, and clicking on the admin page i cannot complete the setup as there is a loading gif instead of the GET STARTED button.

![fb-ext](https://user-images.githubusercontent.com/55797281/65606613-80834900-dfab-11e9-8f3c-fbeef1275f59.jpg)

**Comment by shue249** [comment]
@GBud80 Can you open up the Javascript console and refresh the page to see if there's any errors shown on the console.

**Comment by GBud80** [comment]
this is what i shown in the console:

VM117 facebookadsextension&token=6D9hAZYFAMjns53L8rGORcgIS6hvRQ1F&user_token=6D9hAZYFAMjns53L8rGORcgIS6hvRQ1F:41 Uncaught SyntaxError: Unexpected token '}'
dia_2_1_10.js:297 Uncaught TypeError: Cannot read property 'diaSettingId' of undefined
    at Object.refreshUIForDiaSettings (dia_2_1_10.js:297)
    at HTMLDocument.<anonymous> (index.php?route=extension/facebookadsextension&token=6D9hAZYFAMjns53L8rGORcgIS6hvRQ1F&user_token=6D9hAZYFAMjns53L8rGORcgIS6hvRQ1F:414)
    at j (jquery-2.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.1.min.js:2)
    at Function.ready (jquery-2.1.1.min.js:2)
    at HTMLDocument.I (jquery-2.1.1.min.js:2)


also i now have this error displayed in open cart admin:

Warning: sizeof(): Parameter must be an array or an object that implements Countable in /home/plumbing/public_html/system/storage/modification/admin/controller/common/dashboard.php on line 16Warning: sizeof(): Parameter must be an array or an object that implements Countable in /home/plumbing/public_html/system/storage/modification/admin/controller/common/dashboard.php on line 46

Any ideas?

**Comment by shue249** [comment]
@GBud80 Can you check if you have given read+write access (775) for the admin, catalog, system folders on your webserver, and then reinstall the plugin again.

What version of PHP are you using

**Comment by shue249** [comment]
@GBud80 Are you still facing problem with the plugin?

**Comment by shue249** [comment]
@GBud80  We will be closing out this ticket. Feel free to reach to us if you have further questions.
