### ISSUE TITLE
Having problem with setup 

### ISSUE THREAD

**Issue by Ashon95** [facebookincubator/Facebook-For-OpenCart#257]
Im using 
Opencart 3.0.3.2 
Journal 3

i have installed with no problems and run through the setup - http://prntscr.com/pdiep1 everything is ok there then when i go to dashboard i get this error - http://prntscr.com/pdifin 

i have done what it says and deleted facebook and re-run the setup and still the same also get this on facebook plugin page - http://prntscr.com/pdig65

**Comment by shue249** [comment]
@Ashon95 Did you logout from Facebook on your browser after you finished the setup?

**Comment by shue249** [comment]
@Ashon95 We will be closing out this ticket. Feel free to reach to us if you have any further questions.
