### ISSUE TITLE
Problem with My gtmetrix 

### ISSUE THREAD

**Issue by Ashon95** [facebookincubator/Facebook-For-OpenCart#258]
so after installing the plugin im get this and its issue for me is there was i can fix please - http://prntscr.com/pdjf26

**Comment by shue249** [comment]
@Ashon95 Can you help us understand better on what is the issue for you and how will you like the plugin to be improved?

**Comment by shue249** [comment]
Will be closing out this request. Feel free to reach to us if you have further questions
