### ISSUE TITLE
Shopping tags stop working on IG

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#259]
Hello

Can you assist me with shopping tag issue? 
The old one still intact but cant add new and dont see shopping settings in settings 
![13A443BC-E51A-4FFD-9877-F13DD033AEEB](https://user-images.githubusercontent.com/50840258/66017826-3d384700-e491-11e9-945a-d14968fd71ca.png)
![C35CD9CF-D4AF-4693-AF46-2C997E7A3317](https://user-images.githubusercontent.com/50840258/66017827-3dd0dd80-e491-11e9-86bf-404cd975f1b3.png)

**Comment by shue249** [comment]
@KonstantinGOT Will you be able to reach to our support team at this link - https://www.facebook.com/business/help/support. They will have specialists who can help deep dive into your IG shopping specific problems.

Will be closing out this ticket
