### ISSUE TITLE
is there a way to change the plugin name 

### ISSUE THREAD

**Issue by Ashon95** [facebookincubator/Facebook-For-OpenCart#260]
i want to make the name smaller as it looks ugly and to long - http://prntscr.com/pf21w6

i just want it to says "facebook business"

**Comment by shue249** [comment]
@Ashon95 You can make this changes on these 4 files on your webserver folder.

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/language/en-gb/extension/facebookadsextension.php#L8
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/language/en-gb/extension/module/facebookadsextension_installer.php#L8
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/language/english/extension/facebookadsextension.php#L8
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/language/english/extension/module/facebookadsextension_installer.php#L8

Will be closing out this ticket. Feel free to reach to us if you have further questions.
