### ISSUE TITLE
Problem with new version 

### ISSUE THREAD

**Issue by Ashon95** [facebookincubator/Facebook-For-OpenCart#261]
getting this on my pages - http://prntscr.com/pg8ge2 

found the file - http://prntscr.com/pg8giy

and here - http://prntscr.com/pg8gou ( admin/controller/extension/facebookadsextension.php )

**Comment by shue249** [comment]
@Ashon95 Thanks for the heads up! We are working on this urgently now

**Comment by Ashon95** [comment]
no problem please update me when fixed

**Comment by shue249** [comment]
@Ashon95 We have released a new version 2.1.12 to fix the issue.

Will be closing out this ticket, let us know if you have any further questions. https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.12

**Comment by Ashon95** [comment]
@shue249 has it been updated and fixed ?

**Comment by shue249** [comment]
@Ashon95 Yes, pls check the latest version 2.1.13
