### ISSUE TITLE
Pixel not installed on website

### ISSUE THREAD

**Issue by exitsport** [facebookincubator/Facebook-For-OpenCart#262]
Hi,

We instalations new version Facebook Business Extension Plugin Version: 2.1.12.
Try to cleaned all: 

 We have detected the Facebook pixel/Messenger customer chat is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have Refresh the modifications, View steps
2. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
3. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

We going step by step, but not help, the area is red, where is issue?

![Opencart issue](https://user-images.githubusercontent.com/14319188/66410353-a3c1e580-e9fa-11e9-8b2a-ad02b379156f.JPG)

**Comment by exitsport** [comment]
![Opencart issue](https://user-images.githubusercontent.com/14319188/66410309-94429c80-e9fa-11e9-9217-2645e41860ff.JPG)

**Comment by shue249** [comment]
@exitsport What is your website store URL?

**Comment by exitsport** [comment]
> @exitsport What is your website store URL?

www.exitsport.eu

**Comment by shue249** [comment]
@exitsport We checked on your website and found that the plugin warnings are false positive, ie you can safely ignore those messages. The setup is correct on your website and there is nothing you need to do for now.

Explaining more details, we found that you have a code minifier which strip away excess comments that we used as a detection mechanism to check if the pixel is fired successfully. In view of this, we will revisit on how we do this detection and improve on this on the next version.

**Comment by hydramod** [comment]
I am getting the same error, website can be found at hydramod.com

**Comment by exitsport** [comment]
Thank you, maybe some know, what is best solution to add Messenger to Opencart?

**Comment by exitsport** [comment]
> @shue249  Thank you, maybe some know, what is best solution to add Messenger to Opencart?

**Comment by shue249** [comment]
@hydramod We checked your website and found that there should not have any errors. Can you share the screenshot of how the Facebook Business Extension admin panel looks like.

**Comment by shue249** [comment]
@exitsport You can follow the guide here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#setup-for-facebook-messenger-chat

**Comment by hydramod** [comment]
I checked to take a screenshot of the error just now and it is gone, i guess it was truly a false error, because i dont notice anything broken. I would screenshot it and show you but it is completely normal now. Thank you for taking the time to confirm that everything is functional @shue249

**Comment by exitsport** [comment]
> @shue249  But messenger is activated, but not show in web

![image](https://user-images.githubusercontent.com/14319188/66484791-5a33d200-eab0-11e9-89de-f426bd7afdc7.png)

**Comment by tuncaytunckol** [comment]
![111111](https://user-images.githubusercontent.com/56370945/66525982-da355880-eaff-11e9-8ea6-8f0c31f1a65a.JPG)
https://www.tunckol.com

**Comment by shue249** [comment]
@tuncaytunckol You can ignore the error on the admin panel, as it is the same case as the others - presence of minifier. The pixel is correct on your website

**Comment by stemo-1975** [comment]
The same here: https://www.domusz.hu

![FireShot Capture 020 - Facebook OpenCart rendszerre - www facebook com](https://user-images.githubusercontent.com/32204845/67068005-dc8b5880-f178-11e9-812a-5bce42585db6.png)

**Comment by shue249** [comment]
@stemo-1975 You are correct. The pixel code is not injected into your website, there are no pixel fires, and the diagnostics about missing pixel is correct. Are you able to follow the 3 instructions on the warning to see if it works for you.

**Comment by shue249** [comment]
@exitsport , @hydramod , @tuncaytunckol  We have released a new version 2.1.13 which should be fixing this issue that you are facing, you can download the version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13

We are closing out this ticket, Feel free to reach to us if you have further questions.

@stemo-1975 , can you help us to create a new ticket if the problem still persists on your side. Also we have these 2 guides that you may want to read through to see if it helps to solve your problem.
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md
