### ISSUE TITLE
Getting Error on back end even though pixel is working on front end

### ISSUE THREAD

**Issue by Ashon95** [facebookincubator/Facebook-For-OpenCart#263]
getting a message on backend saying pixel is not working - http://prntscr.com/pgkfwz

yet it working on front end - http://prntscr.com/pgkgfd

**Comment by shue249** [comment]
@Ashon95  Can you share your website URL?

**Comment by iq860** [comment]
same issue 
an error even my website is up and running both pixel and chat
website URL: el-vet.com
opencart: Version 3.0.2.0
default
![Screen Shot 2019-10-11 at 1 14 01 AM](https://user-images.githubusercontent.com/15311677/66607050-7163e400-ebc4-11e9-86dd-6a1d639a23bf.png)
 theme

**Comment by shue249** [comment]
@iq860 We checked and the pixel setup is correct. You can ignore this error message while we work to improve the pixel detection mechanism.

**Comment by shue249** [comment]
@Ashon95 , @iq860  We have released a new version 2.1.13 which should be fixing this issue that you are facing, you can download the version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13

We are closing out this ticket, Feel free to reach to us if you have further questions.
