### ISSUE TITLE
Facebook ads extension

### ISSUE THREAD

**Issue by gagan28510** [facebookincubator/Facebook-For-OpenCart#265]
We are currently using opencart 3.0.2 version and facebook ads extension version 2.1.10,

Now fb ads ext. 2.1.12 is available, please share steps how to upgrade , we wish to upgrade it

**Comment by shue249** [comment]
@gagan28510 You can follow the steps here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#upgrade-the-plugin-to-a-later-version
