### ISSUE TITLE
Wrong product query

### ISSUE THREAD

**Issue by hristonev** [facebookincubator/Facebook-For-OpenCart#266]
Guys, I have ecommerce and try this module. However upload of all products do not work correctly. Fix is in `admin/controller/extension/facebookproductfeed.php` 
    
    $filter_data = array(
          'start' => $batch_number *
            FacebookCommonUtils::FACEBOOK_PRODUCT_QUERY_BATCH_COUNT,
          'limit' => FacebookCommonUtils::FACEBOOK_PRODUCT_QUERY_BATCH_COUNT,
          'filter_status' => 1
        );

Filter must include status 1.

**Comment by shue249** [comment]
@hristonev Thanks for the heads up! We will look into this

**Comment by shue249** [comment]
@hristonev We are enforcing the enabled status on the code level instead on the SQL level (https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookproductfeed.php#L270). We are now working to move the filter to the SQL level (as you have suggested) to improve on the potential SQL query.

**Comment by shue249** [comment]
@hristonev  We have released a new version 2.1.13 which should be fixing this issue that you are facing, you can download the version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13

We are closing out this ticket, Feel free to reach to us if you have further questions.

**Comment by hristonev** [comment]
Thanks, Shue.
