### ISSUE TITLE
admin path change plugin not work

### ISSUE THREAD

**Issue by Simon55** [facebookincubator/Facebook-For-OpenCart#267]
Hi we got problem with this extension, that not make any sense! There are problems with the installation of the Facebook Ads Extension. We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders. fail.. with permission is all ok but this extension not recognized other path name folder of admin?

/home/domains/domains/domains.com/public_html
/home/domains/domains/domains.com/public_html
and over and over .....continue 
/home/domains/domains/domains.com/public_html

please make a fix asap.

**Comment by bonyod** [comment]
Got these error too

**Comment by shue249** [comment]
Thanks, we are aware of this and working to solve this. 

Duplicate issue as https://github.com/facebookincubator/Facebook-For-OpenCart/issues/135

**Comment by yao-tx** [comment]
Hi @bonyod @Simon55 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The latest version of the FBE plugin (version 4.0.0 and above) doesn't require additional configurations if you have a custom admin folder name as it utilises the default OpenCart Extension Installer feature to install the plugin. Unless you are manually uploading the files onto your web server to install the plugin, you shouldn't encounter any problems with custom admin folder names.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
