### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Superstar18** [facebookincubator/Facebook-For-OpenCart#268]
Hi,

A few days ago this error started to appear even if we didn't made any modifications:

 Warning: Encountered problem updating product(s) to Facebook. Please retry again. Check the error log file for more details

We did the update today, refresh the modifications, etc. but the error is still there.
We also saw that facebook ads did not consume any budget today at any of the campaings. I don't know if the issues are linked. 
I also checked in facebook ads the section catalog/products but i see no products loaded even if i have at the summary: 2.9K Products

What do you recommend us to do?

Thank you!
Marius

**Comment by shue249** [comment]
@Superstar18 Will you be able to share the log file from our plugin with us? You can find the download link on the bottom right of the plugin module on the admin panel.

**Comment by Superstar18** [comment]
Hi,

I tried to reply you here but adding the log as a attachment doesn't work. I'm getting a error.
I replied you by e-mail. Didi you get the e-mail?

**Comment by shue249** [comment]
@Superstar18 We didnt receive any email. Can you try to zip up the file and then attaching to this ticket?

**Comment by Superstar18** [comment]
I'm trying but i get this error when i'm trying to attach anything here: https://prnt.sc/piaytg
Do you have a e-mail where i can send it?

**Comment by shue249** [comment]
@Superstar18 Can you send to ads_extension_opencart@fb.com

**Comment by shue249** [comment]
@Superstar18 We have received your log file. 
1. Can you do a resync of your products
![image](https://user-images.githubusercontent.com/11957585/66893528-e0a46280-f020-11e9-8d05-2fb141ca3742.png)

2. Can you share with us your website URL

**Comment by Superstar18** [comment]
Hi,
I resynced the products.
The store is iconicul.ro

**Comment by shue249** [comment]
@Superstar18 We checked on the catalog for both the dynamic ads and page shop, the products seems to be ok now.

![image](https://user-images.githubusercontent.com/11957585/66968223-95d52a00-f0b6-11e9-865e-03d65b6286fb.png)

For now, if you encounter further issues, you can do a resync to solve it. We are working on a catalog revamp to make this better, will inform you soonest when ready.

**Comment by sbillis** [comment]
Hi,

I recently install Facebook Business Extension Plugin Version: 2.1.13 on Opencart Version 3.0.3.2 with Journal theme 3.0.41

I still get this error after deleting and reinstalling the plugin :
 

> There is an error making API calls using the access token. The error encountered is "Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.".
> To update your access token, please click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Update token.

I dissable the cache, I delete the plugin and I made refresh to modifications. After that I re-install the plugin downloaded from Github. Yesterday the plugin worked and let me resync the products.
Today I am getting this error (again) and I cannot resync the products. The products are 26 items. Is still checking the upload status.

I attached the error log.

Can you help me?

Thanks in advance!
[sbillis_error_2019-11-20_07-38-15_facebook_ads_extension.txt](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3868017/sbillis_error_2019-11-20_07-38-15_facebook_ads_extension.txt)

**Comment by shue249** [comment]
@Superstar18 , @sbillis  

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

We will be closing out this ticket, feel free to reach to us on this ticket if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302
