### ISSUE TITLE
No pixel is added to the pages of the site.

### ISSUE THREAD

**Issue by neshchadin** [facebookincubator/Facebook-For-OpenCart#27]
Hello. No pixel is added to the pages of the site.
Products were synchronized normally. But the pixel helper does not see the pixel on the site.
Thank you in advance.

[Kidzzz - магазин детской одежды_2018-08-17_08-53-45_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2296133/Kidzzz.-._2018-08-17_08-53-45_facebook_ads_extension.log)

**Comment by shue249** [comment]
Thank you for your feedback. Can we understand what is your website URL?

**Comment by shue249** [comment]
@neshchadin We have released a new update of our plugin. 
1. Can you download the version from Opencart marketplace - https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
2. Uninstall the previous version and install in the new version
3. Check if the pixel is fired correctly

**Comment by shue249** [comment]
@neshchadin We will be closing off this ticket as we released a new version to fix this problem. But feel free to open up this ticket again and feedback to us on any follow up questions and we will be happy to take it from there.
