### ISSUE TITLE
new version 2.1.12 the facebook Messenger still not working

### ISSUE THREAD

**Issue by wegee-us** [facebookincubator/Facebook-For-OpenCart#270]
@shue249 Hi, we updated to the Version: 2.1.12, the messenger is still not showing. and it shows an error, we already refresh the modification
![image](https://user-images.githubusercontent.com/50933832/66612205-df34ef00-eb75-11e9-9654-b884643a0fca.png)

**Comment by shue249** [comment]
@wegee-us Can you share your website again for us to take a look?

**Comment by wegee-us** [comment]
@shue249 yes, this is our website: https://wegee.us/

**Comment by shue249** [comment]
@wegee-us We checked and found that the div element for the messenger chat plugin seems to not being able to load. Are you using some page optimiser/minifier (eg nitropack)? Will you be able to test disabling those optimisers/minifers to see if it will allow the chat plugin to be shown?

**Comment by wegee-us** [comment]
@shue249 Hi, we did test it without cache. as we mentioned before, after some version, you moved this plugin from footer to header, that makes plugin dispeared. before that change, it is good to display in our site. we suggested to make an option to let us to choose the plugin where to show.

**Comment by shue249** [comment]
@wegee-us We found the problem with the latest version of the plugin. We have added in the redundancy case by adding the Messenger chat plugin for both header and footer but there was a bug in the check. We will fix it and update you soonest.

**Comment by nhoangnam93** [comment]
> @wegee-us We found the problem with the latest version of the plugin. We have added in the redundancy case by adding the Messenger chat plugin for both header and footer but there was a bug in the check. We will fix it and update you soonest.

I'm having same issue, please check.

**Comment by shue249** [comment]
@wegee-us , @nhoangnam93   We have released a new version 2.1.13 which should be fixing this issue that you are facing, you can download the version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13

We are closing out this ticket, Feel free to reach to us if you have further questions.
