### ISSUE TITLE
Issue with new in stock changes

### ISSUE THREAD

**Issue by ryanstacey** [facebookincubator/Facebook-For-OpenCart#271]
I saw in the changelogs that youve updated how the extension pulls products and changes their status on facebook catalogue.

All our products are technically in stock and we let people order them on the website, but we use the custom out of stock status to let people know how many days it'll be.

Will these products show as out of stock on facebook?

<img width="608" alt="Screenshot 2019-10-12 at 11 11 33 pm" src="https://user-images.githubusercontent.com/44474887/66708262-aba8bf00-ed45-11e9-9241-095ee849c638.png">

**Comment by shue249** [comment]
I believe your "5-7 Days" is a custom out of stock status. All custom out of stock status are treated as in stock in Facebook. So all your stocks which have "5-7 Days" will be treated as In stock on Facebook if the quantity is zero or less. If the quantity is one or more, it will always be treated as In stock on Facebook.

The code pointer is here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L207-L209

We will be closing out this ticket. Feel free to to reach out to us if you have further questions.
