### ISSUE TITLE
Facebook Ads Extension without messenger not works?!

### ISSUE THREAD

**Issue by Simon55** [facebookincubator/Facebook-For-OpenCart#272]
Hi fb warning include that we allready clear cache saas etc, but still get this errors! Second thing below:

We've found that Facebook pixel / Messenger customer chat is not set up properly on your online store site. You can try these steps below to fix the problem.

we added correct pixel inside code to header but fb not recognize it, becose we dont have it also avalible chat messenger? We dont want it! Soo add that function that user it self deside if  want also included messenger chat or not!

**Comment by shue249** [comment]
@Simon55 Can you provide us your webstore URL and we can check into this.

**Comment by Simon55** [comment]
comstrok(dot)com

**Comment by shue249** [comment]
@Simon55 We verified that the pixel is installed on your website properly and we will improve on the error detection message in the next version.

**Comment by shue249** [comment]
@Simon55  We have released a new version 2.1.13 which should be fixing this issue that you are facing, you can download the version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13

Feel free to reach to us if you have further questions.

**Comment by Simon55** [comment]
Soo any update for us? Still waiting and no one respond!

**Comment by shue249** [comment]
@Simon55 As commented earlier, we have released a new version 2.1.13, which aims to resolve your problem. Are you able to test out this version.

Also, we tried to visit your website, but encounters a 403 forbidden error.

![image](https://user-images.githubusercontent.com/11957585/67644608-c9893d00-f95d-11e9-8b2b-4a66572d92fb.png)
