### ISSUE TITLE
How do i completly remove this from my store 

### ISSUE THREAD

**Issue by Ashon95** [facebookincubator/Facebook-For-OpenCart#273]
i want to completely delete plugin from store and reinstall fresh with a new Facebook page i have ran 

delete from setting where code = 'facebook';

is SQL and there is no such thing also tried delete from setting where code = 'oc_facebook';

and still no so where are the credentials saved as i have uninstalled the plugin and reinstalled it and its still logged in my old page

**Comment by shue249** [comment]
@Ashon95 To re-setup the Facebook Business Extension with a new set of settings, you will need to delete away the existing settings. This can be done easily from the Facebook Business Extension screen, see this video - https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

For deleting of the settings from the SQL, this is only for rare cases, where the Facebook Business Extension is unable to load and display.

We will be closing out this ticket. Feel free to reach to us if you have further questions.

**Comment by Ashon95** [comment]
i dont have that option when i go to settings i get a error - http://prntscr.com/pivqi7
