### ISSUE TITLE
issue in installing Facebook ads extension v2.1.12

### ISSUE THREAD

**Issue by jsuhand** [facebookincubator/Facebook-For-OpenCart#274]
getting following error after installing facebook ad extention
"
parse error:syntax error,unexpected'.',expecting','or';' public_html/system/library/facebookcommonutils.php on line 138  "

opencart Version 3.0.2.0
journal 2 theme

**Comment by shue249** [comment]
@jsuhand Have you made any changes to the plugin files on your webserver? What is the PHP version that you are using?

**Comment by jsuhand** [comment]
> @jsuhand Have you made any changes to the plugin files on your webserver? What is the PHP version that you are using?

No i haven't made any change on webserver ..PHP version is 7.2.7

**Comment by shue249** [comment]
@jsuhand We checked on this error and found that this happens on PHP 5.5 and lower, and should not happen for PHP 7.2.7.

However, we will still fix this problem to be compatible with PHP 5.5, and will update you when the new version is ready.

**Comment by shue249** [comment]
@jsuhand We have released a new version 2.1.13 which should be fixing this issue that you are facing, you can download the version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13

Feel free to reach to us if you have further questions.
