### ISSUE TITLE
Delete Facebook Business Extension settings directly

### ISSUE THREAD

**Issue by Ashon95** [facebookincubator/Facebook-For-OpenCart#275]
@Ashon95 To re-setup the Facebook Business Extension with a new set of settings, you will need to delete away the existing settings. This can be done easily from the Facebook Business Extension screen, see this video - https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

For deleting of the settings from the SQL, this is only for rare cases, where the Facebook Business Extension is unable to load and display.

We will be closing out this ticket. Feel free to reach to us if you have further questions.

_Originally posted by @shue249 in https://github.com/facebookincubator/Facebook-For-OpenCart/issues/273#issuecomment-541474689_

**Comment by Ashon95** [comment]
Can you tell me where to details in the database is to delete details of the facebook login as i get this error every time i click manage settings - http://prntscr.com/pj42q0

**Comment by shue249** [comment]
@Ashon95 Thank you for the feedback, and we apologise for the not ideal situation.

The SQL will be:

DELETE FROM oc_setting WHERE `code` = 'facebook';

You can do a select first to check if the data is correct:
SELECT * FROM oc_setting WHERE `code` = 'facebook';

Note that I used oc_setting as the table. The prefix "oc_" is dependent on what you choose when you setup OpenCart initially (the default is oc_).

**Comment by Ashon95** [comment]
Thank you that work like a charm
