### ISSUE TITLE
Fatal error: Class 'FacebookCommonUtils' not found

### ISSUE THREAD

**Issue by Deepeshsharma0** [facebookincubator/Facebook-For-OpenCart#277]
We are working on OpenCart 3.0.3.1 with journal theme 3.0.39.

when we are update our facebook ad Extension v2.1.12. After the updates we are getting error on our website home page **Fatal error: Class 'FacebookCommonUtils' not found in /home/comnascent/ocart-data/storage/modification/catalog/controller/common/footer.php on line 6** 
on admin panel this error showing **Fatal error: Class 'FacebookGraphAPIError' not found in /home/comnascent/ocart-data/storage/modification/admin/controller/common/dashboard.php on line 33**

Website Url: https://www.nascentcreations.com/

Please help us to resolve this error.

**Comment by shue249** [comment]
@Deepeshsharma0 From your error message, it seems that you have renamed the "admin" folder to a custom name. At the moment, our plugin is not able to support for setups where the admin folder has been renamed.

This is on our roadmap for improvements, and we will update you soonest when the new version is ready.

**Comment by kiwircik** [comment]
I am working on OpenCart 3.0.3.2 and after uninstall the Facebook-For-OpenCart I got this error, what should I do?

Fatal error: Uncaught Error: Class 'FacebookCommonUtils' not found in /home/barisdalyan/public_html/dcbouw.shop/system/storageeushhtvbzvig/modification/catalog/controller/common/footer.php:11 Stack trace: 
#0/home/barisdalyan/public_html/dcbouw.shop/system/storageeushhtvbzvig/modification/system/engine/action.php(79): ControllerCommonFooter->index(Array) 
#1/home/barisdalyan/public_html/dcbouw.shop/system/storageeushhtvbzvig/modification/system/engine/loader.php(48): Action->execute(Object(Registry), Array) 
#2/home/barisdalyan/public_html/dcbouw.shop/system/storageeushhtvbzvig/modification/catalog/controller/common/home.php(19): Loader->controller('common/footer') #3 /home/barisdalyan/public_html/dcbouw.shop/system/storageeushhtvbzvig/modification/system/engine/action.php(79): ControllerCommonHome->index() 
#4/home/barisdalyan/public_html/dcbouw.shop/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) 
#5 /home/barisdalyan/public_html/dcbouw.shop/system/storageeushhtvbzvig/modification/system/engi in /home/barisdalyan/public_html/dcbouw.shop/system/storageeushhtvbzvig/modification/catalog/controller/common/footer.php on line 11

**Comment by shue249** [comment]
@kiwircik Thank you for the feedback. After you uninstall the plugin, pls ensure that you have click on "Refresh modifications button". See the screenshot here - https://drive.google.com/open?id=1H5ppQPXnx2UYo6v82d5comDJKPu064X2

**Comment by AlexGolemis** [comment]
I had the same error today after uninstalling the plugin. Has anybody found a solution?

**Comment by ankitjn227** [comment]
Got the same error today..

Did anyone find the solution, plz help/

**Comment by shue249** [comment]
@AlexGolemis , @ankitjn227 Can you check this reply and see if it works for you.

**Comment by ankitjn227** [comment]
@shue249  i got this error after i uninstalled the facebookadsextension.ocmod module from admin panel opencart, before i refresh the modification, i have refreshed the main webpage, error occurs, 

also i am not able to open admin panel, getting error at admin panel also...

atal error: Uncaught Error: Class 'FacebookGraphAPIError' not found in /home/ambrokuf/storage_opencartnew/modification/admin/controller/common/dashboard.php:42 Stack trace: #0 /home/ambrokuf/storage_opencartnew/modification/system/engine/action.php(79): ControllerCommonDashboard->index() #1 /home/ambrokuf/public_html/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #2 /home/ambrokuf/storage_opencartnew/modification/system/engine/action.php(79): ControllerStartupRouter->index() #3 /home/ambrokuf/storage_opencartnew/modification/system/engine/router.php(150): Action->execute(Object(Registry)) #4 /home/ambrokuf/storage_opencartnew/modification/system/engine/router.php(139): Router->execute(Object(Action)) #5 /home/ambrokuf/public_html/system/framework.php(165): Router->dispatch(Object(Action), Object(Action)) #6 /home/ambrokuf/public_html/system/startup.php(104): require_once('/home/ambrokuf/...') #7 /home/ambrokuf/public_html/admin/index.php(22): start('admin') #8 {main} thrown in /home/ambrokuf/storage_opencartnew/modification/admin/controller/common/dashboard.php on line 42

i have refreshed oc_modification from db but didn't get resolved..

then deleted facebookadsextension module from database oc_modification, still not resolved issue.

**Comment by ankitjn227** [comment]
@shue249 still having facebookadsextension.ocmod.zip extension under oc_extension_install

should i delete this also from db, to get the issue resolved..

**Comment by shue249** [comment]
@ankitjn227 Can we follow up on this ticket for your issue https://github.com/facebookincubator/Facebook-For-OpenCart/issues/374

**Comment by ankitjn227** [comment]
Thanks
