### ISSUE TITLE
product not sync in facebook page

### ISSUE THREAD

**Issue by palangiux** [facebookincubator/Facebook-For-OpenCart#278]
in new version facebook extension bug with product sync still exist. In facebook page after resync product in eshop admin panel in facebook main page products is with discounts on them but then you push button  to show all products you can see all product from your eshop but without discounts on them. Is it possible to fix this bug?

Pictures atached

![Screenshot_20191019_103659_com facebook katana](https://user-images.githubusercontent.com/55613475/67139872-abd11f00-f25d-11e9-94bd-140df0419feb.jpg)
hhh
![Screenshot_20191019_103720_com facebook katana](https://user-images.githubusercontent.com/55613475/67139887-c86d5700-f25d-11e9-9d40-ce7c31a23de7.jpg)

**Comment by shue249** [comment]
@palangiux Can you share your webstore URL and your Facebook page. Also can you provide us with few product examples (with the product URL) where the discounts are wrong.

**Comment by palangiux** [comment]
NAUJA ĮRANGA  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
NAUJA ĮRANGA
 
kirpyklos įranga nauja ir naudota bei didelis pasirinkimas atsarginių dalių kriauklės, dušiukai, sifonai, hidraulika kėdėms, maišytuvai, kėdžių, plautuvių remontas
  |   |

  |

  |

  
https://www.facebook.com/Kirpyklų-įranga-315133118670442/  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Kirpyklų įranga
 
Kirpyklų įranga, Palanga. 682 likes. NAUJA IR NAUDOTA KIRPYKLŲ ĮRANGA ATSARGINĖS DALYS
  |   |

  |

  |

  
Sent from Yahoo Mail on Android 
 
  On sk, spal. 20, 2019 at 16:50, shue249<notifications@github.com> wrote:   
@palangiux Can you share your webstore URL and your Facebook page. Also can you provide us with few product examples (with the product URL) where the discounts are wrong.

**Comment by palangiux** [comment]
Any suggestions? 

Sent from Yahoo Mail on Android 
 
  On sk, spal. 20, 2019 at 16:50, shue249<notifications@github.com> wrote:   
@palangiux Can you share your webstore URL and your Facebook page. Also can you provide us with few product examples (with the product URL) where the discounts are wrong.

**Comment by shue249** [comment]
@palangiux We are unsure what is the problem and we will like to seek more help from you to allow us to better understand the problem.

Can you:
Share with us 1 example of the product on your website and indicate to us what should be the expected price with the discount. Then we can cross check on the Facebook Page shop on the price which is shown now for that product.

**Comment by shue249** [comment]
For example, we looked into 1 such product. The discount price match correctly.
Facebook Page Shop URL - https://www.facebook.com/commerce/products/3091199217618947/
Website product URL - https://www.kirpyklosiranga.lt/index.php?route=product%2Fproduct&product_id=148

![image](https://user-images.githubusercontent.com/11957585/67649298-702c0880-f973-11e9-87c2-ba28e7caf00b.png)

![image](https://user-images.githubusercontent.com/11957585/67649158-dd8b6980-f972-11e9-946c-5e8c8aa4783f.png)

**Comment by shue249** [comment]
@palangiux  We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.
