### ISSUE TITLE
insecure script blocked

### ISSUE THREAD

**Issue by magbor** [facebookincubator/Facebook-For-OpenCart#281]
Mixed Content: The page at 'https://xxxxxx.com/' was loaded over HTTPS, but requested an insecure script 'http://freegeoip.net/shutdown'. This request has been blocked; the content must be served over HTTPS.

Please advice how to proceed for upgrade.

**Comment by shue249** [comment]
@magbor Most likely you are still on an older version of our plugin. You can download the latest version from OpenCart marketplace or our github

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13

For the plugin upgrade steps, you need to uninstall/remove the plugin then install the new version. You can read up more here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#upgrade-the-plugin-to-a-later-version

We will be closing out this ticket, but feel free to reach to us if you have more questions.
