### ISSUE TITLE
Messenger customer chat is not correctly setup

### ISSUE THREAD

**Issue by guilhermeojs** [facebookincubator/Facebook-For-OpenCart#282]
We have detected the Facebook pixel, Messenger customer chat is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have Refresh the modifications, View steps
2. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
3. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

<img width="1093" alt="Screen Shot 2019-10-24 at 16 31 25" src="https://user-images.githubusercontent.com/20118742/67518764-cb13e600-f67b-11e9-81b0-1795cdd62dc5.png">

The Messenger chat does seem to work just fine. I've tried doing all the steps above and the message doesn't disappear.

**Comment by shue249** [comment]
@guilhermeojs Can you share with us your website store URL

**Comment by shopyub** [comment]
This add-on has caused a major problem in the site that it is the worst addition over the history of OpenCart even the sitemap caused a problem I will delete it completely

**Comment by shue249** [comment]
@guilhermeojs Are you still encountering the problem? Will you be able to share with us your webstore URL?

**Comment by shue249** [comment]
@guilhermeojs  We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.
