### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by markharmerisme** [facebookincubator/Facebook-For-OpenCart#283]
I installed it according to your requirements. But it didn't work.
Can you help me see what the problem？
Display the following information。 
We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have Refresh the modifications, View steps
2. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
3. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

**Comment by shue249** [comment]
@markharmerisme Can you provide us the website store URL

**Comment by markharmerisme** [comment]
@shue249 Thank you for your reply.
It's working. Is the website root directory permission problem.

**Comment by Simon55** [comment]
We will check new realise and let you know.

**Comment by shue249** [comment]
@markharmerisme , @Simon55  We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.
