### ISSUE TITLE
the product is not showing on facebook page

### ISSUE THREAD

**Issue by dumechosen** [facebookincubator/Facebook-For-OpenCart#284]
the product is not showing on the facebook page this is the error message
 Your post couldn't be shared, because this link goes against our

please what can do to solve the problem

**Comment by shue249** [comment]
@dumechosen Can you share with us the link of the product

**Comment by dumechosen** [comment]
this is the link   https://momehyo.com.ng

**Comment by dumechosen** [comment]
> @dumechosen Can you share with us the link of the product

this is the link https://momehyo.com.ng

**Comment by dumechosen** [comment]
THIS IS THE F

> > @dumechosen Can you share with us the link of the product
> 
> this is the link https://momehyo.com.ng

THIS IS THE FACEBOOK PAGE LINK  https://web.facebook.com/MOMEHYO

**Comment by shue249** [comment]
@dumechosen 
1. Do you have the link of the exact product? Can you share that with us
2. Can you try to do a Resync of your products? You can do that from the Facebook Business Extension module.

**Comment by shue249** [comment]
@dumechosen  We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.
