### ISSUE TITLE
 Facebook Ads Extension bug

### ISSUE THREAD

**Issue by Papov555** [facebookincubator/Facebook-For-OpenCart#286]
Plugin Version: 2.1.3   opencart 2.0.3 
[Интернет-супермаркет Agroman.by_2019-11-04_07-40-14_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3803174/-.Agroman.by_2019-11-04_07-40-14_facebook_ads_extension.log)
There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.

**Comment by shue249** [comment]
@Papov555 Thank you for the feedback.

You can refer to this video on how to Delete away the settings and restart the setup - https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

If the problem persists, can you share with us the log file here?

**Comment by shue249** [comment]
@Papov555  We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.
