### ISSUE TITLE
Instalation Error when you have custom admin folder

### ISSUE THREAD

**Issue by rod2k** [facebookincubator/Facebook-For-OpenCart#287]
For security, before install fb plugins we had changed our admin folder, the instalation is not reading the admin variable from config.php

How to replay:

in a fresh opencart instalation (ver 3.0.2) change the admin folder to another one, change the path in new admin name\config.php

install plugins, it will install, but you can't configure correctly unless you rename your admin path to default

**Comment by shue249** [comment]
Thanks for the headsup! We are aware of this and looking at this.

Duplicated as https://github.com/facebookincubator/Facebook-For-OpenCart/issues/135

**Comment by yao-tx** [comment]
Hi @rod2k 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The latest version of the FBE plugin (version 4.0.0 and above) doesn't require additional configurations if you have a custom admin folder name as it utilises the default OpenCart Extension Installer feature to install the plugin. Unless you are manually uploading the files onto your web server to install the plugin, you shouldn't encounter any problems with custom admin folder names.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
