### ISSUE TITLE
Reinstallation without losing the Instagram shopping data

### ISSUE THREAD

**Issue by flaviotomazella** [facebookincubator/Facebook-For-OpenCart#288]
Hi,

I'm having the Setup Problem for the second time. I installed the Plugin, and used it for months and someday it was showing the problem below at my opencart admin page:

"There is an error with Facebook Business Extension setup. Click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing."

I deleted and restarted the setup, but i lost every links that was showing at my instagram posts. So i used again for 1 month, and now i am having the same problem as above.

How can i fix this, without losing the Instagram shopping links? It´s terrible to lose evertything i have done. And why this is happening? What can i make to dont happen again?

Regards
Flavio

**Comment by shue249** [comment]
@flaviotomazella Thank you for your feedback. Can you share your log file with us here?

**Comment by flaviotomazella** [comment]
Hi,

Follow my Log File

[Lavine Store_2019-11-11_22-46-38_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3833516/Lavine.Store_2019-11-11_22-46-38_facebook_ads_extension.log)

Thank you
Flavio

**Comment by shue249** [comment]
@flaviotomazella Thank you for the log file. Like to check if you have tried to click on the Resync products button?

**Comment by flaviotomazella** [comment]
Hi,

I dont know why when i got this error, the button resyng is not appearing anymore.

Regards
Flavio

**Comment by flaviotomazella** [comment]
correcting "Resync button" is not appearing anymore.

**Comment by flaviotomazella** [comment]
Shue, please... could you help me?? the resync button is not appearing anymore and my catalog is not updating with this error. I dont wanted to reconfigure again and lose every post i made =/

**Comment by shue249** [comment]
@flaviotomazella 

Apologies for the late reply.

1. We suspect there is some error on your Facebook Business Extension module page. Are you able to access the javascript console log and share with us a screenshot? If you are using Chrome, from the menu bar, click on View -> Developer -> Javascript console.

2. We are now working to change the catalog sync method from API to full scheduled feed approach. We are targeting to roll out the new plugin version in 1st week of Dec. This new update should solve your problem on the log run.

**Comment by flaviotomazella** [comment]
1. Follow the print. It shows that the server "https://www.lavinestore.com/admin/index.php?route=extension/facebookadsextension/getinitialproductsyncstatus&user_token=XJG8RWG3wYCJsI94BUUzgB6yl9kJ5zue&token=XJG8RWG3wYCJsI94BUUzgB6yl9kJ5zue" is responding with the status of 400.

![image](https://user-images.githubusercontent.com/57532959/69537209-6095e480-0f5e-11ea-85bf-911715640223.png)


2. Thank you, looking forward for the update.

**Comment by shue249** [comment]
@flaviotomazella It seems that there is some issue with the plugin code on your webserver, but we are unable to debug further as the error 400 is too generic. What we can suggest is the following.

1. Can you check if the admin, catalog and system folders are given read+write permission recursively on your webserver
2. Uninstall the plugin and reinstall the plugin again
3. Check if the console still shows up error.

**Comment by shue249** [comment]
@flaviotomazella  

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

Feel free to reach to us if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302

**Comment by shue249** [comment]
@flaviotomazella Any updates from your side?

**Comment by shue249** [comment]
@flaviotomazella We will be closing out this ticket. Feel free to reach to us if you have further questions.
