### ISSUE TITLE
Website blocked for no reason..

### ISSUE THREAD

**Issue by JuvVaid** [facebookincubator/Facebook-For-OpenCart#289]
Hi

I made facebook page for my website (https://vanquishstore.com) almost a week ago, i just connected it with my  store. 2 days later i opened it to check it but finds out that my facebook shop isn't appearing on my page, i tried to post about my products manually but got the message that this website doesn't meet our community standards, I tried complaining about the issue but even after 2-3 days got no answer and it's still blacklisted; tried to run facebook debugger but nothing works, right now i can't even run any campaign regarding my website & it's impossible to run dropshipping business without facebook/instagram advertisement. The website doesn't contain anything illegal or it's new so there is no logical reason for blocking it. can any of you help me regarding this? 

Thank you

**Comment by shue249** [comment]
@JuvVaid Thank you for your feedback. We will like to direct you to this direct help link for you to share more context and our internal teams will reach out to you for more details. https://www.facebook.com/help/contact/571927962827151

We will be closing out this ticket, but feel free to reach to us if you have more questions.
