### ISSUE TITLE
Facebook cookie consent bar

### ISSUE THREAD

**Issue by magixrys** [facebookincubator/Facebook-For-OpenCart#29]
Hi, I have installed this extension (version 2.0.3). Everything is ok, except one thing. When visiting my site a cookie consent/opt out bar appears at the bootom of the page. This bar is about  cookies, terms etc of facebook (not  my site). So if a visitor clicks one link (eg for privacy policy), he is redirected to facebook's privacy policy. 
What should I do to make this bar disappear?

**Comment by shue249** [comment]
@magixrys 

At the end of the cookie bar, visitor can choose to opt out or enable cookies. (see screenshot). This cookie bar is required to fulfil the GDPR compliance.

If you like to disable the cookie bar totally, you can make the change on the plugin files directly.

![image](https://user-images.githubusercontent.com/11957585/44399952-039dc880-a57c-11e8-8c2e-d27109574fed.png)

**Comment by magixrys** [comment]
thank you for replying. I found how to remove the cookie consent bar at #20

**Comment by tatcheff** [comment]
HI, for OC 3.0.2.0 it should be in header.twig or footer.twig fut I dont find it - can anyone help with locating the cookie bar text?
Thanks in advance a lot.

**Comment by shue249** [comment]
@tatcheff You need to look into the modifications folder to make the changes as that is where our plugin made the change - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/20#issuecomment-408645847. But do be aware that the changes will be gone after you activate the refresh and you need to make the changes again.
