### ISSUE TITLE
error occur 'We have detected the Facebook pixel is not correctly setup in your web store site.'

### ISSUE THREAD

**Issue by xmana** [facebookincubator/Facebook-For-OpenCart#291]
Hello!
I have a problem with the Facebook Business Extension for OpenCart.
After updating the Facebook Business Extension for OpenCart, I can’t get it working properly.
The update went as follows: the previous plugin was removed, then the current one was installed.
After installation, when I enter the Facebook Business Extension settings in the OpenCart admin panel, I get the following errors:

 We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have Refresh the modifications, View steps
2. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
3. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

OpenCart verison: 2.1.0.2
Facebook Business Extension Version: 2.1.13
PHP Version: 5.6.40-12+ubuntu16.04.1+deb.sury.org+1
Kernel version: 4.4.0-166-generic #195-Ubuntu SMP x86_64

Modifications have been refreshed.

After installation, it was reported that I did not own the pixel. After extensive manipulation of the rights - pixel saw.

Uploading goods to the FB store does not occur.
The upload icon spins for a long time and nothing happens.

Please help me fix issues with uploading products to the FB store.

**Comment by xmana** [comment]
![001](https://user-images.githubusercontent.com/8395478/68855773-a4c7f000-06e7-11ea-9c2e-2b105a7d7244.jpg)
![002](https://user-images.githubusercontent.com/8395478/68855775-a4c7f000-06e7-11ea-9108-d2e6a2f112c0.jpg)
![003](https://user-images.githubusercontent.com/8395478/68855776-a4c7f000-06e7-11ea-98f6-eb174168baf9.jpg)
![004](https://user-images.githubusercontent.com/8395478/68855777-a5608680-06e7-11ea-8e1a-f25652916ed8.jpg)
![005](https://user-images.githubusercontent.com/8395478/68855778-a5608680-06e7-11ea-9259-f76fe0efce44.jpg)
[Медтехніка_2019-11-14_12-00-58_error.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3846351/_2019-11-14_12-00-58_error.log)
[Медтехніка_2019-11-14_12-01-26_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3846352/_2019-11-14_12-01-26_facebook_ads_extension.log)

**Comment by xmana** [comment]
can someone help me?

**Comment by shue249** [comment]
@xmana, apologies for the late reply.

1. We found that the pixel setup is correct on your webstore. The warning message on your plugin module page is incorrect. You can ignore the warning message and we will look into the reason why the warning message is shown up. Can we also check with you that your webstore URL is https://fmf.com.ua/

2. We found that the products have been successfully uploaded to Facebook. You can view your catalog here - https://www.internmc.facebook.com/products/catalogs/2294241284155610/products

**Comment by xmana** [comment]
Surprisingly, the error disappeared without intervention on our part.
The problem is currently settled.
