### ISSUE TITLE
Error validating access token (plugin v.2.1.13 , OC v.3.0.3.2)

### ISSUE THREAD

**Issue by sbillis** [facebookincubator/Facebook-For-OpenCart#293]
Hi,

I reopen this issue because I haven't find yet the solution on this forum and the topics related are with old versions or are closed.

I recently install Facebook Business Extension Plugin Version: 2.1.13 on Opencart Version 3.0.3.2 with Journal theme 3.0.41

I still get this error after deleting and reinstalling the plugin :

There is an error making API calls using the access token. The error encountered is "Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.".
To update your access token, please click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Update token.

I dissable the cache, I delete the plugin and I made refresh to modifications. After that I re-install the plugin downloaded from Github. Yesterday the plugin worked and let me resync the products.
Today I am getting this error (again) and I cannot resync the products. The products are 26 items. Is still checking the upload status.

I attached the error log.

Can you help me?

Thanks in advance!
sbillis_error_2019-11-20_07-38-15_facebook_ads_extension.txt

**Comment by shue249** [comment]
@sbillis 

Apologies for the late reply.

We are now working to change the catalog sync method from API to full scheduled feed approach. We are targeting to roll out the new plugin version in 1st week of Dec. This new update will solve the existing problem of "invalid access token"

In the meantime, we can suggest you these 3 things.
1. To re-update your access token, you can follow the steps in the screenshot - https://drive.google.com/open?id=18koOQZmV3ra6wMsjsaWUPDuYZR_phl3J

2. If the button to update access token is not available, you can follow this temporary fix. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142#issuecomment-482908951

3. Avoid logging out from Facebook from your browser as it will cause the access token to be invalidated.

Let us know if you have any further questions.

**Comment by sbillis** [comment]
Thank you for your reply and for your time!!!
I will wait the update. Is a must and very good extension and it must work !

**Comment by arsh7023** [comment]
I am facing the same issue. is there any update? my  Plugin Version: 2.1.13  and OpenCart Version 3.0.2.0
I have also tried the above comments such as putting window.facebookAdsToolboxConfig.tokenExpired = 'true' in developer console but didn't work.

Please let us know what is the status.

**Comment by shue249** [comment]
@arsh7023 We are still working on the update for complete testing across all OpenCart versions to ensure the best experience when we roll out the update. We are still targeting the rollout to be in the first week of Dec (this week) and we will update everyone soonest when it is ready.

**Comment by shue249** [comment]
@sbillis , @arsh7023  

We have released a new version of the plugin, 2.2.0. In this new version, we have changed the catalog sync to using 100% feed file and the API/access token is no longer needed. This will resolve your current problem. You need to do an upgrade of the existing catalog and the steps to do that is highlighted in the release notes.

Here is the release notes:
2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

We will be closing out this ticket, feel free to reach to us on this ticket if you have any further questions - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/302
