### ISSUE TITLE
product option & special price

### ISSUE THREAD

**Issue by whitesnow91** [facebookincubator/Facebook-For-OpenCart#294]
hi, yesterday i was updating the plugin, and appear some issue

1. product are sync to facebook catalog with price instead of special price
2. product are sync to facebook catalog with the highest price of  the product option instead of lowest

any way to get rid of this ?

**Comment by shue249** [comment]
@whitesnow91 Can you share more details about your problem and provide some examples?

You can also refer to point 2 on our FAQ with respect to special prices. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#product-configurations-and-settings

**Comment by whitesnow91** [comment]
hi, when my product have 
-price
-special price
-option price

it will sync price to facebook catalog,not the special price or lowest option price
![Screenshot_3](https://user-images.githubusercontent.com/51204211/69610169-37607b80-1066-11ea-853d-f453fd3faf15.png)
![Screenshot_4](https://user-images.githubusercontent.com/51204211/69610170-37607b80-1066-11ea-8929-c40a62d57965.png)
![Screenshot_5](https://user-images.githubusercontent.com/51204211/69610171-37f91200-1066-11ea-9ca1-8c7838a077d0.png)
![Screenshot_6](https://user-images.githubusercontent.com/51204211/69610173-37f91200-1066-11ea-9e8f-5801c58d8600.png)

**Comment by shue249** [comment]
@whitesnow91 Thank you for the feedback.

1. The plugin does not support the option price feature from OpenCart as the option feature is not available on Facebook catalog

2. For the special price, is there a date range specified? We only sync in the special price as discount if the date range is still valid (either the special price is currently ongoing or set as a future date), or if the date range is not entered (which means the special price is always ongoing).

**Comment by shue249** [comment]
@whitesnow91 Wondering if you have any further insights on the product prices issue.

**Comment by shue249** [comment]
@whitesnow91 We will be closing out this ticket. Feel free to reach to us if you have further questions.
