### ISSUE TITLE
 POST-INSTALLATION PROBLEM

### ISSUE THREAD

**Issue by smlyrdsvn** [facebookincubator/Facebook-For-OpenCart#295]
Hi,
I tested the plug-in after installing Opencart. Then I was going to introduce my page immediately after accessing the real Facebook account. But it didn't. I keep getting the "Sorry, this content isn't available right now" error, and I can't even get to the token screen.

![2](https://user-images.githubusercontent.com/58137597/69494746-3c8bc200-0ed0-11ea-9495-0c87a4eddb17.png)
![1](https://user-images.githubusercontent.com/58137597/69494747-3c8bc200-0ed0-11ea-84e1-8bf083e612cd.png)

**Comment by smlyrdsvn** [comment]
I also performed deletions in Chrome and the Database. I've also tried it with multiple versions.
[WENOLG_2019-11-24_12-40-10_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3883551/WENOLG_2019-11-24_12-40-10_facebook_ads_extension.log)

**Comment by shue249** [comment]
@smlyrdsvn Some suggestions for you to check.

1. It seems that your Facebook account may need to perform some verification. Can you log into Facebook on your browser to complete the verification.

2. Is the Facebook page still valid? Some users encounter this problem after they deleted away the Facebook page

3. You can reset the entire plugin settings by manually removing away the plugin data on the database. Follow the steps here - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/275

**Comment by shue249** [comment]
@smlyrdsvn Like to follow up on this, are you still facing the problems in the plugin setup?

**Comment by shue249** [comment]
@smlyrdsvn  We will be closing out this ticket. Feel free to reach to us if you have further questions.
