### ISSUE TITLE
dont see other pixels 

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#296]
Have an issue that i dont see all the pixels that i have available 
please assist me on this matter. have only 3 out of 6
![Screen Shot 2019-11-28 at 8 40 00](https://user-images.githubusercontent.com/50840258/69770247-ee6e0b80-11ba-11ea-9c63-1b1e9535a448.png)

**Comment by shue249** [comment]
@KonstantinGOT Usually such issues are due to permissions. Can you verify if you have access to those pixels on your business manager.

**Comment by shue249** [comment]
@KonstantinGOT Like to follow up on this, are you able to resolve the permission issue for the other pixels?

**Comment by shue249** [comment]
@KonstantinGOT We will be closing out this ticket. Feel free to reach to us if you have further questions.
