### ISSUE TITLE
Probelm with Uninstalling

### ISSUE THREAD

**Issue by bengleking** [facebookincubator/Facebook-For-OpenCart#297]
Dear sir madam. I need some help. We needed to rename our admin directory but this seems causing problem accessing my admin dashboard as FB showing errors. I have also tried to uninstall this but seems uninstalling Facebook Ad extension doesn't work in opencart.It forcefully keeps reactivating.

**Comment by shue249** [comment]
@bengleking 

At the moment, our plugin does not support custom admin folder names.

Can you refer to this guide on uninstalling the plugin - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin

If you are still encountering problems/errors, can you share more details and screenshots of the errors.

**Comment by shue249** [comment]
@bengleking We will be closing out this ticket. Feel free to reach to us if you have further questions.
