### ISSUE TITLE
Update to last version

### ISSUE THREAD

**Issue by exitsport** [facebookincubator/Facebook-For-OpenCart#298]
We update to last version: Plugin Version: 2.1.13
But in facebook not sync any products and Facebook shop is empty or only loading photos

![image](https://user-images.githubusercontent.com/14319188/69977417-704f9300-1533-11ea-8986-8eaca1564298.png)

**Comment by exitsport** [comment]
Also in Extension any buttons not work
![image](https://user-images.githubusercontent.com/14319188/69977642-d9cfa180-1533-11ea-8b51-e3bae0b3c59f.png)
**
![image](https://user-images.githubusercontent.com/14319188/69977730-ff5cab00-1533-11ea-91ee-106b86bf8f45.png)
**

**Comment by shue249** [comment]
@exitsport 
1. Can you share with us your web store URL?
2. Can you check if you are using any ad blocker on your browser that is doing the setup?
3. Can you share with us your Facebook page

**Comment by exitsport** [comment]
www.exitsport.eu
second is Explorer messengre: that is black and if we changed some text in inside, in the messenger is same info, not changed any text

![image](https://user-images.githubusercontent.com/14319188/70045997-ccff8c00-15cd-11ea-93c1-2c4f357f1722.png)

**Comment by shue249** [comment]
@exitsport 

1. Can you share your Facebook page which you used during the Facebook Business Extension setup?

2. The products are uploaded the Facebook catalog. You can view your products here - https://www.facebook.com/products/catalogs/403808090316739/products
![image](https://user-images.githubusercontent.com/11957585/70110512-2af1a980-168a-11ea-8109-9ea7f5c6a751.png)

3. For the Messenger chat plugin, we tested your website on Chrome and we do not experience the black text background as your screenshot. What is the browser that you are using?
![image](https://user-images.githubusercontent.com/11957585/70110585-6ee4ae80-168a-11ea-98b3-bbe96fef97e4.png)

**Comment by exitsport** [comment]
In black text is Microsoft Edge browser:
https://gyazo.com/6c403277d29838df619f51396ab12447

**Comment by shue249** [comment]
@exitsport Thank you for the feedback on the MS Edge browser. We will bring this to our team.

Can you also share your Facebook page so that we can debug on the issue where you are not able to see the products on your FB page shop.

For the warning message on your Admin panel, we have checked on your website and it is a false alarm (ie, the pixel setup is correct and you can ignore this message). Give us some time to debug on why is the message showing up as false alarm on your admin panel.

**Comment by exitsport** [comment]
facebook is: https://www.facebook.com/exitsport.eu/
But in new update going new messages;

**We have detected the Facebook pixel, Messenger customer chat is not correctly setup in your web store site. You can try these below steps to fix the problem.**
**1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver**
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View stepsIn new update is going new alarm:

**Comment by shue249** [comment]
@exitsport 

1. For your Facebook page shop, we are able to see the products loaded. Clicking on one of the product is also leading correctly to the product on your website.
![image](https://user-images.githubusercontent.com/11957585/70330456-9305e280-1878-11ea-8df1-f90352ea25a7.png)

2. For the diagnostics error on pixel/messenger chat not correctly setup, you can ignore this error. We have checked on your website that the setup is correct. Give us some time to debug on why is the error message showing up as false positive.

3. Thank you for sharing this PHP error. Let us look into this.

**Comment by itshaman** [comment]
> 
> 
> facebook is: https://www.facebook.com/exitsport.eu/
> But in new update going new messages;
> 
> **We have detected the Facebook pixel, Messenger customer chat is not correctly setup in your web store site. You can try these below steps to fix the problem.**
> **1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver**
> 2. Ensure that you have Refresh the modifications, View steps
> 3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
> 4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View stepsIn new update is going new alarm:
> 
> and error in PHP..Undefined index: from in system/library/controller/extension/facebookproductfeed.php on line 336
> catalog/controller/extension/facebookeventparameters.php on line 494

Have the same troble ((

**Comment by shue249** [comment]
@itshaman Can you share with us your webstore URL so that we can check.

**Comment by exitsport** [comment]
> @itshaman Can you share with us your webstore URL so that we can check.
https://www.exitsport.eu

**Comment by shue249** [comment]
@itshaman and @exitsport Like to verify if both of you are reporting for the same website?

We are aware of www.exitsport.eu and are working on the issue where the pixel incorrect setup diagnostics error is shown.

**Comment by dtying** [comment]
@itshaman @exitsport 
Thank you for error reporting. We're working on fix PHP undefined error from facebookproductfeed.php. Currently it has caused issue in generating product feed file, and failure in uploading products into Facebook Catalog. Once it's fixed, the error should be gone .

**Comment by shue249** [comment]
@exitsport , @itshaman 

We have release a newer version 2.2.1 which fixes the pixel incorrect setup warning message and undefined index error/warning. You can download the version from here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

We will be closing out this ticket, feel free to reach to us if you have any further questions.

**Comment by itshaman** [comment]
> 
> 
> @itshaman and @exitsport Like to verify if both of you are reporting for the same website?
> 
> We are aware of [www.exitsport.eu](http://www.exitsport.eu) and are working on the issue where the pixel incorrect setup diagnostics error is shown.

Site https://vikart-molbert.ru
fb https://fb.com/vikartmolb

**Comment by shue249** [comment]
@itshaman Are you still facing the same pixel not correctly setup warning message with version 2.2.1?

**Comment by shue249** [comment]
@itshaman We will be closing out this ticket. Feel free to reach to us if you have further questions.

**Comment by kanjuo** [comment]
> @exitsport Thank you for the feedback on the MS Edge browser. We will bring this to our team.
> 
> Can you also share your Facebook page so that we can debug on the issue where you are not able to see the products on your FB page shop.
> 
> For the warning message on your Admin panel, we have checked on your website and it is a false alarm (ie, the pixel setup is correct and you can ignore this message). Give us some time to debug on why is the message showing up as false alarm on your admin panel.



> @itshaman We will be closing out this ticket. Feel free to reach to us if you have further questions.

I am having similar issue - how can i send you my store URL

**Comment by shue249** [comment]
@kanjuo We see that you have created a new ticket https://github.com/facebookincubator/Facebook-For-OpenCart/issues/324, let us follow up on that ticket.
