### ISSUE TITLE
Acces denied

### ISSUE THREAD

**Issue by tatcheff** [facebookincubator/Facebook-For-OpenCart#30]
after fresh install on OC 3.0.2.0 with Journal theme the extention says
Access Denied! Please contact your administrator! cash was refreshed after install.
please advice.
ms-style.eu
Also - the cookie bar must be removed, but there is no setting for it.
Thanks

**Comment by shue249** [comment]
Thank you for your feedback. 

For OpenCart v3.x, there is an additional step required. Pls refer to this video guide - https://drive.google.com/open?id=1-ljN_pNcyZBbN2LoXtxwaJEy0dfnxAum

For the cookie bar, it is with reference to the GDPR requirement. At the moment, there is no setting to disable this. We may look into how to configure for this later on.

**Comment by tatcheff** [comment]
Thank you fir this video. I did this step as well /it is done for many other OC v3.x extentions/. at this step of the module it gives: **page does not exist**, so actually did not solve the problem.

**Comment by shue249** [comment]
@tatcheff Will you be able to share a screenshot of this so that we can better understand where is the problem that you are encountering.

**Comment by tatcheff** [comment]
Sure, here are the screens:
![1](https://user-images.githubusercontent.com/42522760/44388875-f4922880-a531-11e8-9b2c-12647dd142c8.png)
![2](https://user-images.githubusercontent.com/42522760/44388876-f4922880-a531-11e8-8095-45c475b2ab01.png)

**Comment by tatcheff** [comment]
and this is when you click on "edit" blue button on the extention in the module list menu

![3](https://user-images.githubusercontent.com/42522760/44390245-7c2d6680-a535-11e8-8528-3bb5d3535245.png)

**Comment by shue249** [comment]
So, we are only auto-registering the permissions for Administrator groups. 
1. What is the user group you are having
2. Can you check the screenshot below to enable the permission for your group

![image](https://user-images.githubusercontent.com/11957585/44397383-bf59fa80-a572-11e8-95d7-eac44343e774.png)

**Comment by tatcheff** [comment]
yes, sorry - this was the issue. clicked off by default for all user groups.

**Comment by shue249** [comment]
For your earlier question on cookie bar, we can recommend https://github.com/facebookincubator/Facebook-For-OpenCart/issues/29
