### ISSUE TITLE
Mandatory upgrade of catalog to be 100% feed approach

### ISSUE THREAD

**Issue by shue249** [facebookincubator/Facebook-For-OpenCart#302]
From version 2.2.0 onwards, we have provided an approach to upgrade your catalog to be 100% feed approach and the API/access token is no longer in use. The API/access token will be eventually deprecated and we highly recommend all existing plugin users to upgrade to the newer versions.

2.2.0 - 11 Nov 2019
* Changed the product catalog sync method. On earlier versions, the plugin adopted 2 approaches - using feed file for initial catalog sync and API for subsequent product changes. From this version onwards, the plugin is adopting feed file for both initial catalog sync as well as subsequent product changes.
  1. There will be a daily feed pull to update the product catalog changes from your OpenCart website to Facebook product catalog.
  2. For existing plugin merchants, you need to perform a step to automatically generate the daily pull mechanism. Access the Facebook Business Extension module, click on Manage Settings, click on Advanced options. You will be able to see the notification indicating that the Catalog sync is successful. See screenshot here - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0
  3. Access token is no longer needed and there is no longer any need to update the access token nor to keep the Facebook account signed in.
  4. Better integration with other 3rd party product plugins. You can use any of the 3rd party product plugins to perform add/edit/delete product changes. These product changes will be automatically updated to Facebook via the daily feed mechanism.
  5. You can trigger immediate product sync to Facebook. Access the Facebook Business Extension module, click on Manage Settings, click on Your Products. Click on Fetch Now to sync your products to Facebook. See screenshot here - https://drive.google.com/open?id=1bCTT4gU4gC8pi6T6HLhpe2fkHWI-RvhN

Comment on this ticket if you are encountering any issues.

**Comment by alireza-shamakhy** [comment]
Hi,

I have updated the extension, however still have issues. The error message has gone but I cannot see manage settings at all.
I want to change my password in settings but there is no way for me to do that in opencart extension. It is just spinning. I removed the extension and reinstalled but no lock.
Please advise, thanks!
![Screen Shot 2019-12-06 at 7 59 11 pm](https://user-images.githubusercontent.com/1912181/70310204-33e9a300-1863-11ea-92b5-d9405ba61ba3.png)

**Comment by shue249** [comment]
@alireza-shamakhy Can you do a force refresh of your broswer, it could be a problem of caching of old data on your browser. If this still does not work, can you open up the javascript console and share a screenshot of any errors on the console.

**Comment by arsh7023** [comment]
I have delete cache, and hard reload page but still same issue.``
![Screen Shot 2019-12-07 at 8 22 47 am](https://user-images.githubusercontent.com/1134716/70359618-72697700-18d0-11ea-85a4-56c307b667f2.png)

**Comment by shue249** [comment]
@arsh7023 

We need to check the source settings for Facebook Business Extension to verify the problem. Will you be able to view source, and share out lines 14 to 319 with us here. Note that you should NOT share out line 320, as it contains your OpenCart token.

**Comment by dtying** [comment]
@arsh7023 Could you also try to click on 'refresh' button in Menu -> Extensions -> Modifications, and then check if the error gone?
![Screen Shot 2019-12-09 at 2 44 10 PM](https://user-images.githubusercontent.com/21333308/70413700-fa977a00-1a92-11ea-9cc2-f6808c7ce5a8.png)

**Comment by arsh7023** [comment]
Hi,

I have clicked on the refresh button and also cleared the modifications.
Also exactly what part of the code you guys needed? Are you looking for /admin/controller/extension/facebookadsextension.php?
What is the difference between facebook Ads extension and business extension?

Also please have a look at two screen shots below:
![Screen Shot 2019-12-09 at 6 26 18 pm](https://user-images.githubusercontent.com/1134716/70415956-faf33d80-1ab1-11ea-83ce-881fa8da5d47.png)
![Screen Shot 2019-12-09 at 6 31 23 pm](https://user-images.githubusercontent.com/1134716/70416022-283feb80-1ab2-11ea-94fa-28b215f8b20f.png)

Can you please double check in your end and let me know whether my data has synced?
Thanks for your support.

**Comment by shue249** [comment]
@arsh7023 Thank you for the screenshots. There are 2 problems.
1. The earlier problem where the loading indicator keeps showing and error showing on the javascript console is gone. We can close this problem.

2. For the new second problem (warning message showing that pixel is not correctly setup), can you share with us your webstore URL.

Also, may I ask if your website is the same as that reported by @alireza-shamakhy ?

**Comment by arsh7023** [comment]
Hi ,
the website is :
https://sunsharesolar.com.au
and also yes, it is the same report.

Cheers

**Comment by shue249** [comment]
@arsh7023 We looked at your website, 2 things we like to share.

1. For the pixel incorrect setup warning message shown by our plugin, we have released a newer version 2.2.1 which fix this problem. You can download the version from here https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

2. We found a set of existing pixel codes on your website. We highly recommend you to remove the existing pixel codes to avoid duplicate fires for the pixel.
![image](https://user-images.githubusercontent.com/11957585/70417981-6a126700-1a9d-11ea-96c7-9f191fb1b002.png)

**Comment by arsh7023** [comment]
Thanks @shue249 
I have updated the plugin and also removed the existing pixel code. I think it is working now, can you please double check in your end if possible?
Cheers

**Comment by shue249** [comment]
@arsh7023 A quick check on your website shows that the pixel setup is ok.

**Comment by arsh7023** [comment]
There is a fatal error when a user uses paypal to complete shopping (paying by cart). I think it is related to your plugin. can you please have a look at this asap. thanks,
![Fatal Error-inspect](https://user-images.githubusercontent.com/1134716/71151657-64303900-2288-11ea-89d4-6295b4c7dfa0.png)
![Fatal Error](https://user-images.githubusercontent.com/1134716/71151666-67c3c000-2288-11ea-86bc-00cac0bdeffd.png)

**Comment by shue249** [comment]
@arsh7023 

There could be some old files which are not updated correctly, can you run through these steps:
1. Delete away the plugin from your OpenCart and click on refresh modifications (https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw)
2. Ensure that your admin, catalog and system folders are given read+write permissions
3. Install back the plugin
4. Click on refresh modifications (https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw)

Let us know if these helps

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions.
