### ISSUE TITLE
Php 7.x warning message should be fixed - A non-numeric value line 494

### ISSUE THREAD

**Issue by condor2** [facebookincubator/Facebook-For-OpenCart#304]
Line 494 from facebookeventparameters.php

I think need to be changed from
`list($sort, $order, $page, $limit) = $this->getGeneralFilterParameters();`

to
`list($sort, $order, $page, $limit) = (int)$this->getGeneralFilterParameters();`

**Comment by shue249** [comment]
@condor2 Thank you for the feedback. Let us look into this.

**Comment by shue249** [comment]
@condor2 Can we check what is your webstore URL?

**Comment by shue249** [comment]
@condor2 We have rolled out a new version 2.2.1, which should fix this problem. https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

We will be closing out this ticket, feel free to reach to us if you have any further questions.
