### ISSUE TITLE
Text in Facebook shop

### ISSUE THREAD

**Issue by exitsport** [facebookincubator/Facebook-For-OpenCart#306]
Hi,

It is possible to see in Facebook shop same text, what we add from Opencart? In Facebook shop all info whitout any spaces: Cube Reaction GTC 29", Carbon. Raami suurus: **19"RAAM:GTC** Twin Mold Monocoque Technology, ARG2, Tapered Headtube, PressFit BB, X12, Integrated Cable **RoutingVÄRV:carbon´n´greenFORK:Manitou** M30 Air, Remote Lockout, **100mmHEADSETFSA** Orbit I-t-R, Integrated, Top 1 1/8", Bottom 1 1/8"STEMCUBE Performance Stem Pro, 31.8mmHANDLEBARCUBE Flat Race Bar 720mm 8°GRIPSCUBE Performance GripREAR DERAILLEURShimano XT RD-M8000-DSGS, ShadowPlus, 11-Speed, Direct MountFRONT DERAILLEURShimano XT FD-M8020-D, Direct Mount, Side SwingSHIFTERSShimano SLX SL-M7000BRAKE SYSTEMShimano BR-M315, Hydr. Disc Brake (180/160CRANKSETRace Face Ćffect SL 36x26T, 175mmCASSETTEShimano SLX CS-M7000, 11-42TCHAINKMC X11RIMSCUBE EX21, 32H, Disc, Tubeless readyFRONT HUBShimano Deore HB-M615, CenterlockREAR HUBShimano Deore FH-M618, Centerlock, 142x12mmFRONT TIRESchwalbe Tough Tom, Active, 2.25REAR TIRESchwalbe Rapid Rob, Active, 2.25SADDLECube Active 1.1SEAT POSTCUBE Performance Post, 27.2mmSEATCLAMPCUBE Varioclose, 31.8mmWEIGHT11.95 kg

**Comment by shue249** [comment]
@exitsport We are using the description from the OpenCart product. We believe that that the descriptions are multi-line long text and the plugin have stripped away all special characters, including the next line, resulting in all the info meshing together.

This is the method function which generates the description - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L121

**Comment by shue249** [comment]
@exitsport  We will be closing out this ticket. Feel free to reach to us if you have further questions.
