### ISSUE TITLE
An error occurs while going to the module page

### ISSUE THREAD

**Issue by mankovds** [facebookincubator/Facebook-For-OpenCart#309]
An error occurs while going to the module page.

We have detected the Facebook pixel, Messenger customer chat is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

The rights to folders under paragraph 1 are normal. Checked and tried different options.
Point 2, updated modifiers, sense 0.
Disabled and cleared the cache under item 3
And on the fourth point - no changes were made in the twig files.

By the way, I even tried to reinstall. Did not help.
What do i do?

**Comment by mankovds** [comment]
I enclose a screenshot of the error:
![image](https://user-images.githubusercontent.com/43268584/70549741-60603080-1b7d-11ea-8b8d-9e42c1bc9c1e.png)

**Comment by shue249** [comment]
@mankovds We have just released a newer version 2.2.1. Can you remove the older version and install the newer version, refresh modifications and see if this solves the warning messages. We checked on your website and the pixel setup is correct, so the warning message is a false positive.

https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

**Comment by webdreamsbg** [comment]
Hello,

I have the same problem even when I put the newest version 2.2.1, OC 2.3.0.2

Hope you can find a solution

**Comment by mankovds** [comment]
> @mankovds We have just released a newer version 2.2.1. Can you remove the older version and install the newer version, refresh modifications and see if this solves the warning messages. We checked on your website and the pixel setup is correct, so the warning message is a false positive.
> 
> https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

Hello. Again tried to update, tried to reinstall from scratch. Did not help. All the same error.

**Comment by ozfarmer** [comment]
Hi I have just installed the latest version 2.2.1 but it hangs see https://prnt.sc/q9l1n8 I am using opencart 3.0.3.2

All the best Kenso.

**Comment by ozfarmer** [comment]
If I drop back to Plugin Version: 2.1.13 it works fine.

**Comment by mankovds** [comment]
Откат на предыдущую версию так же не помог. 
Почему может такое происходить?

**Comment by mankovds** [comment]
Here are the modifier logs. maybe they will tell you where to dig.

MOD: Facebook Business Extension
CODE: public function index(
LINE: 22

FILE: admin/controller/common/dashboard.php
CODE: public function index(
LINE: 52
CODE: public function index(
LINE: 31
CODE: public function index(
LINE: 33
CODE: </head>
LINE: 443
CODE: </header>
LINE: 549
CODE: {{ footer }}
LINE: 750

FILE: admin/view/template/common/dashboard.twig
CODE: <div class="container-fluid">{% if error_install %}
LINE: 37

FILE: admin/language/ar/common/dashboard.php
CODE: <?php
LINE: 9

FILE: admin/language/en-gb/common/dashboard.php
CODE: <?php
LINE: 9

FILE: admin/language/ru-ru/common/dashboard.php
CODE: <?php
LINE: 9

FILE: system/engine/router.php
CODE: public function __construct($registry
LINE: 37
CODE: while ($action instanceof Action) {
LINE: 76
CODE: public function dispatch(Action $action, Action $error) {
LINE: 60
CODE: while ($action) {
NOT FOUND - OPERATIONS ABORTED!
CODE: public function dispatch($action, $error) {
NOT FOUND - OPERATIONS ABORTED!
CODE: $result = $this->execute($pre_action);
LINE: 74

FILE: catalog/language/ar/common/header.php
CODE: <?php
LINE: 6

FILE: catalog/language/en-gb/common/header.php
CODE: <?php
LINE: 6

FILE: catalog/language/ru-ru/common/header.php
CODE: <?php
LINE: 6

FILE: catalog/controller/common/footer.php
CODE: public function index(
LINE: 31
CODE: public function index(
LINE: 33

FILE: catalog/view/theme/default/template/common/footer.twig
CODE: </footer>
LINE: 256
CODE: </footer>
LINE: 267

**Comment by mankovds** [comment]
Hello. Yesterday again I tried to update, remove the module. It didn’t work. Today I got to the site and decided to go in and see what’s wrong with the module, and it miraculously earned. Not a single mistake. How is this possible? Perhaps this was a problem on the Facebook side?

**Comment by mankovds** [comment]
Hello again. The module works every other time. Last night I earned, this morning the same mistake! Where to go out? It doesn’t matter that one day the goods are synchronized, the second is not.

**Comment by shue249** [comment]
@mankovds , @webdreamsbg 

Can you share with us your website url? Our pixel diagnostics mechanism is rather simple and we have challenges with users who have installed web optimsers which break the diagnostics, even though the pixel may be correctly firing.

**Comment by shue249** [comment]
@ozfarmer Can you open up javascript console and share with us screenshot of any errors showing up on the console.

Also, can you do a force refresh of your browser and disable any caching.

**Comment by webdreamsbg** [comment]
> 
> 
> @mankovds , @webdreamsbg
> 
> Can you share with us your website url? Our pixel diagnostics mechanism is rather simple and we have challenges with users who have installed web optimsers which break the diagnostics, even though the pixel may be correctly firing.

Sure, this is the website: https://www.ribarcheto.bg

**Comment by mankovds** [comment]
> @mankovds , @webdreamsbg
> 
> Можете ли вы поделиться с нами URL вашего сайта? Наш механизм диагностики пикселей довольно прост, и у нас есть проблемы с пользователями, которые установили веб-оптимизаторы, которые нарушают диагностику, даже если пиксель работает корректно.

https://kidds.shop

**Comment by shue249** [comment]
@webdreamsbg We are getting a 403 on your website. Are there any IP restrictions for your website? 

![image](https://user-images.githubusercontent.com/11957585/71137780-375a3280-2244-11ea-9fec-200cbe960cb2.png)

**Comment by shue249** [comment]
@mankovds We checked on your website and the pixel installation is correct, so the warning on your OpenCart admin Facebook business extension module is a false positive. Will you be able to do a force refresh of your browser to see if the warning message goes away.

If the warning message persists, can you look at the file config.php on your OpenCart webserver, find the line which has HTTPS_CATALOG and share with us the details of this line.

**Comment by mankovds** [comment]
> @mankovds We checked on your website and the pixel installation is correct, so the warning on your OpenCart admin Facebook business extension module is a false positive. Will you be able to do a force refresh of your browser to see if the warning message goes away.
> 
> If the warning message persists, can you look at the file config.php on your OpenCart webserver, find the line which has HTTPS_CATALOG and share with us the details of this line.

In which config to look for HTTPS_DIRECTORY did not quite understand? In the opencart config or in the hosting configuration?

**Comment by shue249** [comment]
@mankovds Apologies for not being clear. Here is the steps.

![image](https://user-images.githubusercontent.com/11957585/71273200-c5423480-238e-11ea-88f4-71e479ac47fd.png)

**Comment by mankovds** [comment]
> @mankovds Apologies for not being clear. Here is the steps.
> 
> ![image](https://user-images.githubusercontent.com/11957585/71273200-c5423480-238e-11ea-88f4-71e479ac47fd.png)

define('HTTPS_CATALOG', 'https://kidds.shop/');

**Comment by shue249** [comment]
@mankovds Apologies for the late reply. Like to check if you have uninstalled our plugin from your website?

**Comment by shue249** [comment]
@webdreamsbg We checked on your website. The pixel installation is correct. Are you still getting the warning message about incorrect pixel installation on the Facebook Business Extension module? If so, you can ignore the warning message as false positive detection.

**Comment by webdreamsbg** [comment]
> 
> 
> @webdreamsbg We checked on your website. The pixel installation is correct. Are you still getting the warning message about incorrect pixel installation on the Facebook Business Extension module? If so, you can ignore the warning message as false positive detection.

Everything is ok now. Thanks!

**Comment by shue249** [comment]
@mankovds We will be closing out this ticket, but pls feel free to reach to us if you have further questions!
