### ISSUE TITLE
synchronized with Facebook, but the site does not install the pixel

### ISSUE THREAD

**Issue by neshchadin** [facebookincubator/Facebook-For-OpenCart#31]
Hello, the goods are synchronized with Facebook, but the site does not install the pixel. Log attached. Site - https://kidzzz.online/

**Comment by neshchadin** [comment]
[Kidzzz - магазин детской одежды_2018-08-22_08-48-38_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2309041/Kidzzz.-._2018-08-22_08-48-38_facebook_ads_extension.log)

**Comment by shue249** [comment]
@neshchadin Thank you for your feedback! There was some issues with the version of the plugin from the partner gallery on Facebook. We are currently updating that version of the plugin.

Can you download the updated version from OpenCart. 
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336

After you remove and install in the new version the pixel should be fired. There is no need to re-setup the Facebook Ads Extension.

**Comment by shue249** [comment]
@neshchadin We have also updated the plugin file from the partner gallery on Facebook. We will proceed to close out this ticket, but feel free to reopen if you need any help from us.

**Comment by reginamor** [comment]
i've installed the extension and i hace a problem with the url of the feed, because when i've installes de https certificated, i have to erase the url on the config files (i don't have url)
Where can i chage the url of the feed? i found the file that sends this configuration, but i can't found it. Thanks
