### ISSUE TITLE
Images do not show on products

### ISSUE THREAD

**Issue by virgiltu** [facebookincubator/Facebook-For-OpenCart#312]
Anybody has any idea why the pictures do not show on all products? 

https://business.facebook.com/pg/istyle.furniture/shop/?ref=page_internal

**Comment by shue249** [comment]
@virgiltu This could be a case of caching. We are checking on this and will get back to you soonest.

**Comment by shue249** [comment]
@virgiltu Apologies for the late reply. We did a quick check and the images are now showing on the page shop products. Let us know if you have any further questions.

**Comment by shue249** [comment]
@virgiltu We will be closing out this ticket. Feel free to reach to us if you have further questions.
