### ISSUE TITLE
facebook business extension

### ISSUE THREAD

**Issue by doandbe** [facebookincubator/Facebook-For-OpenCart#313]
Good morning 
can not upload and install new version it says the the files are not compatible or not valid see the picture 
![facebook business manager fail instalation](https://user-images.githubusercontent.com/58469642/70887845-8fe0c400-1fe7-11ea-8dba-c4e1dc293db8.PNG)

**Comment by doandbe** [comment]
also there is another issue messenger plug in should be appearing in all pages you should get a choice for the user or even the administrator to swicth it off in some pages and maybe disable greeting , lot of my customers are complaining  because most of them use mobile devices and this makes it very difficult to navigate and have all the time messenger along with greeting maybe you should put it a side.

my customers can not even access the products on mobile devices because the greeting is on the bar

maybe greeting should disappear after a few seconds

**Comment by shue249** [comment]
@doandbe Thank you for the feedback.

1. For the problem on file not compatible or invalid, you may have zipped up the plugin files in an incorrect way (if you are unable to download the zip file directly). You can check this FAQ (point 3) and screenshot on how to zip up the plugin files in a correct way.
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#plugin-installation
https://drive.google.com/open?id=1A_EwXnTBc8OOES6D1D0yiEzp4NTN1VbU

2. We have taken in the feedback on the messenger chat display on mobile devices.

**Comment by shue249** [comment]
We will be closing this ticket. Feel free to reach to us if you have further questions.
