### ISSUE TITLE
Pixel does not work in website

### ISSUE THREAD

**Issue by Aelfriclake** [facebookincubator/Facebook-For-OpenCart#315]
I did everything updated to latest version too still geting the same error:  
  
 We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

fenomenkids.com

**Comment by Aelfriclake** [comment]
Pixel didn't work so i had to add it maunally to my header.tpl file. Now it works but the backend still doesn't detect it. Would it work okay?

**Comment by shue249** [comment]
@Aelfriclake  Apologies for the late reply. You are correct that the pixel installation from our plugin is incomplete, we couldnt find the pixel firing from our plugin on your website.

Although you have added in the pixel base code, but there wasnt additional events fired from the various pages, eg ViewContent from the product details page, AddToCart when clicking on the Cart button etc.

We can either troubleshoot to figure out why the plugin wasnt able to install the pixel codes or you can manually add in the individual pixel events to the various pages.

**Comment by Aelfriclake** [comment]
We should try to troubleshoot it i think because i won't be able to use the messenger app too with this. I tried to allow folder permissions etc. checked everything but i just can't find why it doesn't work? How can we proceed about this?

**Comment by shue249** [comment]
@Aelfriclake Apologies for the delay.

Here are my suggestions on how we can do the troubleshooting.

1. Verify if the modifications are applied correctly from the log file. Pls share the log contents.
![image](https://user-images.githubusercontent.com/11957585/72115407-decd0f80-3381-11ea-8bd0-59fceff1f6d1.png)

2. Locate the files header.tpl (OpenCart 2.x) or header.twig (OpenCart 3.x) in the system/storage/modifications/catalog/view/theme/<your theme>/common folder. Inpsect the file to check if the pixel code is inserted correctly.
![image](https://user-images.githubusercontent.com/11957585/72115627-b0036900-3382-11ea-86c6-e4f71345247f.png)

3. Do you have vqmod installed? Is the cache cleared?

4. Have you disabled the cache if you are on OpenCart v3.x? https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm

5. Did you make any changes to the header or footer design if you are on OpenCart v3.x? https://drive.google.com/open?id=1066BSKAqjKegzw-5oKuvtZuzu_PzkRZT

**Comment by shue249** [comment]
@Aelfriclake Wondering if we have any updates to the issues you are facing with the plugin?

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions.
