### ISSUE TITLE
Add Products With Facebook Pixel Problem

### ISSUE THREAD

**Issue by tomeda** [facebookincubator/Facebook-For-OpenCart#316]
I'm trying to create catalog using facebook pixel but I get missing id error, do you have any idea how would I fix that? I see that some plugins use 'content_ids as product ID.
![_22  Products](https://user-images.githubusercontent.com/10818796/71532666-1b6a2700-28fd-11ea-8912-cba2c4d8742d.png)
![Catalog Microdata Debug Tool](https://user-images.githubusercontent.com/10818796/71532667-1c02bd80-28fd-11ea-9825-c22cb45bb76a.png)

**Comment by shue249** [comment]
@tomeda Is this for the same website (https://protein4e.com) or a different website? if this is for the same website, then our plugin has already created a catalog for you. You can find the catalog by clicking on the "Manage Setting" button, "Your products" and then "See your products on Facebook".

**Comment by tomeda** [comment]
I have a catalog created but I thought this would be an easy fix so we can use both way.

**Comment by shue249** [comment]
@tomeda 

1. To generate the pixel from catalog, you will need to ensure that the microdata with the product details (eg id) is included in the website. The pixel will then pick up these microdata and use them for the catalog generation. This does not include the "content_id" from the pixel parameters. You can refer to this document for more details on the microdata - https://developers.facebook.com/docs/marketing-api/catalog/guides/microdata-tags

2. Can we understand how do you intend to use the second catalog?

**Comment by shue249** [comment]
@tomeda We will be closing out this ticket. Feel free to reach to us if you have further questions.
