### ISSUE TITLE
Facebook Business Extension forever syncing

### ISSUE THREAD

**Issue by marcelhai** [facebookincubator/Facebook-For-OpenCart#317]
Hello!

I installed the extension, but unfortunately I am unable to use it because it loads forever.
I attached a screenshot for better understanding.

<img width="900" alt="Screenshot 2019-12-29 21 14 57" src="https://user-images.githubusercontent.com/59341790/71560887-6ceeef00-2a80-11ea-85f7-30c0d517f537.png">

**Comment by shue249** [comment]
@marcelhai Thank you for the feedback.

1. Can you screenshot for us the javascript console of the module page. We suspect there is some errors on the page.

2. We experienced a similar case where the plugin files are not copied over correctly to the Opencart webserver. Can you verify that the admin, catalog and system folders are given read+write permissions, then remove away the plugin and re-install back the plugin again.

**Comment by hongyiu** [comment]
i have the same problem after i upgrade the extension to 2.2.1

**Comment by shue249** [comment]
@hongyiu Thank you for the feedback.

1. Can you screenshot for us the javascript console of the module page. We suspect there is some errors on the page.

2. We experienced a similar case where the plugin files are not copied over correctly to the Opencart webserver. Can you verify that the admin, catalog and system folders are given read+write permissions, then remove away the plugin and re-install back the plugin again.

**Comment by TomasQ789** [comment]
i have the same problem after i upgrade the extension to 2.2.1
1. Having tasted a copy file, it’s always in dia.js. 
2. Files having also tried uploading via FTP.
3. The right of access to the tags in the OPENCART panel
![Снимок экрана (127)](https://user-images.githubusercontent.com/61805208/75922685-2b0d6b00-5e6c-11ea-804a-9757beec29a0.png)
![Снимок экрана (128)](https://user-images.githubusercontent.com/61805208/75922695-31034c00-5e6c-11ea-80b3-dfc05eadd871.png)

**Comment by shue249** [comment]
@TomasQ789 Can you do a force refresh and clear cache on your browser. This is because the front end of your admin page is still using the older version of the js file.

**Comment by TomasQ789** [comment]
thnx it help
