### ISSUE TITLE
Add google event snippet to checkout success in opencart

### ISSUE THREAD

**Issue by creativegg** [facebookincubator/Facebook-For-OpenCart#318]
Hi,

I need to add google event code to me checkout success page code, but I don`t know where to find it.
Can you help me?

**Comment by shue249** [comment]
@creativegg 

Without more information on your google event code, we are unable to help you specifically on this.

However, we can share the logic on how our pixel code works on the checkout success page. Hopefully this will provide you with some insights on how you can solve your problem. We will share the logic in bullet point steps. One key principle for you to be aware of is that we use a central location to fire pixels for the entire website (vs firing pixel on individual pages). 

1. We added in a new controller (facebookeventparameters.php) which will be run everything a webpage is visited. This controller is invoked from the front.php (if you are on OpenCart v2.x) or router.php (if you are on OpenCart v3.x). The invocation codes are injected into front.php and router.php via ocmod when you installed the plugin and refreshed the modifications.

2. Within the facebookeventparameters.php controller, we will inspect the incoming URL route path and determine which is the right event to fire. This is a common controller where we declare some session variables which will be picked up later to be used in the pixel firing. This is the specific code pointer for checkout success page - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L128. If you trace through the code block, we store the data into the fbevents session variablehttps://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L57

3. The fbevents session variable will then be picked up the OpenCart header.php. We have injected some codes to read these data array and then put the variables into the "data" array. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L169-L202

4. Finally, the "data" array is picked up by the OpenCart header.tpl (OpenCart v2.x) or header.twig (OpenCart v3.x). Similarly, we injected codes to read the variables and then use them in the javascript to fire the FB pixel. 
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L247-L383
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L449-L585

We hope that this information is useful for you to make your code changes. Will be closing out this ticket, feel free to reach to us if you have further questions.
