### ISSUE TITLE
Problem with checkout - HTTP Error 500

### ISSUE THREAD

**Issue by monefff** [facebookincubator/Facebook-For-OpenCart#319]
Hello,

When I updated the module to the latest version, and when I try to make a purchase It gives me the following error:

This page isn’t workingMYDOMAIN.com is currently unable to handle this request.

I believe the error is because the module is adding "working" before the domain name, and it causes not to find the page.

I rolled back to the previous version, and it's working perfect.

Anyone else has the same error?

**Comment by shue249** [comment]
@monefff Can you check the following:

1. Ensure that you have given read+write permissions to the admin, catalog and system folders.

2. Delete away the plugin from the modifications page. Then reinstall back the plugin. 

3. Ensure that you have clicked on the Refresh modifications button

In our latest version, we moved the catalog sync from API to feed approach. As part of this change, we also removed away the need to call the API to update the FB product stock availability after your consumers successfully purchased. We believe that the purchase webpage is still on the older version which is making the API call on your OpenCart server, but this API call is no longer available, resulting in the 404 error.

**Comment by shue249** [comment]
@monefff We will be closing off this ticket. Feel free to reach to us again if you have any further questions.
