### ISSUE TITLE
sync error (not big catalog ) only 4K 

### ISSUE THREAD

**Issue by ramirami593** [facebookincubator/Facebook-For-OpenCart#320]
Hello
i have searched here and couldn't find any solution 

![image](https://user-images.githubusercontent.com/59527664/71778102-eec7a680-2fb1-11ea-9489-20fed20f3e76.png)

![image](https://user-images.githubusercontent.com/59527664/71778105-f5561e00-2fb1-11ea-9128-6ff73d9088a0.png)

opencart version 3.0.2.0

please advise what to do

**Comment by shue249** [comment]
@ramirami593 

We have a newer version of the plugin. Can you delete away the current version (which is an older version), install the newer version and click on Refresh modifications.

https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

You will be asked to upgrade your catalog which you can follow these steps - https://drive.google.com/open?id=1dAF88Spg-iAwPXmkwcVvAqg82UYJ5IJ0

**Comment by ramirami593** [comment]
i did what you ask me and have this problem now
![image](https://user-images.githubusercontent.com/59527664/71801780-9a313380-3064-11ea-9632-39e088426299.png)

**Comment by ramirami593** [comment]
i press the try again offcourse couple of time and Refresh modifications and all

**Comment by shue249** [comment]
@ramirami593 Can you share with us your website URL.

**Comment by ramirami593** [comment]
https://www.ikiaz.com/

**Comment by shue249** [comment]
@ramirami593 Like to check with you. Have you been using this plugin since Jan 2019 (last year)?

**Comment by ramirami593** [comment]
i don't remember exactly but yes we have been using it more than a year i think
the older version off course.

**Comment by dtying** [comment]
Hi @ramirami593, the 'Catalog Sync Failed' error is due to data discrepancy in our backend. Can you follow the steps here (https://github.com/facebookincubator/Facebook-For-OpenCart/issues/308#issuecomment-564849885) and try again?

**Comment by ramirami593** [comment]
Working now thank you
