### ISSUE TITLE
displayed value

### ISSUE THREAD

**Issue by willianschiavao** [facebookincubator/Facebook-For-OpenCart#321]
Is there a possibility to choose the value to be displayed? I have 3 types of customer registered on the site.

![opencart-facebook](https://user-images.githubusercontent.com/59648985/71976695-b31d1e80-31f5-11ea-84de-cec01b962af4.PNG)

**Comment by shue249** [comment]
@willianschiavao Thank you for the feedback.

We do not have any plans to support for prices based on customer groups. On Facebook, we have 2 prices - the normal price and sales price.

However, if you have engineering resources, we can provide the code pointers on where you can extract out the relevant prices to be used to display on Facebook.
1. This is the controller where the plugin extracts out the list of products and the product data which will be used to be converted into a csv product feed file. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/controller/extension/facebookproductfeed.php#L138-L139

2. This is the model file which makes the SQL call to the database to extract out the product list. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/model/extension/facebookproduct.php#L15-L149

3. This is the utility class which converts the product data into the feed data. This method is where the price is extracted - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L175-L180

4. Similarly, this is the method for extracting the discount price - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L235-L287

5. Finally, you can do the debugging and verification on the feed file which is generated. This is the physical location of the feed file on your server - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/controller/extension/facebookproductfeed.php#L71-L77

Do let us know if you have any further questions.

**Comment by shue249** [comment]
@willianschiavao We will be closing out this ticket. Feel free to reach to us if you have further questions.
