### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by stonecoldwpass** [facebookincubator/Facebook-For-OpenCart#322]
The page you are looking for could not be found! Please contact your administrator if the problem persists. after install

**Comment by shue249** [comment]
@stonecoldwpass 

1. What is the Facebook page that you used for the original setup? We have seen similar reports from other users when they deleted away the Facebook page used in the setup.

2. What is your webstore URL?

**Comment by stonecoldwpass** [comment]
https://www.choicecomputertechnologies.com/

 

https://www.facebook.com/choicecomputertechnologies/

 


Thank You

 

Jamie Mclean


Owner Technician


Choice Computer Technologies - Canadian Computer Store
Computer Sales and Repairs


p:

587 333 2019  m: 587 581 8281


a:

808 1101 84 street North East, Calgary, Alberta T2A 7X2


w:

 <https://www.choicecomputertechnologies.com/> www.choicecomputertechnologies.com  e:  <mailto:info@choicecomputertechnologies.com> info@choicecomputertechnologies.com




 <https://www.facebook.com/choicecomputertechnologies/>   <https://twitter.com/Choicecomputer1>   <https://www.linkedin.com/pub/jamie-mclean/33/104/b76>   <https://plus.google.com/u/0/b/109820331291577340114/109820331291577340114>   <https://www.pinterest.com/Choice_Computer/choice-computer-technologies/>

**Comment by shue249** [comment]
@stonecoldwpass There could be some issues with the Facebook business extension settings. Have you run any ads using the catalog created from our plugin?

**Comment by shue249** [comment]
@stonecoldwpass Circling back to your problem. Are you still facing the problem?

**Comment by shue249** [comment]
Closing this issue. Pls feel free to reach to us if you have further questions.
