### ISSUE TITLE
Total order value vs Content value

### ISSUE THREAD

**Issue by filipburman** [facebookincubator/Facebook-For-OpenCart#323]
Hi,

We used to have the pixel manually installed on the site. We moved over to your module now but I have 1 problem. Before I used the track the value of the order, not it tracks the content instead. 
So if I have a product that cost €100 and someone uses a discount code with 50%. Then it still tracks the value of €100. So the ROAS on my ads is misleading. 

How can I track the value of the order instead of just the product?

Regards, Filip

**Comment by shue249** [comment]
@filipburman Thank you for your feedback.

This request is currently not on our roadmap. However, if you have engineering resources, we can point to you the code pointers to make the changes to the plugin code so that you can pass in the final order value. Let us know your thoughts.

**Comment by filipburman** [comment]
Dear,

That would be great! Thank you so much. Then I can give it to my developer.

May I know why this is not in your "roadmap". Because I feel that this is something that every webshop owner is interested in. Everyone wants to see a clear ROAS on their ads. And this is creating a very misleading view.

REgards, Filip

**Comment by shue249** [comment]
@filipburman Thank you for the feedback.

The starting code pointer will be here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L129. The code will pull out the purchased products, sum up the product values and return back the product ids and the summed value. Your developer will need to change the codes here to include in the discount value as well.

Your feedback on having a clear ROAS with the discount value is well taken into consideration. Some of the core considerations include prioritization on other core features for the plugin which we are investing time in at the moment.

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions.
