### ISSUE TITLE
We have detected the Facebook pixel, Messenger customer chat is not correctly setup in your web store site. You can try these below steps to fix the problem.

### ISSUE THREAD

**Issue by kanjuo** [facebookincubator/Facebook-For-OpenCart#324]
Hi

I have gone through all the recommended steps and continue to experience the same issue.

![Screen Shot 2020-01-21 at 9 43 04 PM](https://user-images.githubusercontent.com/17259480/72837374-0c298f80-3c97-11ea-8ee3-a52614414047.png)

**Comment by shue249** [comment]
@kanjuo Can you share with us your webstore URL here?

**Comment by svremeto** [comment]
Hello @shue249 I have the same problem with my new store (I made a full copy of my last store to keep  all the settings that i`ve made). I deleted the facebook extension and installed the last version (221). So now I dont see the chat and also the extension for Chrome - Facebook Helper doesn`t find any pixel on the website.

**Comment by kanjuo** [comment]
I thought this module could help set up Pixel Events....also where is the Pixel code located after then module installation

**Comment by shue249** [comment]
@svremeto Can you share with us your web store URL, so that we can help to look into this

**Comment by shue249** [comment]
@kanjuo Can you share with us your web store URL, so that we can help look into this

**Comment by shue249** [comment]
To provide more context, we have implemented some simple detection mechanisms to check if the pixel and messenger chat are setup properly. However, some of the websites may have installed optimization which causes false positives in the detection mechanisms.

**Comment by svremeto** [comment]
@shue249  https://nsvendor.com/

**Comment by docidoci68** [comment]
> Hi
> 
> I have gone through all the recommended steps and continue to experience the same issue.
> 
> ![Screen Shot 2020-01-21 at 9 43 04 PM](https://user-images.githubusercontent.com/17259480/72837374-0c298f80-3c97-11ea-8ee3-a52614414047.png)

**Comment by shue249** [comment]
@svremeto We checked on your website and the pixel setup is correct. Are you still facing the warning message on your OpenCart admin panel?

**Comment by shue249** [comment]
@docidoci68 Can you share with us your webstore URL?

**Comment by svremeto** [comment]
@shue249 Yes, Still the same. The messenger I used was a script that I placed in the website. Not the script that the extension place on the website. The red message in the admin pan still the same.

**Comment by docidoci68** [comment]
Hello I have two installations of Opencart

One actually working , with Fastor Theme, -https://shop.agrodrip-zahara.com/


and another, that I use to prepare the Journal theme  -
https://jurnal.shop.agrodrip-zahara.com/



I have managed to install an older version of the plugin 2.1.3

I am able to install version 2.2.10  also but it gives the errors

IF you want I can also send you the admin user and passwords

regards
*Стара Загора, Бешбунар*
*тел:+359879542562, +359879542564*
*http://shop.agrodrip-zahara.com/ <http://shop.agrodrip-zahara.com/>*




На вт, 18.02.2020 г. в 3:17 shue249 <notifications@github.com> написа:

**Comment by shue249** [comment]
@svremeto You can ignore the warning messages on the OpenCart admin panel, as we verified that the pixel is working correctly. This is a false detection.

**Comment by svremeto** [comment]
@shue249 Okay, thanks. But the pixel helper also doesn't finds any existing pixel on the website.

**Comment by shue249** [comment]
@svremeto Want to check if you have installed any ad blocker or disabled the cookie on the machine where pixel helper was not able to detect any pixel.

We verified on our side and the pixel is shown up correctly.
![image](https://user-images.githubusercontent.com/11957585/76376795-30931580-6384-11ea-9665-6f3c66c54d8d.png)

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions.
