### ISSUE TITLE
Unable to Scroll page when extension is enabled

### ISSUE THREAD

**Issue by reorado** [facebookincubator/Facebook-For-OpenCart#325]
Dear support,

I experienced this problem for a while and just realize that the extension might have caused the problem and happens only on iphone

I am using opencart 3.0.3.2 with journal 3 theme. When browsing the page, the page just couldn't be scrolled. I now disabled the extension and the page can be scrolled again.

I still have to keep monitor the page to see if it happens again. Would you have any suggestion?

**Comment by shue249** [comment]
@reorado We like to learn more on this.

1. When you mention that the page cannot be scrolled, do you mean your webstore page?

2. What is your webstore URL?

**Comment by shue249** [comment]
@reorado We will be closing out this ticket. Feel free to reach to us if you have further questions.
