### ISSUE TITLE
Login in Messenger

### ISSUE THREAD

**Issue by exitsport** [facebookincubator/Facebook-For-OpenCart#326]
Hi

We used Messenger in web. One issue: if customer want to chat whit us, you need to sign in to messenger. But that not work

https://gyazo.com/52cd2efe57536abe9e885b3cc905d15c

**Comment by shue249** [comment]
@exitsport Thank you for the feedback! We have shared this feedback with our Messenger teams.

**Comment by exitsport** [comment]
exitsport.eu
All browser: Chrome, Edge

**Comment by shue249** [comment]
@exitsport Apologies for the delay. 

When we tested on your website earlier about the experience, we could not replicate the behaviour in your video. We were able to see and interact on the Messenger chat without that infinite loop on Sign in/Log in.

Want to check if you have installed any ad blocker on the machine which gave the behaviour.

**Comment by shue249** [comment]
@exitsport We will be closing out this ticket. Feel free to reach to us if you have further questions.
