### ISSUE TITLE
Turn off automatically product sync

### ISSUE THREAD

**Issue by aminruddin27** [facebookincubator/Facebook-For-OpenCart#327]

**Comment by shue249** [comment]
@aminruddin27 Can we understand the reasons for you wanting to turn off the automatic product sync? The automatic sync is to ensure that your website products are up to date on Facebook catalog.

**Comment by aminruddin27** [comment]
@shue249 I do integration with ERP system that sync the product from ERP to Opencart very frequent and I have 5k item in the list to sync.

**Comment by shue249** [comment]
@aminruddin27 Thank you for the feedback.

Currently the automatic sync from your OpenCart to Facebook is performed once daily. 

If you really wish to turn off the automatic sync, you can follow the steps in the below image to do that. However, you will need to manually trigger the sync from Facebook to OpenCart to keep the products on Facebook up to date. You can use the URL indicated on the schedule to do the manual sync.

![image](https://user-images.githubusercontent.com/11957585/74694399-f1f9b780-522a-11ea-81dc-123fe6b61a4c.png)

We will be closing out this ticket. Feel free to reach to us if you have further questions.
