### ISSUE TITLE
replaces the journal theme 

### ISSUE THREAD

**Issue by docidoci68** [facebookincubator/Facebook-For-OpenCart#328]
Hello I am trying to install Facebook add add extension  facebook_ads_extension.ocmod and before instsling it have to istall the ftp fix localcopy.ocmod. When I install it it does not work wit the theme. The istalation is not in  public_html directory. Is there a way to install the files manually of Facebook extention with file Zila. I have tried but I don see the extention

**Comment by shue249** [comment]
@docidoci68 Thank you for the feedback. We have several questions.

1. Have you followed the installation guide here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation

2. Have you rename the "admin" folder to a different name in your OpenCart folder?

We have users who have successfully used our plugin with the Journal theme, so we are suspecting that it could be a different problem which you are facing.

**Comment by docidoci68** [comment]
@docidoci68 <https://github.com/docidoci68> Thank you for the feedback. We
have several questions.

   1.

   Have you followed the installation guide here -
   https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation


Yes I have,

   1.

   Have you rename the "admin" folder to a different name in your OpenCart
   folder?

I have one admin folder named "admin" -  and another an old one  "admin1"

We have users who have successfully used our plugin with the Journal theme,
so we are suspecting that it could be a different problem which you are
facing.
*Стара Загора, Бешбунар*
*тел:+359879542562, +359879542564*
*http://shop.agrodrip-zahara.com/ <http://shop.agrodrip-zahara.com/>*




На вт, 18.02.2020 г. в 3:14 shue249 <notifications@github.com> написа:

**Comment by shue249** [comment]
@docidoci68 Want to check if you are still encountering any issues with the installation?

**Comment by docidoci68** [comment]
Hello

The only version that is working ok for me is  2.13  it is installed on one
of my domains and everything is ok :  https://shop.agrodrip-zahara.com/

I have installed 2.19 version on another domain manually. It was all ok -I
mean the extension did what it has to be done, made the connection with the
page   but I did not find the pixel on the page so I removed it

About the latest version, I did not try more and can not tell. I think
there will not be any change


*Стара Загора, Бешбунар*
*тел:+359879542562, +359879542564*
*http://shop.agrodrip-zahara.com/ <http://shop.agrodrip-zahara.com/>*




На пн, 2.03.2020 г. в 5:06 shue249 <notifications@github.com> написа:

**Comment by shue249** [comment]
@docidoci68 Ideally we will like for you to be using the latest version (v2.2.1), as there are some improvements to the catalog sync mechanism. To help us further troubleshoot this, can we ask for you on this.

1. Can you Clear away the modifications log.
![image](https://user-images.githubusercontent.com/11957585/76040077-4e7a0800-5f89-11ea-96f1-8c43ca9cdd8c.png)

2. Remove the current version and install the version 2.2.1 plugin. Then click on Refresh modifications.

3. Capture the modifications log and share with us. The modifications log will contain information that show the installation process. When the pixel is not installed properly, the log will reflect where are the failures, which will give us information on the possible causes.

**Comment by docidoci68** [comment]
Hello, I did what you have written. By chance, I managed to install version
2.2.0 first, then removed it and installed 2.2.1 and everything in the
admin panel  seems ok, but the pixel is not recognized from Facebook pixel
helper. I checked the source page and it is found on the source but the
helper can not find it . I have attached a video link to see the process:

https://my.pcloud.com/publink/show?code=XZltWekZPvwlml2lNRQcw7VmWuzxyF59bXgy

I have also attached the copied log file

*Стара Загора, Бешбунар*
*тел:+359879542562, +359879542564*
*http://shop.agrodrip-zahara.com/ <http://shop.agrodrip-zahara.com/>*




На пт, 6.03.2020 г. в 3:05 shue249 <notifications@github.com> написа:

**Comment by shue249** [comment]
@docidoci68 Apologies for this late reply.

We did a check on your website (URL from your video) and found that the pixel is firing correctly. Perhaps you can check if your browser has ad blocker installed which prevents the pixel from firing.

![image](https://user-images.githubusercontent.com/11957585/77500146-234f4e00-6e8f-11ea-8ea4-4d7ad2ed0864.png)

We will be closing out this ticket. Feel free to reach to us if you have further questions.
