### ISSUE TITLE
can not switch off messenger pixel problem

### ISSUE THREAD

**Issue by doandbe** [facebookincubator/Facebook-For-OpenCart#329]
i am not able to switch off the messenger on Facebook business extension i tried uninstall and install and it doesn't do anything 
because it is an eshop a have problem with customers because there is another issue: from mobile devices when you press x to close messenger (by the way the x is too small) it keeps appearing in every page you go again and again and customers get tired
Also i have a problem with pixel on the main page for  facebook business manager it shows ok but inside it doesnt recognize the pixel which was working on the past and it doesnt let me make any changes

**Comment by shue249** [comment]
@doandbe 

1. For disabling the Messenger chat plugin, can you follow these steps - https://drive.google.com/open?id=1J_kOcyIWBZeO3YJZMJFMQlWui5eSn3Kq

2. Thank you for the feedback for the mobile experience. We have shared this with our teams!

3. For the pixel problem, can you describe more on the problem to help us understand better. If there are any screenshots, it will help us greatly if you can copy-paste the screenshots here.

**Comment by shue249** [comment]
@doandbe We will be closing out this ticket. Feel free to reach to us if you have further questions.
