### ISSUE TITLE
cookies notice

### ISSUE THREAD

**Issue by reginamor** [facebookincubator/Facebook-For-OpenCart#33]
how can erase this message? i have my own RGPD cookie notice that saids that i use the facebook pixel, and i don't need a second notice (it's very annoying for my costumers acept 2 notices of cookies)

**Comment by shue249** [comment]
@reginamor Thank you again for your feedback.

We are now looking into enhancing the plugin to allow the option to show the cookie bar. In the meantime, you can look into making a manual change yourself. For the details, pls refer to this ticket https://github.com/facebookincubator/Facebook-For-OpenCart/issues/20

**Comment by reginamor** [comment]
I don't know how to wage that, I'm not a developer, just a web designer
that try to understand.
I saw that it's on the Javascript file, but I don't know in witch part,
because there you also put the information of the pixel.
If I erase something that I don't have to erase, the pixel will not work

**Comment by hrm143** [comment]
Even after clicking allow Cookies/ Opt Out button..the Cookie bar always shows on OC2.3.0.2 so i have to manually removed to disallow cookie bar from the plugin.

**Comment by lennt92** [comment]
> Even after clicking allow Cookies/ Opt Out button..the Cookie bar always shows on OC2.3.0.2 so i have to manually removed to disallow cookie bar from the plugin.

the same problem, what code you change for it ?

**Comment by shue249** [comment]
@reginamor , @hrm143 We have released a latest version of the plugin, v2.1.2, which you can now choose to disable the cookie bar from the Facebook Ads Extension panel. Pls install the latest version for the changes to take effect.

Will be closing out this request, but feel free to reopen the ticket as needed.

**Comment by reginamor** [comment]
hi! i downloaded the extension from github (on facebook still the older version) and when i'm trying to upload gives this error

> Directory that contains files to upload could not be found!


i have opencart 2.3.0.2

**Comment by reginamor** [comment]
@shue249 i don't know how to re-open

**Comment by reginamor** [comment]
@shue249 hello??
