### ISSUE TITLE
Website blocked again because Community Standards

### ISSUE THREAD

**Issue by nymphaclothing** [facebookincubator/Facebook-For-OpenCart#330]
Today we got blocked again, below you can see our last problem that was fixed by a review from internal team. It seems that after almost one year we got this again...Can anybody help? @shue249 
<img width="1057" alt="Screenshot 2020-02-27 at 12 32 58" src="https://user-images.githubusercontent.com/52521975/75438138-2161a000-5960-11ea-8b84-d321bfad656a.png">

Everything went fine for our nymphaclothing.com online store, except yesterday when all of our products cannot be tagged anymore in Instagram, it seems that the feed is seen with 219 products but the product list wont show. The link nymphaclothing.com in instagram bio wont work, also messages in facebook says :
Your message couldn't be shared, because this link goes against our Community Standards.

We dont know what we did wrong, we filed numerous complains but nobody is giving any reasons or explanation, either on Instagram or Facebook. Our business is going down after years with investing and good collaboration. This is so frustrating, to know that any random report can cause this, if this is what happened.... Can you please help us or tell us any quick way to analyze our situation? Where should we address ? Thank you

**Comment by shue249** [comment]
Sorry to hear that, and thank you for the feedback. We are working on this now!

**Comment by shue249** [comment]
@nymphaclothing We went to your FB page & IG page, and this has been resolved. Are you still experiencing the problem on your side?

![image](https://user-images.githubusercontent.com/11957585/75504695-27b15400-5a14-11ea-80eb-8ee58399571e.png)

![image](https://user-images.githubusercontent.com/11957585/75504752-4ca5c700-5a14-11ea-8d7b-619096d3b9ed.png)

**Comment by nymphaclothing** [comment]
Hello, 

No, not anymore, the problem has been solved. 

Thank you very much again for the help. We are trying to figure out what is the problem that occasionally put us in this situation.

**Comment by shue249** [comment]
@nymphaclothing Let us continue to monitor the situation. Will close out this ticket.
