### ISSUE TITLE
Disable greeting opening by default

### ISSUE THREAD

**Issue by pipperis** [facebookincubator/Facebook-For-OpenCart#331]
Hi,

I am using the version 2.2.1 of the module and my website is [here](https://www.beautyangel.gr/).

I have a question. Is there a way so that the greeting message of Messenger will not open by default?
![Annotation 2020-03-18 193711](https://user-images.githubusercontent.com/58871352/76990243-52763480-6950-11ea-9ef6-13aa4259afb6.jpg)

Thanks

**Comment by shue249** [comment]
@pipperis Apologies for the late reply. We like to understand your expectations deeper. 

Can you share more what does the greeting message will not be open by default. What does success looks like for you, how will you like it to be?

**Comment by pipperis** [comment]
Hi,
I would like the Messenger icon to appear without the greeting openning by default. See attached image. When the user clicks on the Messenger icon the greeting will open.
![Annotation 2020-03-25 111333](https://user-images.githubusercontent.com/58871352/77520428-df0d7f00-6e89-11ea-8c7f-88440667a390.png)

**Comment by shue249** [comment]
@pipperis Wondering if you have access to developer resources to make changes to the plugin? There is a setting called "greeting_dialog_display" which you can set in the code such that the Messenger chat will not open the greeting message by default.

For more details on the setting, it is available here - https://developers.facebook.com/products/messenger/tutorials/messenger-customer-chat-plugin-tutorial/

![image](https://user-images.githubusercontent.com/11957585/77874149-b0731800-727e-11ea-90f4-70d875e9fd4d.png)

**Comment by pipperis** [comment]
@shue249 Yes, I have access to the developers resources and I know about the greeting_dialog_display='hide' parameter. 
Do I have to add the parameter in the code of your module?

**Comment by shue249** [comment]
@pipperis Thank you for circling back. We outlined the modifications which you need to make here - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/314#issuecomment-606980640

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions.
