### ISSUE TITLE
Cookie bar disable option missing

### ISSUE THREAD

**Issue by tappa31** [facebookincubator/Facebook-For-OpenCart#332]
Hi I installed the Facebook Business extension and tried all the ways suggested, but still the option to disable the extension does not appear. Is there any other way to disable the cookie bar?

**Comment by shue249** [comment]
@tappa31 Thank you for the feedback. Can you do a Empty cache and hard reload on your browser to see if the cookie bar option is displaying.

If the above method does not work, can you toggle the Developer console and then share a screenshot of any error messages which are showing up on the developer console.

**Comment by shue249** [comment]
@tappa31 We will be closing out this ticket. Feel free to reach to us if you have further questions.
