### ISSUE TITLE
facebook_enable_cookie_bar 

### ISSUE THREAD

**Issue by chauting** [facebookincubator/Facebook-For-OpenCart#334]
你好，我剛安裝OpenCart 3.0.3.2 但當我到訪我的剛站時，出現以下的間題:

**注意：第47行上/home/mccomhk/storage/modification/catalog/controller/common/footer.php中的未定義索引：facebook_enable_cookie_bar 注意：/ home / mccomhk / storage / modification / catalog / controller / common /中的未定義索引：facebook_enable_cookie_bar 第47行的header.php**

請問如何解決，謝謝各位幫忙

**Comment by shue249** [comment]
Thank you for the feedback.

1. Are you using the latest version of our plugin, 2.2.1? https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

2. As you are on OpenCart v3.x, there is an additional install step. You can refer to here for the installation step - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation

3. What is your website URL?

**Comment by chauting** [comment]
1. 不是
2. 當我進入後台後，出現以下情況:
![image](https://user-images.githubusercontent.com/62597431/77518098-1bf06a80-6eb8-11ea-8ae5-fc44edd054dd.png)

3.我的網站網址:  https://www.hkisayyes.com/reunion/upload/

**Comment by shue249** [comment]
@chauting It seems there there could be some files from the plugin which is not copied over correctly on your opencart webserver. Can you check if you have given recursive write+read access to admin, catalog and system folders on your opencart webserver. Then uninstall the plugin and reinstall the plugin again.

**Comment by chauting** [comment]
Thank you for your reply. I had reinstalled a new version OpenCart. v3.0.3.2.
, but when I  upload  facebook_ads_extension.ocmod.zip, I can not succeed.
How could I solve the problem?

[image: image.png]

shue249 <notifications@github.com> 於 2020年3月30日 週一 下午12:10寫道：

**Comment by shue249** [comment]
@chauting We are not able to see the image. Are you able to go to github and attach the image on the ticket? Unfortunately, replying via email will not attach the image on the github.

**Comment by chauting** [comment]
Thank you for your reply. I had reinstalled a new version OpenCart. v3.0.3.2. , but when I  upload  facebook_ads_extension.ocmod.zip, I can not succeed. How could I solve the problem?

![image](https://user-images.githubusercontent.com/62597431/78230856-86cb2280-7504-11ea-9a24-3f265f9d1d5a.png)

**Comment by shue249** [comment]
@chauting When you download the plugin zip package, was it it unzipped automatically and you have to re-zip up again? 

We have seen other users experiencing the same situation and the problem is on the re-zip part. In the zip package, there should not have any sub-folders. Presence of additional sub-folders will cause the plugin to fail. The zip package should immediately contain the upload folder.

To fix this problem, can you re-download the package and re-zip it up but without any sub-folder.

You can refer to point 3 on this FAQ - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#plugin-installation

**Comment by chauting** [comment]
Thanks for your reply. I had succeeded to install extension ".ocmod.zip". But I still have a problem that is my permission denied! How do I fix it?
![image](https://user-images.githubusercontent.com/62597431/78352326-bfd5c680-75da-11ea-9ec6-4f40c4c1c185.png)

**Comment by shue249** [comment]
@chauting You need to perform another step for OpenCart 3.x to ensure that the permission is given to administrator role. We have the installation guide and video on this page which you can use as reference - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation

**Comment by chauting** [comment]
![image](https://user-images.githubusercontent.com/62597431/78559714-74742000-7847-11ea-9c89-7b76d8e68f56.png)
how to fix it , thanks

**Comment by shue249** [comment]
@chauting To upgrade the extension, you will need to remove the current plugin from your OpenCart, before you can install the newer version. You can follow the removal steps on this documentation - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#upgrade-the-plugin-to-a-later-version

On this document, we have the complete steps on how to install, remove, upgrade the plugin.

**Comment by chauting** [comment]
![image](https://user-images.githubusercontent.com/62597431/79041067-73fcd000-7c1f-11ea-89b9-bc200216d7e1.png)
How to I install Facebook Pexi?

**Comment by shue249** [comment]
@chauting Like to check if you are still encountering any issues with the plugin? We tried to access your webstore URL and encounter HTTP error 500 - https://www.hkisayyes.com/reunion/upload/

**Comment by chauting** [comment]
I have reinstall opencart3.0 . That I have install Facebook adv extension. But I got permission denied . How to fix it?
![image](https://user-images.githubusercontent.com/62597431/79455779-fae6e980-801f-11ea-86ee-ea96b076e96e.png)
Url:   hkisayyes.com/online-shop/

**Comment by shue249** [comment]
@chauting Can you follow the install guide here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation. For Opencart 3.x, there is an additional step that you need to do to give your adminstrator role access to the extension.

**Comment by chauting** [comment]
Thank you so much. I had succeeded to get my permission. And then I had opened a Facebook business account (online shop). How do I do to make open cart connect to my Facebook business account?

![image](https://user-images.githubusercontent.com/62597431/79573839-cf343400-80f1-11ea-9e33-ac24615169a3.png)

![image](https://user-images.githubusercontent.com/62597431/79574217-67cab400-80f2-11ea-84f3-f3cd898c8595.png)

![image](https://user-images.githubusercontent.com/62597431/79575042-b62c8280-80f3-11ea-9462-3e1042dcc24f.png)

**Comment by chauting** [comment]
![image](https://user-images.githubusercontent.com/62597431/79575215-04da1c80-80f4-11ea-87db-c2c41069c461.png)

**Comment by dtying** [comment]
Hi @chauting , you may follow the [guide](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#setup-for-facebook-business-manager-page-pixel-catalog-and-page-shop) here to setup your FBE. 
Can you also provide me the ID of the Facebook Business Manager which you created before?

**Comment by dtying** [comment]
Hi @chauting , do you still have any issues with FBE setup?

**Comment by yao-tx** [comment]
Hi @chauting 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
