### ISSUE TITLE
Cannot verify the pixel

### ISSUE THREAD

**Issue by doviis** [facebookincubator/Facebook-For-OpenCart#335]
Hello,
I am using Opencart 3.02 and Journal 3 theme.
Extension verison is 2.1.10

I install the extention, set up everything, however I cannot verify the pixel in business.facebook.com website.
So I decided to put manual code in header (basically in Google analytics module, but looks that it works.)

So, I have added this code:
`
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '2540338916234677');
  fbq('track', 'PageView');
</script>
<script>
  fbq('track', 'Purchase', {
    currency: 'EUR',
  });
</script>
<script>
  fbq('track', 'AddToCart', {
    value: 0.01,
    currency: 'EUR',
  });
</script>
<script>
  fbq('track', 'ViewContent');
</script>
<script>
  fbq('track', 'Search', {
    content_type: 'product',
  });
</script>
<script>
  fbq('track', 'AddToWishlist', {
    content_type: 'product',
  });
</script>
<script>
  fbq('track', 'CompleteRegistration');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=2540338916234677&ev=PageView&noscript=1"
/></noscript>
`

However, as you can see, it's not very good and tracks no real behavior. I would like to ask how to set up extention correctly or how to change this code to track customers correctly.

website is kamehame[dot]lt

**Comment by shue249** [comment]
@doviis Thank you for the feedback.

We checked on your website and the pixel installation form our plugin is correct. Can you remove away the pixel code that you have added manually and we can double check again for you.

Also, you are right that the code you added does not track no real behaviour as you are sending all events to FB. It will be important for you to remove away these code as quickly as possible.

**Comment by shue249** [comment]
@doviis Can you also install our latest version of the plugin here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

**Comment by shue249** [comment]
@doviis We will be closing out this ticket. Feel free to reach to us if you have further questions.
