### ISSUE TITLE
checkout failure when have facebook extension installed

### ISSUE THREAD

**Issue by gip1986** [facebookincubator/Facebook-For-OpenCart#336]
when i have this extension installed i am getting this on checkout which is shame as i was hoping to use the extension and my products to show on facebook. if its not going to be possible i will have to remove.

Fatal error: 'Call to undefined method FacebookCommonUtils::updateProductAvailability()'
in /home/funphoto/GIP/storage/modification/catalog/controller/checkout/success.php:9
Stack trace:
#0 /home/funphoto/GIP/storage/modification/system/engine/action.php(79): ControllerCheckoutSuccess->index()
#1 catalog/controller/startup/router.php(25): Action->execute(Object(Registry))
#2 /home/funphoto/GIP/storage/modification/system/engine/action.php(79): ControllerStartupRouter->index()
#3 /home/funphoto/GIP/storage/modification/system/engine/router.php(71): Action->execute(Object(Registry))
#4 /home/funphoto/GIP/storage/modification/system/engine/router.php(60): Router->execute(Object(Action))
#5 system/framework.php(165): Router->dispatch(Object(Action), Object(Action))
#6 system/startup.php(104): require_once('/home/funphoto/...')
#7 index.php(25): start('catalog')
#8 {main}

**Comment by shue249** [comment]
@gip1986 Thank you for reaching out!

It could be a case whereby the latest files from the plugin are not properly copied over to your webserver. Can you check if you have given recursive read+write permission to the admin, catalog and system folders on your opencart webserver. Then, uninstall away the plugin and reinstall the plugin again.

**Comment by gip1986** [comment]
I have tried this im Happy to give u a login, it doesn’t install the web chat plug in or pics either, I’m on latest version of open cart. Is it a php issue?

Like I said I want to make this extension work

**Comment by shue249** [comment]
@gip1986 Can we also check if you have refresh the modifications after you installed the plugin - https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw

**Comment by gip1986** [comment]
Done all this I undiatslled and went to older version which works, but doesn’t show pixel or setup web chat feature which would like can I give login detials for admin for u to look at

**Comment by shue249** [comment]
@gip1986 Thank you for circling back. Unfortunately, we are unable to log into your server due to company policies and privacy concerns. 

Will you be willing to continue troubleshoot with us here. Can we use the latest version of the plugin as we recommend you to use version 2.2.1.

1. After using 2.2.1 and refreshing the modifications, do you still get the Fatal error where the undefined method FacebookCommonUtils::updateProductAvailability()?

2. After using 2.2.1, and refreshing the modifications, do you see the pixel and customer chat plugin?

What is your website URL?

**Comment by gip1986** [comment]
Yes if I use latest version it still happens 

And get message and on version I am using don’t get chat or pixel 

Matt

**Comment by shue249** [comment]
@gip1986 

1. Can you locate this file on your OpenCart webserver and share with us the file here - /home/funphoto/GIP/storage/modification/catalog/controller/checkout/success.php

2. Can you share your website URL link

**Comment by gip1986** [comment]
Going to do do this now before sleeping so hopefully don’t have to miss u as guessing time difference and apreicate ur help and hopefilly will get resolved

**Comment by gip1986** [comment]
https://we.tl/t-KTQrQjGo6h Is link to we transfer for success file. Did u see in previous email I am using version before latest due to error

**Comment by gip1986** [comment]
My website is www.getitpersonalized.co.uk

**Comment by shue249** [comment]
@gip1986 Thank you for the quick response!

1. The file you shared is really helpful. With the latest version of the plugin, 2.2.1, this file should not exist at all. 2 action items you can take
    a. Delete or rename the file, /home/funphoto/GIP/storage/modification/catalog/controller/checkout/success.php, on your webserver. This will stop the error message on the checkout page
    b. Check if you have given recursive read+write permission on the /home/funphoto/GIP/storage/modification folder

To give more context, the files in this modification folders contain changes which the plugin done to core OpenCart files. We had this file changed in earlier versions but no longer required in the latest version. As such, it is expected for OpenCart to remove away this file when you click on the "Refresh modifications" button. The only case I can think of when this fails is that the folder does not have write permissions, hence OpenCart was not able to delete the file away.

2. Pixel setup is correct on your website, as we can find the pixels fired from our side. When you do your own testing, did you disable the ad blocker?
![image](https://user-images.githubusercontent.com/11957585/78198788-552e6900-74bc-11ea-9089-83f6172ec1b1.png)

**Comment by gip1986** [comment]
Checkout works but I can’t see pics on pages and the web chat doesn’t work or not setup I still get this message 

Can u help me 

Ur such great help can I ask do u also know how to remove gift vouchers on checkout option

**Comment by shue249** [comment]
@gip1986 
I see that you are using our latest version 3.0.0.0. We are working on enabling Messenger chat on this version, we will let you know when it is ready. cc @dtying

In addition, you mentioned that you have a problem with pics on pages. Can you explain more on this.

**Comment by gip1986** [comment]
I don’t see this pixel thing

**Comment by shue249** [comment]
@gip1986 To see the pixel status on your website, you can use the pixel helper tool. It is a Chrome extension that you can install here - https://chrome.google.com/webstore/detail/facebook-pixel-helper/fdgfkebogiimcoedlicjlajpkdmockpc?hl=en

**Comment by gip1986** [comment]
And whatsbenwfit of pixel what does it do,

Also u know how to remove gift voucher completely as option

**Comment by shue249** [comment]
@gip1986 For the usage and benefits of pixels, you can refer to our help center here - https://www.facebook.com/business/help/742478679120153?id=1205376682832142. Accurate implementation of pixel helps you achieved best ads performance on Facebook.

For the question on gift voucher, we are not in the best position to answer that as we did not implement this module, so we do not have the knowledge on this. Perhaps you can seek out the developers of OpenCart to understand more on disabling gift voucher.

**Comment by shue249** [comment]
Will be closing out this ticket, feel free to reach to us if you have further questions.
