### ISSUE TITLE
Warning: There is a problem with your Facebook Ads Extension installation. Please go to Facebook Ads Extension to view more details. - OC Version 3.0.3.2

### ISSUE THREAD

**Issue by head-dunce** [facebookincubator/Facebook-For-OpenCart#339]
Installed the extension. Gave user permissions in OC. Have folder permissions set to 777 as per install instructions.

My OpenCart admin homepage now says -
"Warning: There is a problem with your Facebook Ads Extension installation. Please go to Facebook Ads Extension to view more details."

And when I go to Extensions > Extensions > Modules > Facebook Ads Extension
Then click Edit I get -
"The page you are looking for could not be found! Please contact your administrator if the problem persists." 

I do see the file at -
/var/www/html/admin/controller/extension/module/facebookadsextension_installer.php
I have tried to chmod 777 that file, no change.

Website is https://www.carguygarage.com

**Comment by shue249** [comment]
@head-dunce 

1. Is the plugin still installed on your website, or have you removed the plugin?

2. Can you remove away the plugin and re-install the latest version of the plugin - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

3. Is this the install instructions that you used earlier?
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation

4. Are you able to access the plugin module screen on your computer?
![image](https://user-images.githubusercontent.com/11957585/77975913-0783f600-732e-11ea-9d72-76f3b9fc4aa5.png)

**Comment by head-dunce** [comment]
I removed and re-installed and now get different errors -
```
We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps
```

I see a bigger problem though, it seems you want to leave the theme cache and sas cache off forever? That is not going to work, I get too much traffic to do that.

Also I use Journal 3 for the theme framework, which is the most popular extension for Open Cart. So I will have to change the header differently. (Not a big deal, just FYI.)

**Comment by head-dunce** [comment]
Eh, not sure if I need this extension anymore anyway. I just coded in the required json and added in the pixel to the header. Looks like now I have to wait a bit before I can connect the rest.

**Comment by shue249** [comment]
@head-dunce Thank you for the feedback. 

Our plugin was designed for users who lack developer resources, hence we wanted it to be as simple as possible. The decision to disable theme and SAS cache was to overcome the need for our plugin to insert the javascript codes to the website twig files.

It seems that you have ability to make code changes directly. Here will be our suggestions:
1. Keep the plugin installed - there are some backend codes which ensure that the right events are fired from the right pages as well as the generation of the product catalog file

2. Insert these codes to the header.twig file
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L453-L582
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L594-L629

Let us know if you have further questions.

**Comment by head-dunce** [comment]
Well, looks like you have a problem with cropping images. Like this item -
https://www.facebook.com/commerce/products/2771778576240162/
I've adjusted the settings, but they haven't helped. Maybe they take time to update?

**Comment by head-dunce** [comment]
Seems to be an issue with titles and escaping double quotes, like here -
https://www.facebook.com/commerce/products/2849009838546545/
Not sure where the issue is though, we have both the Open Graph and the ld+json data defined. The descriptions are fine, but if they are pulled from the json they are escaped as \" instead. Do you know which data format gets priority? Looks like we are currently defining both titles by escaping double quotes with &quot;

**Comment by shue249** [comment]
@head-dunce 

Seems that you are using the pixel-based catalog approach to update the catalog details. When we check your product page, seems that you are using the web encoding to escape the title and special characters encoding to escape the description. You can consider changing the title encoding to the same as description.

![image](https://user-images.githubusercontent.com/11957585/78196899-6d02ee80-74b6-11ea-8dc8-ff59c19c687f.png)

In addition, for dynamic ads to work properly, you will need to implement the down funnel events correctly. Eg on the product details page, you will need to send in the ViewContent event.

This file contains the logic where we fire out the events and parameters across the various pages on the OpenCart website - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php

**Comment by head-dunce** [comment]
Your "Facebook Pixel Helper" is actually incorrect. If you view the source of the page you'll see the OG description is using web encoding too
![Capture](https://user-images.githubusercontent.com/58668957/78262483-a0517780-74ce-11ea-9c8f-c658bc567ddb.JPG)
But the JSON is not and using a slash to escape the double quote
![Capture2](https://user-images.githubusercontent.com/58668957/78262728-fde5c400-74ce-11ea-92ab-79e6ae2e43ec.JPG)

This is my confusion, maybe I should just remove the OG information?

**Comment by head-dunce** [comment]
Ok, I changed the JSON to slash escape the name and it seems FB is picking it up correctly now. Odd because Google did not have a problem with the HTML encoded slashes. 
![Capture3](https://user-images.githubusercontent.com/58668957/78267683-3c7e7d00-74d5-11ea-802c-975a373b919e.JPG)
It seems FB ignores the OG if the JSON is defined.

**Comment by shue249** [comment]
@head-dunce It is great to hear that and seems that you have resolved the problem on your side.

We will be closing out this ticket, feel free to reach to us if you have further questions.
