### ISSUE TITLE
Products not syncing  version 2.1.0.2.2 OPENCART.PRO 

### ISSUE THREAD

**Issue by subpro2** [facebookincubator/Facebook-For-OpenCart#34]
Hi, 
I installed and synced, but after that my website got a new products and i cant find them on my Facebook shop! Why? As described here https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336&filter_search=facebook%20ads%20&filter_license=0
 : Any changes made on my OpenCart website are automatically synced with your Facebook shop.

**Comment by shue249** [comment]
@subpro2 Thank you for your feedback.

1. Are the products synced to the Facebook catalog?

2. How are you adding in new products? Are you using the default opencart product management module?

3. What is your website URL?

**Comment by subpro2** [comment]
Hi,
1. Yes, I think it is true (if i want see a new product from my website a should resynced my products http://prntscr.com/kqxljq  BUT, after that the prices do not change) price from Facebook catalog http://prntscr.com/kqxrln and from my website http://prntscr.com/kqxsdd https://dhmd.ru/307_plate_maxim They are different!!! I resynced my products more than 10 times
2. I synced opencart with 1C and add a new product direct to the site's database 
3. https://dhmd.ru/

**Comment by shue249** [comment]
@subpro2 
Thank you for your feedback. We are syncing the product updates from the default OpenCart product management module. We believe that the problem lies in that 1C is a different product management module and our plugin is not integrated to 1C. 

Can you share the URL for the 1C plugin for us to take a closer look?

**Comment by subpro2** [comment]
Hi
And that about syncing product price?

**Comment by subpro2** [comment]
I shared with you the URL for the 1C plugi? please look it closer https://ocmod.net/modul-opencart-exchange-1c-v8x

**Comment by shue249** [comment]
@subpro2 We have released a new version of the plugin - 2.1.10. We greatly improved the performance of the Resync products feature in Facebook Business Extension module. You can use this function to re-sync your products from Opencart to facebook catalog. The catalog will remain the same. You can use this feature to sync the products over to Facebook whenever you use 1C to perform any product changes.

We will be closing out the ticket, feel free to reach to us if you have any further questions.
