### ISSUE TITLE
google_product_category invalid 

### ISSUE THREAD

**Issue by andrelacomski** [facebookincubator/Facebook-For-OpenCart#340]
Hello,
when importing products to facebook, the diagnosis warns that google_product_category is invalid and needs to be able to work on facebook, but I can't do that

**Comment by shue249** [comment]
@andrelacomski Thank you for the feedback.

The requirement for google_product_category is a warning and not a fatal error. You can safely ignore this warning message as it has no impact on your signals, catalog and dynamic ads.
![image](https://user-images.githubusercontent.com/11957585/78542279-8777f780-7829-11ea-8ab4-f46dfa785bab.png)

We will be closing out this ticket, feel free to reach to us if you have further questions.
