### ISSUE TITLE
Issue with access for Facebook Extension Installation

### ISSUE THREAD

**Issue by alecsa09** [facebookincubator/Facebook-For-OpenCart#341]
This is the error I'm getting:
We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders.
/home/...[client name]../public_html/admin//view/image

**Comment by shue249** [comment]
@alecsa09 As the message mentioned, you need to provide read & write permission to the admin/view/image folder on your opencart webserver. We need this folder permission to read images for the Facebook catalog.

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions
