### ISSUE TITLE
Facebook Ads Extension Not Working with opencart 2.2.0.0 ???

### ISSUE THREAD

**Issue by moseur** [facebookincubator/Facebook-For-OpenCart#342]
Hello Concern,

I have tried to connect with facebook by installing facebook ads extensions. But when I clicked Facebook icon on opencart admin panel then its shwoing Page not found???

my opencart version is 2.2.0.0 and I have also checked folder ( read / write ) permission. My Folder permission is 755. 

Please help me out..

![fbe](https://user-images.githubusercontent.com/32351568/78668172-076e9200-78fc-11ea-8cdf-b3472079f007.png)
![fbe1](https://user-images.githubusercontent.com/32351568/78668189-0ccbdc80-78fc-11ea-9649-fffe30b1addd.png)
![fbe2](https://user-images.githubusercontent.com/32351568/78668191-0dfd0980-78fc-11ea-9dbc-f169f1e8d0db.png)

**Comment by shue249** [comment]
@moseur Thank you for the feedback. It seems that there is a server error when you are accessing the plugin module. Are you able to check on your webserver error logs and share the latest error messages with us for us to identify the problem.

**Comment by moseur** [comment]
Dear Concern ,

I am really happy to see your message within short time. May God bless you always. Please find the error message to the image. Hope it can help you. 

Thanks


![image](https://user-images.githubusercontent.com/32351568/78898996-90b9cc00-7a96-11ea-9abe-328329b97023.png)

**Comment by shue249** [comment]
@moseur Unfortunately, we were not able to find anything from your error log.

Also, we noticed that you are still using an older version of the plugin. Could you try to remove the current version and install the version 2.2.1 - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

**Comment by moseur** [comment]
I have installed this version but same result. what can i do, please help me. Also I have another shop which opencart version is latest one with latest facebook ads extension. But here I am facing another problem. after configuring everything after last window Its giving me en error like :"An error occured when creating Facebook Business Extension setup."  When I go to the ads extension log file then I found this error 

2020-04-18 13:47:30 - Generating product feed file for batch 0
2020-04-18 13:47:30 - Feed Generation Time Estimate: 30
2020-04-18 13:47:30 - gen feed file
2020-04-18 13:47:30 - file file is not stale, skip generation
2020-04-18 13:47:30 - feed generation finished, time used: 0 seconds
2020-04-18 13:48:03 - gen feed file
2020-04-18 13:48:03 - file file is not stale, skip generation
2020-04-18 13:48:03 - feed generation finished, time used: 0 seconds
2020-04-18 13:52:00 - Facebook Ads Extension version = 3.0.0
2020-04-18 13:52:00 - OpenCart version = 3.0.3.2
2020-04-18 13:52:00 - PHP version = 7.3.16
2020-04-18 13:52:00 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-04-18 13:52:00 - Pixel ID = false
2020-04-18 13:52:00 - Pixel use PII = false
2020-04-18 13:52:00 - Page ID = false
2020-04-18 13:52:00 - System User Access Token = false
2020-04-18 13:52:00 - Messenger plugin = false

What should I do???

**Comment by shue249** [comment]
@moseur Can I understand that you have 2 shops and both shops have problems with the plugin.

1. What are the plugin versions used for both shops? We have another new version 3.0.0. Can you check if the plugin used is 3.0.0? https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.0.0

2. What is the error you are facing now with both shops? Can you show us a screenshot of the errors

**Comment by moseur** [comment]
![image](https://user-images.githubusercontent.com/32351568/79743325-39351f00-8326-11ea-8380-7dda6b2dc8ef.png)
![image](https://user-images.githubusercontent.com/32351568/79743352-4520e100-8326-11ea-8631-f1ff3ae10a71.png)
![image](https://user-images.githubusercontent.com/32351568/79743384-510ca300-8326-11ea-87b7-4f5fa9d55aa6.png)


Please find the attachment for your kind reference. I am using latest version of facebook ads extension that is 3.0.0 

If anything , please let me know. I need to fix it . thanks for your reply.

**Comment by shue249** [comment]
@moseur Thank you for the screenshots and feedback. 

1. Want to understand if you have installed any ad blocker on your chrome. If so, can you disable the ad blocker and try to launch the plugin again.

2. If point 1 does not work, can you toggle the Chrome developer console and then refresh the webpage. We like to check if there are any error messages on the console.

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions
