### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by TitoEx** [facebookincubator/Facebook-For-OpenCart#344]
Hello ,
I Have Problem after installed plugin and configuration in product page on click add to cart get the following error 
![1](https://user-images.githubusercontent.com/63331409/78743205-41708000-795e-11ea-951d-8dfd9f627d49.PNG)
![2](https://user-images.githubusercontent.com/63331409/78743206-42a1ad00-795e-11ea-8f79-efbb8715f144.PNG)

Using OpenCart 2.0.3.2

**Comment by shue249** [comment]
@TitoEx Thank you for the feedback.

1. What is your webstore URL?
2. What is the plugin version which you are using?
3. Have you followed the installation steps here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md

**Comment by shue249** [comment]
We will be closing this ticket, feel free to reach to us if you have further questions.
