### ISSUE TITLE
 There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup. Please contact Facebook via our Github if this error keeps showing.

### ISSUE THREAD

**Issue by maria037** [facebookincubator/Facebook-For-OpenCart#346]
Добрый день!
Подскажите, пожалуйста, при установлении добавления на сайт (пикселя ФБ) возникла вот такая проблема.
"There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing."
Служба поддержки ФБ говорит, что это не в их компетенции.
Помогите, пожалуйста, справиться с проблемой.

**Comment by shue249** [comment]
@maria037 Thank you for the feedback.

1. Can you download the latest version of the plugin from the OpenCart marketplace - https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336

2. Remove the existing plugin on your Opencart and install the new version.

3. Follow the upgrade instructions

Let us know if you encounter any further errors on the installation

**Comment by maria037** [comment]
Огромное спасибо за помощь! Вроде бы все получилось!)

**Comment by shue249** [comment]
@maria037 We are glad it is working for you now. We will be closing out this ticket. Feel free to reach to us if you have further questions.
