### ISSUE TITLE
microdata required fields are missing, id & availability

### ISSUE THREAD

**Issue by tomasumumu** [facebookincubator/Facebook-For-OpenCart#347]
Could You please help me with microdata, microdata check tool shows that required product fields are missing:
**id** and **availability**.

How I can fix it without adding required fields manually?

OC 3.0.3.2
Fastor theme
FB extension ver. 3.0.0

Thank You in advance

**Comment by shue249** [comment]
@tomasumumu If you are using our plugin, it is not needed to implement the microdata and you can ignore the warning/error message from the microdata check tool.

The reason is because that we are using a regular scheduled feed file to update the catalog details.

**Comment by tomasumumu** [comment]
Thank you!
