### ISSUE TITLE
installed but interface is different to the video

### ISSUE THREAD

**Issue by calvintcow** [facebookincubator/Facebook-For-OpenCart#349]
Hello,

I have just installed the extension and set up.  however there are some questions here

1) the main page is different after I set up, it doesn't show re-sync the product
2) when click manage settings, it goes to Facebook manage page instead of of the screen that I see from the screen shot or video.
3) so I cannot enable the Facebook chat. 

please advise. 
![Screenshot 2020-04-13 at 2 21 41 PM](https://user-images.githubusercontent.com/63576993/79097370-340a2a00-7d92-11ea-8dd7-3765c36e32c7.png)
![Screenshot 2020-04-13 at 2 21 59 PM](https://user-images.githubusercontent.com/63576993/79097377-38cede00-7d92-11ea-8744-e0d7499a04c1.png)

**Comment by dtying** [comment]
Hi @calvintcow , thanks for your feedback.

We're currently working on the installation guide to update it to the latest version.

If you need to use Messenger chat plugin feature urgently, kindly download the[ v2.2.1 ](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1)as an alternative.

**Comment by calvintcow** [comment]
It is not urgent for me to use the messenger.

But when I click on manage setting, it goes to Facebook business page, is it normal? as I don't see the other menu that your video show.

**Comment by dtying** [comment]
Hi @calvintcow , when clicking on manage setting button, a popup should open for you to see modules of features available, e.g. enable page shop. And you can also view your page, pixel, catalog info.

**Comment by dtying** [comment]
Hi @calvintcow , I've updated FAQ and Install_guide to reflect the latest change. Feel free to take a look.
