### ISSUE TITLE
The message received is not from the verified source.

### ISSUE THREAD

**Issue by siteadvice** [facebookincubator/Facebook-For-OpenCart#350]
Hi there
After installing v 3.0.0 of your extension on Opencart v3.0.3.2 I get this error when going to the extension front page:
The message received is not from the verified source.
After apparently completing the integration setup with Facebook and being returned to the extension front page i get this error:
An error occured when creating Facebook Business Extension setup.
Hope you can help!
I have tried uninstalling and reinstalling without any luck.

**Comment by dtying** [comment]
Hi @siteadvice , can you provide me with your webstore url?

**Comment by siteadvice** [comment]
Sure - it is https://shop.bigapplehotdogs.com/

**Comment by dtying** [comment]
Hi @siteadvice , I can see there're two different users setup before.
- Is the error you mentioned above for the 1st user only?
- After the 2nd user setup, is everything working?

**Comment by siteadvice** [comment]
No, it is not working. In fact, as I said, I have disabled it for now.
When I first tried logging in, I realised the owner of the page had not yet added me to his Facebook Business account. I tried again after he had added me and that’s when I got the error “An error occured when creating Facebook Business Extension setup”. Perhaps these two login attempts explain why you see two users from your end?
However, the first error - “The message received is not from the verified source” - was appearing from the very beginning. I ignored it because it was possible to proceed.

**Comment by dtying** [comment]
Thank you @siteadvice.  In your case, because you were added as an admin of the page just before the installation, the backend rejected it as a security precaution to prevent bad actor. 
Can you wait for one week and re-try it? Meanwhile, our team is thinking of better ways to handle this scenario.

**Comment by siteadvice** [comment]
At the moment I cannot r-try it because when I click on the "Get Started" button I get the error "An error occured when creating Facebook Business Extension setup".
Can you advise me on what to do about that? Perhaps you could give me a guide to manually deleting all files and database entries?

**Comment by dtying** [comment]
Here's uninstall guide: https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin

After click 'Get Started' button, in the popup, can you click 'Edit Settings' button? Also wait for one week first before you re-try.

**Comment by siteadvice** [comment]
Will it be exactly one week after the first attempt?
Would it be possible for the owner of the Facebook Business account to log on instead? (I mean sooner than seven days)
He has had a Facebook Page for several years but I think he did not set up the Facebook Business account until this week.

**Comment by dtying** [comment]
Yes, the owner can definitely try. If I'm not wrong, from the log I can see the owner has already setup successfully.

**Comment by siteadvice** [comment]
If he set it up successfully, why would it prompt me to log in and connect the extension to his account?

**Comment by dtying** [comment]
1. Could you share me your log file by clicking 'Download log' link?
If you have access to db, in 'settings' table, check the value of 'facebook_fbe_v2_installed'.
2. You may ask the owner to re-install, and here's the expected screen if success. https://drive.google.com/open?id=1mJu7poPn2rBtnkg2UgfSYi2cGdFDztMp
3. If still not working, you may install v2.2.1 as an alternative.

**Comment by siteadvice** [comment]
1. Not sure where to find the "Download log" link - can you explain?
2. I have these rows in the oc_setting table which match the key "%facebook%":
1687 | 0 | facebook | facebook_last_upgrade_check_time | 2020-04-13 | 0
-- | -- | -- | -- | -- | --
  | Edit | Copy | Delete | 1790 | 0 | facebook | facebook_feed_runtime_avg | 0.2669677734375 | 0
I cannot see 'facebook_fbe_v2_installed'

**Comment by dtying** [comment]
It's not correctly setup. Let me follow up internally and get back to you later.

**Comment by dtying** [comment]
Hi @siteadvice , we have recently fixed an API issue with FBE, this error should not happen now. 
Feel free to open a new ticket if you have further questions.

**Comment by bonny3** [comment]
Hi @dtying ,

I installed the new version 3.0.0 of Facebook Opencart,
but unfortunately I keep getting the error message ...

**_"The message received is not from the verified source."_**

before installing the new version, I removed the previous version 2.10.
I ask how can I solve the problem

Thanks
Best Regards
Alessandro

![2020-05-12_213849](https://user-images.githubusercontent.com/19350758/81738178-95a8db80-9499-11ea-90b7-7e925c39068c.png)
