### ISSUE TITLE
Object Object Error Version 3.0.0

### ISSUE THREAD

**Issue by ltona** [facebookincubator/Facebook-For-OpenCart#351]
Hi,

I get this error object Object when I try to setup the latest version of the Plugin 3.0.0. I have been able to setup the plugin the the oldest Plugins, but the latest one shows this error and I the setup is not finished. What could be the problem?

Check website: coopmarket.al

Thanks.

![error01](https://user-images.githubusercontent.com/63632235/79191914-f9eb6780-7e27-11ea-8b9e-a0d5d9a34757.png)

**Comment by dtying** [comment]
Hi @ltona , can you share your webstore url? Unfortunately the error means there're backend issues to onboard you to our latest version of FBE.

**Comment by ltona** [comment]
Hi @dtying ... yes, https://coopmarket.al.

**Comment by dtying** [comment]
hmm I can see a connection time out error from your webpage, and I can't find any log given your url above.

**Comment by ltona** [comment]
I get this from Log

2020-04-14 8:25:22 - OpenCart version = 3.0.3.2
2020-04-14 8:25:22 - PHP version = 7.2.29
2020-04-14 8:25:22 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-04-14 8:25:22 - Pixel ID = true
2020-04-14 8:25:22 - Pixel use PII = true
2020-04-14 8:25:22 - Page ID = true
2020-04-14 8:25:22 - System User Access Token = false
2020-04-14 8:25:22 - Messenger plugin = false

(p.s. rembemer that with the older versions, I've been able to synchronize products)

**Comment by magbor** [comment]
The same problem with https://magbor.com
Please check....
2020-04-14 12:45:25 - Facebook Ads Extension version = 3.0.0
2020-04-14 12:45:25 - OpenCart version = 2.3.0.2
2020-04-14 12:45:25 - PHP version = 7.1.33
2020-04-14 12:45:25 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-04-14 12:45:25 - Pixel ID = true
2020-04-14 12:45:25 - Pixel use PII = true
2020-04-14 12:45:25 - Page ID = true
2020-04-14 12:45:25 - System User Access Token = false
2020-04-14 12:45:25 - Messenger plugin = false

**Comment by dtying** [comment]
Thank you @ltona @magbor . I think both of you may face the same issue. 
Let me follow up internally first.

**Comment by dtying** [comment]
Hi @ltona @magbor, just to double check when did you see the error. Did you click 'Get Started' button, see the screen as below, finished the setup flow before you see the error?
![Screen Shot 2020-04-16 at 4 10 37 PM](https://user-images.githubusercontent.com/21333308/79431431-083eac80-7ffd-11ea-9c12-eb9c8ebc1184.png)

**Comment by ltona** [comment]
Hi, @dtying . I click Get Started, the new windows opens and says: You've previously linked OpenCart to Facebook. Would you like to continue with your previous settings? I continue with my name. At this moment the windows closes and I get the above-mentioned error.

**Comment by magbor** [comment]
Hi @dtying. The error comes after the click:
path 1) Get Started - Continue as xxxxx = ERROR
path 2) Get Started - Edit settings - Continue - Done - (You've now linked OpenCart to Facebook) - OK = ERROR

**Comment by bonyod** [comment]
Hi, my site https://www.grobmart.com face the same issue... I already click get started, finished the installation, then I click uninstall because I want to change account, but right now when I click get started and click "Continue as (my name)" it just show alert [object Object]

**Comment by danilomacedo10** [comment]
My website has the same error: www.lefotick.com.br
I uninstalled the plugin and reinstalled and now the configuration screen no longer appears after clicking on "Get started". It is a white screen.

![tela-branca-fb](https://user-images.githubusercontent.com/63831088/79618705-309fd700-80e1-11ea-8a62-0807bb6d2c3b.png)

![object-erro-fb](https://user-images.githubusercontent.com/63831088/79618704-30074080-80e1-11ea-97b9-937fecece53a.png)

There is also an error at checkout:

![erro-mobile-FB](https://user-images.githubusercontent.com/63831088/79618703-2f6eaa00-80e1-11ea-821b-3ae7d5cd18ed.jpg)



these are the last lines of the error log. I'm just a site administrator, so I don't have the technical knowledge to fix it myself.

2020-04-17 22:03:27 - Complete - Get Sample product feed
2020-04-17 22:03:52 - Get Sample product feed
2020-04-17 22:03:53 - Complete - Get Sample product feed
2020-04-17 22:05:35 - Get Sample product feed
2020-04-17 22:05:35 - Complete - Get Sample product feed
2020-04-17 22:07:49 - Facebook Ads Extension version = 3.0.0
2020-04-17 22:07:49 - OpenCart version = 2.3.0.2
2020-04-17 22:07:49 - PHP version = 7.2.29
2020-04-17 22:07:49 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-04-17 22:07:49 - Pixel ID = false
2020-04-17 22:07:49 - Pixel use PII = false
2020-04-17 22:07:49 - Page ID = false
2020-04-17 22:07:49 - System User Access Token = false
2020-04-17 22:07:49 - Messenger plugin = false

**Comment by decorello** [comment]
I have the same problem with the object Object + Problems with GDPR...

**Comment by dtying** [comment]
Hi @ltona @magbor, thanks for your waiting. 
There's issue with our backend in the last week and that's why I can't find your installation log from my end. It should have been fixed now, you may re-try and let me know if it's still not working.

**Comment by dtying** [comment]
Hi @danilomacedo10 , this issue should have been fixed now.

**Comment by dtying** [comment]
Hi @decorello , can you show me a screenshot of how your error is triggered?

**Comment by magbor** [comment]
Hi @dtying , nothing changed, the same problem! www.magbor.com
In my case, despite the error, Facebook is showing the new products I created in OC.
2020-04-21 10:26:36 - Get Sample product feed
2020-04-21 10:26:36 - Complete - Get Sample product feed
2020-04-21 10:27:16 - Facebook Ads Extension version = 3.0.0
2020-04-21 10:27:16 - OpenCart version = 2.3.0.2
2020-04-21 10:27:16 - PHP version = 7.1.33
2020-04-21 10:27:16 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-04-21 10:27:16 - Pixel ID = true
2020-04-21 10:27:16 - Pixel use PII = true
2020-04-21 10:27:16 - Page ID = true
2020-04-21 10:27:16 - System User Access Token = false
2020-04-21 10:27:16 - Messenger plugin = false

**Comment by blakerr** [comment]
I got exactly same problem on OC 2.3 with new version of extension, please tell us how to solve the problem ?

**Comment by missbow** [comment]
Same Issue on Version 2.3.0.2 
![image](https://user-images.githubusercontent.com/34458043/79873222-83360780-83ef-11ea-950b-e7af16966484.png)

**Comment by dtying** [comment]
Hi @blakerr , @missbow can you provide me with your webstore url?

**Comment by dtying** [comment]
Hi @magbor , I think your catalog sync can work is because your previous setup with FBE is still working.
In this case, it'd be easier for you to downgrade to the previous version first, so that you can keep your operation continuing.

**Comment by missbow** [comment]
> Hi @blakerr , @missbow can you provide me with your webstore url?

https://e-trenaki.gr/

**Comment by valiobar** [comment]
Hi @dtying same issue https://nexo.bg/

**Comment by dtying** [comment]
Hi @valiobar , may I know when is your last time setup FBE and encountered issue? This is because we recently had an issue with FBE so that all user were impacted. The issue was already fixed, can you try to setup again and let me know if it still doesn't work?

**Comment by valiobar** [comment]
@dtying I just uninstall the modification and install it again and it still dosesn't work

**Comment by missbow** [comment]
Hello @dtying is there any new on this?
It's a little bit critical at the time being :)
Thank you in advance.

**Comment by dtying** [comment]
Hi @missbow , if it's urgent, please download our previous version as an alternative. https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

**Comment by dtying** [comment]
Hi @valiobar , did you try click 'Edit Settings' button after FB login popup is opened? This will bring you through setup again.

**Comment by valiobar** [comment]
@dtying yes I did, couple of times still no success. Is this previous version compatible with oc 3.0.3.2

**Comment by dtying** [comment]
@valiobar Yes the previous version is also compatible with oc 3.0.3.2.

**Comment by missbow** [comment]
@dtying  I'm switching back to the previous version as a workaround. 
Let me know if you have any update on this.
Regards

**Comment by dtying** [comment]
Hi everyone, we have recently fixed an API issue of FBE plugin v3.0.0, the [object Object] error should be gone for now.

**Comment by missbow** [comment]
Hi @dtying I've installed the new version again but the I'm facing the same error
![image](https://user-images.githubusercontent.com/34458043/81398109-44af8500-9131-11ea-972b-13b15ff92ad5.png)
