### ISSUE TITLE
Cannot see my page

### ISSUE THREAD

**Issue by cepcemuh** [facebookincubator/Facebook-For-OpenCart#353]
Hello, I cannot see the facebook page I'd like to connect due the integration process. Everything was good before the update but now when I try to connect the page I'd like to use - I am not able to do.

**Comment by dtying** [comment]
Hi @cepcemuh , could you share your webstore url?

**Comment by cepcemuh** [comment]
Hey @dtying , thanks for your response. My website URL is https://www.instrumentami.com/
At the moment I just uninstalled new version and install Plugin Version: 2.2.1. It work and due the installation process my FB page appeared but with the latest version it does not appear. Thanks.

**Comment by dtying** [comment]
Thanks @cepcemuh , I also checked that with v2.2.1, your setup is correct now.
The reason that you can't see the page could be due to missing of permissions.

**Comment by cepcemuh** [comment]
Yeah, I guess but I don't know how to change the permissions. I tried in page settings but nothing...

**Comment by dtying** [comment]
Thank you for the info! Let me follow up internally first and come back to you later.

**Comment by dtying** [comment]
Hi @cepcemuh , we have recently updated the FBE UI to show the disabled pages in grey color, and when you hover on it, it also tells the reason why you can't select that page. I hope this can help you to solve the page access issue.

**Comment by cepcemuh** [comment]
Hey @dtying sorry for late response. I just checked, it shows the pages now but cannot fix the reason - You don't have permissions... I do not know why is that... I have full access to the pages and all permissions as an administrator...
