### ISSUE TITLE
Facebook Ads Extension Error update token

### ISSUE THREAD

**Issue by johnnyipp** [facebookincubator/Facebook-For-OpenCart#354]
I installed Facebook Ads Extension 2.1.3
in Opencart 3.0.3.2
It looks like it installed everything and is working correctly only issue is 
The following red error messages I am getting in the Opencart Dashboard.

There is not a update token button under advanced options...

What do I need to do to update the token and remove the error messages

![FB1](https://user-images.githubusercontent.com/63671760/79264855-d988d080-7e5a-11ea-99b3-ad892dd4635d.PNG)
![FB2](https://user-images.githubusercontent.com/63671760/79264865-dbeb2a80-7e5a-11ea-95bd-eb2fe3ae7676.PNG)
![FB 3](https://user-images.githubusercontent.com/63671760/79264974-02a96100-7e5b-11ea-9c62-b1bcc570c866.PNG)

**Comment by dtying** [comment]
Hi @johnnyipp, we're slowly deprecating this version now. Feel free to download [v2.2.1](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1) or [v3.0.0](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.0.0) as a better choice.

**Comment by dtying** [comment]
Hi @johnnyipp, I'll close out this ticket for now. Let me know if you have any further questions.
