### ISSUE TITLE
I can't see pages that own to other Business Manager and i have full access

### ISSUE THREAD

**Issue by xakou** [facebookincubator/Facebook-For-OpenCart#355]
Hello, i can't see pages that own to other Business Manager and i have full access.
I can see only pages marked as "Individual people own this" .

Any help?

**Comment by dtying** [comment]
Hi @xakou, can you elaborate more on your use case? It's probably because you don't have the permissions to modify the page which is owned by the other Business Manager.

**Comment by xakou** [comment]
@dtying at previous version 2.2.1 i can see all pages. 
Also i have full access at the other Business Manager.

**Comment by dtying** [comment]
Thanks for the info! Let me follow up internally first and come back to you later.

**Comment by elavweb** [comment]
Hello,
we have the same issue with Facebook Business Extension v 3.0.0 on opencart v 3.0.3.2 and journal theme v3.0.46
We don't see the page when we have to select one.
We have all permissions for that page.
Why?
thanks

**Comment by dtying** [comment]
Hi @elavweb , could you follow FAQ and verify first?

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#setup-for-facebook-business-manager-page-pixel-catalog-and-page-shop

**Comment by xakou** [comment]
Any good news??? 
At previous version 2.2.1 i can see all pages.
At this version 3.0.0, i see only new of them...

**Comment by dtying** [comment]
Hi @xakou, we have recently updated the FBE UI to show the disabled pages in grey color, and when you hover on it, it also tells the reason why you can't select that page. I hope this can help you to solve the page access issue.

**Comment by xakou** [comment]
@dtying  Hello again,
i have hover on page i have the error "You don't have permission to edit these settings. Reach out to the admin of xxxx Business Manager to to gain access."

As i see at **mine** Business Manager, i have all the permitions. 
What is my wrong? With FBE 2.2.1 everyting work OK.

![img_460](https://user-images.githubusercontent.com/49698771/81529252-259a3880-9367-11ea-9251-95de8b106547.jpg)

**Comment by xakou** [comment]
@dtying  any news? Did you see my previous post 8 days before ?

**Comment by dtying** [comment]
Hi @xakou , sorry that I missed your latest msg.
In order for us to troubleshoot, could you provide us your webstore url, business_manager_id, and page_id which you want to connect to FBE?

**Comment by xakou** [comment]
@dtying can i send you to a private message?

**Comment by dtying** [comment]
@xakou , sure you can send to this email address -ads_extension_opencart@fb.com

**Comment by xakou** [comment]
Thank you, please also re-open this ticket. It isn't Closed

**Comment by xakou** [comment]
@dtying do you have any news? The problem exists at version 3.1
