### ISSUE TITLE
Product categories in facebook page shop section is not showing

### ISSUE THREAD

**Issue by ramirami593** [facebookincubator/Facebook-For-OpenCart#356]
Hi,
Product categories in facebook shop section is now showing - only "all products" is showing with no categories.

Website
www.ikiaz.com

Facebook page
https://www.facebook.com/KIAZmore/?ref=bookmarks 

Opencart V. 3.0.2.0 and the latest extension.

Please advise,
Thank you.

**Comment by cheekymykool** [comment]
Hi Im having the same issue i have it all set up but nothing shows in my shop of facebook

**Comment by shue249** [comment]
@ramirami593 We are unable to access your page. Is the page public and still available?

**Comment by shue249** [comment]
@cheekymykool Want to check if you have deleted your Facebook business extension settings? We did not see the Shop tab on your Facebook page

**Comment by cheekymykool** [comment]
sorry https://www.facebook.com/MajicPersonalisation/?view_public_for=659546914254182

**Comment by cheekymykool** [comment]
i have set it up but it isnt sending it to my facebook page

**Comment by ramirami593** [comment]
> @ramirami593 We are unable to access your page. Is the page public and still available?

i think you get confused with the other user data please read my message again the first message.

my page and my website is available please let me know if you cant see it

**Comment by shue249** [comment]
@ramirami593 We are getting this when we tried to access your Facebook page.
![image](https://user-images.githubusercontent.com/11957585/79521862-ca896480-808c-11ea-948e-03736424af96.png)

On the topic of categories on Page shop, we are not creating the categories, hence only All products is available.

**Comment by cheekymykool** [comment]
im getting same but not sure what is going on that is why i sent message

**Comment by dtying** [comment]
Hi @ramirami593 , I've checked that:
- your FBE setup is correct
- ensure your page shop plugin is enabled as below:
1. click 'Manage Setting'
![Screen Shot 2020-04-15 at 11 26 04 AM](https://user-images.githubusercontent.com/21333308/79529493-60c68600-809f-11ea-91f5-9014fc2b80a1.png)
2. click 'View'
![Screen Shot 2020-04-15 at 1 46 43 PM](https://user-images.githubusercontent.com/21333308/79529427-370d5f00-809f-11ea-8c5d-e349cc9851b1.png)
3. Click 'Add Plugin'
![Screen Shot 2020-04-15 at 11 35 30 AM](https://user-images.githubusercontent.com/21333308/79529450-47253e80-809f-11ea-8926-5b47b8d1e5c7.png)

**Comment by dtying** [comment]
Hi @cheekymykool , I think you're on older version of FBE before v3.0.0, and the problem is that your catalog is not connected with your page shop.

If so, you need to:
1. remove existing settings: https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#delete-the-existing-settings-for-facebook-for-opencart
2. setup FBE settings again with page shop toggle enabled: https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#setup-for-facebook-pixel-catalog-and-page-shop

**Comment by cheekymykool** [comment]
Hi Im running the latest version i have tryed uninstalling and reinstalling it is not getting anywhere

**Comment by ramirami593** [comment]
> hence

**Comment by ramirami593** [comment]
> @ramirami593 We are getting this when we tried to access your Facebook page.
> ![image](https://user-images.githubusercontent.com/11957585/79521962-03c1d480-808d-11ea-9219-c6ef5a1c52fb.png)
> 

> **### > On the topic of categories on Page shop, we are not creating the categories, hence only All products is available.**

@shue249  shue249  - Why no categories will show in facebook shop ? i mean i have categories in my website and it should show products within their normal categories , can we solve this ? 

Thank you

**Comment by dtying** [comment]
Hi @cheekymykool , can you follow the guides here?
1.[ Setup for Facebook business manager, page, pixel and catalog](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#setup-for-facebook-business-manager-page-pixel-and-catalog)
2. [Launch Management View](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#launch-management-view)
3. [Setup for Facebook Page Shop](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#setup-for-facebook-page-shop)

**Comment by cheekymykool** [comment]
all im getting is 
![image](https://user-images.githubusercontent.com/63763201/79554603-e0b91400-80d0-11ea-874a-43e6cd93c59e.png)
if needed i can supply a login to our site if you have a secure email i can send detail too

**Comment by dtying** [comment]
Hi @cheekymykool , this error screen looks like is from the previous FBE version. Can you double check which plugin version are you on? Below shows how to check your plugin version.
![Screen Shot 2020-04-21 at 11 18 33 AM](https://user-images.githubusercontent.com/21333308/79828814-1a8d6180-83d4-11ea-8833-cbbcf987e68c.png)

**Comment by cheekymykool** [comment]
As per photo v3 I have downloaded this from your site

 

Warmest Regards

 

Mike Carter

Majic Personalisation

08 6363 5163

0491057248

2322 Albany Hwy

Gosnells WA 6110

 <http://www.majicpersonalisation.com.au/> www.majicpersonalisation.com.au

**Comment by cheekymykool** [comment]
the version i have is v 3 downloaded from this site to make sure

Regards

**Comment by dtying** [comment]
Hi @ramirami593 , category is not available in FBE at this moment, I'll take this as a feedback to the team.
Hi @cheekymykool , I've checked that your FBE setup is done correctly and the catalog is synced to your FB Shop now.

I'll close out the ticket. Feel free to open new tickets for further questions.
