### ISSUE TITLE
Error on facebook business extension 3.0.0 = [object Object].

### ISSUE THREAD

**Issue by igorechaves** [facebookincubator/Facebook-For-OpenCart#358]
hello guys, i have some problems to install the extension, could you help me please?

This firts image show the version of my extension: 3.0.0
![image](https://user-images.githubusercontent.com/63788082/79449521-c0e2fc80-7fb9-11ea-86fd-3eb2993241d8.png)

when i click on get start i inform my facebook login and show this msg [object Object].
![image](https://user-images.githubusercontent.com/63788082/79449767-32bb4600-7fba-11ea-923e-6e171fecc910.png)

i already refesh the modifications
deleted the old files from my db.
clear and disable the cache.
No have modification on my header and footer.

without fix that on i can not able to sincronize my pixel. he never verify and do not activate my comunication.
![image](https://user-images.githubusercontent.com/63788082/79450039-acebca80-7fba-11ea-9ff5-81cec97a05d1.png)

Hope some help to solve this issue to use more ads.  Thanks a lot.

**Comment by igorechaves** [comment]
follow the log:

MOD: Facebook Business Extension
CODE: public function index(
LINE: 22

FILE: admin/controller/common/dashboard.php
CODE: public function index(
LINE: 45

FILE: catalog/controller/common/header.php
CODE: public function index(
LINE: 31
CODE: public function index(
LINE: 33

FILE: catalog/view/theme/default/template/common/header.twig
CODE: </head>
LINE: 170
CODE: </header>
LINE: 249
CODE: {{ footer }}
LINE: 603

FILE: admin/view/template/common/dashboard.twig
CODE: <div class="container-fluid">{% if error_install %}
LINE: 32

FILE: admin/language/en-gb/common/dashboard.php
CODE: <?php
LINE: 8

FILE: admin/language/pt-br/common/dashboard.php
CODE: <?php
LINE: 8

FILE: system/engine/router.php
CODE: public function __construct($registry
LINE: 37
CODE: while ($action instanceof Action) {
LINE: 76
CODE: public function dispatch(Action $action, Action $error) {
LINE: 60
CODE: while ($action) {
NOT FOUND - OPERATIONS ABORTED!
CODE: public function dispatch($action, $error) {
NOT FOUND - OPERATIONS ABORTED!
CODE: $result = $this->execute($pre_action);
LINE: 74

FILE: catalog/language/en-gb/common/header.php
CODE: <?php
LINE: 6

FILE: catalog/language/pt-br/common/header.php
CODE: <?php
LINE: 6

FILE: catalog/controller/common/footer.php
CODE: public function index(
LINE: 31
CODE: public function index(
LINE: 33

FILE: catalog/view/theme/default/template/common/footer.twig
CODE: </footer>
LINE: 216
CODE: </footer>
LINE: 227

**Comment by igorechaves** [comment]
User group access was checked all too!

**Comment by dtying** [comment]
Hi @igorechaves , could you provide me with your webstore url?

**Comment by igorechaves** [comment]
momentodivertido.com

**Comment by igorechaves** [comment]
i update my store and refresh some tables nome on my database and are working fine the integration
