### ISSUE TITLE
Special Price not showing on Facebook Catalog

### ISSUE THREAD

**Issue by rhinsu** [facebookincubator/Facebook-For-OpenCart#359]
I have installed Facebook for Opencart v3.0 on open cart 3.0.3.2 with Journal 3 theme. All installation works well but special price does not display on Facebook Shop. When I downgrade Facebook for Opencart to V2 it works well and special prices sync very well. Please see the example of what I refer to.

https://i.postimg.cc/BZySdkSW-/fbdetails.jpg
https://i.postimg.cc/9fpXKfM1/sitedetail.jpg

www.devikenya.com

**Comment by shue249** [comment]
@rhinsu Can you try to install the latest version of the plugin and do a resync for us to check on the issue.

**Comment by rhinsu** [comment]
We have already tried resync earlier but the special price does not display, interestingly any new products created get updated but not the special price

**Comment by shue249** [comment]
@rhinsu Can you share with us 2 examples of such products (where the sale price is not reflected) on your website so that we can help to check. Information that will be useful for us:
1. webstore URL of the product
2. What is the sale price and normal price

We want to verify that the sale price is shown on your website and then match it against the facebook product catalog sale price.

**Comment by rhinsu** [comment]
@shue249 i have installed again the new version and the issue still remains the same, check new screenshots below

https://i.postimg.cc/v8SZxPGh/fbsnip.jpg
https://i.postimg.cc/X7RNQpGy/feedsnip.jpg
https://i.postimg.cc/L8j972LQ/ocsnip.jpg

the images attached
1. Snip from Catalog Manager from Facebook
2. Snip from Special Price tab from Opencart
3. Snip from csv extract from /index.php?route=extension/facebookfeed/genfeed

**Comment by rhinsu** [comment]
> @shue249 i have installed again the new version and the issue still remains the same, check new screenshots below
> 
> https://i.postimg.cc/v8SZxPGh/fbsnip.jpg
> https://i.postimg.cc/X7RNQpGy/feedsnip.jpg
> https://i.postimg.cc/L8j972LQ/ocsnip.jpg
> 
> the images attached
> 
> 1. Snip from Catalog Manager from Facebook
> 2. Snip from Special Price tab from Opencart
> 3. Snip from csv extract from /index.php?route=extension/facebookfeed/genfeed

forgot the item link on example, but the whole site does not sync special price.
https://www.devikenya.com/y9s-6gb-ram-128gb-rom-6-59-4g-lte-black

**Comment by shue249** [comment]
@rhinsu Want to check with you if the Facebook Business Extension setup is completed or have you deleted away the setup.

**Comment by rhinsu** [comment]
@shue249 i still have the setup installed, haven't removed it yet

**Comment by shue249** [comment]
@rhinsu Wondering if you could share the catalog ID with us.

**Comment by rhinsu** [comment]
@shue249 
1066643733705749 Catalog ID

**Comment by shue249** [comment]
@rhinsu 

Using the previous product as an example, we checked on your catalog and found that the sales price is correctly synced in.

https://www.devikenya.com/y9s-6gb-ram-128gb-rom-6-59-4g-lte-black

![image](https://user-images.githubusercontent.com/11957585/80450733-c692f780-8954-11ea-98d4-d218943f95cb.png)

Like to better understand your problem better. Are you not able to see this sale price on your side? If so, where is the place you are not seeing the sale price? Can you share screenshots so that we can better understand.

**Comment by rhinsu** [comment]
@shue249 voila!!! if you check the below link screenshot you can clearly see that special price was not captured...
in my opinion, I think I may have been impatient to before it could complete sync

https://i.postimg.cc/v8SZxPGh/fbsnip.jpg

Anyway, I'm happy to see it work...thanks alot

Is there a way I can add the manufacturer name before the product name on sync..

**Comment by shue249** [comment]
@rhinsu Glad to know that the sale price is alright on your catalog.

For the changes to the manufacturer name, if you have access to developer resources, I can point you to the code pointers. However, do note that any local changes made will be overwritten when you install a new version of the plugin or re-install the existing version of the plugin.

This is the code location where we extract out the product listing from the underlying database. You need to ensure that the manufacturer name is inside the array returned back - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/model/extension/facebookproduct.php#L15

This is the code location where we put in the product name from the OpenCart product to FB product. If the manufacturer information is extracted from the database, you will be able to access it here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L115

We will be closing out this ticket. Feel free to reach to us if you have further questions.

**Comment by rhinsu** [comment]
@shue249 it is very kind of you to show me the files to edit, but since i am a novice developer i wouldn't know the exact edit, if you don't mind would you be able to show me the edit,
Example
Opencart name in product - Galaxy A51
Manufacturer - Samsung

current facebook catalog is showing - Galaxy A51
need it to show - Samsung Galaxy A51

really appreciate your assistance.
