### ISSUE TITLE
Facebook ads Extension Edit Error 

### ISSUE THREAD

**Issue by mashum** [facebookincubator/Facebook-For-OpenCart#36]
Hello!
I have problem when i am going to edit the facebook_ads_extension under the module it give me the error page not found path(extension/module/facebookadsextension_installer&user_token=4rf7et7r0NuqX1dsfh1Hn8reE5ijTjXQ) Where really the index function can not exist how i can enable or disable the extension. I am using latest version.
Best Regd: Mashum
Thanks!

**Comment by mashum** [comment]
[facebookadsextension_installer.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2383068/facebookadsextension_installer.zip)
this is the file where request is going

**Comment by mashum** [comment]
### _****_

**Comment by shue249** [comment]
@mashum 
Thanks for the feedback! Can I understand the reason for you to disable the extension? We will like to take in the feedback to better improve our plugin.

To setup the extension, pls follow these videos - 
1. Step by step video guide for installing the Facebook Ads Extension https://drive.google.com/open?id=1V4Nu8nlmHX5ppKqsjcR-xR05Rozb7MKN

2. Additional installation step required for OpenCart v3.x https://drive.google.com/open?id=1-ljN_pNcyZBbN2LoXtxwaJEy0dfnxAum

3. Step by step video guide for setting up the Facebook Ads Extension https://drive.google.com/open?id=1JPXQ0mS1pGk2Bat9RV02vYNdbRfCLP9r

4. Step by step video guide for setting up permissions for Facebook Ads Extension https://drive.google.com/open?id=1JUwZPlUNIhFO7I8U0slbJSQNjyu4al_J

To uninstall the plugin, you can follow these steps.
![image](https://user-images.githubusercontent.com/11957585/45583029-04ace600-b8ed-11e8-8ba2-c83ce18b4178.png)
