### ISSUE TITLE
I cannot find the chat bubble on facebook extension.

### ISSUE THREAD

**Issue by baud13** [facebookincubator/Facebook-For-OpenCart#360]
hi, i had the extension up an running well downloaded form fb. Since a new update arrived i updated it but it seems there is a difference between the extension from opencart market place and fb. 
the previous had a different environment and i could enable and edit the chat bubble. this one does not but i still get the bubble on my website. so how to i edit the bubble and turn it on and off?

now i have facebook business extension installed version 3.0.0 in oc 3.0.2.3
when i click on manage settings it looks like the picture here 
https://ibb.co/tZsWV7M

 where is the bubble settings? 
 before it didn't look like this.

i uninstalled this and installed the one from facebook agan then the bubble settings are there but if i turn it on it does not appear on my website. 
Website is flowerstore.gr

with this setup i get the bubble but cannot edit it... :(

**Comment by shue249** [comment]
@baud13 We are working on enabling the Messenger chat features on the version 3.0.0 of our plugin. We will update you soonest when it is ready.

Can you explain more on what is the problem that you are facing now and is not able to solve.

**Comment by baud13** [comment]
Thank you for your reply, thats great!
Right now i just have the extension from git with an enabled chat bubble that i cannot change the text or disable. Its like the extension from git and the one from facebook merged somehow. 
Can i somehow manage the chat bubble text? Already i tried to uninstall and install the old extension but its not responding when i turn the chat on and off..

**Comment by shue249** [comment]
@baud13 Unfortunately, we are unable to provide further insights on the 3rd party Messenger chat, as we do not own this 3rd party plugin.

We can update you soonest when our Messenger chat plugin is ready for v3 and you can use our plugin to customise the chat welcome text.

**Comment by baud13** [comment]
Excellent, thank you very much for your reply.
