### ISSUE TITLE
Messenger Plugin Not Showing

### ISSUE THREAD

**Issue by honeynatividad** [facebookincubator/Facebook-For-OpenCart#362]
I have not changed the header.twig in the Theme Editor.

I was able to install and add the products on my Facebook page but not the messenger. Any help is appreciated. Thank you!

**Comment by shue249** [comment]
@honeynatividad Thank you for the feedback. Can you share with us your website URL?

Also have you followed the installation steps here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation. Pls ensure that you have followed the step to "Refresh modifications"

**Comment by SilverDario** [comment]
Messenger plugin not showing after update. Products are OK. OC version 3,0,2,0, Journal 3 theme,  Any help is appreciated. Thank you!

**Comment by shue249** [comment]
@SilverDario What is the plugin version that you are using? If you are using version 3.0.0, we are now working to enable Messenger chat plugin. If you are using older versions of v2.x, can you share with us your web store URL.

**Comment by shue249** [comment]
We will close off this ticket. Feel free to reach to us if you have further questions.
