### ISSUE TITLE
Can't load facebook ligin page in pop up window

### ISSUE THREAD

**Issue by alexeypp** [facebookincubator/Facebook-For-OpenCart#363]
Using the Facebook extension in the Opencart the browser can't load the login page. When I close the window, the browser says: User cancelled login or did not fully authorize.
![New Bitmap Image (2)](https://user-images.githubusercontent.com/63948651/79682957-3d324580-822f-11ea-8b4a-7bca4f70a667.png)
![Untitled](https://user-images.githubusercontent.com/63948651/79682963-428f9000-822f-11ea-92c6-d85598ebc3e7.png)
![New Bitmap Image](https://user-images.githubusercontent.com/63948651/79682964-46bbad80-822f-11ea-9765-4d782e53fbd3.png)

**Comment by nasrulizwan** [comment]
same problem,

**Comment by tuncaytunckol** [comment]
same problem,

**Comment by alexeypp** [comment]
Also, if I clear the cache of the browser or opened it in incognito mode, the page load the first step. The authorization window, then I add my username and password. And the next window is the same... same window with the same error message.

**Comment by and33sand** [comment]
Same problem...

**Comment by dtying** [comment]
Thank you all for the feedback! Sorry for the inconvenience.
Let me check with the team internally first.

**Comment by dtying** [comment]
Meanwhile, you may use the previous version as an alternative: https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

**Comment by and33sand** [comment]
> Same problem...
With 2.2.1 working perfect! Thanks!

**Comment by dtying** [comment]
This issue should have already been fixed now. Let me know if you still can't see the login screen.
