### ISSUE TITLE
Error Opencart 2.3

### ISSUE THREAD

**Issue by llll7uoh** [facebookincubator/Facebook-For-OpenCart#364]
When I first start the module, I get an error.
Tell me how to solve?
http://prntscr.com/s27ace

**Comment by shue249** [comment]
@llll7uoh Thank you for the feedback. Can you download the latest version of the plugin - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.0.0, remove the existing plugin and install the latest version. Then follow the on screen steps to upgrade your settings.

**Comment by Stiliyana1** [comment]
I have the same problem and after the installation of facebook_ads_extension.ocmod.zip, and follow the step "Get started".....I have the error [object Object]. What to do to solve the problem?

**Comment by dtying** [comment]
Hi @Stiliyana1, could you provide your webstore url?

You may also refer to FAQ for updates: https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#setup-for-facebook-business-manager-page-pixel-catalog-and-page-shop

**Comment by Stiliyana1** [comment]
Hi, I now installed the Fb AD Extension, given from fb, and I success to follow the steps "Get started..", but now I have an error with and products still uploading! - www.destibg.com

![1111](https://user-images.githubusercontent.com/64435880/80449203-270b4000-8927-11ea-838c-f64f09f93544.JPG)
![222222](https://user-images.githubusercontent.com/64435880/80449210-283c6d00-8927-11ea-9154-9f44fa5c14aa.JPG)
![3333](https://user-images.githubusercontent.com/64435880/80449211-283c6d00-8927-11ea-812c-3cdc60f3d717.JPG)

**Comment by Stiliyana1** [comment]
You can see that should click on UPDATE TOKEN, but I can't
![444444444](https://user-images.githubusercontent.com/64435880/80450039-4e630c80-8929-11ea-80e6-ce1cd71c9dac.JPG)
Txs

**Comment by Stiliyana1** [comment]
Hi, I now installed the Fb AD Extension, given from fb, and I success to follow the steps "Get started..", but now I have an error with and products still uploading! - www.destibg.com
![gfgdg](https://user-images.githubusercontent.com/64435880/80587601-82b8f480-8a1f-11ea-9fd7-d549c3b73153.JPG)
![ggfgfgfgf](https://user-images.githubusercontent.com/64435880/80587604-83518b00-8a1f-11ea-955c-341bb8674117.JPG)

**Comment by yao-tx** [comment]
Hi @Stiliyana1 @llll7uoh 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
