### ISSUE TITLE
Plugin Version: 3.0.0 - no action (OC v3.0.3.1)

### ISSUE THREAD

**Issue by nunaoppa** [facebookincubator/Facebook-For-OpenCart#365]
![image](https://user-images.githubusercontent.com/56949405/79715176-8b197d00-8305-11ea-84bc-9ff217ce1217.png)

I downloaded 3.0.0 ver, and installed it

There's no response when I Click <Get Stared> 

![image](https://user-images.githubusercontent.com/56949405/79715247-cf0c8200-8305-11ea-8085-668b4a859a45.png)

**Comment by dtying** [comment]
Thank you for the feedback! 
We're currently aware of the issue and working on the fix.

**Comment by nunaoppa** [comment]
Please reply when the problem is solved.
Can I download the previous version?

**Comment by nunaoppa** [comment]
> Thank you for the feedback!
> We're currently aware of the issue and working on the fix.

Please reply when the problem is solved.
Can I download the previous version?

**Comment by dtying** [comment]
Yup, pls use the previous version as an alternative.

**Comment by nunaoppa** [comment]
> Yup, pls use the previous version as an alternative.

Where can I download it?

**Comment by dtying** [comment]
Here you go: https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

**Comment by dtying** [comment]
This issue should have already been fixed now. Let me know if you still can't see the login screen.
