### ISSUE TITLE
FacebookAdsExtension is not defined

### ISSUE THREAD

**Issue by AlexGolemis** [facebookincubator/Facebook-For-OpenCart#368]
I installed the extension, but it loads infinitely and throws a console error &quot;Uncaught ReferenceError: _facebookAdsExtension is not defined&quot; .

**Comment by AlexGolemis** [comment]
I have already Downloaded the latest version of your Extension from here:
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.0.0
![facebook extension error](https://user-images.githubusercontent.com/64062947/79854947-ef564280-83d2-11ea-9aa5-813959418322.png)

**Comment by shue249** [comment]
@AlexGolemis Can you perform a clear cache and hard reload on your browser to see if the error message is resolved.

**Comment by AlexGolemis** [comment]
I cleared all the storage and cache of the page, ctrl +F5, logged in again and have the same error. Which is the official ocmod for the 3.0.3.2 OC version (in order to check if my installation package is correct)?

**Comment by shue249** [comment]
@AlexGolemis Can you check this post and see if it works for you. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/374#issuecomment-618174399

**Comment by AlexGolemis** [comment]
The issue you mention does not help. The error i get is different. I checked the files you say the should exist in system/library directory and they exist. 
System, catalog and admin directory have all 755 permissions

**Comment by shue249** [comment]
@AlexGolemis We may need further information to debug this more. Can we ask for you to download the page as a standalone html and send the page to us at our email - ads_extension_opencart@fb.com

**Comment by dtying** [comment]
Hi @AlexGolemis , did you click Modifications->Refresh?
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation

Your admin site is not loading the latest bundle of plugin. That's why you see the js error as above.

**Comment by AlexGolemis** [comment]
I have done Refresh, clear cache etc...Finally i uninstalled the extension and start again.
The latest version is this:
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.0.0

Correct?

**Comment by dtying** [comment]
Yes this is the latest version.

**Comment by AlexGolemis** [comment]
i uninstalled and installed again the latest version from the url posted here and now it works. After choosing the account i cant choose page. It says _You don't have permission to edit these settings. Reach out to the admin of ''P&B' Business Manager to to gain access._

I am admin at the account
![2020-04-29 17_54_08-Σύνδεση μέσω Facebook](https://user-images.githubusercontent.com/64062947/80611091-d4bf4180-8a42-11ea-9212-57bf6ee4db5b.png)

![2020-04-29 17_55_57-Ρυθμίσεις επιχείρησης](https://user-images.githubusercontent.com/64062947/80611123-e0126d00-8a42-11ea-848d-0eebf1cc4c74.png)

How do i change these permissions?

**Comment by dtying** [comment]
Hi @AlexGolemis , glad it works now!

Regarding to the permission, can you refer to FAQ [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#setup-for-facebook-business-manager-page-pixel-catalog-and-page-shop) - _2. I can't see my page_ , and then let me know the result?

**Comment by AlexGolemis** [comment]
I didn't find any solution at FAQ. I also tried to communicate with Facebook support. They informed me that i have all the admin permissions.

**Comment by AlexGolemis** [comment]
The problem solved after communicating with Facebook Support. There was an old Facebook business account that created the conflict.

**Comment by xakou** [comment]
@AlexGolemis  goodmoring Alex (καλημέρα, έχω το ίδιο πρόβλημα... τι είπες στο support και τι σου έκαναν;) , i have the same problem  "you don't have permission to edit these settings. Reach out to the admin of xxxxx Business Manager to gain access"

**Comment by AlexGolemis** [comment]
Δε γνωρίζω τον ακριβή διάλογο γιατί επικοινώνησε το τμημα marketing. Το πρόβλημα ήταν ότι υπήρχε παλιός λογαριασμός και δημιουργούταν conflict.

I don't know the exact dialogue because the marketing department contacted me. The problem was that there was an old account and there was a conflict.

**Comment by xakou** [comment]
@AlexGolemis επαφή (email?) από το τμήμα marking? 

Contact from the marketing team ?

**Comment by dev-mamun** [comment]
TypeError: body is null
mdb.js:15384:9
Query param variable dev_host_prefix not found index.html:264:17
Query param variable system_user_name not found index.html:264:17
Query param variable business_vertical not found index.html:264:17
Query param variable merchant_settings_id not found index.html:264:17
Query param variable fbe_v2_installed not found index.html:264:17
Loading failed for the <script> with source “https://connect.facebook.net/en_US/sdk.js”. index.html:1:1
ReferenceError: FB is not defined
