### ISSUE TITLE
Error with Facebook Ads Extension Set-Up

### ISSUE THREAD

**Issue by marcusanson** [facebookincubator/Facebook-For-OpenCart#37]
Hi there,

I've tried to install your mod to OpenCart to have it up and running, but when I install it, I get a message that says:  You have yet to setup Facebook Ads Extension. Please click on Facebook Ads Extension and Get Started.

The problem is, when I click on it, there is no Get Started option. There's only a blue swirly circle that never seems to finish loading. Any ideas or help would be greatly appreciated. Thanks! The log file is attached. 

[Until There's A Cure_2018-09-18_23-25-57_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2394834/Until.There.s.A.Cure_2018-09-18_23-25-57_facebook_ads_extension.log)

**Comment by marcusanson** [comment]
Hi there. My apologies for the severe delay, family issues arose and I’ve been out of town. The image I get when I load into the Dashboard looks like this: 
![28ce046c-8129-47e9-9760-4b272798dfe3](https://user-images.githubusercontent.com/18747686/45979041-abd30100-c002-11e8-81a2-e9bdc827f124.png)

Then when I go and click on the Facebook Ads Extension, instead of the “Get Started” button, I get this: 
![63fae52a-95c2-4caa-ba49-916299fa72c5](https://user-images.githubusercontent.com/18747686/45979071-bc837700-c002-11e8-85f6-a5c65b0dc660.png)

And as far as I’ve seen, no matter how long I stay on that page or reload it, the blue circle never seems to actually load. Any help you could give would be much appreciated.

**Comment by shue249** [comment]
@marcusanson Thanks for your feedback and hope everything's well for you and your family.

I believe there is an error on the browser side. Do you think you can access your admin panel using Chrome and launch developer tools and access Facebook Ads Extension and provide us the error message shown?

![image](https://user-images.githubusercontent.com/11957585/45990477-0f1c6c00-c0b3-11e8-870b-bbfb743559e9.png)

**Comment by marcusanson** [comment]
Hi there,

I pulled up the page with Chrome using the Developer Tools, and it gave me the following error codes:

index.php?route=extension/facebookadsextension&token=300fc27f22b42230833f2d3d9b0c2f6a&user_token=300fc27f22b42230833f2d3d9b0c2f6a:32 Uncaught SyntaxError: Unexpected identifier
dia.js:272 Uncaught TypeError: Cannot read property 'diaSettingId' of undefined
    at Object.refreshUIForDiaSettings (dia.js:272)
    at HTMLDocument.<anonymous> (index.php?route=extension/facebookadsextension&token=300fc27f22b42230833f2d3d9b0c2f6a&user_token=300fc27f22b42230833f2d3d9b0c2f6a:644)
    at j (jquery-2.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.1.min.js:2)
    at Function.ready (jquery-2.1.1.min.js:2)
    at HTMLDocument.I (jquery-2.1.1.min.js:2)

Let me know if this helps or if you need anything else. Thanks.

**Comment by shue249** [comment]
@marcusanson As there was sensitive data in your comment, I removed it away and repost a new one without the data.

Hi there,

I pulled up the page with Chrome using the Developer Tools, and it gave me the following error codes:

index.php?route=extension/facebookadsextension&token=&user_token=:32 Uncaught SyntaxError: Unexpected identifier
dia.js:272 Uncaught TypeError: Cannot read property 'diaSettingId' of undefined
at Object.refreshUIForDiaSettings (dia.js:272)
at HTMLDocument. (index.php?route=extension/facebookadsextension&token=&user_token=:644)
at j (jquery-2.1.1.min.js:2)
at Object.fireWith [as resolveWith] (jquery-2.1.1.min.js:2)
at Function.ready (jquery-2.1.1.min.js:2)
at HTMLDocument.I (jquery-2.1.1.min.js:2)

Let me know if this helps or if you need anything else. Thanks.

**Comment by shue249** [comment]
@marcusanson The feedback is really helpful. Pls give us some time to look into this to find the root cause.

**Comment by chichebiev** [comment]
I have the same problem.
The error comes when an update to the last version. 
I see the button Manage Settings. But is not active.
Is it have a decision?

**Comment by shue249** [comment]
@chichebiev Your problem seems like it is different. Can you create a new ticket and we follow up from there?

**Comment by shue249** [comment]
@chichebiev Thank you for opening the OpenCart ticket. The fault is on me for not being clear, as I will like you to create a new github issue instead. I have opened up a new one for you. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/43

Can you share a screenshot of your screen on the new ticket?

**Comment by chichebiev** [comment]
![image](https://user-images.githubusercontent.com/12606396/46456501-c69e3600-c7b7-11e8-8ab2-4019d1fa05d7.png)

**Comment by chichebiev** [comment]
Yes, that is right, this is an error from chrome browser. I try with Mozilla and everything works.
I had to check before sending a ticket.
Sorry, stupid mistake.

**Comment by shue249** [comment]
@chichebiev Thank you for your valuable feedback. Do you still happen to have the error from Chrome? We will like to check in more details on what is the error and how can we further improve on our plugin.

**Comment by shue249** [comment]
@marcusanson Our sincere apologies for the late reply, as we were previously working on some other fixes. We will like to circle back to your problem. We think we may have some idea on what is the problem.

Can we ask for this information from you.

![image](https://user-images.githubusercontent.com/11957585/49056735-e7bf5800-f237-11e8-9e52-960b9bb0f541.png)
![image](https://user-images.githubusercontent.com/11957585/49056792-1b01e700-f238-11e8-8772-bc1b75b69e3a.png)

**Comment by impresya** [comment]
Hi, I would like to report the same bug as the author of this issue. I get a notification on my dashboard that "You have yet to setup Facebook Ads Extension. Please click on Facebook Ads Extension and Get Started." However when I do click on the Facebook Ads Extension, instead of the “Get Started” button I get a spinning wheel.
I followed all additional instructions, eg. refreshed modifications, added permissions to users, ensured the folders are writable etc. I am using Opencart 3.0.2.0. This happens immediately after install. Any suggestions please?
![image](https://user-images.githubusercontent.com/29625622/49116933-fee16280-f296-11e8-892e-ec4e972e2e54.png)

**Comment by impresya** [comment]
@shue249 I am encouraged by your comment that you may have some idea on what is causing the problem. As this is exactly the same issue as @marcusanson was experiencing a few months back I hope my screenshot below will help you verify your idea
![image](https://user-images.githubusercontent.com/29625622/49117408-7794ee80-f298-11e8-9ee9-409a30f54978.png)
Looking forward to your reply

**Comment by shue249** [comment]
@impresya Thank you for your feedback! Yes, your screenshot is very helpful as it confirmed our bug. The problem is on line 35, where presence of special characters in the store name caused the formatting to break. In your case, it is the presence of the single quote (Impresya's store). We are working on this fix now and will update you soonest once we release the plugin.

**Comment by impresya** [comment]
That's great, many thanks for that! Looking forward to trying the new release

**Comment by impresya** [comment]
@shue249 I can confirm, the use of special character causes the bug to appear. After removing it from the store's name it works like a charm, this workaround allows me to carry on with my project. Many thanks!

**Comment by shue249** [comment]
@marcusanson , @impresya  We have released a new version 2.1.3 to address the special characters issue on your store name. You can either download from OpenCart or from here https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3.

We will close out the ticket, but feel free to let us know if there's further questions.

@impresya We will continue the conversation on the multi-store feature on the separate ticket thread.
