### ISSUE TITLE
Force fetch Product to Sync

### ISSUE THREAD

**Issue by bonyod** [facebookincubator/Facebook-For-OpenCart#370]
Hi, in previous version before ver. 3 I can find "Fetch Now" button to sync.
In version 3 I can't find it, how to re-sync my product immediately? Or sync from beginning

**Comment by dtying** [comment]
Hi @bonyod , here's the workaround:
1. Launch management view, and open Catalog tab
2. Click the button, it should link to Catalog Manager
3. In Catalog Manager -> Product Data Sources, click Edit button
![Screen Shot 2020-04-22 at 4 11 41 PM](https://user-images.githubusercontent.com/21333308/79958012-040b0700-84b5-11ea-86b3-6ecc9f8a5954.png)
4. In the URL field, change the endpoint from 'genFeed' to 'genFeedNow', and Save it
![Screen Shot 2020-04-22 at 4 12 57 PM](https://user-images.githubusercontent.com/21333308/79958005-01101680-84b5-11ea-9394-ca93afcf5654.png)
5. Click Request Update Now button whenever you need to sync catalog immediately
![Screen Shot 2020-04-22 at 2 54 37 PM](https://user-images.githubusercontent.com/21333308/79950330-7ece2500-84a9-11ea-8657-21c6de077abe.png)
