### ISSUE TITLE
How set synchronize time FB shop witch OC store? 

### ISSUE THREAD

**Issue by arturiokas** [facebookincubator/Facebook-For-OpenCart#371]
How set synchronize time FB shop witch OC store?

**Comment by shue249** [comment]
@arturiokas Can you share more on your problem. Are there any screenshots that you can use to explain on syncing FB shop time with OC store time.

**Comment by arturiokas** [comment]
One of module functions is " Auto synchronize OpenCart products to Facebook catalog."
I created Facebook catalog whith this module, but in Facebook  showing products synchronized with opencart at catalog creation date. And product in FB catalog not renewing.
Question. How set in module synchronization FB catalog with OC?
Thank you

**Comment by dtying** [comment]
Hi @arturiokas - We are using a daily scheduled generated feed to sync the OpenCart products to Facebook catalog.

Refer to below workaround if you need to force catalog sync at realtime.
https://github.com/facebookincubator/Facebook-For-OpenCart/issues/370
