### ISSUE TITLE
Facebook Ads Extension not connecting to Business manager

### ISSUE THREAD

**Issue by Bjornhjacobs** [facebookincubator/Facebook-For-OpenCart#372]
As requested in your email, I am continuing the support issue here. 

We have successfully created the FB Pixel but cannot get it to sync with our OC website. This issue occurred after upgrading to version 3.0.0.0 of the OC Facebook Ads Extension.

**Comment by dtying** [comment]
Hi @Bjornhjacobs, may I confirm that your webstore_url is as below? https://www.artdevivresansgluten.com/

I can see that your store's FBE setup is completed.
However, your store currently has two active pixels. 796601444010452 is the one newly created when you setup v3.0.0 FBE, and you don't need to touch pixel script code of this one because it has already been injected to fire events when you've setup FBE.

May I know what's your current problem now?

**Comment by Bjornhjacobs** [comment]
Hello, 

Yes, indeed our domain is artdevivresansgluten.com <http://artdevivresansgluten.com/>

The issue that we are having is that even after completing the setup process from the OC extension, there are no events which are being reported by the pixel. Both the opencart Extension and Facebook are stuck and continue to return the configuration steps, see below. This screenshot has been taken just a few moments ago and the OC extension is at the same stage, with the blue Get Started button. 



Thanks! 

PS, I am including Gregory Maroc on this reply as he is the one taking care of this installation for us, please include his email address in future communications so that we may all be in the loop. 

Thank you very much! 

Bjorn Jacobs
514-815-2788

**Comment by dtying** [comment]
Hi @Bjornhjacobs , I found that you were actually an existing user of FBE before v3.0. So when you upgraded to v3.0, you shouldn't create any new pixel or catalog but to reuse the existing ones. By default, your previous FBE connected assets should automatically be migrated to the latest version.

The expected migration screen should look like this for the existing user: https://drive.google.com/file/d/1QdOM1ZdcoY8YfrJJPD6MeN76XpLRH6bm/view

I've verified your [pixel](https://business.facebook.com/events_manager/pixel/events?business_id=558422218122880&selected_data_sources=PIXEL&pixel_id=701411177277620) in your store is working correctly.

**Comment by Bjornhjacobs** [comment]
Hi, 

Indeed, we were able to get everything to work again, I’m not sure exactly what changed but luckily everything is up and running now. I thank you very much for your help! 

Have a great day, I hope you are well in these uncertain times! 

Bjorn Jacobs
514-815-2788

**Comment by dtying** [comment]
Thank you no problem!
