### ISSUE TITLE
"Get started" button missing after bad sync 

### ISSUE THREAD

**Issue by tej17584** [facebookincubator/Facebook-For-OpenCart#373]
Hello, I have version 2.1.3 of the extension currently. When I installed it the first time, it worked correctly, timing, etc.
Afterwards, I modified a model file (the specific file is the facebookproduct.php file), saved the changes and tried to sync again. Synchronization did not take place so I closed the window and stopped connecting to facebook. Then, when reloading, the Get Started button disappeared.

Attached screenhoot.

![image](https://user-images.githubusercontent.com/32106099/80003975-02bee780-847f-11ea-99b7-c16b86b39d6e.png)

**Comment by shue249** [comment]
@tej17584 As you mentioned there was modifications to the model file which could have resulted in errors from the modifications. Can you look at the browser console log and your server error logs to see if there are any errors.

Also, we have a latest 3.0.0 version, which you can download and upgrade your Facebook Business Extension settings. https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.0.0

**Comment by tej17584** [comment]
Actually, there was a typo error in the model that causes to crash.

I fixed it.
Thanks..all done.

**Comment by shue249** [comment]
Thank you for the feedback.
