### ISSUE TITLE
Sincronyse errors 

### ISSUE THREAD

**Issue by arturiokas** [facebookincubator/Facebook-For-OpenCart#375]
google_product_category: Invalid google product category provided (28 520 products affected) | google_product_category: Invalid google product category provided (28 520 products affected)
-- | --
google_product_category: Invalid google product category provided (28 520 products affected)
google_product_category: Invalid google product category provided (28 520 products affected) | google_product_category: Invalid google product category provided (28 520 products affected)
google_product_category: Invalid google product category provided (28 520 products affected)
title: Field contains all uppercase letters (353 products affected) | title: Field contains all uppercase letters (353 products affected)
title: Field contains all uppercase letters (353 products affected)

**Comment by shue249** [comment]
@arturiokas You can safely ignore the warnings. You can refer to this post for more info - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/340#issuecomment-609672424

We will be closing out this ticket
