### ISSUE TITLE
Can't see Facebook label in my admin label

### ISSUE THREAD

**Issue by Luciano26** [facebookincubator/Facebook-For-OpenCart#376]
Hi, i've installed you plugin but i can't see the Facebook Business Extension label in my admin panel. that's the situation:
![Schermata 2020-04-23 alle 09 40 28](https://user-images.githubusercontent.com/14168951/80072665-d8d0f800-8546-11ea-86d8-36a35335bd95.png)
![Schermata 2020-04-23 alle 09 40 08](https://user-images.githubusercontent.com/14168951/80072670-db335200-8546-11ea-9030-7816049c41a8.png)

**Comment by Luciano26** [comment]
I've installed also the latest version(3.0), but have the same issue.

**Comment by Luciano26** [comment]
this is the log:
![Schermata 2020-04-23 alle 09 52 26](https://user-images.githubusercontent.com/14168951/80073530-344fb580-8548-11ea-9c70-eb7324ef9773.png)
![Schermata 2020-04-23 alle 09 52 16](https://user-images.githubusercontent.com/14168951/80073537-36b20f80-8548-11ea-828a-bb9e941fb92e.png)
![Schermata 2020-04-23 alle 09 52 07](https://user-images.githubusercontent.com/14168951/80073542-37e33c80-8548-11ea-8b46-6a99f1492647.png)

**Comment by shue249** [comment]
@Luciano26 

1. Will you be able to do a hard refresh your browser to see if the menu label comes up

2. Otherwise, you can access the URL directly via index.php?route=extension/facebookadsextension

**Comment by Luciano26** [comment]
Trying to access to the URL but i have this page:
![Schermata 2020-04-23 alle 12 58 38](https://user-images.githubusercontent.com/14168951/80091909-31fa5500-8562-11ea-94e8-c5460ef83c9a.png)

**Comment by shue249** [comment]
@Luciano26 Can you look at point 4 on this FAQ to see if it helps you to overcome the Access denied problem - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#accessing-the-facebook-business-extension-module

**Comment by Luciano26** [comment]
Thank you, I solved the problem giving access permission by following the 4th point on the FAQ. you're great.
