### ISSUE TITLE
Can't Connect Opencart to Facebook

### ISSUE THREAD

**Issue by marcdoyle** [facebookincubator/Facebook-For-OpenCart#378]
Hi - I have used this extension for over 2 years but this morning it disconnected from Facebook so I tried to reconnect but it just shows the timer but does not connect. I have tried to uninstall and reinstall but no joy.
Can you suggest anything?
Regards
Marc Doyle
www.thescarfseller.com
![connection](https://user-images.githubusercontent.com/64322768/80285047-1fc31700-871a-11ea-87c2-65a82772988f.png)

**Comment by dtying** [comment]
Hi @marcdoyle , I have checked that your existing FBE setup is still working as before.

Above screen shows that you may have issue in upgrading to the latest version v3.0 when granting permissions. You can try re-login your FB account. However, if it's still not working, you can keep using the older plugin version.

**Comment by marcdoyle** [comment]
Hi - I've tried to login numerous times but it doesn't work. :-( 

Where can I download an older version?

Cheers

**Comment by marcdoyle** [comment]
The older version works fine. Thanks for your help.

**Comment by wegee-us** [comment]
@dtying i got the same problem, after that i got [object Object] error. but older version is working fine

**Comment by dtying** [comment]
Thank you @wegee-us - We have recently fixed an API issue in FBE plugin v3.0.0, the [object object] error should be gone now.
