### ISSUE TITLE
facebook_ads_extension - page not found

### ISSUE THREAD

**Issue by dunamit** [facebookincubator/Facebook-For-OpenCart#38]
Hello! I have problem when i am going to edit the facebook_ads_extension under the module it give me the error page not found path(extension/module/facebookadsextension_installer&user_token=4rf...

I walked the steps exactly as in the ticket ([Facebook ads Extension Edit Error #36](https://github.com/facebookincubator/Facebook-For-OpenCart/issues/36))

**Comment by dunamit** [comment]
opencart 2.1.0.1
module from [here https://www.facebook.com/business/help/1494437460610744?helpref=faq_content](url)

**Comment by shue249** [comment]
@dunamit Thank you for your feedback. You do not need to click on the edit function. You should setup Facebook Ads Extension from the menu bar.

![image](https://user-images.githubusercontent.com/11957585/45768394-4f24be80-bc6f-11e8-819e-244406fe79eb.png)

You may also want to refer to this vide guide for the full instructions - https://drive.google.com/open?id=1JPXQ0mS1pGk2Bat9RV02vYNdbRfCLP9r

**Comment by shue249** [comment]
@dunamit I will be closing this ticket, but pls feel free to open up if you are still having problems
