### ISSUE TITLE
Parse error: syntax error, unexpected '{' in

### ISSUE THREAD

**Issue by Vemonz** [facebookincubator/Facebook-For-OpenCart#380]
Parse error: syntax error, unexpected '{' in /home/u7150790/storage/modification/admin/model/catalog/product.php on line 680

`
[product.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/4544915/product.zip)
`

**Comment by shue249** [comment]
@Vemonz Thanks for the feedback. Can you re-attach the zip file via the desktop web browser? Unfortunately the zip package was not successfully attached in the 1st post

**Comment by Vemonz** [comment]
[product.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/4544954/product.zip)

**Comment by Vemonz** [comment]
@shue249 did u check it?

**Comment by shue249** [comment]
@Vemonz Which version of opencart are you using?

**Comment by Vemonz** [comment]
3.0.3.2

shue249 <notifications@github.com>, 29 Nis 2020 Çar, 14:35 tarihinde şunu
yazdı:

**Comment by shue249** [comment]
@Vemonz We want to check with you on what is the version of the plugin that you are using? Are you using the latest 3.0.0 plugin version? 

You can download the latest version here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.0.0

Remove the existing version and install this newer version and refresh modifications. Let us know if this helps.

**Comment by shue249** [comment]
We will be closing off this ticket. Feel free to reach to us if you have further questions.
