### ISSUE TITLE
Join manufacturer name with product name

### ISSUE THREAD

**Issue by rhinsu** [facebookincubator/Facebook-For-OpenCart#381]
@shue249 i being novice into programming, i would like your assistance to assist me with the code for joining the two, from the previously advised links.

**Comment by rhinsu** [comment]
@shue249 we have run into a strange issue, the title column is showing empty

**Comment by shue249** [comment]
@rhinsu Can we check on your empty title column first. Can you share example products where the title is empty. Did you make any changes to the coding?

**Comment by rhinsu** [comment]
@shue249 all product titles were empty, also facebook reported a problem importing the feed. but a while ago I checked and all was back to normal...i have cloudflare running, can that in any case interfere with realtime sync??

I tried an edit on this file, but all was restored back to original file about a week ago
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/model/extension/facebookproduct.php#L15

**Comment by shue249** [comment]
@rhinsu Are you still seeing the problem where the product titles are empty? If so, can you share your catalog id with us and want to understand if you have made any edits to the code file yourself.

With regards to the ask to provide code changes on joining the manufacturer name. We are currently unable to help on this at the moment, as we are focusing on other priorities. We are unable to provide a timeline on when we may be able to look into this for you, you may want to consider getting access to external developer resources.

**Comment by shue249** [comment]
We will be closing off this ticket. Feel free to reach to us if you have more questions.
