### ISSUE TITLE
How to disable Cookie Bar

### ISSUE THREAD

**Issue by AlexGolemis** [facebookincubator/Facebook-For-OpenCart#383]
How can i disable the cookie bar from opencart admin? There is no option at Facebook Business Extension. My site url is pnb-shop.gr

![image](https://user-images.githubusercontent.com/64062947/80967820-a913d100-8e1f-11ea-84ce-2d611f61a47b.png)

![image](https://user-images.githubusercontent.com/64062947/80968047-fc861f00-8e1f-11ea-965d-368272ad319a.png)

**Comment by shue249** [comment]
@AlexGolemis The option to disable the cookie bar will appear after you complete the setup process, which you can start by clicking on Get Started. If you have yet to complete the setup, the cookie bar disable option will not be shown.

We will be closing out this ticket, feel free to reach to us if you have further questions.
