### ISSUE TITLE
Microdata for pixel

### ISSUE THREAD

**Issue by thrift4good** [facebookincubator/Facebook-For-OpenCart#384]
Regarding Microdata meta tags, is there a way to automatically generate? For my pixel to work it says I need to add meta tags to each of my products for the pixel to work. Since the product pages are generated dynamically, is there a way to also generate the tags dynamically?
--

![facebook-pixel](https://user-images.githubusercontent.com/64807399/81007320-a19bfa00-8e16-11ea-9332-3a0bca686834.jpg)

**Comment by shue249** [comment]
@thrift4good Have you completed our Facebook Business Extension setup? Our setup will automatically create a product catalog with the Data source set as the product feed which is generated from your webserver.

It seems to us that this catalog is not created from our plugin.

**Comment by thrift4good** [comment]
The feed is showing up properly with all of the items in the manager, but none of the products are showing in the shop.

**Comment by shue249** [comment]
@thrift4good can you share with us your catalog ID. Is a new catalog generated or are you using the existing catalog?

**Comment by thrift4good** [comment]
This catalog feed was generated when I installed the extension.
Feed ID: 1345136379018791

Product Set:
ID: 1011387282596421

I want the catalog to be generated fully from the data feed. My facebook
page is @thrift4good.

Taylor Watts

**Comment by thrift4good** [comment]
I created the data set with your app.
see pic
Taylor Watts
817320928


[image: image.png]

**Comment by thrift4good** [comment]
Just checking in to see if I can get some help with this issue.

I created the data set with your app.
see pic
Taylor Watts
817320928


[image: image.png]

**Comment by shue249** [comment]
@thrift4good We checked your catalog and everything seems correct. There are now 80 products and the last sync is on 11th May. Looks to me that everything is in order and you do not need to implement any micro data for pixel.

Are there other questions/issues that you are seeing or facing?

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions.
