### ISSUE TITLE
 We have detected the Facebook pixel is not correctly setup in your web store site.

### ISSUE THREAD

**Issue by garganoadv** [facebookincubator/Facebook-For-OpenCart#385]
Hello,

I have gone through all the recommended steps and continue to experience the same issue.
All products have been successfully imported into the business manager, but I don't receive any events from the pixel.

<img width="1717" alt="Schermata 2020-05-05 alle 12 50 02" src="https://user-images.githubusercontent.com/25225822/81058650-20ed0480-8ecf-11ea-80a6-febce75a68a2.png">

**Comment by shue249** [comment]
@garganoadv Can you share your webstore URL?

**Comment by garganoadv** [comment]
Yes is https://www.xtremeaerodynamics.it/

**Comment by shue249** [comment]
@garganoadv The pixel code from our plugin is not successfully setup on your website. If you look at the suggestions on the module page, those are the usual causes of error. Can you take a look to see if it helps.

In particular, if you are using OpenCart v3.x, are you making any changes to the header and footer from the Theme design. Also you may want to check if you disable the theme/SASS cache.

**Comment by garganoadv** [comment]
@shue249 Thanks. The problem is the customized footer in Fastor template. I modified the default footer and now all it's ok.

**Comment by shue249** [comment]
Glad that it works for you. We will be closing out this ticket. Feel free to reach to us if you have further questions.

**Comment by nik-anto** [comment]
> @shue249 Thanks. The problem is the customized footer in Fastor template. I modified the default footer and now all it's ok.

I have the same problem, could you please explain your silution?

**Comment by garganoadv** [comment]
> > @shue249 Thanks. The problem is the customized footer in Fastor template. I modified the default footer and now all it's ok.
> 
> I have the same problem with fastor theme, could you please explain your solution?

Try to disable the footer in the common folder of the fastor template, this should start the footer of the basic Opencart template. In this way the Facebook module should start.
