### ISSUE TITLE
My opencart use 3rd  theme  JOURNAL 3.045,Seems the Pixel  not work,

### ISSUE THREAD

**Issue by huaxiashenqi** [facebookincubator/Facebook-For-OpenCart#386]
i contact the facebook, but when i text connect with the pixel , it is not work, 

my questions is this plugs not support the 3rd theme?

best regards

**Comment by huaxiashenqi** [comment]
my website:  www.foogme.com  ,opencart 3.032

**Comment by dtying** [comment]
Hi @huaxiashenqi , the pixel_id which you have connected with FBE is 1140228989662560. 
I also checked in your webstore, the pixel works correctly.
