### ISSUE TITLE
Facebook Business Manager Warnings

### ISSUE THREAD

**Issue by AlexGolemis** [facebookincubator/Facebook-For-OpenCart#387]
All my products have been synced and i can see them at Facebook Business Manager. But i get some warnings.

**Invalid Google product category provided** : The Google product category specified in the feed file does not match the standard taxonomy defined by Google: https://support.google.com/merchants/answer/6324436. You can specify either the string representation or the numeric representation of your category. (Lines 36,51,243,441,470)

You can specify either the string representation or the numeric representation of your category.,google_product_category,BAGS / ACCESSORIES,719216898888811,"05/05/2020, 17:24"

You can specify either the string representation or the numeric representation of your category.,google_product_category,OFFERS,719216898888811,"05/05/2020, 17:24"

You can specify either the string representation or the numeric representation of your category.,google_product_category,SLIM FIT,719216898888811,"05/05/2020, 17:24"

You can specify either the string representation or the numeric representation of your category.,google_product_category,CASUAL SET,719216898888811,"05/05/2020, 17:24"

You can specify either the string representation or the numeric representation of your category.,google_product_category,CASUAL SET,719216898888811,"05/05/2020, 17:24"

**Insecure protocol** : The URL specified in property checkout_url uses an insecure protocol. Ensure that your website supports secure protocols such as HTTPS, and update the URL in your feed to use a secure protocol. (Lines 36,51,243,441,470)

http://www.pnb-shop.gr/index.php?route=product/product&product_id=828,719216898888811,"05/05/2020, 17:24

http://www.pnb-shop.gr/index.php?route=product/product&product_id=880,719216898888811,"05/05/2020, 17:24

http://www.pnb-shop.gr/index.php?route=product/product&product_id=715,719216898888811,"05/05/2020, 17:24"

http://www.pnb-shop.gr/index.php?route=product/product&product_id=505,719216898888811,"05/05/2020, 17:24"

http://www.pnb-shop.gr/index.php?route=product/product&product_id=494,719216898888811,"05/05/2020, 17:24"

How is that possible. I have enabled https at all my site pages. Why these pages don't have https?

**Comment by shue249** [comment]
@AlexGolemis You can ignore the warnings on the google product category as it does not have impact on the catalog or dynamic ads.

For the HTTPS setting, we leverage on the HTTP_CATALOG php setting on your server. Can you check the file admin/config.php and see if this setting has https, and if not, you can change this setting to https.

Alternatively, if you have developer resources, you can change this code on our plugin file in your webserver to return HTTPS_CATALOG instead of HTTP_CATALOG. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L163-L166

**Comment by AlexGolemis** [comment]
I had only HTTPS_CATALOG url at my  config.php file. I added HTTP_CATALOG  with https at url and now i don't have the warnings.
The only warning i still have is the google product category. Can you give me more information about the reason i see it and why it does not affect the catalog or dynamic ads?

**Comment by shue249** [comment]
@AlexGolemis When feed file with google product category is uploaded to Facebook, we do a validation against the Google taxonomy to check if it is following Google's specifications. If not, we will show the warnings to inform the advertisers of this problem.

However, this is only shown up as warnings to notify the advertisers. This does not impact the catalog or dynamic ads. Even if the products have invalid or empty google product category, the catalog can still be used for Facebook page shop as well as dynamic ads.

We will be closing out this ticket, feel free to reach to us if you have further questions.
