### ISSUE TITLE
facebook messager is gone in Version: 3.0.0

### ISSUE THREAD

**Issue by wegee-us** [facebookincubator/Facebook-For-OpenCart#389]
Hi,
i want to make sure, the facebook messager is removed in Version: 3.0.0? because i can't see add facebook messager in setting anymore. and facebook messager is disappeared when we upgrade from version 2 to Version: 3.0.0

**Comment by dtying** [comment]
Hi @wegee-us , you may refer to the update here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#setup-for-facebook-messenger-chat

The messenger plugin will be brought back in the next plugin version.
