### ISSUE TITLE
How install pixel and don't remove modifications?

### ISSUE THREAD

**Issue by meverikxp** [facebookincubator/Facebook-For-OpenCart#391]
Hello, I installed the plugin but got pixel error
but I got this error
We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

But I can't clear my modifications becuase I have many changes on my website. Is there any way to install pixelcode manually and it will work with plugin. Becuase I already added pixel script but plugin still not work

Thank you!

**Comment by dtying** [comment]
Hi @meverikxp , a better way for your to validate whether your pixel is firing event correctly is to install [Facebook Pixel Helper](https://developers.facebook.com/docs/facebook-pixel/support/pixel-helper/) chrome extension.

If the pixel helper shows signals firing, you may ignore the warning.

**Comment by shue249** [comment]
@meverikxp Do you have developer resources? If so we can point to you on the code path to make the changes so that you do not need to click on Refresh modifications.

However, if you do not have developer resources, it will be very hard for us to guide you to make those changes, as things may go wrong easily.

**Comment by meverikxp** [comment]
Yep I have developer resources

вт, 12 мая 2020 г. в 11:06, shue249 <notifications@github.com>:

**Comment by shue249** [comment]
@meverikxp This will be my suggestions on how to go about doing this.

1. Look up this file which contains all the pointers where we need to make the changes on your OpenCart website. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml

2. Each <file> tag is the modification section. In summary, what you need to do is to edit the file on your webserver, locate the code string then insert the code changes.
![image](https://user-images.githubusercontent.com/11957585/81803035-ac0e7000-9549-11ea-8026-4f20d776b3b0.png)

3. You need to do for all the <file> tags. However, there could be some files which are not applicable, eg twig file extension is only for OpenCart v3.x. If you cannot locate those files, you can ignore them.

**Comment by meverikxp** [comment]
Hello,
Thank you for your response
But I already have facebook link in left menu. My problem is in pixel,
Plugins doesn't find it
[image: image.png]
How I can fix this problem, without clean modifications?

ср, 13 мая 2020 г. в 13:45, shue249 <notifications@github.com>:

**Comment by yao-tx** [comment]
Hi @meverikxp 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
