### ISSUE TITLE
Error during plugin configuration

### ISSUE THREAD

**Issue by atlantisevo** [facebookincubator/Facebook-For-OpenCart#393]
After install and after login to facebook account i get this error: An error occured when creating Facebook Business Extension setup.
![musicstore_fb](https://user-images.githubusercontent.com/65234913/81698308-13eb8a80-9466-11ea-8749-5e2a8d272a9d.png)
[Music Store_2020-05-11_16-43-02_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/4615904/Music.Store_2020-05-11_16-43-02_facebook_ads_extension.log)

**Comment by dtying** [comment]
Hi @atlantisevo , can you provide your webstore_url?

**Comment by atlantisevo** [comment]
Url is: https://www.musicstore.sm/

**Comment by dtying** [comment]
Hi @atlantisevo , I checked the log that your installation failed due to 'Can't approve request to add Page to a Business Manager account: As a security precaution, you aren't allowed to approve a request to add this Page to a Business Manager account because you were added as an admin on the Page less than a week ago'.

Can you try again after one week?

**Comment by atlantisevo** [comment]
Thank you very much. I'll wait.

**Comment by PaulBogdanCom** [comment]
Hi, i have the same problem on OC 3.X while setting up FB Extension:
An error occured when creating Facebook Business Extension setup.
Store is : motocorner.ro

**Comment by atlantisevo** [comment]
I tried to install the plugin again. 10 days have passed since the configuration change on Facebook. Am I still waiting? Is it possible there is another problem? Thanks

**Comment by atlantisevo** [comment]
Ho provato a disinstallare e reinstallare il plug in, ora ho questo errore:

![image](https://user-images.githubusercontent.com/65234913/82604362-7fdf9880-9bb4-11ea-8e5e-b23732a99c5a.png)

**Comment by yao-tx** [comment]
Hi all,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336) or from [GitHub Latest Release](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/latest). 

We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow one of the following:
* Quick installation guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart)
* Detailed step-by-step guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
