### ISSUE TITLE
How can I remove cookie bar ?

### ISSUE THREAD

**Issue by myartmarket** [facebookincubator/Facebook-For-OpenCart#394]
Hi, How can I remove cookie bar on mobile view ? 
we already have one and don't need a second one.

**Comment by shue249** [comment]
We have an option to disable the cookie bar. You can read more details here.  https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#cookie-bar-shown-on-web-store

**Comment by shue249** [comment]
We will be closing out this ticket, Feel free to reach to us if you have any further questions.
