### ISSUE TITLE
Proble with cart notification in Journal 3

### ISSUE THREAD

**Issue by pipperis** [facebookincubator/Facebook-For-OpenCart#395]
Hi,

I am using Journal 3 with OC 2.3.0.2 and Facebook Business Extension v3.0.
When a product is added in the cart, the notification on the cart icon remains 0 (see attached image).

I contacted the support of Journal about the issue and they replied:
_Your issue is related to Facebook Pixel extension, please consult with its developers for more information._

Can you please advise.
Thanks

![Annotation-2020-05-12-170544](https://user-images.githubusercontent.com/58871352/81795095-64b9bc80-9514-11ea-9e54-10f8fcd4f9b6.png)

**Comment by shue249** [comment]
@pipperis Can you share with us your website URL

**Comment by pipperis** [comment]
Please click [here ](https://www.beautyangel.gr/)to visit the website.

**Comment by pipperis** [comment]
@shue249 Have you managed to check if there is a conflict of the extension with Journal 3?

**Comment by shue249** [comment]
@pipperis We played around the cart functionality on your website, looks like it is not simply a zero display problem.

1. If we try to add multiple items, the cart counter notification will increment, but at 1 number lesser

2. If you access the cart page, the cart counter notification will show the correct number

3. if you access back any product pages, the cart counter notification will show back as 1 number lesser.

If we refresh the webpage, the behaviour remains the same.

To the best of our knowledge, we do not make any changes to the cart notification display on our plugin. 

Have you tried to uninstall our plugin and see if the same problem happens on your website?

**Comment by pipperis** [comment]
@shue249 I uninstalled the Facebook extension and the problem stopped. See image attached.
After the test, I re-installed the extension and the problem is back. 
Any advise on how to solve?
Should I re-install the previous version of the Facebook extension?
![Annotation 2020-05-18 183918](https://user-images.githubusercontent.com/58871352/82232173-eeafbe00-9936-11ea-94bf-e4dea4571176.png)

**Comment by shue249** [comment]
@pipperis We do not have the exact same setup on your site, hence posing challenges for us to dive into the problem.

You can try out the previous versions of our plugin - but I am not hopeful for this, as we are pretty confident that we did not make changes on the cart between these versions. https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.1

**Comment by pipperis** [comment]
@shue249 you were right. Even with v.2.2.1 the problem remains.
Do you know of a previous version that may not cause the problem with the cart?

**Comment by shue249** [comment]
@pipperis Apologies for the late reply. We have not changed the implementation for the cart since the beginning, so I will say this could be a general incompatibility with this particular journal template.

Unfortunately, we do not have the bandwidth at the moment to dig deeper into your setup to figure out the root cause. 

One suggestion I can provide is to look for this file on your webserver and comment/delete away these lines of code below and see if the cart notification is working properly (you need to do a hard reload of your browser)
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/view/javascript/facebook/facebook_pixel_3_0_1.js#L65-L97

**Comment by yao-tx** [comment]
Hi all,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!

**Comment by yao-tx** [comment]
Hi @pipperis 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
