### ISSUE TITLE
"The message received is not from the verified source."

### ISSUE THREAD

**Issue by bonny3** [facebookincubator/Facebook-For-OpenCart#396]
Hi,

I installed the new version 3.0.0 of Facebook Opencart,
but unfortunately I keep getting the error message ...

"The message received is not from the verified source."

![2020-05-15_113816](https://user-images.githubusercontent.com/19350758/82036003-9eb7c980-96a0-11ea-967a-c37902554d14.png)

before installing the new version, I removed the previous version 2.10.
I ask how can I solve the problem

Thanks
Best Regards
Alessandro

**Comment by dtying** [comment]
Hi @bonny3 , could you provide us your webstore url?

**Comment by bonny3** [comment]
> 
> 
> Hi @bonny3 , could you provide us your webstore url?

Hi @dtying,
I am testing on my test site
https://www.occhialando.it/test/
first important thing if the admin folder has been renamed
the extension doesn't work, you need to re-link
in the facebookadsextension.php file
in admin / controller
Another problem today is an object / object error

**Comment by dtying** [comment]
@bonny3 , did you receive the object / object error in last installation only? From backend the installation runs correctly.
Can you open FBE popup -> click on "Continue as xxx" button again?

**Comment by bonny3** [comment]
@dtying ,
I solved the problem of (object object)
going to change the settings in "edit"
in the popup, now this error is no longer present ..
but the error continues
"The message received is not from the verified source"
I send you a video

https://www.occhialando.it/test/Video_2020-05-19.wmv

**Comment by dtying** [comment]
Hi @bonny3, thanks a lot for your video, it's very useful! 
I never encountered the issue like yours before so I'm a bit surprised to see it. Will try to do a minor release as early as possible.

**Comment by bonny3** [comment]
Hi @dtying ,
ok Thanks

**Comment by pankajparas** [comment]
Hello, I am facing with same issue.
My Installation steps.
1. Uploaded facebookadsextension.ocmod.zip
2. Uploaded manually "upload" folder/subfolders to our server (Due to facebook B ext. not found on dashboard after refreshing modification)

**Comment by bonny3** [comment]
Hi @dtying ,
did you manage to fix the problem?

**Comment by dtying** [comment]
Hi @bonny3 , I've uploaded the latest version here: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336. Github will be updated in a later time.

**Comment by bonny3** [comment]
Hi @dtying ,
the message problem seems to be solved,
but I notice a message in the PHP error.log

[21-May-2020 15:43:16] WARNING: [pool xxxxxxxxxxxxx] child 48231 said into stderr: "NOTICE: PHP message: feed file = /home/wwwxxxxxxxxxxx/public_html/test/system/storage/download/fbe_product_catalog.csv"

**Comment by bonny3** [comment]
Hi @dtying ,

I have encountered an additional problem
when facebook import the feed
with this link:

https://www.my_site.com/index.php?route=extension/facebookfeed/genFeedNow

every time it is regenerated in my store,
this is a problem, because I have so many products
about 43000 if it is regenerated at the time of download
the session expires and facebook is unable to import the products
I found the problem with .csv files with a size of 31 MB

to make it work, like for example with google,
first you need to generate the feed and then export the file
doing it at the same time does not work with very large files

I was able to import a maximum of 28 MB .csv file

**Comment by bonny3** [comment]
Hi @dtying ,

can you answer me please?

**Comment by dtying** [comment]
Hi @bonny3 , could you change the url setting from 'https://www.my_site.com/index.php?route=extension/facebookfeed/**genFeedNow**' to 'https://www.my_site.com/index.php?route=extension/facebookfeed/**genFeed**'?
I made this update because several users requesting for real-time catalog sync last time.

**Comment by bonny3** [comment]
Hi @dtying ,

if I use the link you gave me, it doesn't work properly,
an 8MB file is downloaded comparing the 32MB of the generated file in the "system / storage / download" folder
many products are missing from this file

this is not a good solution,
you have to think that there are large databases that cannot implement this option.

you should add the choice whether to use this option
in this way the user can decide which method to use

I ask you to update the extension to make it work properly

Thanks

**Comment by dtying** [comment]
Hi @bonny3 , thanks for your feedback! This is a good point and let me follow up internally first.

**Comment by bonny3** [comment]
ok Thanks!
when can you upgrade?

**Comment by dtying** [comment]
Hi @bonny3 , would you mind providing your catalog_id in order for us to troubleshoot this? 
You may email to ads_extension_opencart@fb.com

**Comment by bonny3** [comment]
Hi @dtying ,
can I get an answer to the problem on the new Facebook feed import?
Thanks

**Comment by yao-tx** [comment]
Hi @bonny3 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!

**Comment by bonny3** [comment]
> 
> 
> Hi @bonny3
> 
> Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.
> 
> To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).
> 
> For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).
> 
> If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/).
> 
> Thank you!

Hi,
I have installed the new version 4.0.2,
but the setting popup does not open ...
how can i solve the problem? 
Thanks

![2021-04-30_150210](https://user-images.githubusercontent.com/19350758/116698821-1c193e80-a9c5-11eb-9eee-ecae86c5768d.jpg)

**Comment by yao-tx** [comment]
Hi @bonny3 

Please open a support ticket with us via our help desk [here](https://marketinsg.zendesk.com/) and we will assist you with the issue.
