### ISSUE TITLE
Feed update

### ISSUE THREAD

**Issue by Vollanddzaft** [facebookincubator/Facebook-For-OpenCart#397]
I have updated prices and images on the website, and when i am trying to update it in www.facebook.com/products/catalogs/ - manually it updates me old date. So Feed is always old. On the website is new information - in Feed is old

**Comment by dtying** [comment]
Hi @Vollanddzaft ,

1. Refer here for our current design: https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog
2. Here's a workaround for real-time feed updating: https://github.com/facebookincubator/Facebook-For-OpenCart/issues/370
