### ISSUE TITLE
При установке выдало ошибку

### ISSUE THREAD

**Issue by Albertovi4** [facebookincubator/Facebook-For-OpenCart#398]
![Снимок экрана 2020-05-19 в 0 40 10](https://user-images.githubusercontent.com/65570585/82262467-a1007900-9969-11ea-80b7-80ab100516eb.png)
При установке расширения выдает следующую ошибку.

**Comment by Albertovi4** [comment]
Попробовал установить версию 3.0 выдает такое сообщение. Прошел по пунктам, не помогло((
![Снимок экрана 2020-05-19 в 0 44 33](https://user-images.githubusercontent.com/65570585/82262738-22580b80-996a-11ea-931e-cdabfdbddb6a.png)

**Comment by Albertovi4** [comment]
https://www/kvartyra.ru

**Comment by shue249** [comment]
@Albertovi4 Seems like your website is down or the domain is not correct. Want to understand if the URL is correct.

![image](https://user-images.githubusercontent.com/11957585/82333601-85ed4200-9a19-11ea-8fc5-dd1c961578ed.png)

**Comment by Albertovi4** [comment]
https://kvartyra60.ru/

**Comment by Albertovi4** [comment]
Ошибся чуть))
