### ISSUE TITLE
3.0.1

### ISSUE THREAD

**Issue by PaulBogdanCom** [facebookincubator/Facebook-For-OpenCart#399]
An error occured when creating Facebook Business Extension setup. {"success":true,"pixel_id":"2599893580338004","installed":true}

**Comment by dtying** [comment]
Hi @PaulBogdanCom , there's a typo in your HTTP_CATALOG constant - currently is 'https:/.motocorner.ro/'.

Could you correct HTTP_CATALOG under admin/config.php, and then retry?

**Comment by PaulBogdanCom** [comment]
@dtying oh hell, did not seen that, works but Messenger still is with red alert and does not work

**Comment by dtying** [comment]
Hi @PaulBogdanCom, messenger is unavailable in current version. We're targeting to bring it back in next release.

**Comment by dtying** [comment]
3.1.0 released with Messenger plugin.
