### ISSUE TITLE
Feed URL

### ISSUE THREAD

**Issue by serkanbalta** [facebookincubator/Facebook-For-OpenCart#4]
Hello,
This is really great module and thank you for great work.

There is a small issue with updating catalog products in fb business manager. I have tried the schedule it for auto update per hour, but it asks feed url and i couldn't find it.
Could you please help me about this feed url ? Because i already started to catalog commercials but it's really important to define or schedule auto update in fb business manager catalog.
Thank you.

**Comment by shue249** [comment]
Thank you for your question. The short answer is the products on your Opencart store are automatically synced to Facebook product catalog through API.

For the detailed explanation. We are adopting a 2 mechanism approach to ensure a good experience for you when you setup the Facebook Ads Extension. When you completed the setup, we will automatically create a Facebook product catalog and sync all your OpenCart products through the use of a one time feed file. This ensures a smooth operation even if you have a large number of products on your store. Subsequently, we will send real time product updates to Facebook whenever you make changes or new additions to your OpenCart products.

This means that there is nothing needed on your side, there is no need to input the feed url.
