### ISSUE TITLE
Ошибка объект-объект

### ISSUE THREAD

**Issue by Albertovi4** [facebookincubator/Facebook-For-OpenCart#401]
сайт: https://kvartyra60.ru/
ocstore 3.0
Была установлена предыдущая версия Facebook Business Extension 2.2.1
Была удалена предыдущая версия расширения.
Pixel halper показывает что пиксель не установлен.
Установлена ​​новая версия 3.0.1,
Путь 1 - Начало работы - (Вы ранее связали OpenCart с Facebook
Хотите продолжить с прежними настройками?) - Продолжить как xxxxxxx = объект - Ошибка объекта.
Путь 2 - Начало работы - Редактировать Настройки - (Подключите свои бизнес-инструменты.
Отредактируйте или продолжите, чтобы завершить подключение вашего магазина, НЕ возможно редактировать что-либо, но все в порядке ...) - Продолжить - (Что разрешено делать OpenCart? Да ... Да ...) - Далее = object object
![Снимок экрана 2020-05-26 в 11 37 22](https://user-images.githubusercontent.com/65570585/82879231-540e3b00-9f45-11ea-9028-f960d429244a.png)

Pixel halper показывает что пиксель не установлен на сайт.
![Снимок экрана 2020-05-26 в 11 38 46](https://user-images.githubusercontent.com/65570585/82879372-8455d980-9f45-11ea-82b8-fe13fce908ad.png)

**Comment by mzilyaev** [comment]
Вы не решили вопрос? у меня такая же ошибка((

**Comment by Albertovi4** [comment]
нет, не решил

**Comment by dtying** [comment]
Hi @Albertovi4 , your installation failed due to some backend exceptions. Give us some time to look into it.

**Comment by yao-tx** [comment]
Hi @Albertovi4 @mzilyaev 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
