### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by gogescuvicentiu** [facebookincubator/Facebook-For-OpenCart#403]
Hi,
I have a problem with Facebook Business Extension: after I switched to SSL the extension does not work anymore. No other settings were made. Please advice.
I receive the following error:

We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

Thank you!
Best regards,
Vicentiu.
www.artelier.online

**Comment by Albertovi4** [comment]
Скачай последнюю версию 3.0.1 У меня была данная ошибка, помогло обновление на более свежую версию. Однако новая версия выдает ошибку object object))

**Comment by dtying** [comment]
Hi @gogescuvicentiu , I see that you have uninstalled FBE as in the latest step, please confirm is it correct.

**Comment by gogescuvicentiu** [comment]
Hi,
No, I haven't uninstalled it. I've only activated SSL. Now, I receive the attached errors on admin page  and Facebook.
Thank you!
Regards,
Vicentiu,
![Screenshot_2020-05-29 Facebook Business Extension](https://user-images.githubusercontent.com/65999584/83246771-4823b280-a1ab-11ea-9111-ffb4087cee53.png)
![Screenshot_2020-05-29 Facebook](https://user-images.githubusercontent.com/65999584/83246773-48bc4900-a1ab-11ea-8d2b-2dd358343f39.png)

**Comment by dtying** [comment]
Hi @gogescuvicentiu , I found two different connections in your history:
* http://www.artelier.online/store/ ==> currently disabled ==> That's why you see error screenshot above when launch management view
* http://artelier.design/ ==> currently active

Note that we use HTTP_CATALOG constant defined under admin/config.php as the key identifier during setup. My suggestion would be:
1. Uninstall the setup connected to http://artelier.design/ 
2. Re-install the setup to activate http://www.artelier.online/store/ connection

**Comment by gogescuvicentiu** [comment]
Hi,
I''ve already did this a few times. I receive the same errors as in the before message...

**Comment by yao-tx** [comment]
Hi all,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
