### ISSUE TITLE
Sorry, something went wrong. 3.0.1

### ISSUE THREAD

**Issue by haxcop** [facebookincubator/Facebook-For-OpenCart#405]
After updating the plugin I receive the following error

> Sorry, something went wrong.
> We're working on getting this fixed as soon as we can.
> Go Back

Logs

`020-05-28 10:10:54 - Get Sample product feed`
`2020-05-28 10:10:55 - Complete - Get Sample product feed`
`2020-05-28 10:12:20 - Get Sample product feed`
`2020-05-28 10:12:21 - Complete - Get Sample product feed`
`2020-05-28 10:18:19 - Get Sample product feed`
`2020-05-28 10:18:20 - Complete - Get Sample product feed`
`2020-05-28 10:24:51 - Facebook Ads Extension version = 3.0.1`
`2020-05-28 10:24:51 - OpenCart version = 3.0.3.2`
`2020-05-28 10:24:51 - PHP version = 7.3.11`
`2020-05-28 10:24:51 - Verifying Availability of Facebook Ads Extension Settings Availability`
`2020-05-28 10:24:51 - Pixel ID = false`
`2020-05-28 10:24:51 - Pixel use PII = false`
`2020-05-28 10:24:51 - Page ID = false`
`2020-05-28 10:24:51 - System User Access Token = false`
`2020-05-28 10:24:51 - Messenger plugin = false`

**Comment by dtying** [comment]
Hi @haxcop , could you share the webstore_url with us?

**Comment by haxcop** [comment]
> Hi @haxcop , could you share the webstore_url with us?

thanks for your prompt reply @dtying . our site is: 

https://lookyourtech.com/

**Comment by dtying** [comment]
Hi @haxcop , I see that your last activity was on May 5th. Could you try to open the FBE popup, click on 'Continue as xxx' button, and see if it works?

**Comment by haxcop** [comment]
It was A not know issue with my Facebook account. everything works now
