### ISSUE TITLE
Errore per Plug In Facebook per Open Cart

### ISSUE THREAD

**Issue by atlantisevo** [facebookincubator/Facebook-For-OpenCart#406]
Good morning, I tried to install the plug in on the site www.musicstore.sm but I get this error:

An error occured when creating Facebook Business Extension setup. {"success":true,"pixel_id":"708518805987126","installed":true}

![image](https://user-images.githubusercontent.com/65234913/83131558-4a6d0a80-a0e0-11ea-92be-2fc78aff27d4.png)

How can I do?

**Comment by dtying** [comment]
Hi @atlantisevo , I see the last time you installed is on May 8th. Could you try click 'Edit Settings' when opening FBE popup and go through the setup flow again?

**Comment by yao-tx** [comment]
Hi @atlantisevo 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
