### ISSUE TITLE
This may be because of a technical error that we're working to get fixed. Try reloading this page

### ISSUE THREAD

**Issue by monefff** [facebookincubator/Facebook-For-OpenCart#409]
Hello,

We have Migrated from 2.2.1 to 3.0.1 and now we have major issue with the pixel.
We have 2 websites for 2 different countries.

The first website went perfect with the new module, got connected to business manager, the catalog imported, pixel works fine, and everything is perfect. 

Now we tried and deleted and disconnected the old module and installed the new one on the other website. (The 2 websites has 2 separated pages, 2 different ad accounts, 2 different pixels, 2 different catalogs). 

We stopped all ads, disconnected from the profile, and installed the new one, then tried to connect, and this is what is happening:
![Error1](https://user-images.githubusercontent.com/49583900/83629299-830a5980-a5a2-11ea-8649-3b89594fa4a0.png)
![Error2](https://user-images.githubusercontent.com/49583900/83629302-843b8680-a5a2-11ea-9860-efcadd948450.png)

I have it on video but there are some sensitive data, and I can show it to the developers of the module if requested.

We have tried 2 procces:
1 attempt
: Get started > Continue as <the user admin name>  
The error we got is " [Object Object]

2 attempt
: Get started > Edit Settings > Connect Your Store to Facebook > Select Business Manager
> Select Page >Connect Your Instagram > Select Your Ad Account > Select Pixel > Select Catalog
> What is OpenCart allowed to do?  and Error1 pops > This may be because of a technical error that we're working to get fixed. Try reloading this page. After we close the window, the same error as the attempt 1 [Object object]

In the process we select entirely different ad account, instagram, pixel, catalog, page (Same Business manager though) 

2020-06-03 11:12:48 - Facebook Ads Extension version = 3.0.1
2020-06-03 11:12:48 - OpenCart version = 2.3.0.2
2020-06-03 11:12:48 - PHP version = 7.0.33
2020-06-03 11:12:48 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-06-03 11:12:48 - Pixel ID = false
2020-06-03 11:12:48 - Pixel use PII = false
2020-06-03 11:12:48 - Page ID = false
2020-06-03 11:12:48 - System User Access Token = false
2020-06-03 11:12:48 - Messenger plugin = false

What seems to be the problem? What we are doing wrong? Is it possible this module to work with 1 Business manager and on different domains?

Now After we detached the old module, the catalog got deleted, and we have to start making entirely new ads, because of the issue, and maybe after a solution is found, we have to start all over again, because we have to detach the old module, and attach it to the new module, but still we have to make new catalog.. That's a lot of work and loosing money for ad optimization..

I hope there is a fix soon, or if can someone can help us out

Best Regards,
Simeon

**Comment by cepcemuh** [comment]
Same here...

**Comment by dtying** [comment]
Hi @monefff , feel free to downgrade to the latest version of previous major release 2.x.x to resume your business operation. 

The error means your FBE setup failed due to backend exception. Kindly share your webstore url so that I can help to check.

**Comment by monefff** [comment]
> Hi @monefff , feel free to downgrade to the latest version of previous major release 2.x.x to resume your business operation.
> 
> The error means your FBE setup failed due to backend exception. Kindly share your webstore url so that I can help to check.

Thank you for the response. We have downgraded to latest release. Can I share url in private message somehow?

**Comment by dtying** [comment]
Hi @monefff , sure you can email us at ads_extension_opencart@fb.com

**Comment by ivent** [comment]
Several errors occurred, but it was not possible to finish whenever this error was not finished, but it was possible to downgrade to version 2.xxx and it is working perfectly now. I hope you can solve these problems in the new versions.

**Comment by yao-tx** [comment]
Hi all,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336) or from [GitHub Latest Release](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/latest). 

We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow one of the following:
* Quick installation guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart)
* Detailed step-by-step guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
