### ISSUE TITLE
Provide support for vqmod

### ISSUE THREAD

**Issue by shue249** [facebookincubator/Facebook-For-OpenCart#41]
From OpenCart support ticket ID 183633:

Hi, well, I finally installed this using extension installer. I have tried so many times. Each time by restoring my whole site to try different methods. With or without 775 permission.
I tried with default files, I tried by modifying the admin folder, etc.

I get this error: 
Warning: require_once(/home/cpaneluser/public_html/subdomain/admin/../admin/controller/extension/facebookproducttrait.php): failed to open stream: No such file or directory in /home/cpaneluser/public_html/subdomain/vqmod/vqcache/vq2-admin_controller_extension_facebookproduct.php on line 8

Can you please create a normal vQmod version? So many people use vQmod and this Ocmod is not working well for me.

I want to be able to install this for me and my clients in one shot. Meaning, through my server, I can log in via SSH and push the files to everyone right away. Using Ocmod installation method is time consuming as I have to log in to each account, and then go to each one's database to do this.
Either way, the installation method did not work :(.

**Comment by RamseyKal** [comment]
Hi, I am wondering if there has been any progress for creating a vQmod module? I'm interested in this. Thanks!

**Comment by shue249** [comment]
@RamseyKal thank you again for checking back with us and your continued interest and support for the plugin.
 
The support for vqmod is still on our roadmap. We were not able to prioritize this feature yet as we have been fixing and addressing other issues reported by other users. We want to ensure the best experience for you and other users when the support for vqmod is ready, so pls do bear with us while we iron out the issues. You can find our release notes here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/RELEASE
 
We will update you soonest when the vqmod support is ready.

**Comment by EsmondTan** [comment]
With the latest release for this extension, we have upgraded it to use the Events system. This reduces compatibility issues with custom themes. As such, vQmod will not be supported since the Events system is being used instead.
