### ISSUE TITLE
Special Sales Price is not displaying in Facebook Catalog Manager - Products

### ISSUE THREAD

**Issue by SaneepGeorge** [facebookincubator/Facebook-For-OpenCart#413]
Please help to fix to display the Special Sales Price of the products in my FB Catalog Manager, the products are synced from my site.. When I checked the Sales Price & Date Range field values, the details are available but not displaying. Please find the attached screenshots.

www.DealsForBrands.in
Catalogue ID: 1424429091081660

![image](https://user-images.githubusercontent.com/36241690/83824558-e81b9780-a6e7-11ea-9c86-77cfccb37675.png)
![FBCatalogManager-SpecialSalesPrice Issue 05062020](https://user-images.githubusercontent.com/36241690/83824630-17ca9f80-a6e8-11ea-89c1-eebeb4000f42.png)

**Comment by dtying** [comment]
Hi @SaneepGeorge , I can see that your Facebook Page Shop displayed the sales price correctly. This shouldn't be an issue.
https://www.facebook.com/commerce/products/2072355722889469/ 
![Screen Shot 2020-06-06 at 12 48 25 PM](https://user-images.githubusercontent.com/21333308/83936215-1b4b4d00-a7f4-11ea-91cb-e89ad3270206.png)

**Comment by PaulBogdanCom** [comment]
I have the same problem, eshop is agrotech.ro and we have products on sale but does not take or show them

**Comment by dtying** [comment]
@PaulBogdanCom , Hi could you share a screenshot to show?

**Comment by yao-tx** [comment]
Hi @SaneepGeorge @PaulBogdanCom 

The older versions of the FBE plugin (version 3.1.2 and below) has a known issue with the pulling of special price from OpenCart products. The latest version of the FBE plugin (version 4.0.0 and above) has fixed up this issue and pulls the special price just like how OpenCart does it. It will only pull active special prices for the default customer group, according to priority.

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336) or from [GitHub Latest Release](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/latest). 

We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow one of the following:
* Quick installation guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart)
* Detailed step-by-step guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
