### ISSUE TITLE
Facebook shop all products show "out of stock"

### ISSUE THREAD

**Issue by azonicdh2000** [facebookincubator/Facebook-For-OpenCart#414]
hello. installed the facebook extension and on my facebook page shop all the products are showing out of stock but in the catalog manager its showing In Stock, Can you help me with this?

**Comment by dtying** [comment]
Hi @azonicdh2000 , could you share with us your web store url, as well as the Facebook Shop?

**Comment by azonicdh2000** [comment]
https://www.facebook.com/pg/davaoarts/shop/?ref=page_internal

**Comment by atiteccr** [comment]
the same happens to me

**Comment by azonicdh2000** [comment]
@atiteccr Hi. I made another Catalog and a new Facebook Shop and everything is working fine now.
Maybe you can try creating a new Catalog, just a thought.
