### ISSUE TITLE
The cookie bar is displayed continuously

### ISSUE THREAD

**Issue by mrozsmann** [facebookincubator/Facebook-For-OpenCart#415]
Hi!

I installed the newest Facebook for OpenCart extension to my page (rozsmanncukraszda.hu) and if I accept the cookies and then click on a product then it apperears again and so on. 

My OpenCart version is 2.1.0.2.

How can I solve this problem or disable the cookie bar totally? 

Thanks.

**Comment by shue249** [comment]
@mrozsmann You can disable the cookie bar, the instructions are here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#cookie-bar-on-the-webstore

We will be closing out this ticket, feel free to reach to us if you have further questions.
