### ISSUE TITLE
admin com erro 500 apos instalar extenção

### ISSUE THREAD

**Issue by edersonserviopencart** [facebookincubator/Facebook-For-OpenCart#416]
instalei uma estençao do pixel de facebook no site agora não entra mais no admin do site, da erro 500 o site esta funcionando mas na hora de fechar o pedido da essa mensagem: Warning: require_once(/home/consor2/public_html/catalog/../admin/controller/extension/facebookproduct.php): failed to open stream: No such file or directory in /home3/consor2/public_html/system/library/facebookcommonutils.php on line 286

**Comment by edersonserviopencart** [comment]
Aviso: require_once (/ home / consor2 / public_html / catalog /../ admin / controller / extension / facebookproducttrait.php): falha ao abrir o fluxo: esse arquivo ou diretório não existe em / home3 / consor2 / public_html / escservi / controller / extension /facebookproduct.php na linha 8

**Comment by edersonserviopencart** [comment]
consegui resolver ronomeando dos codigos admin para escservi que é a minha pagina admin do site renomeada, mas a extenção do facebook não funcionou,  You have yet to setup Facebook Ads Extension. Please click on Facebook Ads Extension and Get Started. qunado clico na aba do facebook dentro do admin a pagina dsai fora

**Comment by shue249** [comment]
@edersonserviopencart Can you share with us a screenshot of the error that you are seeing.

**Comment by yao-tx** [comment]
Hi @edersonserviopencart 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
