### ISSUE TITLE
The currency and value parameters are not set in the Complete Registration event

### ISSUE THREAD

**Issue by makyha** [facebookincubator/Facebook-For-OpenCart#417]
Good afternoon. We are having problems integrating with Facebook. Catalog is not enabled, and one or more registration events that you have completed do not have the Value and Currency parameters. 
![Снимок экрана 2020-06-08 в 18 29 25](https://user-images.githubusercontent.com/66633335/84049888-a58edf00-a9b5-11ea-8abb-179b81036ca7.png)
![Снимок экрана 2020-06-08 в 18 31 31](https://user-images.githubusercontent.com/66633335/84050132-03232b80-a9b6-11ea-96b8-f970ec6442a6.png)
![Снимок экрана 2020-06-08 в 18 32 55](https://user-images.githubusercontent.com/66633335/84050219-1b934600-a9b6-11ea-955e-b1abdb5a7799.png)
Everything is correct in OpenCart
![Снимок экрана 2020-06-08 в 18 38 04](https://user-images.githubusercontent.com/66633335/84050756-d6234880-a9b6-11ea-8348-6969156baa96.png)
![Снимок экрана 2020-06-08 в 18 37 47](https://user-images.githubusercontent.com/66633335/84050778-dde2ed00-a9b6-11ea-8f9b-02c364ff26d4.png)
![Снимок экрана 2020-06-08 в 18 37 40](https://user-images.githubusercontent.com/66633335/84050789-e0dddd80-a9b6-11ea-933b-d2db81ca9ae8.png)

So how could anything be the matter?

**Comment by shue249** [comment]
@makyha You can ignore this warning message on Currency and Value for CompleteRegistration. From your screenshots, seems the pixel events are coming in correctly. So things should be good.

We will be closing out this ticket. Feel free to reach to us if you have further questions.
