### ISSUE TITLE
 Cannot redeclare ModelCheckoutOrder::checkMapTables

### ISSUE THREAD

**Issue by lennt92** [facebookincubator/Facebook-For-OpenCart#42]
Hi! This part of code cause an error when I try to confirm order. If comment it, all work normal. OC 2.3.0.2

```
<!--<file path="catalog/model/checkout/order.php">
<operation>
<search><![CDATA[class ModelCheckoutOrder extends Model]]></search>
<add position="after"><![CDATA[
public function getOrderProductIds($order_id) {
$sql = "SELECT product_id FROM " . DB_PREFIX . "order_product " .
"WHERE order_id = '" . (int)$order_id . "'";
return $this->db->query($sql)->rows;
}
]]></add>
</operation>
```

> PHP Fatal error: Cannot redeclare ModelCheckoutOrder::checkMapTables() in /.../public_html/system/storage/modification/catalog/model/checkout/order.php on line 233

**Comment by shue249** [comment]
@lennt92 Thanks for following up on this!

Are there other 3rd party plugins installed on your opencart? 

For full context, I am going into the technicality of how opencart plugin works. 

For the error mentioned, the "checkMapTables()" method is found multiple times on the order.php file. Unfortunately, this "checkMapTables() is not introduced by our plugin. As you have highlighted on your message, here are our codes on the install.xml to add in a new method https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/install.xml#L347-L359. 

What OpenCart ocmod system does here is to read through the install.xml. For each operation declared to make the changes determined. In the case, it will go to the catalog/model/checkout/order.php file, add in our new method getOrderProductIds($order_id) below the line "class ModelCheckoutOrder extends Model". After which a copy of the order.php file will be generated with those changes and be in the system/storage/modifications folder.

My suspicion is that there is another 3rd party plugin, which is also modifying the order.php, causes the error mentioned (the checkMapTables() is included twice).

My suggestion is to identify which plugin may be generating this checkMapTables() and to check how is it inserting the method checkMapTables() into the order.php file.
![image](https://user-images.githubusercontent.com/11957585/46338322-719cdb80-c662-11e8-8fe5-c9f743bd5845.png)

**Comment by shue249** [comment]
We will be closing out this ticket as we checked that the code is not from our plugin. But pls feel free to reopen the ticket, if there's any further follow up needed.
