### ISSUE TITLE
catalog pictures bad quality

### ISSUE THREAD

**Issue by vadymand** [facebookincubator/Facebook-For-OpenCart#420]
Hello
we have a problem with the quality of pictures in the catalog - it is much lower than the pictures on the site. what could be the problem and how to solve it?

**Comment by dtying** [comment]
Hi @vadymand , the feed image_url is pointing to the exact same location of your product image, you can verify that from your Catalog Manager. Are you saying that the image you see in Page Shop is much lower than the site?

**Comment by vadymand** [comment]
https://brand-centr.com/men/futbolka-lacoste-kt3237
<img width="1024" alt="Снимок экрана 2020-06-16 в 15 21 52" src="https://user-images.githubusercontent.com/66863128/84773543-36347300-afe5-11ea-8fb4-a4a73f7f5a61.png">
its 1500x1500 on my site, but 600x600 in fbcatalog the same item

**Comment by yao-tx** [comment]
Hi @vadymand 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
