### ISSUE TITLE
This may be because of a technical error that we're working to get fixed. Try reloading this page.

### ISSUE THREAD

**Issue by amOn101** [facebookincubator/Facebook-For-OpenCart#422]
I have two mistakes at once. The first in the admin panel shows an error
![Screenshot_20200614-193205](https://user-images.githubusercontent.com/64661787/84598903-bbe5e080-ae76-11ea-8cf1-95c8ba7a9446.png)
Second if I'm trying to finish setting up
![Screenshot_20200614-193148](https://user-images.githubusercontent.com/64661787/84598930-e768cb00-ae76-11ea-801a-1f8617fe05cb.png)
site www.megamall.in.ua 
Log file: [Megamall_2020-06-14_16-41-50_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/4776859/Megamall_2020-06-14_16-41-50_facebook_ads_extension.log)
help fix problems

**Comment by yao-tx** [comment]
Hi @amOn101 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336) or from [GitHub Latest Release](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/latest). 

We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
