### ISSUE TITLE
Can't access the Create Collection button in the FB-store 

### ISSUE THREAD

**Issue by nab0306** [facebookincubator/Facebook-For-OpenCart#423]
Hi, please help me with the problem. 
When i create a FB-catalog manually on a page in the store section i have access to Create Collection button. But when i create a catalog through the plugin Facebook-For-OpenCart and bind it to the store, there is no button i see to create a collection. Products appeare in the store, but there is no way to manage them. 
Can I somehow access the button in this store using this catalog?
Sorry for my English) 
There is no button:
![image](https://user-images.githubusercontent.com/66925441/84606435-d936a100-aeae-11ea-8521-4fb91e067e1b.png)
![image](https://user-images.githubusercontent.com/66925441/84606456-0be09980-aeaf-11ea-98c8-9a08519789e5.png)

**Comment by dtying** [comment]
Hi @nab0306 , I think our feed doesn't support Collection feature at this moment. Hopefully it'll be available in the next half.

**Comment by nab0306** [comment]
I did not understand you) 
do you think or do you know? 
I have the Facebook Ads Extension 2.0.2 plugin installed.
Perhaps in the new version of the plugin Version v3.0.1 there is this possibility?

**Comment by dtying** [comment]
No, this feature is not available.
