### ISSUE TITLE
Help for fix errors in catalog

### ISSUE THREAD

**Issue by nab0306** [facebookincubator/Facebook-For-OpenCart#425]
Please help me!
The catalog was created through a plugin Facebook-For-OpenCart
there are 2 errors in the catalog 
There are no errors in the pixel.
There are no errors per pixel helper.

how to fix these errors ?

Website https://missdm.com/
Facebook page @ MissDM.ua

![image](https://user-images.githubusercontent.com/66925441/84606903-54e61d00-aeb2-11ea-93f1-7f42e2d884f2.png)
![image](https://user-images.githubusercontent.com/66925441/84606909-59aad100-aeb2-11ea-91a0-21bdd16a378b.png)

**Comment by dtying** [comment]
Hi @nab0306 , the screenshots were too blurred to read, could you upload a higher resolution one?

Also, I've checked in your Catalog Manager and didn't find the error as above. Is it still happening now?

**Comment by nab0306** [comment]
Hi, sorry!
I see these errors now in the directory Catalog Manager .
There was another error last night.
I did not do anything.
I don’t understand why the errors are different?

![FireShot Capture 001 - (84) Catalog Manager - business facebook com](https://user-images.githubusercontent.com/66925441/84768248-9a9f0480-afdc-11ea-85bc-a9171e4a3c24.png)
