### ISSUE TITLE
Facebook Extension Problem

### ISSUE THREAD

**Issue by icop** [facebookincubator/Facebook-For-OpenCart#426]
I have a problem with the instal of the Module. i got the following error

There are problems with the installation of the Facebook Ads Extension.
We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders.

I've changed the permissions but i still got the same error. Seems like that the problem is that i've changed the admin folder name. Do you have any solution for this or should i change it back?

**Comment by dtying** [comment]
Hi @icop , here're the files which we uploaded to the [admin folder](https://github.com/facebookincubator/Facebook-For-OpenCart/tree/master/upload/admin), you can try to upload the files to the renamed admin folder directly.

However, inside this method we're also checking whether the [required file existed](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookadsextension.php#L519-L538), you may need to modify the admin path too.

**Comment by icop** [comment]
I have already uploaded the files but i fixed the required file path and everything is ok. Thanks for your time.
