### ISSUE TITLE
2 errors in the catalog

### ISSUE THREAD

**Issue by nab0306** [facebookincubator/Facebook-For-OpenCart#427]
Please help me!
The catalog was created through a plugin Facebook-For-OpenCart
there are 2 errors in the catalog
There are no errors in the pixel.
There are no errors per pixel helper.

how to fix these errors ?

Website https://missdm.com/
Facebook page @ MissDM.ua

![FireShot Capture 001 - (84) Catalog Manager - business facebook com](https://user-images.githubusercontent.com/66925441/84829294-2b530000-b030-11ea-862a-4df71ebde60e.png)

**Comment by dtying** [comment]
Hi @nab0306 , you can install Facebook Pixel Helper to troubleshoot pixel on your own.
https://developers.facebook.com/docs/facebook-pixel/support/pixel-helper

![Screen Shot 2020-07-27 at 12 02 40 PM](https://user-images.githubusercontent.com/21333308/88502505-37ec5000-d001-11ea-9056-6faf21bd2f8a.png)

**Comment by yao-tx** [comment]
Hi @nab0306 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
