### ISSUE TITLE
Business Manager 

### ISSUE THREAD

**Issue by TyrannosaurHex** [facebookincubator/Facebook-For-OpenCart#428]
Is it not possible to use this extension without Business Manager? It seems overkill for a small business like ours, where we manage ads etc. in-house.

Additionally, even after spending countless hours trying to connect the Page to Business Manager I have made little progress. While trying to link my page from within the extension, I am getting the following error:

"You don't have permission to edit these settings. Reach out to the admin of ''XXXXX.' Business Manager to to gain access."

Once I go into the business manager, and Add the Page/Request access to page, I get"Your request for access is pending" message in Business Manager, but where has that request for access gone? I have checked Page Roles under FB Page settings & under my Personal FB page. I am the page owner, so the request for access should come to me - which is nowhere.

Please share how do I go back to the previous simpler system of syncing the store and running ads without the Business Manager which is of no use to a small business owner like me.

Regards

**Comment by dtying** [comment]
Hi @TyrannosaurHex , thanks for sharing your experiences and true feelings with us! 
As Business Manager is our recommended way to setup and manage the assets in the future, it's really meant to help our users take best use of the tools. I do see many users have raised confusions and questions related to BM, especially for those who are originally from v1.
I'll share the feedback with team, and see how we can improve the UI flow.

**Comment by dtying** [comment]
Hi @TyrannosaurHex , could you share your webstore url? so that we can troubleshoot your case.

**Comment by TyrannosaurHex** [comment]
hi @dtying, I've tried to deep dive into the cause of this problem, and it is an issue with how Facebook Business Manager works rather that the Opencart extension itself. 

Having said that there should still be an option to not use Business Manager; and after using it, I clearly see that it is of no use to me as a small business owner, but just adds a layer of complexity without any value-addition. If Facebook is interested in ad revenue from someone like me, using Business manager is one way of not how to do it. And I am fairly tech-savvy, Imagine a non-techie trying to use it. 

Regards

**Comment by dtying** [comment]
Hi @TyrannosaurHex, we completely understand the addition of complexity. A business manager is required to properly deal with privacy and security. Could you connect with me at ads_extension_opencart to help us figure out what is going on? You may provide your page_id, business_id for us to better investigate.
