### ISSUE TITLE
All products do not load

### ISSUE THREAD

**Issue by zaur-pixel** [facebookincubator/Facebook-For-OpenCart#430]
Hello, I apologize in advance for my English. The text is made with the help of Google translator.

My problem:
When integrating facebook with my website, not all products are uploaded to the facebook store.
The number of products on the site is 2088, the number of products in the facebook catalog is 255.

Site:  https://xozyayushka.az/
Plugin:  Facebook Ads Extension 2.1.3. (The new version of the plugin does not work. Mistake (object object)
Your Facebook Store ID: 267718277833859
Catalog ID:  580256536251472

**Comment by dtying** [comment]
Hi @zaur-pixel , just to double check - are you using version 2.1.13 rather than 2.1.3 ?

**Comment by zaur-pixel** [comment]
> Hi @zaur-pixel , just to double check - are you using version 2.1.13 rather than 2.1.3 ?

Plugin Version: 2.1.3.

**Comment by zaur-pixel** [comment]
> Hi @zaur-pixel , just to double check - are you using version 2.1.13 rather than 2.1.3 ?

I found an interesting fact. When I go into the goods - in the product card - I DO NOT CHANGE ANYTHING, and press save - the product appears in the facebook catalog

**Comment by dtying** [comment]
Hi @zaur-pixel , 2.1.3 is quite an old version, maybe you can upgrade to 2.1.13

**Comment by zaur-pixel** [comment]
> Hi @zaur-pixel , 2.1.3 is quite an old version, maybe you can upgrade to 2.1.13

How i can update? Pls give me instruction and link

**Comment by yao-tx** [comment]
Hi @zaur-pixel 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
