### ISSUE TITLE
Problems activating Facebook extension in Open Cart 2.x

### ISSUE THREAD

**Issue by rubensyanes** [facebookincubator/Facebook-For-OpenCart#431]
Web Site: tasha.com.ar
Country: Argentina
IP: 190.18.1.121
Extension Opencart Version: 2.3.0.2
Opencart Version: 2.3.0.2
Both OC version Match: Yes

I have been able to upload the extension, but when I activate it, the page crash!
There is no error message, just the front end goes white, until the extension is deactivated again.

any hints?

**Comment by shue249** [comment]
@rubensyanes Are you able to access the webserver error log? The log file may provide some hints on the problem.

**Comment by yao-tx** [comment]
Hi @rubensyanes 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
