### ISSUE TITLE
All facebook shop products is Unavailable

### ISSUE THREAD

**Issue by exitsport** [facebookincubator/Facebook-For-OpenCart#432]
Hi,

We Fetch Now all products but in Facebook shop is all products Unavailable, but in our web all products in the stock
Plugin Version: 2.2.1

**Comment by exitsport** [comment]
![image](https://user-images.githubusercontent.com/14319188/86231980-0320e080-bb9c-11ea-83de-c4f998254b01.png)

**Comment by shue249** [comment]
Can you share with us your facebook page?

**Comment by exitsport** [comment]
exitsport.eu

**Comment by yao-tx** [comment]
Hi @exitsport 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
