### ISSUE TITLE
Feed update errors (after disabling a product listing on the OC catalog)

### ISSUE THREAD

**Issue by djlaserman** [facebookincubator/Facebook-For-OpenCart#433]
**I always have the usual fb extension error:** We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

But the plugin somehow works and syncs to facebook, it did however try to change my email address from the one set by business manager to my github email address, so I canceled the setup and restarted it, and it worked and connected to fb but in doing so disabled the default fb business manager from being the one which manages the page.

So since the feed worked and synced all my 1.3k products, I didn't mind the quirks. Today I disabled one product using the OC catalog manager and immediately saw a sync error displayed above the page. So I'm yet to check if the feed which seemed to fail and work afterwards (without any fixing really) actually removed the disabled product or not. I downloaded the log file and am going to paste it below.

I couldn't find the "Advanced Settings" in order to "delete the settings and re-setup the plugin" as laid out in the log file. So I don't know maybe I didn't look hard enough but under Settings, from clicking on Manage Settings it's not there; It connects to facebook and behaves sorta normal when I click that. 

Find my log attached. Thanks
[TekNerds IT Shop_2020-07-01_09-55-53_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/4857206/TekNerds.IT.Shop_2020-07-01_09-55-53_facebook_ads_extension.log)

**Comment by yao-tx** [comment]
Hi @djlaserman 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
