### ISSUE TITLE
Stock Availability Information Not Carried Across To Facebook Correctly

### ISSUE THREAD

**Issue by djlaserman** [facebookincubator/Facebook-For-OpenCart#434]
The plugin shows incorrect information on facebook, clearly the quantity of the items that are at zero (stock levels in OC) show on facebook as available. Therefore customers can attempt to purchase them only to find when they reach the store that those items are not available to buy because they are not in stock.

This should be rectified.

![fbe stock 03](https://user-images.githubusercontent.com/41134053/86248800-aa0e7800-bbae-11ea-94c5-ba66543c34d1.png)
![fbe stock 02](https://user-images.githubusercontent.com/41134053/86248806-ab3fa500-bbae-11ea-8adc-e065c1632cf4.png)
![fbe stock 01](https://user-images.githubusercontent.com/41134053/86248811-ac70d200-bbae-11ea-9b97-bd8144965116.png)
![fbe stock 04](https://user-images.githubusercontent.com/41134053/86248813-ad096880-bbae-11ea-9c26-aebd449d928b.png)

**Comment by exitsport** [comment]
We have a same problem, but the other way around: In OC products in stock, but in Facebook all products is Unavailable

**Comment by shue249** [comment]
Can you share with us your FB page?

**Comment by djlaserman** [comment]
My facebook page is: https://facebook.com/teknerds

**Comment by djlaserman** [comment]
> Can you share with us your FB page?

My facebook page is: https://facebook.com/teknerds

**Comment by djlaserman** [comment]
> Can you share with us your FB page?

My facebook page is: https://facebook.com/teknerds

**Comment by djlaserman** [comment]
Looks like there's not much action about this issue. Can someone detail which source code file would have the logic for counting products or actually determining availability? I can debug this myself if I know where to begin

**Comment by yao-tx** [comment]
Hi @djlaserman 

For the older versions of the FBE plugin (version 3.1.2 and below), you need to look at the `getAvailability()` function in `facebookproductformatter.php` located in `system/library` to modify the logic of how the availability of your products are set when exporting to Facebook Catalog.

That being said, we have a new version of the Facebook Business Extension plugin for OpenCart - Version 4.0.0 and above.  We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you need to modify the logic of the products availability for the latest FBE plugin (v4 and above), you need to look into the `getAvailability()` function in `facebook_business.php` located in `catalog/controller/extension/module` for OpenCart v2.3 to v3 and above or `catalog/controller/module` for OpenCart v2.0.x to v2.2.x. 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336).

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
