### ISSUE TITLE
Unable to connect to Facebook Business Account (OC 2.3.0.2)

### ISSUE THREAD

**Issue by darrist** [facebookincubator/Facebook-For-OpenCart#435]
I have recently installed Facebook Opencart OCMod (Latest for OC 2.3.0.2). When I am authorizing my Facebook business account (the OAuth pop-up).

Procedure:
1. I click "Get Started" for the OAuth pop-up to opens up.
2. I sign in with Facebook credentials.
3. I was presented "Connect Your Store to Facebook" info and permission page, I continued.
4. I was presented to choose from my business accounts, I choose any one.
5. When I click continue here, I will be brought back to "Connect Your Store to Facebook" page.

Things to note is, there are no issue displayed in Chrome console. I have tried different device and multiple browsers including Chrome, Chromium, Firefox Nightly, Safari.

**Comment by bitrixlviv** [comment]
me too

**Comment by dtying** [comment]
Hi @darrist , it could be due to a product bug which we have fixed recently.
Can you download latest 3.1.0 release and try again?
