### ISSUE TITLE
connect.facebook.net / ../en_US/fbevents.js

### ISSUE THREAD

**Issue by mattalt** [facebookincubator/Facebook-For-OpenCart#437]
After installaing the plug in I realized that the speed of the site is penalized by Google pagespeed as the transfer size of https://connect.facebook.net/signals/config/xxxxxxxxxxxxx?v=2.9.21&r=stable is very large: 133,2 kb

Is it possible not to load at the start of the page or if not how can I uninstall it?

**Comment by dtying** [comment]
It's the base code used to initialize Facebook Pixel. 
https://developers.facebook.com/docs/facebook-pixel/implementation/#base-code
