### ISSUE TITLE
not linking to my facebook account

### ISSUE THREAD

**Issue by ramimeraabi** [facebookincubator/Facebook-For-OpenCart#439]
hello i have this error when i try to connect to facebook

Oops, something went wrong.
This may be because of a technical error that we're working to get fixed. Try reloading this page.

2020-07-14 12:15:53 - Facebook Ads Extension version = 3.0.1
2020-07-14 12:15:53 - OpenCart version = 2.0.3.1
2020-07-14 12:15:53 - PHP version = 7.3.19
2020-07-14 12:15:53 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-07-14 12:15:53 - Pixel ID = true
2020-07-14 12:15:53 - Pixel use PII = true
2020-07-14 12:15:53 - Page ID = true
2020-07-14 12:15:53 - System User Access Token = false
2020-07-14 12:15:53 - Messenger plugin = true

**Comment by stavtime** [comment]
Same problem. Have you solved it?

**Comment by dtying** [comment]
Hi @ramimeraabi, can you provide your webstore url?

**Comment by ramimeraabi** [comment]
Www.waffershop.com


Sent from my iPhone
-- 

 

Regards,

 

Rami Meraabi | CEO

SMARTA Solutions | www.smarta.ws

KSA - Lebanon: +961 6 439999 | Mobile: +961 76 000198 | Email: rami.meraabi@smarta.ws

 

This e-mail may contain confidential, proprietary or legally privileged information.  It should not be used by anyone who is not the original intended recipient. 
If you have received this message by mistake, please delete it immediately and notify the sender.

**Comment by yao-tx** [comment]
Hi @ramimeraabi 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
