### ISSUE TITLE
Error  UTF-8

### ISSUE THREAD

**Issue by reginamor** [facebookincubator/Facebook-For-OpenCart#44]
Hi! i have a lot of errors that says this
/system/library/facebookcommonutils.php on line 127Warning: html_entity_decode(): charset `UTF-8;' not supported, assuming utf-8 in 

![captura de pantalla 2018-10-05 a las 10 59 24](https://user-images.githubusercontent.com/27919921/46527782-6b8d4180-c892-11e8-8556-6a4cf8e2a5e3.png)

how can i fix it?

**Comment by shue249** [comment]
@reginamor Thanks for the feedback!

A search on google returns these top matches. I believe it is a wrong configuration on the php.ini file. Can you locate that file and do a search to see what is the value of the default-charset in your php.ini file.

https://stackoverflow.com/questions/49251687/php-warning-html-entity-decode-charset-utf-8-not-supported-assuming-utf

For your reference, this is our php.ini on our test servers.
![image](https://user-images.githubusercontent.com/11957585/46577767-b89f1e00-ca20-11e8-9abc-f06a9fe08bc9.png)

**Comment by shue249** [comment]
@reginamor We will be closing this ticket as it is a settings change on the apache server
