### ISSUE TITLE
Special price or sale price was wrong.

### ISSUE THREAD

**Issue by dev-mamun** [facebookincubator/Facebook-For-OpenCart#440]
feed does not submit my discounted price to facebook. it submit same price for both price and sale price. for this discount does not show on facebook shop.
my site https://arcbaby.com/

**Comment by yao-tx** [comment]
Hi @dev-mamun 

Please ensure that you have enabled the syncing of special price as discount option. There is also a known issue about the previous versions of the FBE plugin (v3.1.2 and below) where the special price is pulled incorrectly.

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The latest version of the FBE plugin (v4.0.0 and above) has corrected this issue and pulls the special price according to how OpenCart does it. Now, it only pulls active special prices for the default customer group, based on priority.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
