### ISSUE TITLE
Few special prices depending on user groups

### ISSUE THREAD

**Issue by Aukvito** [facebookincubator/Facebook-For-OpenCart#441]
Hi there,

Special prices on my site differ depending on the user group: wholesale, drop-shipping and retail.
I guess by default your FB_extension takes the cheepest one (wholesale) for feed update. And there is a problem for me: I don`t need to make wholesale prices public and want the extension to take the price for retail.
Special price for retail is always the highest special price. So I hope the problem can be solved changing database query:
![image](https://user-images.githubusercontent.com/52528405/87939453-c5c7b880-caa0-11ea-8a8d-5f7644bcf4bc.png)

Can you help me to solve this problem?

**Comment by shue249** [comment]
@Aukvito Currently we do not support user groups as this feature is not available on Facebook side. We are using the 1st special price which is applicable now. 

However, we are unable to make custom changes. If you have developer resources, here is the code pointer for you to make the changes - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L235

We will be closing off this ticket.
