### ISSUE TITLE
Error: An error occurred while fetching FBE Install config

### ISSUE THREAD

**Issue by Miroslav020788** [facebookincubator/Facebook-For-OpenCart#442]
After comleted all steps? i get this error.
How can I fix it?
![image](https://user-images.githubusercontent.com/24765320/88156019-853b7c80-cc11-11ea-8674-195f6c6a2c71.png)

**Comment by dtying** [comment]
Hi @Miroslav020788 , can you provide your webstore url?

**Comment by Miroslav020788** [comment]
Corrector.com.ua

**Comment by Miroslav020788** [comment]
@dtying corrector.com.ua

**Comment by Miroslav020788** [comment]
@dtying, or  anyone else ...)))  what's wrong? How can i fix that?

**Comment by asamaaa** [comment]
Hi, I am facing the same problem, what is the solution

**Comment by Miroslav020788** [comment]
Have no idea. Anyone don`t give me an answer :(

**Comment by Miroslav020788** [comment]
seems to be the trouble is settled

**Comment by baron-kg** [comment]
@Miroslav020788 Hi. I'm having the same problem with the extension. Could you please share what you did to solve it? Thanks in advance.

**Comment by carlopezs** [comment]
x2

**Comment by merlynv** [comment]
Hi. I have the same problem. Maybe because our countries are blocked by Facebook?
