### ISSUE TITLE
Cannot connect it with existing ad account.

### ISSUE THREAD

**Issue by cepcemuh** [facebookincubator/Facebook-For-OpenCart#443]
Associated ad account with the Business Manager, Page, and Pixel is not shown. It gives me only to CREATE new ad account but I do not wanna do it. Even if I try to create new one - it gives me an error.

**Comment by yao-tx** [comment]
Hi @cepcemuh 

Have you ensured that you are logged into the correct Facebook account?

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
