### ISSUE TITLE
Facebook for Opencart 3.1.0 linking error

### ISSUE THREAD

**Issue by SonataR** [facebookincubator/Facebook-For-OpenCart#444]
Hi,

It is imposible to link Opencart with FB. Always getting an error: Something went wrong. This may be because of a technical error that we're working to get fixed. Try reloading this page

How to fix it?

**Comment by dtying** [comment]
Hi @SonataR , can you provide your webstore url?

**Comment by SonataR** [comment]
Hi,

www.voverytesbutikelis.lt

**Comment by ofrost** [comment]
I have the same situation. How to complete integration?

**Comment by lipmycar** [comment]
I am experiencing the same issue. I am not able to complete the integration . Please help us with this

**Comment by yao-tx** [comment]
Hi @SonataR @ofrost @lipmycar 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
