### ISSUE TITLE
New upadate crashing website on checkout

### ISSUE THREAD

**Issue by nichinu** [facebookincubator/Facebook-For-OpenCart#445]
Hey, I just installed the new update 3.1.0 and it just messed up mys business.
The website works fine but just on clinking checkout it crashes with 500 server error. I uninstalled the module from the admin and cleared modification but the FBE was still there.
So i jhad to uninstall the module's settings as well.
Please look into it and also provide me the earlier version 3.0.1.

Thanks

**Comment by dev-mamun** [comment]
same problem here, its show 
"PHP message: PHP Catchable fatal error:  Argument 1 passed to FacebookAds\CrashReporter::buildParamsFromException() must be an instance of Throwable, instance of ErrorException given, 
called in /home/ubuntu/arcbaby/system/library/vendor/facebook/php-business-sdk/src/FacebookAds/CrashReporter.php on line 146 and defined in 
/home/ubuntu/arcbaby/system/library/vendor/facebook/php-business-sdk/src/FacebookAds/CrashReporter.php on line 167" while reading response header from upstream, 
client: 103.25.120.134, server: arcbaby.com, request: "GET /index.php?route=checkout/cart HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php5.6-fpm.sock:",
 host: "arcbaby.com", referrer: "https://arcbaby.com/fashion?product_id=157"

**Comment by samanoudi** [comment]
Same issue

**Comment by blackhacker3** [comment]
same problem  how to fix it

**Comment by dtying** [comment]
Hi, as Facebook Graph API doesn't support HTTP2, it has caused issue in your webpage (which is on HTTP2).
https://developers.facebook.com/docs/graph-api/using-graph-api/

You may downgrade to v3.0.1 to continue use. https://github.com/facebookincubator/Facebook-For-OpenCart/tags
