### ISSUE TITLE
An error occurred while processing this request. Please try again later.

### ISSUE THREAD

**Issue by zlioo** [facebookincubator/Facebook-For-OpenCart#446]
When we create manage account by extend.we get error as title

**Comment by dtying** [comment]
Hi @zlioo , can you provide your webstore url and a screenshot to illustrate how to reproduce the error?

**Comment by dahmsh** [comment]
SyntaxError: JSON Parse error: Unrecognized token '<'
parsererror
<br />
<b>Fatal error</b>: Uncaught Error: Class 'FacebookAds\Object\ServerSide\AdsPixelSettings' not found in /home/seejad/public_html/vqmod/vqcache/vq2-system_library_facebookcommonutils.php:446
Stack trace:
#0 /home/seejad/public_html/vqmod/vqcache/vq2-admin_controller_extension_facebookadsextension.php(422): FacebookCommonUtils-&gt;getPixelAAMSetting('243710134320989...')
#1 /home/seejad/public_html/vqmod/vqcache/vq2-system_storage_kwetiqjeitqjt_modification_system_engine_action.php(79): ControllerExtensionFacebookAdsExtension-&gt;updateSettings()
#2 /home/seejad/public_html/admin/controller/startup/router.php(26): Action-&gt;execute(Object(Registry), Array)
#3 /home/seejad/public_html/vqmod/vqcache/vq2-system_storage_kwetiqjeitqjt_modification_system_engine_action.php(79): ControllerStartupRouter-&gt;index()
#4 /home/seejad/public_html/vqmod/vqcache/vq2-system_storage_kwetiqjeitqjt_modification_system_engine_router.php(171): Action-&gt;execute(Object(Registry))
#5 /home/seejad/public_html/vqmod/vqcache/vq2-system_storage_kwetiqjeitqjt_modificati in <b>/home/seejad/public_html/vqmod/vqcache/vq2-system_library_facebookcommonutils.php</b> on line <b>446</b><br />

https://prnt.sc/unezfr
https://prnt.sc/unf03g
https://prnt.sc/unf09d

**Comment by vincent714** [comment]
Any Updates?

**Comment by dahmsh** [comment]
opencart_Arabic_V3033

**Comment by yao-tx** [comment]
Hi @dahmsh 

This could be an issue where the Facebook Business PHP SDK files are missing.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
