### ISSUE TITLE
Add custom text in facebook catalog upload feed

### ISSUE THREAD

**Issue by rhinsu** [facebookincubator/Facebook-For-OpenCart#447]
Hello there!!

I would like to add custom text like manufacturer name on the product name feed so that the shop displays that custom text. How do i do that.

**Comment by dtying** [comment]
Hi @rhinsu , in the current feed file, 'brand' field is populated by manufacturer.
https://developers.facebook.com/docs/marketing-api/catalog/reference#da-commerce

**Comment by rhinsu** [comment]
Hi @dtying thanks for your reply.
My products currently only have the product name without the manufacturer name and i have a custom code on my opencart displaying the manufacturer name only in the product page. 
Example; name- Galaxy S20; Manufacturer- Samsung
i would like facebook feed to capture name as "Samsung Galaxy S20"

**Comment by rhinsu** [comment]
@dtying any update on a previous support

**Comment by yao-tx** [comment]
Hi @rhinsu 

If you have a custom code that appends the manufacturer name to the end of the product name, you will have to add the same code into the FBE plugin code as well. For the current versions of the FBE plugin (version 3.1.2 and below), you should modify the codes at `system/library/facebookproductformatter.php`, under the `getName()` function.

For the latest version of the FBE plugin (version 4.0.0 and above), you can modify the `getName()` function at:
- For OpenCart 2.0.x to 2.2.x: `catalog/controller/module/facebook_business.php`
- For OpenCart 2.3 to 3.x and above: `catalog/controller/extension/module/facebook_business.php`

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!

**Comment by rhinsu** [comment]
Hi @yao-tx 
Thanks for the update. I have upgraded to version 4, and now i've broke connection to facebook. My feed uploads without title. While i was finishing the facebook linking, i couldn't add shop, and it mentioned "We were unable to set up your Commerce Account due to an issue on our end. Please try again later." Please advise. Thanks

**Comment by yao-tx** [comment]
> Hi @yao-tx
> Thanks for the update. I have upgraded to version 4, and now i've broke connection to facebook. My feed uploads without title. While i was finishing the facebook linking, i couldn't add shop, and it mentioned "We were unable to set up your Commerce Account due to an issue on our end. Please try again later." Please advise. Thanks

Hi @rhinsu 

I believe we've received your support ticket in our help desk (Ticket 18305). We will assist you from there.
