### ISSUE TITLE
error instalación plugin facebook business extension

### ISSUE THREAD

**Issue by cgonzalez-p** [facebookincubator/Facebook-For-OpenCart#448]
instalo siguiendo pasos guía y persiste advertencia de errores que ya verifiqué y todo ok. Por favor ayuda https://canaldeventasdigitalescgp.com/

![pantalla_plugin_facebook_error](https://user-images.githubusercontent.com/54340494/88444089-f41b0000-cde0-11ea-8d46-390881d47d60.PNG)
![error_javascript_no_capturado](https://user-images.githubusercontent.com/54340494/88444096-fed59500-cde0-11ea-85c9-666f48cdbc19.PNG)

**Comment by yao-tx** [comment]
Hi @cgonzalez-p 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
