### ISSUE TITLE
Check out error

### ISSUE THREAD

**Issue by dev-mamun** [facebookincubator/Facebook-For-OpenCart#449]
"PHP message: PHP Catchable fatal error:  Argument 1 passed to FacebookAds\CrashReporter::buildParamsFromException() must be an instance of Throwable, instance of ErrorException given, 
called in /home/ubuntu/arcbaby/system/library/vendor/facebook/php-business-sdk/src/FacebookAds/CrashReporter.php on line 146 and defined in 
/home/ubuntu/arcbaby/system/library/vendor/facebook/php-business-sdk/src/FacebookAds/CrashReporter.php on line 167" while reading response header from upstream, 
client: 103.25.120.134, server: arcbaby.com, request: "GET /index.php?route=checkout/cart HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php5.6-fpm.sock:",
 host: "arcbaby.com", referrer: "https://arcbaby.com/fashion?product_id=157"

**Comment by dtying** [comment]
Hi @dev-mamun , as Facebook Graph API doesn't support HTTP2, it has caused issue in your webpage (which is on HTTP2).
https://developers.facebook.com/docs/graph-api/using-graph-api/

You may downgrade to v3.0.1 to continue use. https://github.com/facebookincubator/Facebook-For-OpenCart/tags
