### ISSUE TITLE
Error after installing Facebook  for OpenCart Extension

### ISSUE THREAD

**Issue by wayday** [facebookincubator/Facebook-For-OpenCart#45]
Please help . 
There is an error after i install the extension
Fatal error: require_once(): Failed opening required '/home/mysite/admin/../admin/controller/extension/facebookproducttrait.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/mysite/admin/controller/extension/facebookproduct.php on line 8 

Already set permission Read and Write .

**Comment by shue249** [comment]
@wayday Thank you for your feedback.

Can you check your server file server to confirm that the file facebookproducttrait.php exists. If not, can you delete away the plugin and re-install again.

![image](https://user-images.githubusercontent.com/11957585/46923896-fdded380-d050-11e8-8642-4b29f74f3355.png)

**Comment by shue249** [comment]
@wayday We will be closing out this ticket, but pls feel free to reopen if you have further questions
