### ISSUE TITLE
"500 - Internal Server Error" on cart page

### ISSUE THREAD

**Issue by hongyiu** [facebookincubator/Facebook-For-OpenCart#451]
**Webstore Url**
https://www.eeconshop.com/

**FBE plugin version**
3.1.0

**OpenCart version**
3.0.3.2

**Describe the bug**
"500 - Internal Server Error" on cart page after upgrade to FBE 3.1.0

**To Reproduce**
go to below link:
https://www.eeconshop.com/index.php?route=checkout/cart
https://www.eeconshop.com/index.php?route=checkout/checkout

**Screenshots**
<img width="859" alt="螢幕截圖 2020-07-30 下午4 30 01" src="https://user-images.githubusercontent.com/49752301/88900711-5d3bc100-d282-11ea-87ff-422996e5ae4b.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 84.0.4147.105

**Additional context**

**Comment by dtying** [comment]
Thanks @hongyiu. Are you able to access your webserver and find the detailed exception from your error log?

**Comment by samanoudi** [comment]
Same issue here. When I disable the extension carts is working fine
https://www.el-wafaa.com/index.php?route=checkout/cart

FBE plugin version
3.1.0
Opencart
Version 3.0.3.2

Apache log at my hosting provider did not receive any error with respect to this problem

**Comment by sefasaid** [comment]
same here 
2020-08-08 14:42:59.043120 [NOTICE] [4041456] [188.119.61.215:33639-Q:20650CA7014B5D85-91#APVH_www.xxx.com.tr:443] [STDERR] PHP Catchable fatal error:  Argument 1 passed to FacebookAds\CrashReporter::buildParamsFromException() must be an instance of Throwable, instance of ErrorException given, called in /home/xxx/domains/xxxx.com.tr/public_html/system/library/vendor/facebook/php-business-sdk/src/FacebookAds/CrashReporter.php on line 146 and defined in /home/xx/domains/xxxx.com.tr/public_html/system/library/vendor/facebook/php-business-sdk/src/FacebookAds/CrashReporter.php on line 167

**Comment by hongyiu** [comment]
same problem

**Comment by hongyiu** [comment]
> same problem

down to FBE 3.0.1 and normal

**Comment by hongyiu** [comment]
> Thanks @hongyiu. Are you able to access your webserver and find the detailed exception from your error log?

sorry i do not know how to but the problem resolved after FBE downgraded to other version

**Comment by dtying** [comment]
Hi @hongyiu, as Facebook Graph API doesn't support HTTP2, it has caused issue in your webpage (which is on HTTP2).
https://developers.facebook.com/docs/graph-api/using-graph-api/

![Screen Shot 2020-08-25 at 10 49 21 AM](https://user-images.githubusercontent.com/21333308/91117225-ae43a700-e6c0-11ea-898e-bcef14c79a15.png)

You may downgrade to v3.0.1 to continue use. https://github.com/facebookincubator/Facebook-For-OpenCart/tags
