### ISSUE TITLE
Facebook Data Feed 

### ISSUE THREAD

**Issue by gioluv80** [facebookincubator/Facebook-For-OpenCart#452]
Hi I have Facebook Extension For Opencart 3+ I have installed the extension but when the feed uploads to Facebook it does not upload the sizes available for each item. You can now check out on facebook. However, when I connect the data fees to Facebook it does not upload all the variations such as 
Color Options
Size Options 
Quantity 

I need a Facebook feed that will upload and include all options and variants Of the products. 
Can someone help with that?

**Comment by yao-tx** [comment]
Hi @gioluv80 

As OpenCart does not support variants, and instead, only supports options, the Facebook Business Extension plugin is unable to map every options as a variant as each option does not have a unique ID or SKU to it. On top of that, it is not possible to differentiate the different type of options such as Size/Colour Options with other types of options as users can name their options anyway they like it.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
