### ISSUE TITLE
Oops, something went wrong

### ISSUE THREAD

**Issue by mzilyaev** [facebookincubator/Facebook-For-OpenCart#453]
Have installed extension to my opencart 2.3.0.2.3. Everytime I try to connect FBE I get message - 
Oops, something went wrong.
This may be because of a technical error that we're working to get fixed. Try reloading this page.
Strore's link - https://belok.shop/
Please kindly help

**Comment by TyrannosaurHex** [comment]
Getting the same error on Opencart v2.3.0.2 & FBE-3.1.0.

It works fine till the last page where it asks for permission etc, but on the final step it shows connecting etc and then this error comes up.

**Comment by finallynl** [comment]
I also have the same problem, everything looks fine. Then the connection is made and then "An error occured while generating system user access token: (#10) Application does not have permission for this action" 

What can we do?

**Comment by finallynl** [comment]
Ready!
![ready](https://user-images.githubusercontent.com/69470288/89899968-5e0a1680-dbe3-11ea-9252-3e1807f4e3db.png)

Not working
![notworking](https://user-images.githubusercontent.com/69470288/89899978-62363400-dbe3-11ea-9373-dc15d82cb41c.png)

**Comment by lipmycar** [comment]
I am experiencing the same issue. Is there any solution ?

**Comment by finallynl** [comment]
Nobody can help with this? What can we do?

**Comment by finallynl** [comment]
> 
> 
> Have installed extension to my opencart 2.3.0.2.3. Everytime I try to connect FBE I get message -
> Oops, something went wrong.
> This may be because of a technical error that we're working to get fixed. Try reloading this page.
> Strore's link - https://belok.shop/
> Please kindly help

Can you maybe change the topic to [BUG] Oops, something went wrong?

**Comment by jakemake** [comment]
Same problem

**Comment by monefff** [comment]
Sam problem here. When install the newest module, it cannot sync it gives Oops, something went wrong.
We rolled back to Plugin Version: 2.1.3, works fine for now, but most of the time the access token is lost, and we need to reconnect it. That's a bit annoying. 

Hope a fix is released soon.

**Comment by yao-tx** [comment]
Hi all,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
