### ISSUE TITLE
[BUG] problem after instalation

### ISSUE THREAD

**Issue by zaine99** [facebookincubator/Facebook-For-OpenCart#454]
after i install the extension i have the error???

.554555 [NOTICE] [28644] [66.249.76.151:50987-1#APVH_defb.ro:lsapi] [STDERR] PHP Fatal error: Uncaught Error: Undefined class constant 'FACEBOOK_CUSTOMIZATION_LOCALE' in /var/www/vhosts/defb.ro/httpdocs/system/storage/modification/catalog/controller/common/footer.php:13
Stack trace:
#0 /var/www/vhosts/defb.ro/httpdocs/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(51): ControllerCommonFooter->index(Array)
#1 /var/www/vhosts/defb.ro/httpdocs/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php(35): Action->execute(Object(Registry), Array)
#2 /var/www/vhosts/defb.ro/httpdocs/vqmod/vqcache/vq2-system_storage_modification_catalog_controller_product_product.php(1018): Loader->controller('common/footer')
#3 /var/www/vhosts/defb.ro/httpdocs/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(51): ControllerProductProduct->index()
#4 /var/www/vhosts/defb.ro/httpdocs/catalog/controller/startup/router.php(25): Action->execute(Object(Registry))
#5 /var/www/vhosts/defb.ro/httpdocs/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(51 in /var/www/vhosts/defb.ro/httpdocs/system/storage/modification/catalog/controller/common/footer.php on line 13

what is to be done??

**Comment by yao-tx** [comment]
Hi @zaine99 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
