### ISSUE TITLE
[BUG]  facebook for opencart installation error

### ISSUE THREAD

**Issue by zzhou9** [facebookincubator/Facebook-For-OpenCart#455]
I add the facebook bussiness extension to my opencart website, and make every right move about the install, but when I click to start facebook bussiness extension, it always happen the error.
 Warning: mysqli::query(): MySQL server has gone away in /home/profchris/public_html/system/library/db/mysqli.php on line 21Warning: mysqli::query(): Error reading result set's header in /home/profchris/public_html/system/library/db/mysqli.php on line 21.

**Comment by yao-tx** [comment]
Hi @zzhou9 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
