### ISSUE TITLE
[BUG] - 'FacebookAds\\CrashReporter ' contains invalid characters

### ISSUE THREAD

**Issue by TimwaySupport** [facebookincubator/Facebook-For-OpenCart#456]
**FBE plugin version**
3.1.0

**OpenCart version**
3.0.2.0

**Describe the bug**
Add any product to cart, go to the cart page, and Internal server error 500 will show.
Apache error log:
[Fri Aug 07 11:37:19.851100 2020] [http:error] [pid 24658] AH02429: Response header name 'FacebookAds\\CrashReporter ' contains invalid characters, aborting request

**To Reproduce**
 - Install and enabled the facebook extension.
 - Add any product to cart, got the the cart page, and Internal server error 500 will show.

**Desktop (please complete the following information):**
All Versions.

**Comment by dtying** [comment]
Hi @TimwaySupport , can you provide your webstore url?

**Comment by TimwaySupport** [comment]
We have two webshop encounter such issue: 
jekca  .com   .au
ma nym   anygoods  .com
(Please remove the space in between.....)

However, as both the shop production status, we cannot keep the FB extension on "enabled" status for you check.
Any other information we may provide to help you to check for the issue?

**Comment by dtying** [comment]
Hi @TimwaySupport , as Facebook Graph API doesn't support HTTP2, it has caused issue in your webpage (which is on HTTP2).
https://developers.facebook.com/docs/graph-api/using-graph-api/

You may downgrade to v3.0.1 to continue use. https://github.com/facebookincubator/Facebook-For-OpenCart/tags

**Comment by TimwaySupport** [comment]
Thank you for your check and reply.

We will try to use v3.0.1 version on our shops.

Any schedule for making the FB extension to support HTTP2 protocol? Thank you.

**Comment by TimwaySupport** [comment]
Our customer just try to reconnect the Facebook account to the Facebook extension v3.0.1 version, however, on the "Confirm Settings" (OpenCart will be connected to: ....) screenshot, once we click "Continue" , the page just "refresh" and stay on the same page with no error / no connected confirmation.

**Comment by dtying** [comment]
Hi @TimwaySupport, can you share your webstore url?

**Comment by TimwaySupport** [comment]
The shop URL:
jekca    .com    .au
(Please remove all the spaces)

**Comment by TimwaySupport** [comment]
Just an update, the problem just gone and our customer able to use the FB extension with the FB Pixel now.
Thank you for your support.

**Comment by TimwaySupport** [comment]
> Hi @TimwaySupport , as Facebook Graph API doesn't support HTTP2, it has caused issue in your webpage (which is on HTTP2).
> https://developers.facebook.com/docs/graph-api/using-graph-api/
> 
> You may downgrade to v3.0.1 to continue use. https://github.com/facebookincubator/Facebook-For-OpenCart/tags

Hi, we find that some of our shops running oc 2.X version has no problem 

> Hi @TimwaySupport , as Facebook Graph API doesn't support HTTP2, it has caused issue in your webpage (which is on HTTP2).
> https://developers.facebook.com/docs/graph-api/using-graph-api/
> 
> You may downgrade to v3.0.1 to continue use. https://github.com/facebookincubator/Facebook-For-OpenCart/tags

We just find that our website seems not running on http2:
Website: https://www. jekca .co m.au/

http2 server test:
https://tools.keycdn.com/http2-test

So for the error: [Fri Aug 07 11:37:19.851100 2020] [http:error] [pid 24658] AH02429: Response header name 'FacebookAds\CrashReporter ' contains invalid characters, aborting request

Will it be caused by other issue?
