### ISSUE TITLE
[BUG]After installation - Administration Panel - Few sections certain fields are deleted

### ISSUE THREAD

**Issue by stampgo7** [facebookincubator/Facebook-For-OpenCart#457]
**Webstore Url**
www.tshirtgallery.gr

**FBE plugin version**
Plugin Version: 2.1.3

**OpenCart version**
Version of OpenCart 3.0.2.0

**Describe the bug**
After installation I start to have few problems.
in the last few days and while I make changes in the management environment of tshirtgallery.gr, which is opencart, I get the error you see in the screenshots that I attach.
At the same time yesterday while I had added about 25 different geo zones after saving most of them disappeared. I had to add them again without knowing if it would happen again.
Today while I added to the custom modules which were 15 already, one more, after saving everything disappeared from both the management and the front page. I had to restore backup.

Please see if it has anything to do with the error and what it means or what else is to blame.

**To Reproduce**

**Screenshots**
![screen shot 1](https://user-images.githubusercontent.com/69384731/89706805-b5a14b80-d971-11ea-8c08-644b99f365d8.jpg)
![screen shot 2](https://user-images.githubusercontent.com/69384731/89706807-b76b0f00-d971-11ea-9ec7-2c64be568bca.jpg)
![screen shot 3](https://user-images.githubusercontent.com/69384731/89706810-b89c3c00-d971-11ea-9b76-b10457b25491.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Google Chrome is up to date
Version 84.0.4147.105 (Official Build) (64-bit)

**Additional context**
Furthermore using the plugin for more than a week does not manage to upload all products on FB and on Instagram appears just few of them.

**Comment by yao-tx** [comment]
Hi @stampgo7 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
