### ISSUE TITLE
[BUG] Accessing Extension Dashboard Fires Error

### ISSUE THREAD

**Issue by baron-kg** [facebookincubator/Facebook-For-OpenCart#458]
**Webstore Url**
www.eparhija.com

**FBE plugin version**
3.1.0

**OpenCart version**
OpenCart 3.0.3.3

**Bug description**
After installing the extension and refreshing on the modifications page I go to the extension dashboard to try to connect to my Facebook account. Clicking on it displays the following error:

Warning: require_once(/usr/www/users/eparhija/eparhija/vqmod/vqcache/vendor/autoload.php): failed to open stream: No such file or directory in /usr/www/users/eparhija/eparhija/vqmod/vqcache/vq2-system_library_facebookcommonutils.php on line 8

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 84.0.4147.105

**Comment by dtying** [comment]
Hi @baron-kg , you may refer here for the solution - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/450#issuecomment-678592126
