### ISSUE TITLE
Upgrade from 2.1.3 to 3.1.0 failed

### ISSUE THREAD

**Issue by rod2k** [facebookincubator/Facebook-For-OpenCart#459]
Hello, i've updated the plugins following the guide, I have made this 4 steps [https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#upgrade-the-plugin-to-a-later-version](url) and now, I have this screen

![image](https://user-images.githubusercontent.com/23507339/90082776-e664e600-dccd-11ea-941f-414a8cfae7c8.png)

But when I press the "Get Started" button, nothing happens, checking the debug panel, I have

![image](https://user-images.githubusercontent.com/23507339/90082835-0f857680-dcce-11ea-883c-e53aa067f263.png)

How do I configure my connection to fb?

**Comment by rod2k** [comment]
I uninstalled and deleted the 3.1.0 version, installed the 2.1.3 and It's already configured all, I have all FB Plugins back syncing products

![image](https://user-images.githubusercontent.com/23507339/90083724-8ae82780-dcd0-11ea-9722-62db35792108.png)

**Comment by yao-tx** [comment]
Hi @rod2k 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
