### ISSUE TITLE
Pixel on mobile site for OC 3.0.2.0

### ISSUE THREAD

**Issue by ivladoff** [facebookincubator/Facebook-For-OpenCart#46]
Hello, 

I have the pixel installed on my site www.uoou.bg and it's operational when I'm checking it with the FB pixel helper. But on the mobile version of the site www.m.uoou.bg it says there is no pixel installed. 

Is this an issue, or problem for reading data correctly as I still can see some of the activities on the mobile site in Facebook analytics? But I don't know if the data is complete and the pixel is functioning correctly. 

Thanks!

**Comment by shue249** [comment]
Thank you for the feedback!

We did a check and found the pixels are correct on both the mobile site as well as the source codes.
The pixel should be fine.

![image](https://user-images.githubusercontent.com/11957585/47341699-4bec7a80-d6d4-11e8-8666-fdcaa6e60784.png)
![image](https://user-images.githubusercontent.com/11957585/47341739-645c9500-d6d4-11e8-9df0-ceb832caa7b8.png)

**Comment by shue249** [comment]
We will proceed to close out this ticket, but pls feel free to open again if there's any questions
