### ISSUE TITLE
error in checkout page" index.php?route=checkout/checkout" Opencart Version 3.0.3.1 With Journal 3 (Theme) , Working Fine in Journal 2 (Theme ), any solution please help error screen shot : https://bit.ly/33Q4uBZ[BUG]

### ISSUE THREAD

**Issue by Devendrapatel3544** [facebookincubator/Facebook-For-OpenCart#460]
**Webstore Url**
Your webstore Url 
https://bombaycollection.co.in/
**FBE plugin version**
Version of FBE plugin
3.1.0
**OpenCart version**
Version of OpenCart
3.0.3.1
**Describe the bug**
error in checkout page" index.php?route=checkout/checkout" Opencart Version 3.0.3.1 With Journal 3 (Theme) , Working Fine in Journal 2 (Theme ), any solution please help
error screen shot : https://bombaycollection.co.in/image/data/fberr.png

**Comment by Devendrapatel3544** [comment]
error in checkout page" index.php?route=checkout/checkout" Opencart Version 3.0.3.1 With Journal 3 (Theme) , Working Fine in Journal 2 (Theme ), any solution please help error screen shot : https://bit.ly/33Q4uBZ[BUG]

**Comment by Devendrapatel3544** [comment]
error in checkout page" index.php?route=checkout/checkout" Opencart Version 3.0.3.1 With Journal 3 (Theme) , Working Fine in Journal 2 (Theme ), any solution please help error screen shot : https://bit.ly/33Q4uBZ[BUG

**Comment by Devendrapatel3544** [comment]
here is the screenshot link https://bombaycollection.co.in/image/data/fberr.png

**Comment by nathanyoliveiraassuncao** [comment]
I saw that you managed to fix the error, can you tell me how?

**Comment by dtying** [comment]
Hi @Devendrapatel3544, as Facebook Graph API didn't support HTTP2, it has caused issue in your webpage (which is on HTTP2).
https://developers.facebook.com/docs/graph-api/using-graph-api/
![Screen Shot 2020-08-25 at 10 07 19 AM](https://user-images.githubusercontent.com/21333308/91116858-eac2d300-e6bf-11ea-98d9-1ab40b0ec2a4.png)


You may downgrade to v3.0.1 to keep using the plugin. https://github.com/facebookincubator/Facebook-For-OpenCart/tags
