### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FrankMontana** [facebookincubator/Facebook-For-OpenCart#461]
**Webstore Url**
cond.land

**FBE plugin version**
Plugin Version: 3.1.0

**OpenCart version**
3.0.2.0

**Describe the bug**
After clicking on the "get started" button, I log into my facebook account and receive the "admin permission required" error and advice to contact the administrator of the old page in the business manager, there is no access to the page, how to link to the new one?

**To Reproduce**
1. Go to Facebook Buisness Extension
2. Click on 'Get started'
3. Log in Facebook

**Screenshots**
https://cond.land/Screen.PNG

**Comment by yao-tx** [comment]
Hi @FrankMontana 

This means that you need to be logged into a Facebook account that has admin access to the page that was previously connected to your website. For these issues, it is advisable for you to contact Facebook's support directly.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
