### ISSUE TITLE
[BUG]Extension: Facebook for OpenCart

### ISSUE THREAD

**Issue by madebylayton** [facebookincubator/Facebook-For-OpenCart#463]
**Webstore Url**
laytonmade.com

**FBE plugin version**
Version of FBE plugin

**OpenCart version**
 3.0.2.0

**Describe the bug**
I have installed this Facebook extensions module and it is giving me errors, I have looked and made sure all the things suggested are correct and still showing errors.
THis is the message that shows up:

We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by yao-tx** [comment]
Hi @madebylayton 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
