### ISSUE TITLE
An error occured while generating system user access token

### ISSUE THREAD

**Issue by CorretjeR** [facebookincubator/Facebook-For-OpenCart#464]
**Webstore Url**
https://www.kaneelkapsules.nl

**FBE plugin version**
3.1.0
**OpenCart version**
3.0.2.0

**Describe the bug**
An error occured while generating system user access token: Unavailable app data cannot be shared: This app's data is unavailable and can't be shared.

I get the above error whoile trying to connect to Facebook. Is this a bug or my mistake?
Thx.

**Comment by dtying** [comment]
Hi @CorretjeR, thanks for reporting. There's an issue with the app settings, and we're fixing it now.

**Comment by samoila** [comment]
FBE plugin version
3.1.0
OpenCart version
3.0.3.2
An error occured while generating system user access token: Unavailable app data cannot be shared: This app's data is unavailable and can't be shared.

**Comment by dtying** [comment]
@samoila , thanks for reporting! Sorry that we're still fixing it.

**Comment by p-henriquesoares** [comment]
I'm waiting for the fix too, thanks for report this issue.

**Comment by dtying** [comment]
Hi all, the issue has been fixed already. You shouldn't see the error now.

**Comment by svremeto** [comment]
@dtying 
Hello, 
I am facing this error. I see with the "Facebook Pixel Helper" that there is no pixel on the website. The chat is working. The catalog is not working.

FBE plugin version
3.1.1
OpenCart version
2.3.0.2

Describe the bug
An error occured while generating system user access token: Unavailable app data cannot be shared: This app's data is unavailable and can't be shared.
