### ISSUE TITLE
[Feature Request] HELP PLEASE

### ISSUE THREAD

**Issue by Laurent3006** [facebookincubator/Facebook-For-OpenCart#466]
Hello, i have this message when i want connect open cart to my new facebook account.

Administrator authorization required
You do not have permission to change these settings. Contact the E 100 Business Manager administrator to gain access.

The E100 it's an old account and i can't connect on it, when i log on the app i log with my new account, but at the second step this message appear and the E100 account it's not linked on the new. I don't understand

**Comment by yao-tx** [comment]
Duplicate of #465
