### ISSUE TITLE
Fresh install shows issue "There are problems with the installation of the Facebook Ads Extension." Opencart 3.0.2

### ISSUE THREAD

**Issue by azhar25git** [facebookincubator/Facebook-For-OpenCart#468]
The issue details: 

``` 
1. We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders.
/[directory]/catalog/view/javascript
```

I have tried by giving the directory 777 permission but still no luck.

**Comment by yao-tx** [comment]
Hi @azhar25git 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
