### ISSUE TITLE
Fails to connect to Facebook - Invalid Token

### ISSUE THREAD

**Issue by meds68** [facebookincubator/Facebook-For-OpenCart#471]
**Webstore Url**
https://alicejones.com.au/

**FBE plugin version**
3.1.0

**OpenCart version**
3.0.3.2

**Describe the bug**
Had an error about an invalid token.  Was an older version (2 I think). So uninstalled that version and downloaded & installed 3.1.0.  It has continually failed to connect

**To Reproduce**
Just go into the extention

**Screenshots**

![image](https://user-images.githubusercontent.com/70637477/91970609-4560cc80-ed5b-11ea-9393-cf690002ed36.png)

**Desktop (please complete the following information):**
Win10/Firefox
iOS/Safari

**Additional context**
Content isn't transferring to Facebook from the website.

**Comment by yao-tx** [comment]
Hi @meds68 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
