### ISSUE TITLE
[BUG] Upgrade issue Error No: 1064

### ISSUE THREAD

**Issue by pao2pao16** [facebookincubator/Facebook-For-OpenCart#473]
Im trying to upload the latest ocmod. But I am getting this error during the installation.

Error Code(0): Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.0012_modification where field = 'xml'' at line 1
Error No: 1064
SHOW COLUMNS FROM `xxx`.oc_modification where field = 'xml' in /home/pdnadm/public_html/system/library/db/mysqli.php on line 40

Upon investigation, the SQL query in question is "SHOW COLUMNS FROM `%s`.%smodification where field = 'xml'", that is located in install.php

I modified it and replace the variables to the actual

SHOW COLUMNS FROM `xxx`.oc_modification where field = 'xml' and I get the same error.

I am guessing that the query field = 'xml' is the culprit here?

**Comment by yao-tx** [comment]
Hi @pao2pao16 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The latest FBE plugin no longer uses OCMOD (only for OpenCart version 2.3 and above) or any custom installation scripts. Instead, it uses the default OpenCart Extension Installer to perform installation.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
