### ISSUE TITLE
[BUG]Messenger chat box does not show

### ISSUE THREAD

**Issue by wsquarez** [facebookincubator/Facebook-For-OpenCart#475]
**Webstore Url**
Www.madison99.com

**FBE plugin version**
3.01

**OpenCart version**
2.3.02

**Describe the bug**

I installed Facebook business extension with no problems, the chat box does shown properly on the page on the first day. However, I was changing some view pictures and clicked refresh under modification couple of times. Then the chat box disappeared.... I tried to uninstall and install the extension, but did solve the problem. 

Please help !

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by yao-tx** [comment]
Hi @wsquarez 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
