### ISSUE TITLE
[BUG] wrong value of product special/discount price

### ISSUE THREAD

**Issue by thorin87** [facebookincubator/Facebook-For-OpenCart#476]
**FBE plugin version**
3.0.0

**OpenCart version**
3.0.3.2

**Describe the bug**
Product special/discount price sync uses the lowest price from all customers group, while it should take special price from default customer group

**To Reproduce**
1. Create new customer group (for example "regular customers")
2. Add discount price for any product for newly created customer group
3. Sync products to Facebook

Expected: Facebook catalog displays price for default customer group
Current: Facebook catalog displays the lowest price from all customer groups

**Additional context**
Line 153 of `system\library\model\extension\facebookproduct.php` should be
```
$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_special WHERE product_id = '" . (int)$product_id . "' AND customer_group_id = '" . (int)$this->config->get('config_customer_group_id') . "' ORDER BY priority, price");
```
(`config_customer_group_id` keeps the id of default user group)

**Comment by monefff** [comment]
I have the same issue. Facebook is taking the lowest price on the Customer's group, but not by the default group. This is causing very big confusions on the ads for price and the ads for the sale.

Please provide fix

**Comment by yao-tx** [comment]
Hi @thorin87 @monefff 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The new FBE plugin (version 4.0.0 and above) has changed the way the plugin is pulling special prices. It will take special prices just like how OpenCart does, from the default customer group and based on priority.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
