### ISSUE TITLE
[BUG] Facebook team!! why you not testing your extension which breaks add2cart and checkout??

### ISSUE THREAD

**Issue by alireza-shamakhy** [facebookincubator/Facebook-For-OpenCart#479]
opencart: 3.0.2.0

Plugin Version: 3.1.0

I uninstalled the extension which breaks the add2cart.
The error log as below:

[12-Sep-2020 04:05:31 UTC] PHP Fatal error:  Uncaught Error: Undefined class constant 'FACEBOOK_CUSTOMIZATION_GREETING_TEXT_CODE' in /home/solarli7/public_html/sunsharesolar.com.au/system/storage3020/modification/catalog/controller/common/footer.php:13
Stack trace:
#0 /home/solarli7/public_html/sunsharesolar.com.au/system/storage3020/modification/system/engine/action.php(79): ControllerCommonFooter->index(Array)
#1 /home/solarli7/public_html/sunsharesolar.com.au/system/storage3020/modification/system/engine/loader.php(59): Action->execute(Object(Registry), Array)
#2 /home/solarli7/public_html/sunsharesolar.com.au/system/storage3020/modification/catalog/controller/product/product.php(730): Loader->controller('common/footer')
#3 /home/solarli7/public_html/sunsharesolar.com.au/system/storage3020/modification/system/engine/action.php(79): ControllerProductProduct->index()
#4 /home/solarli7/public_html/sunsharesolar.com.au/catalog/controller/startup/router.php(25): Action->execute(Object(Registry))
#5 /home/solarli7/public_html/sunsharesolar.com.au/system/st in /home/solarli7/public_html/sunsharesolar.com.au/system/storage3020/modification/catalog/controller/common/footer.php on line 13
**Additional context**

**Comment by dtying** [comment]
Hi, after you installed the latest plugin, did you go to Extensions -> Modifications and clicked the refresh button? Your website html seems staled as 'FACEBOOK_CUSTOMIZATION_GREETING_TEXT_CODE' variable was not used in the latest plugin codebase any more, you need to follow the OpenCart plugin installation steps to properly build the html.

**Comment by alireza-shamakhy** [comment]
Hi,

I am sure that I did  Extensions -> Modifications and clicked the refresh button.
I uninstalled and installed again and then followed the instructions in https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#setup-for-facebook-business-manager-page-pixel-and-catalog 
but again failed. So I had to uninstall it again.
The setup gets completed but when i click add2cart it shows 500 error.

Also I followed the instructions "For OpenCart 3.x, you need to perform an additional installation step" and notified that the Module Facebook Ads Extension is not in my list. Is it problematic?

 "https://drive.google.com/file/d/1sfryAfbG9rUyF0skyZ4BI7nLma8uM1KI/view

happy to have a zoom chat or share my screen if that helps.

Any ideas?

Thanks.

**Comment by dtying** [comment]
Hi, could you install plugin version 3.0.1 instead? https://github.com/facebookincubator/Facebook-For-OpenCart/tree/v3.0.1

**Comment by alireza-shamakhy** [comment]
Hi,

Just did but again failed. :(

**Comment by emreacar** [comment]
Same issue. When clients go checkout page throws an error "page not found" on route=checkout/checkout.

**Comment by asifhu03** [comment]
For info I'm having the same issue. Wasn't there on the previous version of the extension however after updating yesterday my Cart and Checkout pages display the 500 Internal Server Error page. When I disable the extension the issue goes away so it's definitely this extension.

Would love a fix as everything else (including the Messenger button) works perfectly.

**Comment by designlab9898** [comment]
i'm following this thread because i have the exact same issue using latest FBE v3.
cart and checkout page leads to "page not found"

**Comment by konstantinosbotonakis** [comment]
The solution here, is to uninstall **all versions of the plugin** that you may have installed and then install the latest version only and then refresh modifications.

Constant FACEBOOK_CUSTOMIZATION_GREETING_TEXT_CODE is not used by the latest version and there's a conflict when you have a previous version installed along with the latest one.

**Comment by alireza-shamakhy** [comment]
@konstantinosbotonakis  I uninstalled all versions of the plugin and installed the latest version and refreshed modifications but AGAIN FAILED!

**Comment by alireza-shamakhy** [comment]
Facebook team, is there any updates regarding the issue? appreciate if you can fix it.

**Comment by yao-tx** [comment]
Hi @alireza-shamakhy 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
