### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ysn** [facebookincubator/Facebook-For-OpenCart#481]
**Webstore Url**
https://redblue.center

**FBE plugin version**
3.1.0

**OpenCart version**
3.0.2.0

**Describe the bug**

Normal prices come to the catalog. Special prices do not come. uninstalled and reinstalled. Catalog remove & reupload. Do not change.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 85.0.4183.121

**Additional context**
FB Catalog id: 2944185142352941

**Comment by yao-tx** [comment]
Hi @ysn 

Do ensure that you have enabled the 'Sync product special price as discount' option.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
