### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dahmsh** [facebookincubator/Facebook-For-OpenCart#482]
**Webstore Url**
Your webstore Url

**FBE plugin version**
Version of FBE plugin

**OpenCart version**
Version of OpenCart

**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by dahmsh** [comment]
خطأ JSON تحليل: خطأ قواعدي غير المعترف بها رمز '<'
parsererror


خطأ فادح : خطأ Uncaught: الفئة 'FacebookAds \ كائن \ جانب الخادم \ AdsPixelSettings' غير موجود في /home/seejad/public_html/vqmod/vqcache/vq2-system_library_facebookcommonutils.php:446
المكدس trace:
# 0 /home/seejad/public_html/vqmod/vqcache/vq2-admin_controller_extension_facebookadsextension.php(422): FacebookCommonUtils-> getPixelAAMSetting ('243710134320989 ...')
# 1 / home / seejad / public_html -system_storage_kwetiqjeitqjt_modification_system_engine_action.php (79): ControllerExtensionFacebookAdsExtension-> updateSettings ()
# 2 /home/seejad/public_html/admin/controller/startup/router.php(26): Action-> Registry executeصفيف)
# 3/home
/ seejad / public_html / vqmod / vqcache / vq2-system_storage_kwetiqjeitqjt_modification_system_engine_action. > تنفيذ (كائن (التسجيل))
رقم 5 / الوطن / seejad / بوبليك / vqmod / vqcache / vq2-system_storage_kwetiqjeitqjt_modificati في /home/seejad/public_html/vqmod/vqcache/vq2-system_library_facebookcommonutils.php على خط 446

https://prnt.sc/unezfr
https://prnt.sc/unf03g
https://prnt.sc/unf09d

**Comment by yao-tx** [comment]
Hi @dahmsh 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
