### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DORMETA** [facebookincubator/Facebook-For-OpenCart#483]
**Webstore Url** 
https://dormeta.ro/

**FBE plugin version**
3.1.0

**OpenCart version**
2.3.0.2

**Describe the bug**
A - When in category page and add product to cart the pixel doesn't fire (add to cart event missing and the product id's also)
B - When click on finalize order and land on checkout/checkout url to place the name, phone, adress etc the Initiate checkout event is missing and the selected products id's corelated to fb catalog also missing
1. Go to 'https://dormeta.ro/super-oferte/oferta-1plus1-gratis'
2. Click on 'Cumpără'
3. While Popup Cart displayed check event Add to cart + id's of products added,
 all missing
3. Click on 'FINALIZEAZĂ COMANDA'
4. Redirected to: https://dormeta.ro/index.php?route=quickcheckout/checkout
5. Check pixel helper to see events trigered  = Initiate Checkout_ to cart + id's of products added are missing

**Screenshots**

**Desktop (please complete the following information):**
![event missing](https://user-images.githubusercontent.com/48640019/94490373-d312c900-01ee-11eb-9527-514eeded4c45.jpg)
![correct example](https://user-images.githubusercontent.com/48640019/94490685-63e9a480-01ef-11eb-8ac4-a26fa5b9ff26.jpg)

 - Browser [chrome, ]

**Additional context**

**Comment by yao-tx** [comment]
Hi @DORMETA 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
