### ISSUE TITLE
permission denied 

### ISSUE THREAD

**Issue by abooodi8** [facebookincubator/Facebook-For-OpenCart#484]
**Webstore Url**
www.nasaembeauty.com

**FBE plugin version**
3.0.3.1 

**OpenCart version**
3.0.3.3 

**Describe the bug**
I made a connection between the Facebook store and Opencart Store, I did download the plugin but I could not install it from Extension witch I had to upload them through SSH and it cases a problem with some permission to the path of Var/Html/www/system/vendor file which had the premotion of Apache so I couldn't upload  them till I change the permission with 777 to the folder then I could upload the files and install the Plugin but after changes, permission and this issue came out :
1- permission has suddenly changed to my admin account which I can not give it to the admin anymore.
2- most of the use file apache keeps catching them. 
3- when trying to access the Facebook it seems 
The Facebook Business Extension can be accessed from the main menu of your OpenCart admin panel.
Or you can click here to access the Facebook Business Extension.
4- I can not give my admin account full permission from the user Group it seems :
 **Warning: You do not have permission to modify users!**
5- can not even change the user password.
**Warning: You do not have permission to modify users!**

**To Reproduce**
1. Go to admin panel 
2. Click on user group 
3. Scroll down to modify permission.
4. See error when you give permission to a user group.

**Screenshots**
![after changing the permission](https://user-images.githubusercontent.com/57403648/94535000-b8ba0900-0249-11eb-97e8-f6595fe538be.jpg)
![cant give my self permissions as i am the admin](https://user-images.githubusercontent.com/57403648/94535006-b9eb3600-0249-11eb-9753-2960180a4e08.jpg)

**Desktop (please complete the following information):**

**Additional context**

**Comment by yao-tx** [comment]
Hi @abooodi8 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
