### ISSUE TITLE
An Error occurred while fetching FBE install config

### ISSUE THREAD

**Issue by RabeArshad** [facebookincubator/Facebook-For-OpenCart#485]
I am unable to link my local host OpenCart with Facebook store. I have tried all Open cart versions 3.x.x but getting the same error. I am using the latest version of Facebook Business Extension.

![Issue1](https://user-images.githubusercontent.com/72106070/94613497-84e6df80-0259-11eb-88fe-927d3507f4b5.png)
![Issue2](https://user-images.githubusercontent.com/72106070/94613522-8c0ded80-0259-11eb-8665-e5378d9c3c81.png)

Please help!

**Comment by dtying** [comment]
Hi @RabeArshad , localhost is not working as it failed at url validation step and can't be bypassed.

**Comment by stavtime** [comment]
The same error. How to fix? What could be the problem?

**Comment by yao-tx** [comment]
Hi all

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!

**Comment by yao-tx** [comment]
Hi @RabeArshad @stavtime 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
