### ISSUE TITLE
An Error occurred while fetching FBE install config

### ISSUE THREAD

**Issue by AbdalhadyDweik** [facebookincubator/Facebook-For-OpenCart#486]
![facebook ads Jodealz 3](https://user-images.githubusercontent.com/72141854/94689619-c3eb6280-0337-11eb-8bc3-c320d649e5e5.png)
![facebook ads Jodealz 4](https://user-images.githubusercontent.com/72141854/94689824-feed9600-0337-11eb-8548-afdb89d8c759.png)

 Hello,
Please check the issue in last page in setup Facebook, please note that the website in our server.

Thanks

**Comment by AbdalhadyDweik** [comment]
.

**Comment by AbdalhadyDweik** [comment]
An Error occurred while fetching FBE install config

**Comment by danailddd** [comment]
same here

**Comment by yao-tx** [comment]
Duplicate with #488
