### ISSUE TITLE
[BUG] Missing Purchase Value Parameter Opencart FB MODULE

### ISSUE THREAD

**Issue by hassni1** [facebookincubator/Facebook-For-OpenCart#487]
**Webstore Url**
https://www.qmart.pk/

**FBE plugin version**
Plugin Version: 3.1.0

**OpenCart version**
Version of 3.0.2.0

**Describe the bug**
today i noticed in pixel there is diagnostics found 2 errors (Missing Purchase Value Parameter) (Missing InitiateCheckout Value Parameter) 
more detail i checked in details its missing Parameter currency value. 
Please guide how to fix the issue.

**Screenshots**
[https://prntscr.com/ust07r](url)
[https://prntscr.com/ust052](url)

**Comment by Khnaz35** [comment]
Same for me too. When using test event tool everything seems setup correctly but after-while errors happened

**Comment by Khnaz35** [comment]
Yeah, Same

**Comment by yao-tx** [comment]
Hi @hassni1 @Khnaz35 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!

**Comment by Khnaz35** [comment]
Hi TengXiong ,
I have updated my facebook extension now . Just a question is the feed url
is still the same

https://xyz.com/index.php?route=extension/facebookfeed/genFeed

**Comment by yao-tx** [comment]
Hi @Khnaz35 

For the Facebook Business Extension plugin version 4.0.0 and above, the feed URL has been changed to https://your-url.com/index.php?route=extension/module/facebook_business/genFeed, where your-url.com is the domain of your OpenCart website. If you are using OpenCart version 2.0.x to 2.2.x, however, the feed URL will be https://your-url.com/index.php?route=module/facebook_business/genFeed.
