### ISSUE TITLE
An Error occurred while fetching FBE install config

### ISSUE THREAD

**Issue by AbdalhadyDweik** [facebookincubator/Facebook-For-OpenCart#488]
Hi, 
Please see the **issue in last page in configuration** of opencart plugin.

**An Error occurred while fetching FBE install config**

**Important, Important, Important,** 

![facebook ads Jodealz 3](https://user-images.githubusercontent.com/72141854/95176270-4e631480-07c5-11eb-8aac-1bda8fbf9a57.png)

![facebook ads Jodealz 4](https://user-images.githubusercontent.com/72141854/95176283-5622b900-07c5-11eb-946d-cc17324163dc.png)

**Comment by konstantinosbotonakis** [comment]
I can see that you have custom admin folder's name from admin -> margareta

You need to uninstall the plugin, open the files with an editor and replace **admin** with **margareta**. Then zip the files like an ocmod and re-install the plugin. 

If you can't do this, you can do something else.

Uninstall the extension and download this custom version: https://github.com/konstantinosbotonakis/Facebook-For-OpenCart/releases/tag/v3.1.0_custom

that I made and supports custom admin folder's name.

**Comment by stavtime** [comment]
The same error. How to fix? What could be the problem?

**Comment by AbdalhadyDweik** [comment]
> The same error. How to fix? What could be the problem?

You need to download the version from ads manager in Facebook ((just)).

Don't download it from opencart store.

**Comment by stavtime** [comment]
> > Та же ошибка. Как исправить? В чем может быть проблема?
> 
> Вам нужно скачать версию из менеджера рекламы в Facebook ((просто)).
> 
> Не скачивайте его из магазина opencart.
After installation, the button to start configuring the module does not appear. Did you have this problem? 2 btn
![image](https://user-images.githubusercontent.com/51811934/104007286-c5d78400-51b8-11eb-81a9-609ee3473b2d.png)

**Comment by stavtime** [comment]
> > The same error. How to fix? What could be the problem?
> 
> You need to download the version from ads manager in Facebook ((just)).
> 
> Don't download it from opencart store.

After installation, the button to start configuring the module does not appear. Did you have this problem?

![image](https://user-images.githubusercontent.com/51811934/104007488-0fc06a00-51b9-11eb-94d5-bec36ff99c74.png)

**Comment by stavtime** [comment]
I tried to open it through different browsers. The buttons are not displayed anywhere.

**Comment by AbdalhadyDweik** [comment]
Install it again.

**Comment by stavtime** [comment]
> Install it again.

Forgot to clear the cache in the admin area. That helped. Thanks a lot for your help!

**Comment by yao-tx** [comment]
Hi all,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
