### ISSUE TITLE
Messenger Chat not working / showing up even if its enable [BUG]

### ISSUE THREAD

**Issue by patikas14** [facebookincubator/Facebook-For-OpenCart#489]
**Webstore Url**
https://katanou.gr

**FBE plugin version**
3.1.0

**OpenCart version**
3.0.3.2

**Describe the bug**
I have added, edited and enable the facebook messenger chat plugin, but no messenger bubble on front site!
If anyone can help, please contact me..

**Screenshots**
1) https://drive.google.com/open?id=1Ke1DfNX0_MES1yMYLRDPaDOV4k7sQHAZ
2) https://drive.google.com/open?id=13J-D_8BoHEDcomCyLlgeUUTJS_BsePtJ

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [latest]

**Comment by yao-tx** [comment]
Hi @patikas14 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
