### ISSUE TITLE
Facebook Business Extension doesnt enable the category discounts used by Multi discount pack extension

### ISSUE THREAD

**Issue by doandbe** [facebookincubator/Facebook-For-OpenCart#490]
**Webstore Url**
Your webstore Url www.doandbe.gr

**FBE plugin version**
Version of FBE plugin 2.2.1

**OpenCart version**
Version of OpenCart 2.3.0.2

**Describe the bug**
Facebook Business Extension doesn't enable the group discounts used by Multi discount pack extension
Multi Discount pack extension is working properly 
![category discounts](https://user-images.githubusercontent.com/58469642/95312409-8fc3f480-0897-11eb-9fb5-aa8b7b200d21.PNG)
![sample item on website](https://user-images.githubusercontent.com/58469642/95312413-90f52180-0897-11eb-9395-10ee5c761c14.PNG)
![sample item](https://user-images.githubusercontent.com/58469642/95312415-918db800-0897-11eb-8864-f485bd6d906f.PNG)

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by doandbe** [comment]
οκ

**Comment by yao-tx** [comment]
Duplicate with #506
