### ISSUE TITLE
[BUG] Product Feed Information

### ISSUE THREAD

**Issue by Secretsmile85** [facebookincubator/Facebook-For-OpenCart#491]
**Webstore Url**
Schelmart.com

**FBE plugin version**
3.0.0

**OpenCart version**
2.1.0.2

**Describe the bug**
Hi, I couldn't find any way to configure what information and characteristics will be provided for a facebook catalog. The main thing is that facebook gives an advice to specify either fb_product_category or google_product_category. I can't change it in facebook directly - it says that this information shuld come from the feed. But in the Facebook Business Extension module for opencart - there is no way to specify what fields will go to the feed - or I didn't find how to do that. I also have an information about the color of some products - how can I "put" it into the feed so facebook would apply it to the products in the catalog? 
Thanks. 

**Desktop (please complete the following information):**
 - OS: [Windows 8.1]
 - Browser [Chrome] 
 - Version [85.0.4183.121]

**Comment by yao-tx** [comment]
Hi @Secretsmile85 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The new version of the FBE plugin allows you to assign specific Google Product Categories to your products under the 'Facebook' tab in your admin product configurations.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
