### ISSUE TITLE
[BUG] Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by Miroslav020788** [facebookincubator/Facebook-For-OpenCart#494]
**Webstore Url**
https://corrector.com.ua

**FBE plugin version**
Plugin Version: 3.1.0

**OpenCart version**
Version 3.0.3.2 (rs.2)

**Describe the bug**

**To Reproduce**
1. Go to 'https://corrector.com.ua' or any category in the catalog, like a @https://corrector.com.ua/vyroby-z-paperu-1@
2. Click on 'buy button'
4. See an error

merged.08859697.min.js:3 Uncaught TypeError: Illegal invocation

at fireProductInfoEvent (facebook_pixel_3_1_0.js:34)

    jQuery.get(
      'index.php?route=extension/facebookproduct/getproductinfoforfacebookpixel',
      {
        event_name: eventName,
        product_id: productID,
        quantity: quantity,
      },
        function (json) {
        if (json.facebook_pixel_event_params_FAE) {
          _facebookAdsExtension.facebookPixel.firePixel(
            json.facebook_pixel_event_params_FAE);
        }
      }
    );

    at Object.cart.add (facebook_pixel_3_1_0.js:78)

   cart.add = function(productID, quantity) {
        fireProductInfoEvent('AddToCart', productID, quantity);
        oldCartAdd.apply(oldCartAdd, [productID, quantity]);
      };

**Screenshot**
https://prnt.sc/uyemmd
https://prnt.sc/uyemyl
https://prnt.sc/uyenus

**Comment by yao-tx** [comment]
Hi @Miroslav020788 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
