### ISSUE TITLE
Sorry, this content isn't available right now

### ISSUE THREAD

**Issue by AbdalhadyDweik** [facebookincubator/Facebook-For-OpenCart#495]
Hello,
We have issue in Opencart plugin, when press on "Manage Settings" 
it will open new tab: **"Sorry, this content isn't available right now"**.
As below images.

The second Page in: **extension>extension> modules> Facebook Ads Extension**
Any Help please..

![facebook ads Jodealz 5](https://user-images.githubusercontent.com/72141854/96497563-8cdfe100-1253-11eb-8353-79352fbf2238.png)
![facebook ads Jodealz 6](https://user-images.githubusercontent.com/72141854/96497567-8e110e00-1253-11eb-9927-24bba9ce3638.png)

**Comment by dtying** [comment]
It seems that you're using an old version of plugin. Please try to upgrade to v2.2.1 or the latest version.

**Comment by yao-tx** [comment]
Hi @AbdalhadyDweik 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
