### ISSUE TITLE
[BUG]Oops, something went wrong

### ISSUE THREAD

**Issue by Aleksandr111111111** [facebookincubator/Facebook-For-OpenCart#497]
**Webstore Url**
https://itopshop.biz/

**FBE plugin version**
Plugin Version: 3.1.0

**OpenCart version**
OpenCart © 2009-2020 Всички права запазени.
Версия 2.3.0.2

**Describe the bug**
Updated extension facebook does not establish contact with the store

**To Reproduce**
1.  https://drive.google.com/file/d/1UmEhCvB5JUNBnCVIl88fcD7NrHCqWDKm/view?usp=sharing
in the admin panel I click  Get Started
2. https://drive.google.com/file/d/1EfBkLz7kI9sfTsQm0exDuNQkDaw4_gD4/view?usp=sharing
    click  Continue as Iliqna Takieva
3. https://drive.google.com/file/d/1BtZFezGtSEra4x5I6wsFJwtBiGi8MY1L/view?usp=sharing
     click  Continue
4. https://drive.google.com/file/d/1DC_8ZiMNgBoc6oYTPXFVYvjDgpdArfey/view?usp=sharing
    click  Continue
5. https://drive.google.com/file/d/134q20Fn8WIEKUUPjdA0jrv5wLoAfbPMF/view?usp=sharing
     click  Next
6. https://drive.google.com/file/d/1uI5lKIxv3XF8kp1GMKFoER1gEUi8E3MF/view?usp=sharing

**Desktop (please complete the following information):**
tried on various devices (iOS / windows) Google Chrome Version 86.0.4240.80 (Official assembly), (x86_64)

**Additional context**
Removed the integration on the facebook page, according to the instructions

To review or remove the business integrations you've connected to your Facebook account:
Click  in the top right of Facebook.
Click Settings.
Click Business Integrations on the left side.
Filter between Active or Removed at the top, or search for a specific business integration using the search bar to the right.
Click View and Edit next to the business integration to control the info it has access to. Adjust your settings by checking or unchecking the boxes next to your information or using the dropdown menus, and then click Save.
If the business integration has expired user permissions that you want to re-enable, click on Renew.

**Comment by dtying** [comment]
Hi @Aleksandr111111111 , thanks for reporting the issue. The error is due to the currency you set in OpenCart platform 'BGN' is not valid in Facebook platform - https://developers.facebook.com/docs/marketing-api/currencies/

**Comment by Aleksandr111111111** [comment]
thanks

**Comment by Aleksandr111111111** [comment]
Hello
Why in previous versions of the module Facebook had currency, but now it has been removed? what should i do how to get the currency back?

**Comment by Aleksandr111111111** [comment]
The Bulgarian currency has been for five years, but now there is no way to work?
