### ISSUE TITLE
Facebook Ads extension for Opencart 3.x?

### ISSUE THREAD

**Issue by farhanabbas1983** [facebookincubator/Facebook-For-OpenCart#5]
Please let me know when you people are going to deliver an update of Facbeook Ads Extension for Opencart 3.0.2 version. I am populating a store of my client and he is interested in connecting facebook page / shop with his opencart store. I tried the existing plugin but it gives internal server error. 

Hope I will get a positive answer soon.

Regards,

**Comment by shue249** [comment]
Thank you for your feedback! Supporting OpenCart 3.0.2 is on our roadmap. We will inform you soonest when we have clearer visibility on the release date.

**Comment by kunalfule** [comment]
I have developed the opencart store for my client which has multi-stores. Please let me know when will be the extension will be available for opencart 3.0.2.

**Comment by easydev10** [comment]
One the facebook ads extension is here if you want you can download it.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=28804

**Comment by shue249** [comment]
@easydev10  Thank you for your feedback!

Our Facebook Ads Extension is officially developed and supported by Facebook. In addition to pixel, we are also providing support for automated catalog setup and Facebook Page Shop creation.

The work for supporting Opencart v3.x is already ongoing and we are projecting launching the plugin in June. Thank you all for your patience and we will inform everyone soonest when it is ready.

**Comment by ILDaviz** [comment]
shue249, do you need some help for the conversion?

**Comment by shue249** [comment]
Hi! We are pleased to announce the release of our v2.0.0 of our plugin which supports OpenCart v3.0.2.0b

Facebook Ads Extension
Latest version: 2.0.0

Change log
2.0.0 - 12 June 2018
* Supported OpenCart v3.x
** OpenCart v3.x users need to perform 1 more step - access Extensions -> Extensions -> Select Modules -> Click on the green Install button for Facebook Ads Extension
* Deprecated facebookproduct/directcheckout endpoint for products in FB Page shop. All products will now be linked directly to their correspondents in the web store front
* Extended the plugin validation checks to dashboard and product modules to ensure that the required files and database tables in Facebook Ads Extension module are intact

**Comment by kunalfule** [comment]
after installing the new update it's showing the error "The directory admin/controller/facebook is not allowed to be written to!". While trying to install extension through "Extension Installer".

**Comment by shue249** [comment]
@kunalfule We have released the new version v2.0.1 which fixes your problem.

**Comment by kunalfule** [comment]
@shue249: I'm using opencart 3.0.2.0. The previous issue was of opencart 3 not on 
Version2

**Comment by shue249** [comment]
@kunalfule We have released a version 2.0.2 of our Facebook Ads Extension plugin. This version supports for OpenCart 3.x. Can you download this version from OpenCart marketplace - https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336

**Comment by dunamit** [comment]
> @kunalfule Hello!
> I have problem when i am going to edit the facebook_ads_extension under the module it give me the error page not found path(extension/module/facebookadsextension_installer&user_token=4rf7et7r0NuqX1dsfh1Hn8reE5ijTjXQ) Where really the index function can not exist.. I am using latest version.
> Best Regd:Mashum
> Thanks!

Hello! Opencart 2.1.0.2 the same problem

**Comment by easydev10** [comment]
Dear,

Please share with us the updated ftp and admin credentials.

Regards

**Comment by shue249** [comment]
Hello all. We DO NOT require any ftp details nor admin credentials. Please DO NOT share out such details with anyone.

@easydev10 We have reported you as abuse to guithub moderator.

**Comment by KyleVanAswegen** [comment]
Hi Everyone,

Can anyone please help me. I'm am using OC V 3.0.3.6

Can one advise if there is a version of the FB Ads extension for OC 3.0.3.6 or which version on OC I can use to get the FB Ads extension to work?

Also another question I have been wanting to find out but can't seem to find.... Is the Products Data base for 3.0.3.2 different to the data base for for 3.0.3.6?

Hope someone can help me

**Comment by Sameerkashmirbox** [comment]
An error occured while generating system user access token: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.
