### ISSUE TITLE
Facebook helper do not detect any pixel conversion codes

### ISSUE THREAD

**Issue by papke88** [facebookincubator/Facebook-For-OpenCart#50]
Hello,

I have installed your module, everything connected, the catalog was created but when i check website with Facebook pixel helper I cannot see any conversion pixels.... what might be wrong?

**Comment by shue249** [comment]
@papke88 Thank you for your feedback! What is your store website URL?

**Comment by papke88** [comment]
Hello,

http://dev.cr7shop.lt <http://dev.cr7shop.lt/>

The module is now installed and activated, but facebook pixel helper do not detect it…

Regars,
Rokas V.

**Comment by shue249** [comment]
@papke88 
I can see that the pixel is firing on my web browser.
![image](https://user-images.githubusercontent.com/11957585/47649242-99c32000-dbb7-11e8-98bc-844041d36294.png)
![image](https://user-images.githubusercontent.com/11957585/47649290-c840fb00-dbb7-11e8-8d57-118a47bdf914.png)

However, I see that the checkout page is not firing the pixel. Are you using any custom checkout module instead of the default Opencart checkout?

**Comment by shue249** [comment]
@papke88 
2 possible reasons that I know of:
1. Did you opt out of the cookie consent? If you opt out of cookie, the pixels will not be fired. Can you try to opt in?
2. Are you on incognito mode?

**Comment by papke88** [comment]
On my web browser i san see only opt out button. We have our own cookie bar and might be the css files have the same name with yours, so might be why styles are shown not properly. is it possible to shut down your cookie bar from the module?




Regars,
Rokas V.

**Comment by shue249** [comment]
Yes, we are working on this now.

**Comment by papke88** [comment]
So you say that my problem is only because opt out on consensus bar? When you plan to release availability to turn of the cookie bar?

Regars,
Rokas V.

**Comment by shue249** [comment]
We can test out the newer version once its available to see if it solves your problem.

We are working on this ow and should be ready in the next 1-2 weeks.

**Comment by papke88** [comment]
Can you please inform me when its ready to test?


Regars,
Rokas V.

**Comment by shue249** [comment]
Yes, that is definitely the plan. We will update you soonest when it is ready.

**Comment by papke88** [comment]
Hello,

Maybe you have fixed all errors and updated your module?


Regars,
Rokas V.

**Comment by papke88** [comment]
Did you turn off the consensus bar?

Regards,
Rokas V.

**Comment by shue249** [comment]
@papke88 Apologies for the late reply. After you install the latest version of the plugin, 2.1.2, you will be able to turn off the cookie bar from the Facebook Ads Extension module.

![image](https://user-images.githubusercontent.com/11957585/48874213-020ac780-ee2d-11e8-891e-e3ac8a5dfd74.png)

**Comment by papke88** [comment]
Yes I know, i did it and the cookie bar is gone. But my oroginal cookie bar css is still affected and changed cause you css file and my css orginal css files are with the same name. So the design is affected of borh cookie bars and even if I turn off your cookie bar it does not change nothing. You can check how it looks my original cookie bar on on dev.cr7shop.lt (affected by the same name of css) and on cr7shop.lt (without your plugin installed). So for this problem i would like to change your cookie bar css file’s name but when I do, I get an error cause its needed to change some places in other files which I do not know and I hope you will tell me. 

The second problem is that regardless if I turn off or turn on your cookie bar the pixel do not appear on my page when I check with pixel helper. Basically same problem as was in older version. One of your suggestions was that your cookie bar block all cookies until I opt in, but I cant optin because of the first one problem i mentiones above: dublicate css names with my original cookie bar affects the design of your cookie bar and i cant see the opt in button anythere. Also the question would be if i turn off your cookie bar does it really turns off the need to opt in to see the pixel? If it really does then the problem of pixel not showing up might be elsewhere that I hope you will help to find. My logins to the site you have (sent you via support ticket)

Looking forward to get yout answer!

Regards,
Rokas V.

**Comment by papke88** [comment]
Still waiting for your answer!


Regars,
Rokas V.

**Comment by shue249** [comment]
Reopening the issue as the pixel is still not tracked

**Comment by papke88** [comment]
Hello,

Any news on the problem? is it possible for you to try delete completely cookie bar from the code and I try to install? I believe it might help...

**Comment by papke88** [comment]
?

**Comment by shue249** [comment]
@papke88 We are terribly sorry for the late reply and really appreciate your time and patience.

We are happy to inform you that we have released a new version v2.1.3 to address your cookie bar naming conflict issue. Can you install the version either from OpenCart or https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3

Let us know if this works.

**Comment by papke88** [comment]
Just tried updated extension, looks like it works fine, just cant track the pixel on success page, the pixel helper do not show it. Can you check it?

Success page is here
https://cr7shop.lt/atsiskaitymas-sekmingas

**Comment by papke88** [comment]
also cant see the pixel "checkout initianed"

**Comment by shue249** [comment]
@papke88 Thank you for the feedback. We have created another ticket to follow up on this https://github.com/facebookincubator/Facebook-For-OpenCart/issues/82

We will close off this ticket for the cookie bar issue.
