### ISSUE TITLE
[BUG] Oops, something went wrong. Version of OpenCart 3.0.3.6 (Store upgrade from 2.3.0.2 to 3.0.3.6) 3.1.0 (Module upgrade from 2.0.1)

### ISSUE THREAD

**Issue by danailddd** [facebookincubator/Facebook-For-OpenCart#502]
**Webstore Url**
goldenshop.bg

**FBE plugin version**
3.1.0 (Module upgrade from 2.0.1)

**OpenCart version**
Version of OpenCart 3.0.3.6 (Store upgrade from 2.3.0.2 to 3.0.3.6)

**Describe the bug**
Oops, something went wrong.
This may be because of a technical error that we're working to get fixed. Try reloading this page.

**To Reproduce**
Install https://github.com/facebookincubator/Facebook-For-OpenCart/releases/download/v3.0.1/facebook_ads_extension.ocmod.zip

Install and Enable in Extensions

Go to / Facebook  Business Extension

Get started > Next on all prevouosly working options ( on version 2.0.1) 

Getting the error  "Oops, something went wrong. This may be because of a technical error that we're working to get fixed. Try reloading this page."

Error Log:
2020-11-03 13:31:26 - Facebook Ads Extension version = 3.1.0
2020-11-03 13:31:26 - OpenCart version = 3.0.3.6
2020-11-03 13:31:26 - PHP version = 7.3.21
2020-11-03 13:31:26 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-11-03 13:31:26 - Pixel ID = true
2020-11-03 13:31:26 - Pixel use PII = true
2020-11-03 13:31:26 - Use S2S = false
2020-11-03 13:31:26 - Page ID = false
2020-11-03 13:31:26 - System User Access Token = false
2020-11-03 13:31:26 - Messenger plugin = false
2020-11-03 13:31:26 - Messenger customization locale = false

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome/Firefox
 - Version: Latest

**Additional context**
 We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

This is staying regardless of anything.

**Comment by linuxchips** [comment]
same here, i also think #507 is also the same issue here

**Comment by jakemake** [comment]
any solutions?

**Comment by tomeda** [comment]
Same here OC v.2.1.0.2 and Facebook Ads Extension version = 3.1.1? Does anyone know which is the last one of the old versions that are working so I can downgrade to it?

**Comment by yao-tx** [comment]
Hi guys,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
