### ISSUE TITLE
[BUG] products rejected due to errors opencart 3.0.3.6, facebook Plugin Version: 3.1.0, Pixel not ready

### ISSUE THREAD

**Issue by tosswithim** [facebookincubator/Facebook-For-OpenCart#504]
**Webstore Url**
https://www.addfresh.in/

**FBE plugin version**
Plugin Version: 3.1.0

**OpenCart version**
Version 3.0.3.6

**Describe the bug**
A required field is missing:
link
link
Products without "link" information can't be uploaded. Please check that this field is included for each product in a separate, labeled column.

This url is classified as malicious:
image_link
image_link
This link goes against our community standards. Please either change the URL or contact the account manager to whitelist it.

Add Items With Pixel
Pixel
Not ready

[Debug microdata ](https://business.facebook.com/ads/microdata/debug?url=https%3A%2F%2Fwww.addfresh.in%2Findex.php%3Froute%3Dproduct%2Fproduct%26product_id%3D33)

Errors
Products on your website can't be automatically added to your catalog because of these issues.
Errors
A required field is missing: image_link
Products without "image_link" information can't be uploaded. Please check that this field is included for each product in a separate, labeled column.
A required field is missing: price
Products need to have prices to run in ads. Include a price for each product in your data feed file and upload it again. Prices must include cost and an ISO currency code (for example: 10 USD instead of $10 for American dollars).

**To Reproduce**

**Screenshots**
Screenshots attached for your reference. 
![image](https://user-images.githubusercontent.com/11146222/98485028-939dba80-2239-11eb-9101-124b8a16d4c8.png)

![image](https://user-images.githubusercontent.com/11146222/98485059-b6c86a00-2239-11eb-9d86-2dac7d978bc4.png)
![image](https://user-images.githubusercontent.com/11146222/98485080-cfd11b00-2239-11eb-8c19-42faf700b80d.png)

**Desktop (please complete the following information):**
 OS: Windows 10
Browser: Chrome/Firefox
Version: Latest

**Additional context**
We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.

Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
Ensure that you have Refresh the modifications, View steps
For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

**Comment by yao-tx** [comment]
Hi @tosswithim 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!

**Comment by tosswithim** [comment]
found error Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!

**Comment by yao-tx** [comment]
Hi @tosswithim 

Please kindly refer to the installation guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#pre-requisites-prior-to-installing-the-plugin), Point (9):

> Since our plugin uses the Facebook Business SDK internally, the plugin file size might exceed your pre-defined PHP upload_max_filesize value. You may need to increase the value of upload_max_filesize for your web server in order to install the plugin.
