### ISSUE TITLE
facebook business extension[BUG]

### ISSUE THREAD

**Issue by doandbe** [facebookincubator/Facebook-For-OpenCart#505]
**Webstore Url**
Your webstore Url 
www.doandbe.gr

**FBE plugin version**
Version of FBE plugin
2.2.1
**OpenCart version**
Version of OpenCart
2.3.0.2

**Describe the bug**

facebook catalog dont accept discounts made by Multi discount pack on categories , every time I change the category discount I have to go on each product an put a new price on special prices so that can be showed on facebook catalago.

that is a kind a serious problem please help me solve it 

thanks 

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by yao-tx** [comment]
Duplicate with #506
