### ISSUE TITLE
fault when using opencart 3.0.3.3 and vqmod

### ISSUE THREAD

**Issue by robteeshirtguy** [facebookincubator/Facebook-For-OpenCart#508]
hi i keep getting this error when using vqmod and facebook module
if i disable the facebook module my site works fine, if i disable vqmod facebook module works fine but not togetter
here the error im getting hope you can help with a fix
Warning: require_once(/home3/robert123/testing.com/vqmod/vqcache/vendor/autoload.php): failed to open stream: No such file or directory in /home3/robert123/testing.com/vqmod/vqcache/vq2-system_library_facebookcommonutils.php on line 8
Fatal error: require_once(): Failed opening required '/home3/robert123/testing.com/vqmod/vqcache/vendor/autoload.php' (include_path='.:/opt/php71/lib/php') in /home3/robert123/testing.com/vqmod/vqcache/vq2-system_library_facebookcommonutils.php on line 8

**Comment by panxonuker** [comment]
hi i solved the problem by copying the vendor folder of the fb extension to vqcache

**Comment by yao-tx** [comment]
Hi @robteeshirtguy 

The FBE plugin does not support vQmod. Please refer to @panxonuker solution and it should resolve the error.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
