### ISSUE TITLE
CART PAGE NOT WORKING : The page you requested cannot be found!

### ISSUE THREAD

**Issue by myartmarket** [facebookincubator/Facebook-For-OpenCart#509]
**Webstore Url**
https://artmarket.ge/

**FBE plugin version**
Facebook 3.1.1

**OpenCart version**
OC 3.0.3.6

**Describe the bug**
after that user add product in cart they can't access to cart page and i get this error "The page you requested cannot be found!"...
but when uninstall plugin then everything is ok 

**To Reproduce**

**Screenshots**
SCREENSHOT LINK : https://prnt.sc/vm21kd

**Desktop (please complete the following information):**
 - OS: 3.0.3.6
 - Browser Chrome, Safari and etc
 - Version 3.1.1

**Additional context**
after that user add product in cart they can't access to cart page and i get this error "The page you requested cannot be found!"...
but when uninstall plugin then everything is ok

**Comment by wammachado** [comment]
Estou com o mesmo problema, alguem ja possui a solução?

**Comment by zigi00x** [comment]
system/library/facebookcommonutils.php change line 8 to require_once DIR_SYSTEM . 'library/vendor/autoload.php';

**Comment by myartmarket** [comment]
I change : system/library/facebookcommonutils.php change line 8
FROM : require_once __DIR__ . '/vendor/autoload.php';
TO : require_once DIR_SYSTEM . 'library/vendor/autoload.php';
as you mention above and also clean cache, Refresh Modifications and anyway the same result still can't access to CART 
Please help what i miss or what can i do ?

**Comment by zigi00x** [comment]
Do you have some errors in error log?

**Comment by myartmarket** [comment]
NO i Check twice in OC menu and on SERVER also....

**Comment by zigi00x** [comment]
Do you have some plugins what affect cart?

Have you tried disable some plugins?

Have you tried installing a plugin FB on a clean oc template?

**Comment by myartmarket** [comment]
only one plugin "Multivendor" and when i delete FB Plugin then works good - OK, Now i'll try install only FB and Give you answer ASAP...

**Comment by myartmarket** [comment]
As i tested only FB Plugin have Issue....

**Comment by wammachado** [comment]
> I change : system/library/facebookcommonutils.php change line 8
> FROM : require_once **DIR** . '/vendor/autoload.php';
> TO : require_once DIR_SYSTEM . 'library/vendor/autoload.php';
> as you mention above and also clean cache, Refresh Modifications and anyway the same result still can't access to CART
> Please help what i miss or what can i do ?

don't work

**Comment by wammachado** [comment]
> system/library/facebookcommonutils.php change line 8 to require_once DIR_SYSTEM . 'library/vendor/autoload.php';

don't work

**Comment by zigi00x** [comment]
I recommend contacting the template manufacturer.. What template are you using?

**Comment by myartmarket** [comment]
I think issue in FB plugin because other people also have problem like this, and i have tested on default template also and same problem, everything works good before install FB plugin, I've teated almost everything with default plugin, with only FB plugin, other templates also and result FB plugin have issue

**Comment by zigi00x** [comment]
This problem seems to appear in oc 3.0.3.6.

**Comment by Murfur** [comment]
I don't think it is a clash with other extensions.

I got the same error in a client site running on OC 3.0.2.0 with Jupiter theme and several extensions.
As part of my diagnosis, I Installed the 3.1.1 extension on a fresh vanilla install of OC 3.0.2.0 and then OC 3.0.3.6 as well, both with no other extensions or themes. In both cases, everything is fine until you connect the extension to Facebook and then any attempt to view the cart or checkout generates the 'not found' message.

I had to walk the extension back to version 2.1.10 to make it work. _Every_ version after 2.1.10 generates the 'not found' error

**Comment by myartmarket** [comment]
OC 3.0.3.6
THEME : Journal 3
FB v3.0.1

Everything works good with other extensions also

**Comment by yao-tx** [comment]
Hi all,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
