### ISSUE TITLE
"FACEBOOK BUSINESS APP IS NOT SYNCHRONIZING ALL PRODUCT CATEGORIES CANT DO ADS"

### ISSUE THREAD

**Issue by doandbe** [facebookincubator/Facebook-For-OpenCart#511]
Webstore Url
Your webstore Url
www.doandbe.gr

FBE plugin version
Version of FBE plugin
3.1.1
OpenCart version
Version of OpenCart
2.3.0.2

**Describe the bug**
FACEBOOK BUSINESS APP IS NOT SYNCHRONIZING ALL PRODUCT CATEGORIES ON THE CATALOG ALTOUGH IS SHOWING ALL PRODCUTS, THEREFORE I AM NOT ABLE TO MAKE ADS USING PRODUCT CATALOG AND CHOOSING THE CATEGORIES I NEED TO ADVERTISE!!! THIS IS A SERIOUS ISSUE PLEASE ADVISE AS SOON AS POSSIBLE 

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by doandbe** [comment]
NO HELP AT ALL???NO SUPPORT AFTER ALL YOU JUST INSTALL EXETENSIONS AND THERE NOBODY TO HELP YOU

**Comment by yao-tx** [comment]
Hi @doandbe,

The FBE plugin will not be able to synchronise every Category as the Facebook Catalog restricts items to only one category per product.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The new plugin also provides you with a way to assign a specific Google Product Category to your products under the 'Facebook' tab in your product configurations.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
