### ISSUE TITLE
[BUG] Cannot Install Plugin - Error "An error occurred while fetching FBE Install config"

### ISSUE THREAD

**Issue by baron-kg** [facebookincubator/Facebook-For-OpenCart#512]
**Webstore Url**
www.eparhija.com

**FBE plugin version**
3.1.1

**OpenCart version**
OpenCart 3.0.3.3

**Describe the bug**
The bug appears after clicking on the final step of the plugin setup. Once clicked the plugin loads for a short time after witch a screen appears that states the following: "Oops, something went wrong.". After closing that window a popup appears that states that "An error occurred while fetching FBE Install config".

_**What I know is that the problem is with our website since I have tried to install the plugin on a clean OpenCart 3.1.1 installation and it works fine.**_

Could you please suggest where to look for the solution to this problem? Is it perhaps some other plugin that we have installed?

**Screenshots**
The error that appears at the end of the setup process: https://i.imgur.com/SS7UMdK.png
The error that appears after the window from the previous screenshot is closed: https://i.imgur.com/uhTZdlA.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.66

**Comment by stavtime** [comment]
The same error. How to fix? What could be the problem?

**Comment by yao-tx** [comment]
Hi @stavtime  @baron-kg 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
