### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FoZo** [facebookincubator/Facebook-For-OpenCart#513]
**Webstore Url**
popi.se

**FBE plugin version**
311

**OpenCart version**
3.0.2.0

**Describe the bug**
Wrong sale_price and sale_price_effective_date

**To Reproduce**
1. Update catalog data 
2. Check prices

**Additional context**
It looks like index.php?route=extension/facebookfeed/genFeed does not provide the correct information about current "special offers" and does not fetch the correct data from the database -> oc_product_special

**Comment by yao-tx** [comment]
Hi @FoZo 

Sorry that this might be a little late.

Just an update that a new version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) is available for download on the [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions. This includes the way the old FBE plugin was pulling the special prices from database. With the new version, the correct special price should be pulled.

That being said, if you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com).

Thank you!
