### ISSUE TITLE
Messenger Bubble not visible on mobile view

### ISSUE THREAD

**Issue by rhinsu** [facebookincubator/Facebook-For-OpenCart#515]
hello there,
is the messenger bubble not visible on mobile view, or how do i enable it.

**Comment by yao-tx** [comment]
Hi @rhinsu 

This might be a little late but the Facebook Messenger bubble should work and appear in mobile view.

Also, there is a new version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) available for download at [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We've revamped the entire FBE plugin, made improvements to it and resolve many bugs and issues that users are having with the previous versions.

That being said, if you encounter any further issues with the plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
