### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by akulyhin** [facebookincubator/Facebook-For-OpenCart#518]
**Webstore Url**
https://magmus.com.ua

**FBE plugin version**
3.1.1

**OpenCart version**
OcStore 2.3.0.2.3

**Screenshots**
I have a problem after install module: 1) https://prnt.sc/vtlyu5  2) https://prnt.sc/vtlzm9

**Comment by yao-tx** [comment]
Hi @akulyhin 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, made improvements to the plugin and resolved most of the bugs and issues that users are having with the previous versions. This should resolve the issues you are having.

That being said, if you are still encountering any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
