### ISSUE TITLE
An error occured while generating system user access token: Fail to create client business on behalf of client: When you try to create client business on behalf the client business user, it fails

### ISSUE THREAD

**Issue by gahan76** [facebookincubator/Facebook-For-OpenCart#521]
Hello, 
  We are trying to inegrate Plugin Version: 3.1.1  with OpenCart 3.0.2.0.
  We saw problem with BGN currency and solved it by switching to euro.

 All steps passed and we see button "done".
 But when press it, error message popup :

An error occured while generating system user access token: Fail to create client business on behalf of client: When you try to create client business on behalf the client business user, it fails

 We can not see pixel active on site and plugin menu in opencart is still waiting to be configured.
 In facebook profile we can see OpenCart system account, Opencart App and other setup info after all.

How can we solve it, can anyone help us ?

Regards

**Comment by yao-tx** [comment]
Hi @gahan76 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
