### ISSUE TITLE
Issue in OpenCart 3.0.2.0 FB Plugin Version: 3.1.1

### ISSUE THREAD

**Issue by incrediblegifts** [facebookincubator/Facebook-For-OpenCart#522]
Hi

I followed all the steps mentioned in Guthub while installing Facebook Extension, but its not working on my website www.incrediblegifts.in

The Extension showing following warnings, even after i followed all the steps mentioned in warning.
" We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps"

Folder permissions are 755, i hope this is fine, bcoz changing it stopped admin panel of opencart
Modification Refresh done, SASS Cache steps done, Header Design Step Done....

I tried all the possible ways that i could find but pixel is not installed in my website.  Facebook  Pixel Helper is not showing the pixel. I checked View Source and there were no PIXEL HTML installed. Kindly help

![image](https://user-images.githubusercontent.com/75425626/101010643-5ef6f780-3588-11eb-8f4a-2b00b2ffe107.png)

![image](https://user-images.githubusercontent.com/75425626/101011624-a7aeb080-3588-11eb-8495-da8541746ba8.png)

**Comment by incrediblegifts** [comment]
Another Thing happened after installing Facebook Extension, View Cart and Checkout Page showing 501 Server error. and When i am disabling this plugin these pages working fine.

**Comment by hostibr** [comment]
Hey how is everything !? Managed to solve ?

**Comment by hostibr** [comment]
> Hi
> 
> I followed all the steps mentioned in Guthub while installing Facebook Extension, but its not working on my website [www.incrediblegifts.in](http://www.incrediblegifts.in)
> 
> The Extension showing following warnings, even after i followed all the steps mentioned in warning.
> " We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
> 
> 1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
> 2. Ensure that you have Refresh the modifications, View steps
> 3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
> 4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps"
> 
> Folder permissions are 755, i hope this is fine, bcoz changing it stopped admin panel of opencart
> Modification Refresh done, SASS Cache steps done, Header Design Step Done....
> 
> I tried all the possible ways that i could find but pixel is not installed in my website. Facebook Pixel Helper is not showing the pixel. I checked View Source and there were no PIXEL HTML installed. Kindly help
> 
> ![image](https://user-images.githubusercontent.com/75425626/101010643-5ef6f780-3588-11eb-8f4a-2b00b2ffe107.png)
> 
> ![image](https://user-images.githubusercontent.com/75425626/101011624-a7aeb080-3588-11eb-8495-da8541746ba8.png)

Hey how is everything !? Managed to solve ?

**Comment by yao-tx** [comment]
Hi @incrediblegifts @hostibr,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
