### ISSUE TITLE
[BUG] There is an error with Facebook Ads Extension setup OPENCART

### ISSUE THREAD

**Issue by Oblivion91** [facebookincubator/Facebook-For-OpenCart#523]
Hi there, I am writing to you with a problem that appeared on our website www.supraten.md. I am attaching a screenshot of the problem, we did everything according to the instructions, but the problem remains, could you help us, what should we do next?
![fb ex](https://user-images.githubusercontent.com/75472120/101138745-45ea5700-3619-11eb-8170-9e55e822121f.png)
![fb ex 2](https://user-images.githubusercontent.com/75472120/101139745-a75ef580-361a-11eb-9c7e-b97afec27503.png)
Website - www.supraten.md
Extension - Facebook 
Ads Extension setup
Opencart version - Version 3.0.3.2 (trs-3.0.2.0)
Problem - There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup. Please contact Facebook via our Github if this error keeps showing. The sync failure of your products to Facebook may be because of the large number of products on your system (We detected 61753 products).

Looking forward to hearing from you.

**Comment by cojocaru88** [comment]
Добрый вечер Supraten.md
Таже проблема. Никак не мог разрешить. Никто не смог помочь. Решение нашел без данного модуля. 
Ваш бывший поставщик с Кишинева. cojocaru88@mail.ru. Отправьте ваш email и я отпишусь если смогу решить вопрос. Мы будим завтра тестить. Надеюсь получить полный Remarketing

**Comment by yao-tx** [comment]
Hi @Oblivion91 @cojocaru88 ,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
