### ISSUE TITLE
[BUG] Catchable fatal error: Argument 1 passed to FacebookAds\CrashReporter::buildParamsFromException() must be an instance of Throwable, instance of ErrorException

### ISSUE THREAD

**Issue by ImpalerF5** [facebookincubator/Facebook-For-OpenCart#524]
**FBE plugin version**
3.1.1 (latest version at the time)

**OpenCart version**
3.0.3.3

**Describe the bug**

**To Reproduce**
Plugin works for some time but after a weeks time use it break with error shown below when you go to the checkout. 

**Screenshots**
![error](https://user-images.githubusercontent.com/75830049/101875703-c79b3100-3b93-11eb-929f-c62b80f6c84e.jpg)

**Comment by yao-tx** [comment]
Hi @ImpalerF5 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
