### ISSUE TITLE
Problem with installing the extension - Internal Server error

### ISSUE THREAD

**Issue by svremeto** [facebookincubator/Facebook-For-OpenCart#525]
Hello, when I load the ocmod file I receive this message: https://prnt.sc/w1n8qp
I tried to upload manually the files but it doesn't work again.

**Comment by yao-tx** [comment]
Hi @svremeto ,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The latest version of the FBE plugin does not use OCMOD at all (only for OpenCart versions 2.3 and above). 

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
