### ISSUE TITLE
Special Offer Prices dosen't taken in account at Version 3.1.1 & Opencart 2.1.0.2 

### ISSUE THREAD

**Issue by geolits** [facebookincubator/Facebook-For-OpenCart#528]
Hello,

i have installed the extension v 3.1.1. at our opencart eshop version 2.1.0.2

I have Follow the instractions but when i check the "Sync Product Special" at this picture:

https://drive.google.com/file/d/1CSeaZ0BPsue6eNKsLHXjahodXWgNh5ss/view

There is no button ""ResyncProducts to Facebook".

Also i went at Facebook Catalog, i did a refresh ther to resync the catalog but again the prices we have at "Special Offers", for our default customer group, are not taken in account.

How can we take our special offers in account at our facebook catalog?

Thank you

**Comment by geolits** [comment]
Hello,

just an information. I see that the final visitor (view as visitor), can see in the catalog in facebook the discount values. 

But if a product has more than one special prices, for different customer groups, it takes the smaller discounted price,

How is the extension is working with the special prices?

It would be a good idea to take the default customer prices, or to have the extension a choice form which customer group the prices to get retrieved.

Thank you

**Comment by yao-tx** [comment]
Hi @geolits,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

For the new FBE plugin (v4.0.1), there is a change in how the special prices is being pulled to be sent to Facebook Catalog as Sale price. The new setup is to pull the special price just like how OpenCart would for the default customer group. If you need to the plugin to pull the special price in a different way, you will have to make modifications to it.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
