### ISSUE TITLE
Facebook helper do not detect any pixel conversion codes and wrong catalog category

### ISSUE THREAD

**Issue by afourcustom** [facebookincubator/Facebook-For-OpenCart#53]
Hello. Everything is established but the pixel does not collect information, and the application for Chrome does not see it, what could be the problem? 
PS Catalog of goods unloaded without problems. Only a breakdown into categories is a strange part of the categories in Russian (primary language) in English. Be trusted 3.0.2

afourcustom.ru

**Comment by shue249** [comment]
@afourcustom Thanks for the feedback!

We found that an important javascript file is not inserted into the header file resulting in the pixels not fired. Let us look into improving the plugin and we will inform you once we have this ready.

**Comment by afourcustom** [comment]
ok, i will wait for the news from you

**Comment by shue249** [comment]
@afourcustom Do you have any extensions which will compress javascript files on your website? We are trying to figure out why our javascript is not loaded and we noticed that the default opencart js files are also not loaded on your website. So we wanted to learn more

**Comment by afourcustom** [comment]
i use this plugin https://opencartforum.com/files/file/2172-opencart-lightning/

**Comment by afourcustom** [comment]
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=8068&filter_member=MaxD

**Comment by afourcustom** [comment]
hello. It turns out to solve the problem?

**Comment by shue249** [comment]
@afourcustom Thank you for your patience and apologies it took us time to solve the problem.

We have released a new version 2.1.3 to address this issue. You can either download from OpenCart or from here https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3.

We will close out the ticket, but feel free to let us know if there's further questions.
