### ISSUE TITLE
 an error occurred while generating system user access token: Unavailable app data cannot be shared: This app's data is unavailable and can't be shared.[BUG]

### ISSUE THREAD

**Issue by kokaboracreations** [facebookincubator/Facebook-For-OpenCart#531]
**Webstore Url**
www.kokabora.com

**FBE plugin version**
3.1.1
NOTE: the error happened after upgrading to version 3.1.1; reverted back to v2.2.1

**OpenCart version**
2.2.0.0

**Describe the bug**
a error box appeared with " an error occurred while generating system user access token: Unavailable app data cannot be shared: This app's data is unavailable and can't be shared." upon completion of the steps under "manage settings".

**To Reproduce**
NOTE: this error happened upon upgrade of the extension from 2.2.1 to 3.1.1. The v2.2.1 is already linked to an active Facebook/Instagram shop
1. Log in admin panel
2. Go to "extensions"-->"modifications"
3. Delete the existing "facebook business extension"
4. Go to "Extension" --> "extention installer"
5. Upload the new extension
6. Click "continue" to overwite existing files
7. Refresh the modifications
8. Go to the "facebook business extension"
9. click on Manage settings button
10. Review and click next on information
11. one the last step is complete and the modal box disappears, the error appears.

**Screenshots**
n/a - I did not take screen shots before referting to v 2.2.1

**Desktop (please complete the following information):**
 - OS: Windows 10 / linux debian 9 (2 computers used)
 - Browser chrome 
 - Version Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
This was an upgrade from v2.2.1 which was working.

**Comment by yao-tx** [comment]
Hi @kokaboracreations 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
