### ISSUE TITLE
After setting the extension and click Done I receive an error

### ISSUE THREAD

**Issue by svremeto** [facebookincubator/Facebook-For-OpenCart#532]
**Webstore Url**
https://forefathers-art.com/

**FBE plugin version**
3.1.1

**OpenCart version**
2.3.0.2

**Describe the bug**
After Get Started, settings and click Done I receive an error: "An error occured while generating system user access token: Unavailable app data cannot be shared: This app's data is unavailable and can't be shared."

**Screenshots**
https://prnt.sc/wf9gcj

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Crome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
I see with the "Facebook Pixel Helper" that there is no pixel on the website. The chat is working. The catalog is not working.
I followed strictly the upgrading steps. I refreshed the modifications. The permissions of the admin, catalog and system folders are 755.

**Comment by mzilyaev** [comment]
Hi bro, I have same problem. Have you solved it?

**Comment by svremeto** [comment]
@mzilyaev No, still waiting for their responce.

**Comment by rodrigobsm** [comment]
Same here guys. :(

**Comment by umagenta683** [comment]
Same here..

**Comment by svremeto** [comment]
@dtying tried to install the newest version but no success. https://prnt.sc/y566dq

**Comment by yao-tx** [comment]
Hi guys,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
