### ISSUE TITLE
O problema é Há um erro na configuração da extensão de anúncios do Facebook. Clique em Facebook Ads Extension, Manage Settings, vá para Advanced options e clique em Delete Settings para reiniciar a configuração. Entre em contato com o Facebook através do nosso Github se este erro continuar aparecendo.   Eu não sei como solucionar este problema...

### ISSUE THREAD

**Issue by Veiga1978** [facebookincubator/Facebook-For-OpenCart#534]
Eu cliquei em management settings e não consegui fazer a atualização ? Tem como me ajudar por favor ?
Existe uma forma em video que explique como devo fazer ?
 Você pode atualizar para mim ?

**Comment by yao-tx** [comment]
Hi @Veiga1978 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
