### ISSUE TITLE
error occured while generating system user access token

### ISSUE THREAD

**Issue by mzilyaev** [facebookincubator/Facebook-For-OpenCart#535]
website - https://belok.shop/

FBE - 3.1.1.
Opencart -  2.3.0.2.3

After I push Get started and connect with FB and push then Done I get this message.
**An error occured while generating system user access token: Unavailable app data cannot be shared: This app's data is unavailable and can't be shared.**

**Comment by guilhermeojs** [comment]
Having the same issue. Did you manage to fix it somehow?

**Comment by rodrigobsm** [comment]
Same error here! No way to fix it so far.

**Comment by umagenta683** [comment]
Same problem here: OC version v3.2.0.2, Extension v3.1.1.

**Comment by yao-tx** [comment]
Hi guys,

A new version of the Facebook Business Extension plugin for OpenCart is available on [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). You might wish to download it as we've recently revamped the entire plugin, made improvements to the plugin and resolved many bugs and issues that users are having with the previous versions.

If you are still encountering issues with the new FBE plugin, please reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
