### ISSUE TITLE
Server Sending Invalid Match Key Parameters for AddToCart Event

### ISSUE THREAD

**Issue by PaulBogdanCom** [facebookincubator/Facebook-For-OpenCart#536]
Server Sending Invalid Match Key Parameters for AddToCart Event
Your server is sending an invalid ip_address, user_agent parameters value for your AddToCart event. This may be because there was an error in the parameter value.
This may cause issues with the attribution and delivery optimization of ad campaigns that are using this event.

OC 3.0.3.2 and FB Plugin 3.1.1

**Comment by PaulBogdanCom** [comment]
Also:
AddToCart Event Missing Some Deduplication Parameters
You're sending AddToCart events through both your pixel and the Conversions API, but they're not being deduplicated properly because not enough of these events are receiving an event_id parameter. Event instances sent without an event_id parameter cannot be deduplicated.
This may cause issues with the measurement of your events as well as the attribution and delivery optimization of any ad campaigns that are optimizing for this event.

**Comment by yao-tx** [comment]
Hi @PaulBogdanCom,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users were having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
