### ISSUE TITLE
[BUG]This app's data is unavailable and can't be shared

### ISSUE THREAD

**Issue by sch12-p** [facebookincubator/Facebook-For-OpenCart#538]
[Circlerecstore_2021-01-24_14-50-29_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/5862471/Circlerecstore_2021-01-24_14-50-29_facebook_ads_extension.log)
**Webstore Url**
http://www.circlerecstore.ru/

**FBE plugin version**
Plugin Version: 3.1.1 

**OpenCart version**
Version 3.0.3.6 (rs.1)

**Describe the bug**
When i press get started after last step i've got error in alert tab
"An error occured while generating system user access token: Unavailable app data cannot be shared: This app's data is unavailable and can't be shared"

**Comment by hridoy14104043** [comment]
Same Issue

**Comment by reginamor** [comment]
same issue
With my 2 online stores with diferents versions
2.0.3.2 and 3.0.3.6

**Comment by yao-tx** [comment]
Hi @sch12-p @hridoy14104043 @reginamor,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, made improvements to the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
