### ISSUE TITLE
Facebook Pixel Helper not detect any pixel

### ISSUE THREAD

**Issue by bobosg** [facebookincubator/Facebook-For-OpenCart#54]
I installed the enstension, I have correctly configured the catalog but I can't see any pixel...

**Comment by shue249** [comment]
@bobosg Thanks for the feedback, can you share your store website URL

**Comment by bobosg** [comment]
Thanks for the answer
The url is 2yield.it

**Comment by shue249** [comment]
@bobosg I am looking at the website, but could not see that the plugin has been installed. Want to check if you have removed away the plugin?

**Comment by bobosg** [comment]
I checked, the plugin is installed
![schermata 2018-11-08 alle 09 14 36](https://user-images.githubusercontent.com/4668507/48185900-be956100-e336-11e8-83c6-084c2ddd10f0.png)
![schermata 2018-11-08 alle 09 15 36](https://user-images.githubusercontent.com/4668507/48185958-e1c01080-e336-11e8-8b1f-f1d310ccae97.png)

**Comment by shue249** [comment]
@bobosg Thank you for the feedback. 

This is really strange as we are not sure what could have gone wrong.

1. Can you try to do a refresh of your opencart site from the admin panel.
![image](https://user-images.githubusercontent.com/11957585/48200104-1b296800-e399-11e8-9169-c9b892fa1a33.png)


2. What are the extensions you have installed on your opencart server?

**Comment by bobosg** [comment]
in fact it is strange that the pixel does not work
I have already updated


![schermata 2018-11-08 alle 14 16 23](https://user-images.githubusercontent.com/4668507/48200929-ef8a8b80-e360-11e8-8d74-b4726a979032.png)
![schermata 2018-11-08 alle 14 16 08](https://user-images.githubusercontent.com/4668507/48200930-ef8a8b80-e360-11e8-8709-8fa3ca83985e.png)
![schermata 2018-11-08 alle 14 15 54](https://user-images.githubusercontent.com/4668507/48200932-f0232200-e360-11e8-8514-a0d2a6487f66.png)

**Comment by shue249** [comment]
Yes, this is really weird. I checked on your website but could not find any reason why it should fail. Will you be able to share with us the log of the extension mod file? Specifically, I am looking for the references where it changed the /common/header.twig file as this is the place where we inserted in the pixel code.

Also, will you be able to see if the below screenshots make sense to you?

![image](https://user-images.githubusercontent.com/11957585/48238619-8e1cf800-e406-11e8-9aa6-1d9b912323be.png)

![image](https://user-images.githubusercontent.com/11957585/48238704-e8b65400-e406-11e8-9d36-e837d20b1610.png)

![image](https://user-images.githubusercontent.com/11957585/48238837-6bd7aa00-e407-11e8-8073-31c37309e56f.png)

**Comment by dalibordim** [comment]
Hi i have the same problem with the latest version of the plugin on OC 3.0.2
The installation went ok and i have the extension in my admin panel but no pixel code on the front end.
I checked on the default theme of OC and it works fine but not on my custom theme.
Any help or advice pls.
Thanks in advance

**Comment by shue249** [comment]
@dalibordim Thank you for your feedback and sorry to have dropped the ball on this. Will you be able to create a separate ticket for us to follow up separately.

**Comment by shue249** [comment]
@bobosg I will like to follow up on the previous comment. Will you be able to share the plugin installation log so that we can check deeper on the issue.

**Comment by shue249** [comment]
@bobosg , @dalibordim I will like to follow up on this. If you are using OpenCart 3.x and above, it could be a cache issue. Can you disable the cache and do a refresh modifications. 

![image](https://user-images.githubusercontent.com/11957585/52504109-65351a80-2c22-11e9-9ec1-84fd7f31fda4.png)
![image](https://user-images.githubusercontent.com/11957585/52504150-8269e900-2c22-11e9-9e1e-484705b1199a.png)
![image](https://user-images.githubusercontent.com/11957585/52504193-a1687b00-2c22-11e9-8246-769ef94565ef.png)

**Comment by shue249** [comment]
@bobosg , @dalibordim 

We have released a latest version of the plugin, v2.1.4 and can be downloaded from OpenCart marketplace or our github. The new version will resolve the issue with SEO URL.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.4

We will close out this ticket for now, but pls do reach to us if you still have any further questions or issues.
