### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ivan44443** [facebookincubator/Facebook-For-OpenCart#540]
[Gera Showroom_2021-01-29_00-08-51_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/5890839/Gera.Showroom_2021-01-29_00-08-51_facebook_ads_extension.log)
[Gera Showroom_2021-01-29_00-06-18_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/5890840/Gera.Showroom_2021-01-29_00-06-18_facebook_ads_extension.log)

**Webstore Url** gerabeauty.ru
Your webstore Url

**FBE plugin version**
Version of FBE plugin

**OpenCart version** 3.0.3.1
Version of OpenCart

**Describe the bug**Can't install the Facebook Business Extension. At first I installed the wrong version for my OpenCart.
The button is not pressed to adjust the pixel. I have attached the log files. I don't know English, I'm writing from a translator. 

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by yao-tx** [comment]
Hi @Ivan44443 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
