### ISSUE TITLE
OpenCart asking to update to 3.1.2 but release does not include OpenCart version 

### ISSUE THREAD

**Issue by mehtaman** [facebookincubator/Facebook-For-OpenCart#542]
Opencart Version: 3.0.3.6
Facebook Version: 3.1.1
Site: https://www.it-me-up.co.uk/

Admin Dashboard Shows this message:
A newer version of the Facebook Business Extension plugin is available. To download it, go to Github or OpenCart marketplace.

When I go to the release tab:
https://github.com/facebookincubator/Facebook-For-OpenCart/releases

The 3.1.2 version does not include the OpenCart format.
If I install the zip source data I get errors such as /vendor/autoloader.php not found

Could you please compile an OpenCart version?

**Comment by dtying** [comment]
Hi @mehtaman , sorry for the inconvenience. I've just uploaded the latest facebook_ads_extension.ocmod.zip [here](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.1.2), let me know if any issue.

**Comment by mehtaman** [comment]
Thank you for the quick reply!
