### ISSUE TITLE
What version of PHP is supported/required?

### ISSUE THREAD

**Issue by siteadvice** [facebookincubator/Facebook-For-OpenCart#543]
Can you please update the installation guide and system requirements to specify the minimum version of PHP that is supported?

Thanks.

**Comment by siteadvice** [comment]
Could anyone answer this question?
The extension contains numerous PHP files, so there must be a minimum supported PHP version.

**Comment by yao-tx** [comment]
Hi @siteadvice,

As the extension uses PHP SDK and Guzzle internally, please ensure that your PHP version is at least 7.2. 

Also, a new version of the Facebook Business Extension plugin for OpenCart is available on [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). You might wish to download it as we've recently revamped the entire plugin, made improvements to the plugin and resolved many bugs and issues that users are having with the previous versions.

If you are still encountering issues with the new FBE plugin, please reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
