### ISSUE TITLE
[INSTAL-ERROR] Opencart 2.3 dont run install.php

### ISSUE THREAD

**Issue by mrdenisters** [facebookincubator/Facebook-For-OpenCart#546]
**FBE plugin version**
3.1.2

**OpenCart version**
ocStore 2.3.0.2.3

**Describe the bug**
PHP Parse error:  syntax error, unexpected ':', expecting '{' in /system/library/vendor/guzzlehttp/guzzle/src/functions.php on line 16

**To Reproduce**
Sript error run autoload.php

**Screenshots**
https://prnt.sc/yb1hwx

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser [firefox]
 - Version [85]

**Additional context**
Remove the **VENDOR** directory in instalation archive. While it was not extension, it worked fine, as soon as these unnecessary working media files added, the extension stopped being installed and issued an error on OpenCart 2.3

**Comment by yao-tx** [comment]
Hi @mrdenisters,

The Facebook Business Extension plugin for OpenCart uses the Facebook PHP Business SDK internally, which also utilises Guzzle. Hence, do try upgrading your PHP version to 7.2 and above, and it should resolve the errors with Guzzle.

Also, new version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) is available on [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). You might wish to download it as we've recently revamped the entire plugin, made improvements to the plugin and resolved many bugs and issues that users are having with the previous versions.

The new plugin does not use any installation scripts and uses the default OpenCart Extension Installer to perform installation.

If you are still encountering issues with the new FBE plugin, please reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
