### ISSUE TITLE
error occur 'We have detected the Facebook pixel is not correctly setup in your web store site.'

### ISSUE THREAD

**Issue by Zhoha28** [facebookincubator/Facebook-For-OpenCart#547]
Hello!
I have a problem with the Facebook Business Extension for OpenCart.
I am using a fresh install of opencart 3.0.3.6
after adding the Facebook Business Extension for OpenCart, it is throwing the following errors:

 We have detected the Facebook pixel is not correctly set up in your web store site. You can try the below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog, and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

We have detected the Facebook pixel is not correctly set up in your web store site. You can try the below steps to fix the problem.

Facebook Business Extension Version: 3.1.2 (tried using other versions as well, the same issue occurs)

After installation, even though the pixel was stored in the database, it's not showing up on the frontend when tracked using a pixel helper

Please help me fix issues as it is important for my ads to run using Facebook.
I am using the same version of opencart and the same version of Facebook business extension on my other site, its working perfectly there, not able to understand the issue here.

website link :
https://stickitup.in/
![Capture](https://user-images.githubusercontent.com/32241004/107132782-f3befe00-6907-11eb-93e0-43055ebac2de.PNG)

**Comment by haxcop** [comment]
If check everything is correct accordingly to the information given, then uninstall the FB plugging and reinstall it again.

**Comment by Janri1** [comment]
Hello! Have you fixed the problem? I have the same thing. Please share your experience if you have fixed the problem.

**Comment by yao-tx** [comment]
Hi @Zhoha28 @Janri1 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
