### ISSUE TITLE
The ad account that owns this pixel is not eligible

### ISSUE THREAD

**Issue by kanjuo** [facebookincubator/Facebook-For-OpenCart#548]
Hey  Guys

Any idea why this error?:
The ad account that owns this pixel is not eligible

I know the Ad account belongs to me but the page belongs to someone else not sure what to do in this case; i want to use this specific pixel whose ad account (mine) isnt eligible

**Comment by yao-tx** [comment]
Hi @kanjuo,

For this issue, it would be better for you to open a support ticket with Facebook Business's support team [here](https://www.facebook.com/business/help).

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
