### ISSUE TITLE
 How can I solve this problem? 

### ISSUE THREAD

**Issue by wayy634** [facebookincubator/Facebook-For-OpenCart#55]
You do not have permission to access this page, please refer to your system administrator.
Version 3.0.2.0

How can I solve this problem?

**Comment by shue249** [comment]
@wayy634 , Thanks for your feedback!

Can you refer to these 2 video guides
https://drive.google.com/open?id=1-ljN_pNcyZBbN2LoXtxwaJEy0dfnxAum
https://drive.google.com/open?id=1JUwZPlUNIhFO7I8U0slbJSQNjyu4al_J

Will close out the comment, but feel free to reopen them if needed.
