### ISSUE TITLE
Major Bug w/ 3.1.2 update (/var/www/html/system/library/vendor/guzzlehttp/guzzle/src/Utils.php line 379 Unexpected '?')

### ISSUE THREAD

**Issue by jstone616** [facebookincubator/Facebook-For-OpenCart#550]
**Webstore Url**
www.Sportwing.com

**FBE plugin version**
3.1.2

**OpenCart version**
3.0.2.0 (others reported this issue with other versions as well)

**Describe the bug**
Upon installation, error message (/var/www/html/system/library/vendor/guzzlehttp/guzzle/src/Utils.php line 379 Unexpected '?') is shown which breaks entire website until the extension is fully removed.

**Additional context**
Unable to proceed until this is fixed, I am reading many others having the same issue but looks like I'm the first to post about it on Github. Haven't been able to have pixel active since this update, which is affecting our sales. Have proceeded without the installation installed until a verified fix is available. Please help!

**Comment by haxcop** [comment]
looking at the same error on our server log 
Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\\Utils::jsonEncode() in /home/user/public_html/website.com/system/library/vendor/guzzlehttp/guzzle/src/functions.php:166\nStack trace:\n#0 /home/user/public_html/website.com/system/library/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/EventRequestAsync.php(59): GuzzleHttp\\json_encode(Array)\n#1 /home/user/public_html/website.com/system/library/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/EventRequestAsync.php(42): FacebookAds\\Object\\ServerSide\\EventRequestAsync->eventPromise('233571608194621', Array)\n#2 /home/user/public_html/website.com/system/library/facebookserversideevent.php(81): FacebookAds\\Object\\ServerSide\\EventRequestAsync->execute()\n#3 /home/user/public_html/website.com/system/library/facebookserversideevent.php(58): FacebookPixelPlugin\\Core\\FacebookServerSideEvent::send(Array, Object(Config))\n#4 /home/user/public_html/website.com/catalog...', referer: https://www.website.com/index.php?route=product/catalog&limit=100

**Comment by yao-tx** [comment]
Hi guys,

This could be an issue with your PHP version. Do try upgrading it to version 7.2 and above.

Also, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users were having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
