### ISSUE TITLE
Purchase event is not working [BUG]

### ISSUE THREAD

**Issue by umagenta683** [facebookincubator/Facebook-For-OpenCart#551]
**Webstore Url**
Your webstore Url

**FBE plugin version**
3.1.2

**OpenCart version**
2.3.0.2.

**Describe the bug**
None of the serverside/browserside Purchase events are working. If I look in the extension files I see that the purchase event parameters should come from "$this->cart->getProducts()" in the function "getPurchaseEventParameters()" when the $route = "checkout/success" however looking at the controller file of checkout/success the cart gets cleared immediately. Could this cause the bug? 

**Desktop (please complete the following information):**
 - OS: OS X 10.14.5
 - Browser Chrome
 - 88.0.4324.146 (Official Build) (x86_64)

**Comment by alicanso** [comment]
also can not track add to cart events. I'm using latest version of extension on oc 3.0.2.

**Comment by umagenta683** [comment]
One purchase event was tracked today, however we had multiple purchases today. From the past week none of the purchases was tracked

**Comment by yao-tx** [comment]
Hello @umagenta683 @alicanso,

Please download the latest version of FBE (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336) which should fix up the issues with regards to Purchase events not working correctly.

That being said, if you encounter any further issues with the plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
