### ISSUE TITLE
[BUG]Pixel add to cart page not found

### ISSUE THREAD

**Issue by deriktan123** [facebookincubator/Facebook-For-OpenCart#553]
**Webstore Url**
bakeohouse.com

**FBE plugin version**
3.1.2
**OpenCart version**
3.0.3.2

**Describe the bug**
/index.php?route=extension/facebookproduct/getproductinfoforfacebookpixel&event_name=AddToCart&product_id=124&quantity=1

when i press the add to cart button, it show the error 500

**Comment by deriktan123** [comment]
Hi,

i check my facebook pixel manager page it shown

Server Sending Invalid Match Key Parameters for AddToCart Event
Your server is sending an invalid email, fbp, fn, ip_address, ln, phone, user_agent parameters value for your AddToCart event. This may be because there was an error in the parameter value.
This may cause issues with the attribution and delivery optimization of ad campaigns that are using this event.
1 day
since first detected 
​

**Comment by yao-tx** [comment]
Hi @deriktan123 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
