### ISSUE TITLE
An error occured while generating system user access token: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0. [BUG]

### ISSUE THREAD

**Issue by styopchaval** [facebookincubator/Facebook-For-OpenCart#555]
**FBE plugin version**
3.1.2

**OpenCart version**
3.0.3.2

**Describe the bug**
An error occured while generating system user access token: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.

**To Reproduce**
Clicking on Getting Started button to give permissions. It's open popup where I see "https://www.facebook.com/v7.0/dialog/oauth?......." url.

**Screenshots**
![bug](https://user-images.githubusercontent.com/5998581/110077676-ffcf9b80-7d9f-11eb-8cc7-d8111eda65ce.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by AirProjectsPro** [comment]
I have this problem too.
First connect was good.
After deleting link and repeat connection i have this error after last step and success message.

**Comment by drikinukoda** [comment]
same problem here with new installation on OpenCart 3.0.2.0. anw new update on this bug?

**Comment by tudorr89** [comment]
Uninstall the plugin completely, install version 3.0.0 and configure. then just install latest 3.1.2 and it should work. At least it did for me!

**Comment by AirProjectsPro** [comment]
> Uninstall the plugin completely, install version 3.0.0 and configure it with your store. then just install latest version 3.1.2 on top of it and it should work. At least it did for me!

it's work. Thank you

**Comment by styopchaval** [comment]
> Uninstall the plugin completely, install version 3.0.0 and configure it with your store. then just install latest version 3.1.2 on top of it and it should work. At least it did for me!

Thanks, will try it ASAP.

**Comment by styopchaval** [comment]
> Uninstall the plugin completely, install version 3.0.0 and configure it with your store. then just install latest version 3.1.2 on top of it and it should work. At least it did for me!

Dear @tudorr89 this trick is working like charm. Thank You very much. Now I can close this case.

**Comment by AirProjectsPro** [comment]
the last version need to fix.
@styopchaval, maybe reopen issue))

**Comment by ivent** [comment]
I had to go back to version 3.0, unfortunately the new version is giving this error, please release a new version to fix this urgent

**Comment by ivent** [comment]
@styopchaval please reopen the problem it was not solved just bypassed with the return to version 3.0

**Comment by danidesigner** [comment]
Same problem please help me

**Comment by raviajudiya** [comment]
opencart version 2.3.0.2 and fb plugin version : 3.1.2

fetch this problem help me please 
An error occured while generating system user access token: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.

**Comment by ivent** [comment]
I had to return to version 3.0 to resolve the error unfortunately I had to return 4 versions ago, please resolve this urgently so that we can use the new versions
