### ISSUE TITLE
[BUG] Purchase Event Missing Some Deduplication Parameters 

### ISSUE THREAD

**Issue by katsikar** [facebookincubator/Facebook-For-OpenCart#562]
**Webstore Url**
https://www.ilovebbq.gr/

**FBE plugin version**
3.1.2

**OpenCart version**
2.3.0.2

**Describe the bug**
We received the following message from facebook:
"You're sending Purchase events through both your pixel and the Conversions API, but they're not being deduplicated properly because not enough of these events are receiving an event_id parameter. Event instances sent without an event_id parameter cannot be deduplicated.
This may cause issues with the measurement of your events as well as the attribution and delivery optimization of any ad campaigns that are optimizing for this event.
How to fix the issue 
Send to developer 
You'll need to use the solution below to fix the issue. Once you've fixed the issue in your website code you can mark it as resolved. This will move it to the Previously Detected section. If the issue is found again after 3 days it will move back to the Active section. 
Add an event_id parameter to all Purchase events that you're sending from both your pixel and the Conversions API. To add an event_id parameter to the events you're sending through the Conversions API, you can use the Payload Helper tool on the Facebook for Developers site to validate that your payload is set up correctly. To add an event_id parameter to the events you're sending through your pixel, go into your website's source code and add an event_id parameter to each of your Purchase event instances."

**To Reproduce**
I don't lnow if it can be reproduced, it is a message shown on the Facebook Pixel console, tab Diagnostics 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 89.0.4389.114

**Additional context**
![unnamed](https://user-images.githubusercontent.com/19946830/114263606-3d52c480-99ef-11eb-8802-b944a72174d7.png)

**Comment by yao-tx** [comment]
@katsikar 
Hello there,

Please download the latest version (4.0.1) of the Facebook Business Extension plugin for OpenCart at OpenCart Marketplace. This should resolve the issues you are having with the current versions.

**Comment by katsikar** [comment]
Thank you! I will try the new version.
