### ISSUE TITLE
Error in Modification Setting : admin/language/en-gb/common/dashboard.php

### ISSUE THREAD

**Issue by nnsanne** [facebookincubator/Facebook-For-OpenCart#563]
**Webstore Url**
cookiesvibe.com

**FBE plugin version**
Version of FBE plugin
Plugin Version: 3.1.2

**OpenCart version**
Version 3.0.3.2

**Describe the bug**
I have no idea why i got the error message on modification setting. It writes 

File  : admin/language/en-gb/common/dashboard.php
Code  : while ($action) {
ERROR : NOT FOUND - OPERATIONS ABORTED!

File  : admin/language/en-gb/common/dashboard.php
Code  : public function dispatch($action, $error) {
ERROR : NOT FOUND - OPERATIONS ABORTED!

**Screenshots**
https://ibb.co/hR9p8r0

**Desktop (please complete the following information):**

Safari, Mac.

**Comment by yao-tx** [comment]
@nnsanne 
Hello there,

Please download the latest version (4.0.1) of the Facebook Business Extension plugin for OpenCart at OpenCart Marketplace. This should resolve the issues you are having with the current versions.

**Comment by yao-tx** [comment]
Hello @nnsanne,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
