### ISSUE TITLE
SQL Error 1064 on extension install

### ISSUE THREAD

**Issue by 6n54** [facebookincubator/Facebook-For-OpenCart#564]
OpenCart 3.x.x

Error Code(0): Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.mystoreoc_modification where field = 'xml'' at line 1
Error No: 1064
SHOW COLUMNS FROM `mydatabase`.mystoreoc_modification where field = 'xml' in /homepages/18/d864644166/htdocs/system/library/db/mysqli.php on line 41
when I try to install facebook business module, any version, 3.0.1 , 3.1.2...

Using IONOS Web host for DBs

Not sure exactly what is happening..
Don't think I had this error the first time I tried installing the extension.

I'd really like to get facebook integrated, I know the app is having some issues right now but I feel my error is un-related; as I had my Facebook Pixel fully functional about 2 weeks ago.

Even with this error, the app still seems to somewhat function and install with the exception of some errors.

If it is something simple please point me in the right direction. Thanks everyone! I appreciate any help.

**Comment by yao-tx** [comment]
Hello @6n54,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
