### ISSUE TITLE
The currency BGN currently associated with your website isn't supported on Facebook. Contact OpenCart for support.

### ISSUE THREAD

**Issue by venetin** [facebookincubator/Facebook-For-OpenCart#566]
Hello,

With the latest versions 3.1.2 and 4.0 it is not possible to use BGN as a currency. With 2.x versions there is no such issue.

Can someone check and fix this.

**Comment by yao-tx** [comment]
@venetin 
Hello,

Unfortunately, Facebook Ads does not support the currency BGN. This is a restriction from Facebook's end and you might want to contact Facebook's support for more information on that.
