### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dondolou** [facebookincubator/Facebook-For-OpenCart#567]
**Webstore Url**
Your webstore Url - **shop.dondolo.co.ug**

**FBE plugin version**
Version of FBE plugin **v4.0.0**

**OpenCart version**
Version of OpenCart - **3.0.2.0**

**Describe the bug**
I installed the latest version but I can't find the FBE plugin on the modifications list, I get the following error message on this page from the admin pageWarning: htmlentities(): charset `UTF-8;' not supported, assuming utf-8 in /home/yestap/public_html/shop/admin/controller/marketplace/modification.php on line 756 

The front end is deformed as well.

**To Reproduce**
1. Go to '...' admin/extensions/modifications 
2. Click on '....' FBE is not on the list
4. See error - Warning: htmlentities(): charset `UTF-8;' not supported, assuming utf-8 in /home/yestap/public_html/shop/admin/controller/marketplace/modification.php on line 756 

**Screenshots**
https://drive.google.com/file/d/1tAd9iaihA-zU9lgSgEcXRB2u8JSKfxPT/view?usp=sharing

**Desktop (please complete the following information):**

**Additional context**

**Comment by yao-tx** [comment]
@dondolou 
Hi there,

For OpenCart version 2.3 and above (including v3), the new FBE plugin does not utilise OCMOD anymore. Therefore, there shouldn't be any OCMOD scripts listed under Extensions -> Modifications. The new plugin utilises OpenCart events to make modifications instead. You should only need to install the extension by clicking on "Install" under Extensions -> Extensions -> Modules -> 'Facebook Business Extension'.

That being said, do proceed to OpenCart marketplace to download the latest version (4.0.1) of the Facebook Business Extension plugin for OpenCart. It contains the latest improvements and bug fixes to 4.0.0.

For the UTF-8 warning, this is an unrelated warning to the FBE plugin. Please check your php.ini file to ensure that there is no semi-colon appended to UTF-8 for default_charset.
