### ISSUE TITLE
[BUG] Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by haxcop** [facebookincubator/Facebook-For-OpenCart#568]
**Webstore Url**
venemarket.ie

**FBE plugin version**
Plugin Version 4.0.1
**OpenCart version**
Version of OpenCart 3.0.3.6

**Describe the bug**
unable to upload the products to the Facebook page and consecutively unable to setup the shop 

**To Reproduce**
1. Go to the Facebook extension

**Screenshots**
![Screen Shot 2021-04-27 at 4 35 06 PM](https://user-images.githubusercontent.com/7826906/116270114-b8013b00-a776-11eb-8c7f-d13ed8452931.jpg)

**Additional context**
Review of the logs

`PHP Notice: Undefined variable: product_info in ``/home/XXXX/public_html/venemarket.ie/catalog/model/extension/module/facebook_business.php on line 547`

`546:  } else {`
`547:  $value += $this->currency->format($this->tax->calculate($product_info['price'], $product_info['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency'], '', false);
548:  }`

**Comment by yao-tx** [comment]
@haxcop 

Hello,

Please reach out to us via our [help desk](https://marketinsg.zendesk.com/) so that we can assist you with the issue you are having.
