### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jubidubi** [facebookincubator/Facebook-For-OpenCart#57]
hi 
we are using 3.0.2.0 version with differant name for admin folder 
we have downlaoded the module and changed the admin folder name and also admin path in all files 
and tried to install it it is showing the module through installer it is sucessfully installed , then we also installed Extensions >> modules >> Facebook Ads extensions 
after refreshing the modifications we tried to open module for settings it is showing page not found error. we also noticed there is no entry of facebook module on modifications list 

can you please guide us how can we resolve this ?

**Comment by shue249** [comment]
@jubidubi Thank you for the feedback. Can you look at these 2 video guides if they help.
https://drive.google.com/open?id=1-ljN_pNcyZBbN2LoXtxwaJEy0dfnxAum
https://drive.google.com/open?id=1JUwZPlUNIhFO7I8U0slbJSQNjyu4al_J

**Comment by jubidubi** [comment]
hi
Thanks for your suggetions 
we have made all changes on files before installation . and we ddint find any log on modifications and no icon or link on dashboard menu . 
but meanwhile it is working fine with direct url like https://jubidubi.com/customeadmin/index.php?route=extension/facebookadsextension&user_token=hCeRg89CDvxi3SOX33twwlse82Z55aY2

**Comment by shue249** [comment]
@jubidubi Thanks for the feedback. This is really a weird case. At the same time, direct accessing via the URL will work fine as well. Can you go thru the FAE setup flow and see if it works out properly.

**Comment by shue249** [comment]
@jubidubi We will be closing out this ticket, but feel free to open this if you need any help from us.
