### ISSUE TITLE
[BUG] Get Started With Facebook Not Working!

### ISSUE THREAD

**Issue by Khalidsaif78** [facebookincubator/Facebook-For-OpenCart#570]
**Webstore Url**
https://www.aarashi.com.bd

**FBE plugin version**
Version 4.0.2

**OpenCart version**
Version 3.0.3.7

**Describe the bug**
After installing the Facebook Business Extension successfully, I clicked on the "Get started with Facebook"  button, but it's not working. I clicked so many times btw result nothing. It should be a new window popup with Facebook login screen.

**To Reproduce**
1. Go to 'Facebook business Extension' from admin panel
2. Click on 'Get started with Facebook' Button.
You can see the problem when clicked on the button it won't work.

**Screenshots**
Please Check my screenshot from here: http://prntscr.com/12b99hc

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Version 90.0.4430.93]

**Additional context**

**Comment by mvmtdigital** [comment]
I have the same problem.

**Comment by hounw** [comment]
Same problem here but on version 2.3.0.2 of open cart.

The button link is just javascript:void(0); and I see this in the console:

Query param variable dev_host_prefix not found
Query param variable system_user_name not found
Query param variable business_vertical not found
Query param variable fbe_v2_installed not found
Query param variable s2s_configured not found

**Comment by yao-tx** [comment]
Hi @Khalidsaif78 @mvmtdigital @hounw,

Facebook is currently facing an issue regarding an outage affecting JS SDKs (which the Facebook Business Extension plugin uses for logging in and launching Facebook Business Management), and they are currently still working to resolve this issue.

For more updates and details about this issue, please kindly refer to this link [here](https://developers.facebook.com/status/issues/492652922187445/).

**Comment by Khalidsaif78** [comment]
Hi @yao-tx ,

Thank you for telling us the main reason for this issue. Facebook resolves their problem, Now everything is working fine.

**Comment by yao-tx** [comment]
Hi @Khalidsaif78 

No problem. Glad that it's working fine now :)

I will be closing this issue.
