### ISSUE TITLE
Stream Url Upload session failed

### ISSUE THREAD

**Issue by cagatayyersel** [facebookincubator/Facebook-For-OpenCart#573]
Hi friends , My problems is  stream url is 404 not found. But plugin is active and store connect is okey.  Please help me  Error Page: https://ibb.co/gJ6zMms

**Webstore Url**
alltradeshop.com

**FBE plugin version**
Plugin Version 4.0.3
**OpenCart version**
3.0.2

Stream URL:https://www.alltradeshop.com/index.php?route=extension/module/facebook_business/genFeed
Result
Upload session failed

**Comment by yao-tx** [comment]
Hi @cagatayyersel 

Please reach out to us via our [help desk](https://marketinsg.zendesk.com/) so that we can look into this issue for you. Thank you!

**Comment by berettarez** [comment]
Exactly the same problem, does not unload product positions in the feed!

https://mobile-shrek.com.ua/index.php?route=extension/module/facebook_business/genFeed

**Comment by yao-tx** [comment]
Hi @berettarez 

Please reach out to us via our help desk so that we can look into this issue for you. Thank you!
