### ISSUE TITLE
empty purchase event for quest order[BUG]

### ISSUE THREAD

**Issue by marian821** [facebookincubator/Facebook-For-OpenCart#575]
**Webstore Url**
https://sellsell.ro

**FBE plugin version**
4.0.3
**OpenCart version**
3.0.3.2
**Describe the bug**
When im logged in data is passed corectly, but as quest checkout the purchase event is empty.
**To Reproduce**
1. Go to 'choose a product'
2. Click on 'add to cart'
3. Scroll down to '.send order'

**Screenshots**
[
![Screen Shot 2021-05-14 at 1 11 23 AM](https://user-images.githubusercontent.com/84157492/118194169-a21b9780-b451-11eb-8198-c9563aea3ad9.png)
](url)
**Desktop (please complete the following information):**

**Additional context**

**Comment by yao-tx** [comment]
Hi @marian821 

We've received your support ticket at our help desk and we will follow up with you there.
