### ISSUE TITLE
Conversion value is not recorded by pixel [BUG]

### ISSUE THREAD

**Issue by dred171** [facebookincubator/Facebook-For-OpenCart#577]
**Webstore Url**
Your webstore Url
unifashion.ro

**FBE plugin version**
Version of FBE plugin
Plugin Version 4.0.3

**OpenCart version**
Version of OpenCart
2.3.0.3
**Describe the bug**
What I noticed is that it no longer records the value of pixel commands, it records all the additions to the cart and conversions, but not the conversion value:

**Screenshots**
https://imgur.com/cN8DnJD

**Comment by yao-tx** [comment]
Hi @dred171 

This could be an issue with custom extensions causing conflicts with the FBE plugin. Please reach out to us via our [help desk](https://marketinsg.zendesk.com/) so that we can look into this issue for you.

Thank you!

**Comment by dred171** [comment]
> Hi @dred171
> 
> This could be an issue with custom extensions causing conflicts with the FBE plugin. Please reach out to us via our [help desk](https://marketinsg.zendesk.com/) so that we can look into this issue for you.
> 
> Thank you!

Thank you!
I sent a request now where you indicated it to me.
We hope to solve the problem :)

**Comment by yao-tx** [comment]
We've received your ticket and we will be following up with you. As suspected, this is very likely to be an issue with a third-party extension tampering with the session data. As mentioned in the ticket, we've fixed up the issue and I will be closing this issue.

Have a great day ahead! :)
