### ISSUE TITLE
Product limit code needs to be changed on 3.x version

### ISSUE THREAD

**Issue by cartbinder** [facebookincubator/Facebook-For-OpenCart#578]
Hi,

Error: 
PHP Warning:  A non-numeric value encountered in catalog/model/extension/module/facebook_business.php on line 850

**Solution:**

catalog/model/extension/module/facebook_business.php
Line no 844
$limit = $this->config->get($this->config->get('config_theme') . '_product_limit');

Change to 
$limit = $this->config->get('theme_' . $this->config->get('config_theme') . '_product_limit');

**Comment by yao-tx** [comment]
Hi @cartbinder 

Thank you for the bug report, we will be fixing this bug in the next update.

**Comment by ChrisNikolaidis** [comment]
For me the "problem" still exists after this change.

**Comment by yao-tx** [comment]
Hi @ChrisNikolaidis and @cartbinder 

This bug has been fixed in version v4.1.1. Please download the latest version from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336) or download from the latest release on GitHub.

Thank you @cartbinder for the bug report.

**Comment by ChrisNikolaidis** [comment]
Hi @yao-tx 
After update to version 4.1.1 i see the below notice (every second):
PHP Notice:  A non well formed numeric value encountered in .../www/catalog/model/extension/module/facebook_business.php on line 950

**Comment by yao-tx** [comment]
Hi @ChrisNikolaidis 

Please open a ticket with us via our [helpdesk](https://marketinsg.zendesk.com/) so that we can look into the issue for you.

**Comment by carlospaiao** [comment]
Warning: A non-numeric value encountered file /catalog/model/module/facebook_business.php on line 935
Facebook Module 4.1.1
OC 2.2.0.0
PHP 7.3

4.1.1 version still problem

**Comment by yao-tx** [comment]
Hi @carlospaiao 

Please open a ticket with us via our [helpdesk](https://marketinsg.zendesk.com) so that we can look into the issue for you.
