### ISSUE TITLE
Pixel events issue

### ISSUE THREAD

**Issue by ipramov** [facebookincubator/Facebook-For-OpenCart#58]
Hello,
I have installed the extension automatically. Pixel helper shows that only Page view event is fired.  No other event has been installed. What shall I do?
Thanks

**Comment by shue249** [comment]
@ipramov Thank you for the feedback. What is your webstore URL?

**Comment by shue249** [comment]
@ipramov Like to follow up on this problem. What is your website URL?

**Comment by shue249** [comment]
@ipramov We will be closing out this ticket, but pls feel free to reach out to us if you need more help
