### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by phantom-limb** [facebookincubator/Facebook-For-OpenCart#580]
**FBE plugin version**
Version of FBE plugin: 4.1.0

**OpenCart version**
Version of OpenCart: 3.0.3.6

**Describe the bug**
![image](https://user-images.githubusercontent.com/58053798/121401311-f3268a80-c92e-11eb-9c07-eed79e39f0c9.png)

**Comment by yao-tx** [comment]
Hi @phantom-limb

Do open a support ticket with us via our (helpdesk)[https://marketinsg.zendesk.com/] fpr assistance on the issue you are facing. Thank you :)

**Comment by phantom-limb** [comment]
![image](https://user-images.githubusercontent.com/58053798/122466430-ae829b00-cf8f-11eb-97ea-aa7cfa66e948.png)

**Comment by phantom-limb** [comment]
![image](https://user-images.githubusercontent.com/58053798/122466633-eee21900-cf8f-11eb-89e9-c10d63b9860a.png)
