### ISSUE TITLE
Cant install this plugin

### ISSUE THREAD

**Issue by sirluca** [facebookincubator/Facebook-For-OpenCart#583]
I am running opencart 2.3.0.2 after uploading file I get this error when I try to install the module :

error
<br />
<b>Parse error</b>: syntax error, unexpected ':', expecting '{' in <b>/home/baffshq1/public_html/system/library/vendor/facebook_business/vendor/guzzlehttp/guzzle/src/functions.php</b> on line <b>16</b><br />

**Comment by yao-tx** [comment]
Hi @sirluca 

May I know what is the PHP version you are using for your server?

**Comment by yao-tx** [comment]
Hi @sirluca 

If you are still having issues, please reach out to us via our [help desk](https://marketinsg.zendesk.com/).

Thank you.
