### ISSUE TITLE
[Feature Request] Free up <head> from setup scripts (move to footer)

### ISSUE THREAD

**Issue by slyk** [facebookincubator/Facebook-For-OpenCart#587]
**FBE plugin version**
4.1.1

**Is your feature request related to a problem? Please describe.**
Trying to speed up website for mobiles, moved all big css and js to the bottom, so first bytes of HTML be needed to user and be able to show some content... and now after install of Facebook plugin I end up with >100 lines of scripts from Facebook tracking, that loading other scripts and css, and pixel that need jQuery (other big lib that loaded mostly at bottom of my page). We DO NOT NEED this stuff at real top.

**Describe the solution you'd like**
Settings where to put scripts (top, bottom) will be good idea. 

**Additional context**
jQuery is rernder blocking on my website.
https://web.dev/render-blocking-resources/?utm_source=lighthouse&utm_medium=unknown

**Comment by yao-tx** [comment]
Hi @slyk 

You can modify the extension to suit your requirements. If you need assistance with it, please open a ticket with us via our (help desk)[https://marketinsg.zendesk.com/]
