### ISSUE TITLE
[BUG] Extra comma after id

### ISSUE THREAD

**Issue by gutarim** [facebookincubator/Facebook-For-OpenCart#588]
lovehome.design
Your webstore Url

Plugin Version 4.1.1
Version of FBE plugin

PHP 7.3

3.0.3.2
Version of OpenCart

fbe_product_catalog.csv content:

id,title,description...
15,,"Product Title","Product description"...
16,,"Product Title","Product description"...

That extra comma after id causes an error.

That behaviour is reproduced on my another website with the same configuration.
However on my third site that behaviour is NOT reproduced. What could cause it?

Thank you

**Comment by yao-tx** [comment]
Hi @gutarim 

That definitely seems strange as this is the first occurrence of such an issue. That being said, could you kindly open a ticket with our help desk [here](https://marketinsg.zendesk.com/) so that we can investigate into the issue for you?
