### ISSUE TITLE
Issue with catalogue not sychining

### ISSUE THREAD

**Issue by MommyCharms** [facebookincubator/Facebook-For-OpenCart#589]
**Webstore Url**
Your webstore Url

**FBE plugin version**
Version of FBE plugin

**OpenCart version**
Version of OpenCart

**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by yao-tx** [comment]
Hi @MommyCharms 

As there are no description or context provided with regards to the issue you are having, we are unable to provide you with any possible solutions here.

Could you open a support ticket with us via our [helpdesk](https://marketinsg.zendesk.com/) so that we can assist you with the issue you are having?

**Comment by MommyCharms** [comment]
Hi Team,

We have setup instashop and have connected pixel to Magento, however for
the last few weeks instashop is not showing any new Items added on the
website.

When we checked the issue it gave us an error message as *Facebook access
token is invalid. Please click on Facebook Ads Extension, Manage Settings,
go to Advanced options and click on Update token.*

*Here is screenshot of error we are getting*

[image: image.png]
Could you please help us on the same

Regards,
Prasad R

**Comment by yao-tx** [comment]
Hi @MommyCharms 

This repository is for the Facebook Business Extension plugin for OpenCart and not for Magento. We can only provide support for the OpenCart plugin and not for Magento. You might want to open an issue at the Facebook Business plugin for Magento repository instead.

**Comment by MommyCharms** [comment]
Hi Facebookincubator/Facebook-For-Opencart,

These is issue with your Opencart Facebook Ads Extension. We have setup
instashop and have connected pixel to opencart, however for the last few
weeks instashop is not showing any new Items added on the website.

When we checked the issue it gave us an error message as *Facebook access
token is invalid. Please click on Facebook Ads Extension, Manage Settings,
go to Advanced options and click on Update token.*

*Here is screenshot of error we are getting*

[image: image.png]

**Comment by yao-tx** [comment]
Hi @MommyCharms 

May I know what version of the Facebook Business Extension plugin for OpenCart are you using? If you are using version 3.1.2 and below, we would advise you to upgrade to the latest version as the versions below 4.0.0 has been deprecated.

Also, for further assistance on your issue, please reach out to us via our [helpdesk](https://marketinsg.zendesk.com/). Thank you.

**Comment by MommyCharms** [comment]
Hi Team,

We have already upgraded it to 4.0 but still we are facing synchronization
problem.

Please advise.

Prasad

**Comment by yao-tx** [comment]
Hi @MommyCharms 

Please reach out to our [helpdesk](https://marketinsg.zendesk.com/) for assistance. Thank you.
