### ISSUE TITLE
Items Synced but on facebook site they are OUT OF STOCK

### ISSUE THREAD

**Issue by aidebe1** [facebookincubator/Facebook-For-OpenCart#59]
Hello there,
Thank you very much for this extension.
Everything is working fine but what I noticed is that on the facebook site most of my products are OUT OF STOCK. When I open the product on my site it is IN STOCK. Could you please help me resolve this issue .
Regards,
L.P.

**Comment by aidebe1** [comment]
Actually I was just checking and all of the synced products are OUT OF STOCK on Facebook....

**Comment by shue249** [comment]
Thank you for your feedback. We are looking into this for you.

**Comment by shue249** [comment]
@aidebe1 We should have fixed the OUT OF STOCK problem. Can you take a look at your shop if things are in order.

**Comment by beachgeek** [comment]
I am having the same issue in addition to the other issue you are working
on.

*Carlos Faught*
*Bay Breeze Dive Center*

*49 Gulf Breeze Pkwy*

*Gulf Breeze, Fl  32561*
*850-934-8363**carlos@baybreezescuba.com <carlos@baybreezescuba.com>*

**Comment by aidebe1** [comment]
I will check later today and will let you know...;-)

**Comment by aidebe1** [comment]
It looks like everything is in order now ;-)

**Comment by aidebe1** [comment]
Hello again something else came up...when I open all products with Facebook app on my phone and try open to open a product nothing happens...

**Comment by shue249** [comment]
@aidebe1 What is your Facebook page?

@beachgeek The OUT OF STOCK problem should have been resolved for your page. Can you take a look?

**Comment by aidebe1** [comment]
Hi out of stock is ok now but something else came up... when I go to shop and than to all products with Facebook app on my phone and try to open a product... nothing happens...

**Comment by aidebe1** [comment]
https://m.facebook.com/EleganceFashionTrend/shop/?ref=bookmarks&mt_nav=0
This my Facebook page the problem appears only with Facebook app when shop-all products are selected if opened with the browser everything works fine...

**Comment by aidebe1** [comment]
Just a small update this problem appears only when I am logged in with the account  the store if I am logged from another account everything works fine...maybe this is the way it's supposed to be...;-)

**Comment by beachgeek** [comment]
> 
> 
> @aidebe1 What is your Facebook page?
> 
> @beachgeek The OUT OF STOCK problem should have been resolved for your page. Can you take a look?

https://www.facebook.com/Bay-Breeze-Dive-Center-108272231137/?ref=bookmarks

**Comment by shue249** [comment]
@beachgeek Thank you for your feedback. Can I ask for you to help us to create a separate ticket for your product update issue, as we like to keep this ticket for the OUT OF STOCK problem.

For the latest version of the plugin, can you try to get the copy from https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.2 as we have yet to update the plugin version on the Facebook pixel dashboard.

Closing out this ticket for the OUT OF STOCK problem
