### ISSUE TITLE
 [BUG] Fail to send server event! 

### ISSUE THREAD

**Issue by uslualper** [facebookincubator/Facebook-For-OpenCart#590]
**Webstore Url**
https://naarhali.com/

**FBE plugin version**
Version 4.2.0

**OpenCart version**
3.0.3.6

**Describe the bug**
2021-09-29 11:04:43 - Facebook Business Extension :: Fail to send server event! Error Message: Client error: `POST https://graph.facebook.com/v10.0/342428520349770/events` resulted in a `400 Bad Request` response:
{"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_subcode":2804014,"is_transient":false, (truncated...)

**To Reproduce**
at every event

**Screenshots**
![Uploading Screenshot_2.png…]()

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by yao-tx** [comment]
Hi @uslualper 

Please reach out to us via our [helpdesk](https://marketinsg.zendesk.com/) so that we can assist you with the issues you are having. Thank you.
