### ISSUE TITLE
[BUG] Install

### ISSUE THREAD

**Issue by PaulBogdanCom** [facebookincubator/Facebook-For-OpenCart#597]
PATH catalog/model/extension/module/facebook_business.php
LINE 220 : $extension_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "extension` **WEHRE** `type` = 'module' AND `code` = 'facebook_business'");
Should be **WHERE**

**Comment by yao-tx** [comment]
Hi @PaulBogdanCom 

Thank you for the bug report. We will be releasing a patch to fix up this issue.

**Comment by yao-tx** [comment]
Hi @PaulBogdanCom 

Thank you for your bug report. We've pushed an update (version 4.1.1) that fixed the bug mentioned in this issue.
