### ISSUE TITLE
PHP Notice:  A non well formed numeric value encountered in ../catalog/model/extension/module/facebook_business.php on line 959

### ISSUE THREAD

**Issue by thomsungroup** [facebookincubator/Facebook-For-OpenCart#598]
Can't figure this one out. According to the error, the line 959 is the error line.

Line 956        $general_filter_data = array(
Line 957             'sort'                => $sort,
Line 958             'order'               => $order,
Line 959             'start'               => ($page - 1) * $limit,
Line 960             'limit'               => $limit
Line 961         );

Opencart Version: 3.0.3.8
PHP version: 7.3

**Comment by yao-tx** [comment]
Hi @thomsungroup 

Do reach out to us via our [helpdesk](https://marketinsg.zendesk.com) for assistance. Thank you.
