### ISSUE TITLE
[BUG] Facebook Feed

### ISSUE THREAD

**Issue by JakubSVK** [facebookincubator/Facebook-For-OpenCart#599]
Webstore Url
https://jfauto.sk

FBE plugin version
4.2.0

OpenCart version
 3.0.2.0

Hello ! 
I have a problem with facebook feed, feed do not generate any products. Just empty csv. I updated FBE plugin, reset settings, delete old catalog, add new catalog, but same problem. 
In opencart error log i do not have any error with plugin. 
In Facebook i have a error : No products were uploaded

Facebook pixel looks good, i do not have any error.

**Comment by yao-tx** [comment]
Hi @JakubSVK 

May I know what is the PHP version of your web server? Do note that the Facebook Business Extension plugin for OpenCart requires for PHP version 7.2.5 and above due to the internal dependencies on the Facebook Business PHP SDK.

**Comment by JakubSVK** [comment]
Yes we updated PHP version, because it was not possible to upgrade plugin ( half year ago )

**Comment by yao-tx** [comment]
Hi @JakubSVK 

Please reach out to us via our [helpdesk](https://marketinsg.zendesk.com/) so that we can better assist you with your issue(s). Thank you.
