### ISSUE TITLE
VQMod error in opencart ver.: 2.3.0.2 

### ISSUE THREAD

**Issue by harrysrevis** [facebookincubator/Facebook-For-OpenCart#6]
When installing it and trying to enable it in opencart ver.: 2.3.0.2 i get an error 
"Fatal error: Uncaught Error: Class 'FacebookCommonUtils' not found in.. etc.."

**Comment by harrysrevis** [comment]
I've given write+execute permissions to that fodler and still nothing. 
I've also sent an email in ads_extension_opencart@fb.com with the exact error message. 
--

**Comment by shue249** [comment]
Can you take a look on your webserver and see if these files are in the system/library folder. We have seen your error log file and the "class FacebookCommonUtils not found..." error is most likely due to the missing files on your webserver.

If the installation is successful, these files should have been copied over from the plugin to your webserver.

![image](https://user-images.githubusercontent.com/11957585/40884617-a12c641a-6749-11e8-9d16-0808c7a311d6.png)

**Comment by harrysrevis** [comment]
Yeap that was the issue! One last thing, in another pixel inserted in website, in facebook products section i see all the products correctly but there's an "Out of stock" sign in top right corner, while all the products are available.

Any thoughts?

**Comment by shue249** [comment]
Thanks for the feedback! We will be improving on the plugin to make it more robust to better handle the missing file error.

For both the facebook product out of stock as well as your store website console error. Will you be able to share
1. The url of the facebook products
2. The url of your website

**Comment by harrysrevis** [comment]
URL of facebook products: [https://www.facebook.com/contactprints/shop/](url)
Website url: [https://shop.revisios.gr](url)

We have disabled right click for copyright issues. But i also disabled the extension of that in case that was the problem, but the error persists. 

Thank you in advance.

**Comment by shue249** [comment]
For the availability of products on Facebook Page Shop, the logic is as follow. If the product has "subtract stock=yes", we will set the availability to "Out of stock" if the quantity is zero, otherwise the availability will be "In stock". If the product has "subtract stock=no", the availability will always be "In stock".
![image](https://user-images.githubusercontent.com/11957585/40892585-b74b56b6-67cb-11e8-9f61-e8ee04b8a482.png)

For the error shown on the console of your website, it may be due to the journal module, as the error comes from the javascript file in the journal cache. Is this problem happening before you install the FacebookAdsExtension plugin?
![image](https://user-images.githubusercontent.com/11957585/40892523-fe73fa9e-67ca-11e8-9ef8-75270acc458c.png)

**Comment by harrysrevis** [comment]
As for the first, the thing is that every product is available and subtract stock is set to OFF. Nonetheless the availability in facebook shop page is set to out of stock. 

For the second one, when i deactivate the FacebookAdsExtension the problem does not exist anymore.

**Comment by shue249** [comment]
Thank you for your feedback and patience with us.

Let us look into both issues.

**Comment by shue249** [comment]
We identify the problem for the out of stock issue on Facebook page shop and we will be rolling out a fix within the next 1-2 days. Pls bear with us while we work on this.

For the second case, we suspect it is due to incompatibility issue with other plugins. Apart from journal, are there any other plugins you are using on your system? What is the version of journal you are using?

**Comment by harrysrevis** [comment]
First of all thank you for your help and patience,
as for the first problem I will wait for your response as soon as you will fix it.

As for the second one, I use several plugins like live price change,  etc. I also had the "Minify JS" option enabled so i deactivated it and it looks like there's something wrong with the jquery file. If this is helpful for you you can check it in my website link again.

My journal ver. is 2.14.7.

**Comment by harrysrevis** [comment]
Any further news with the FacebookAdsExtension?

**Comment by shue249** [comment]
Thank you for your patience. Can I invite you to re-setup the Facebook Ads Extension again. Re-setup here means for you to access Facebook Ads Extension on your OpenCart -> Click on Manage Settings -> Advanced options -> Delete Settings, and go through the settings again. The products on facebook page shop should be fine now.

Can I also request for you to leave the Facebook Ads Extension setup on, so we can debug on your website again.

**Comment by harrysrevis** [comment]
As for the first one as i can see from the first products inserted everything is fine! 

As for the second problem please inform me if you want me to disable the minify cache so you can work on it! 

If you also want to test what the problem is please enter here: [https://shop.revisios.gr/stylo-me-asemi-kormo](https://shop.revisios.gr/stylo-me-asemi-kormo) and select some product options and add it to cart and check what happens.

Thank you in advance for your help!

**Comment by shue249** [comment]
@harrysrevis Thank you so much for your fast response!

We have a hypothesis and wondering if you can help us to test this out? The steps will be as follow:
1. Download an earlier version, v1.0.12 from here https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v1.0.12
2. Uninstall v1.0.14 and install v1.0.12. Do a refresh from modifications 
3. Check on store front to see if the error persists

**Comment by harrysrevis** [comment]
I should thank you guys for your patience! 

I've reinstalled the extension and the problem persists! 
Moreover i've noticed that my chrome add-on for facebook pixel does not find any pixels in my website. I'm using an extension in my shop where i disable right click for copyright reasons. Is it possible for it to be the problem for not locating it?

**Comment by shue249** [comment]
Thank you again, for your time and patience.

So, unfortunately, our hypothesis is wrong. We need to go back to the drawing board and rethink again. We are able to figure out what is wrong but we need to find out where and what is the cause. Will need to ask for your patience while we work this out.

For more transparency, here are our findings. We located the offending line. However, we are still figuring out where is the part where our plugin breaks your website.
![image](https://user-images.githubusercontent.com/11957585/41193135-0a4137aa-6c3b-11e8-8776-9d67d0ecc1cf.png)

May I request if you can uninstall our plugin from your system? We will like to take a look at the original website again.

For locating the pixel, are you using the chrome extension, pixelHelper? I can see your pixel fired on website from my machine.
![image](https://user-images.githubusercontent.com/11957585/41193067-320c589c-6c3a-11e8-937b-67fbba70c2bd.png)

**Comment by harrysrevis** [comment]
Ok i figured it out it was the disable-right-click extension's fault! After i disabled it it could discover the pixel code! 

As for the main problem with the option, i will disable the extension so the website can work properly and as soon as you have a solution please let me know! 

Thank you!

**Comment by shue249** [comment]
This is really interesting. After the Facebook Ads Extension plugin is disabled, that entire chunk of code  "isHovered = ..." is gone! It seems that our plugin is somehow causing extra codes to be injected.

Ok, so this is our fault. We should have saved a cached copy of your website source with the extension installed and we did not. I know this is going to inconvenience you. Can you install back and refresh the extension again (there is no need to go through the setup again as the settings have been saved). We want to then save the copy of your website source code and compare the source codes of your website with and without the extension to identify the breaking points. 

We have already saved in the copy of your website without the extension.

Thank you again in advance.

**Comment by shue249** [comment]
@harrysrevis Pls ignore the earlier request. Turns out we did kept a copy of the website. We have all the information we need to dig deeper. Will get back to you once we have any updates!

**Comment by harrysrevis** [comment]
@shue249 Hello, 
Do you have any further news as for the problem with the extension?

**Comment by shue249** [comment]
@harrysrevis Thanks you again for your feedback and patience with us!

As we just released the latest version for v3 this week, we have started looking into the errors shown on your website due to the plugin. Pls give us some more time and we will get back to you soonest!

**Comment by shue249** [comment]
@harrysrevis We attached here a separate version of our Opencart plugin. Can we invite you to install this plugin to see if this fixes the error on your web store?

[facebook_ads_extension_200a.ocmod.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2108576/facebook_ads_extension_200a.ocmod.zip)

**Comment by harrysrevis** [comment]
Warning: require_once(facebookproducttrait.php): failed to open stream: No such file or directory in /home/revisios/shop.revisios.gr/vqmod/vqcache/vq2-admin_controller_extension_facebookproduct.php on line 8
Fatal error: require_once(): Failed opening required 'facebookproducttrait.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /home/revisios/shop.revisios.gr/vqmod/vqcache/vq2-admin_controller_extension_facebookproduct.php on line 8

Problem! Can't access admin!

**Comment by harrysrevis** [comment]
Any ideas on how to delete it manually? Cause i can't enter my admin panel

**Comment by shue249** [comment]
![image](https://user-images.githubusercontent.com/11957585/41503484-b5691540-718a-11e8-9c49-2bba51a79282.png)

**Comment by shue249** [comment]
![image](https://user-images.githubusercontent.com/11957585/41503492-f0f4323e-718a-11e8-842a-3501c8cd3e27.png)

**Comment by harrysrevis** [comment]
First of all thank you very much for your quick answer!
Secondly, i have in both folder read and write permissions but let me cross-check it with your answer!

**Comment by harrysrevis** [comment]
I have in both folders read + write permissions and the files are there, but the problem persists!

**Comment by harrysrevis** [comment]
Here are the folders' permissions!
![admin-perm](https://user-images.githubusercontent.com/27227418/41503551-1174b416-71e0-11e8-9101-983f10fbb5e4.PNG)
![catalog-perm](https://user-images.githubusercontent.com/27227418/41503553-174f23bc-71e0-11e8-87d0-43f81281bbca.PNG)

**Comment by shue249** [comment]
The permission 755 is only for read+execute. You will need to provide the write permission, otherwise the files will not be able to be saved to your webserver. Can you give the access 775 for both the admin and catalog folders?

**Comment by harrysrevis** [comment]
I did set them to 775 and the problem persists.

**Comment by shue249** [comment]
So, after you set the admin and catalog folders to 775, you uninstalled the plugin and reinstall the plugin again. And you see the error on the OpenCart admin panel. Is that correct?

**Comment by shue249** [comment]
![image](https://user-images.githubusercontent.com/11957585/41503695-25792d3a-718f-11e8-8417-c79ca04867a1.png)

**Comment by harrysrevis** [comment]
Exactly! Yes the files are there: 
![admin-extension](https://user-images.githubusercontent.com/27227418/41503702-44e4a4de-71e3-11e8-8d97-0b75192f77b9.PNG)

**Comment by harrysrevis** [comment]
The error again: 
Warning: require_once(facebookproducttrait.php): failed to open stream: No such file or directory in /home/revisios/shop.revisios.gr/vqmod/vqcache/vq2-admin_controller_extension_facebookproduct.php on line 8
Fatal error: require_once(): Failed opening required 'facebookproducttrait.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /home/revisios/shop.revisios.gr/vqmod/vqcache/vq2-admin_controller_extension_facebookproduct.php on line 8

**Comment by shue249** [comment]
Thanks for the screenshot. I see that the facebook-related files are all permission 644. Can you put all the facebook-related files into permission 775?

The error which you are seeing is mostly due to permissioning error.

**Comment by harrysrevis** [comment]
Sure, wait please! 
Thank you for your patience!

**Comment by harrysrevis** [comment]
Should i apply 775 to subfolders too? Cause after doing these (after setting 775 to the files you mentioned) the problem now is here:

Warning: require_once(facebookproducttrait.php): failed to open stream: No such file or directory in /home/revisios/shop.revisios.gr/vqmod/vqcache/vq2-admin_controller_extension_facebookproduct.php on line 8
Fatal error: require_once(): Failed opening required 'facebookproducttrait.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /home/revisios/shop.revisios.gr/vqmod/vqcache/vq2-admin_controller_extension_facebookproduct.php on line 8

**Comment by shue249** [comment]
Can we try to put 775 to these folders and its child folders:
admin/controller/extension
admin/model/extension
admin/language
admin/view/template
catalog/controller/extension

**Comment by harrysrevis** [comment]
Still the same problem.

**Comment by shue249** [comment]
Thank you for your feedback! We may have found an incompatibility issue with vqmod. We will continue to investigate this.

For now, pls uninstall the v2.0.0 plugin from your webserver.

At the same time, we noticed that you have uninstalled the disabled-right click module. Can you pls install version 1.0.14 of our plugin and we like to see if the error on the console still appear. The reason is because, we suspect the previous error is due to the disabled-right click module. The 1.0.14 version file is here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v1.0.14

**Comment by harrysrevis** [comment]
I've installed it and as i can see the problem in console persists. Do you want me to keep it so you can track something or can i delete it?

**Comment by shue249** [comment]
I see that the disabled-right click module is enabled on your store. Wondering if you can disable that module. This is still with our OpenCart 1.0.14 plugin installed.

**Comment by harrysrevis** [comment]
The right click is disabled after i enable your module. While i disable it everything work fine.

**Comment by shue249** [comment]
Apologies for the delay!

We have a alpha version for v1.0.14. Like to invite you again to give this version a spin to see if it works on your server. Let us know if the error persists.

Thank you once again for spending time with us on troubleshooting this issue. Really appreciate this.
[facebook_ads_extension_114a.ocmod.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2108730/facebook_ads_extension_114a.ocmod.zip)

**Comment by harrysrevis** [comment]
Nuh, still the same! Here's a screenshot of the console error too: 
![pseudo](https://user-images.githubusercontent.com/27227418/41508529-05e0fa32-724f-11e8-930f-1bb09dff0d9f.PNG)

No problem guys, just trying to help you solve a future problem for other users too! So..!

**Comment by harrysrevis** [comment]
Well guys i figured it out! For future usage here's what caused the problem:
I had installed an extension called "Disable Right click" with OCMod installation method but i forgot that i tried to install it with vqmod too in the past. So i checked the VQMod folder and i had the "Disable right click" vqmod file there.
I deleted it and as i see it works like a charm!! You can also check it in case i forgot something! [https://shop.revisios.gr/stylo-gia-othones-aphes](https://shop.revisios.gr/stylo-gia-othones-aphes)

Thank you once again for your quick responses and your dedication in solving the problem! I really appreciate it! 

Have a good day!

**Comment by shue249** [comment]
Thank you for your feedback! This is super helpful for future users. And we are really happy that this helps you.
