### ISSUE TITLE
Installation issue OC 2.1.0.2

### ISSUE THREAD

**Issue by tomeda** [facebookincubator/Facebook-For-OpenCart#60]
I'm  trying to install your plugin. I got installation successful message, than I refresh modifications, and see the menu in admin panel, when I go there I get error "Page not found", I check user permissions but there I see no extension files. Than I go to the server files and see that there is no files added by your extension?!

**Comment by shue249** [comment]
Can you check if you have given the read+write permissions to the server files? We require at least read+write (775) permission for the admin, catalog, system folders when you install the plugin. You should be able to see the new files from our plugin if the correct permissions are given and OpenCart can copy the new files to the server

![image](https://user-images.githubusercontent.com/11957585/48519495-14728780-e8a8-11e8-8a49-91a7cb44ffda.png)

![image](https://user-images.githubusercontent.com/11957585/48519574-569bc900-e8a8-11e8-9c63-5525923ca1b2.png)

**Comment by shue249** [comment]
@tomeda Following up on the issue. Pls check if you have given the right access rights (775) to your OpenCart admin, catalog and system folders. Once the permissions are given, pls try to install the plugin again.

We will be closing out this ticket, but pls feel free to reopen the ticket if you still encounter the problems.
