### ISSUE TITLE
[BUG] Catalog Can't Be Synced A system error is preventing your catalog from syncing. You can still get website visitors and track sales, and we'll notify you when your catalog is ready to sync.

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#600]
Have and issue with FB - Catalog Can't Be Synced
A system error is preventing your catalog from syncing. You can still get website visitors and track sales, and we'll notify you when your catalog is ready to sync. beside that looks like none of the other pages in this module works at all. Please see screnshots below

<img width="1159" alt="Screen Shot 2021-12-01 at 14 06 57" src="https://user-images.githubusercontent.com/50840258/144321967-6312aa7a-115e-45e1-ab60-2a7bf017c418.png">

Platform us opencart 
<img width="1132" alt="Screen Shot 2021-12-01 at 14 07 14" src="https://user-images.githubusercontent.com/50840258/144321980-f1fc8c49-51f9-44de-87c6-42dee0b523e3.png">
<img width="1146" alt="Screen Shot 2021-12-01 at 14 07 09" src="https://user-images.githubusercontent.com/50840258/144321984-7015fbc0-638d-4852-87d0-08a005108dde.png">
<img width="1133" alt="Screen Shot 2021-12-01 at 14 07 04" src="https://user-images.githubusercontent.com/50840258/144321986-223b6f3b-5114-4832-9cdb-de67e2d77b32.png">

**Comment by yao-tx** [comment]
Hi @KonstantinGOT 

From the screenshots you've provided, it seems like you are using Magento but this repository is for OpenCart.

**Comment by KonstantinGOT** [comment]
> Hi @KonstantinGOT
> 
> From the screenshots you've provided, it seems like you are using Magento but this repository is for OpenCart.

Interesting find, I never noticed that before and not sure how to explain that but im using opencart
<img width="1403" alt="Screen Shot 2021-12-01 at 20 39 54" src="https://user-images.githubusercontent.com/50840258/144358890-32b41659-9859-47fc-9a5c-aad33ce50cf0.png">

**Comment by KonstantinGOT** [comment]
@shue249  Please have a look

**Comment by yao-tx** [comment]
Hi @KonstantinGOT 

It seems like you are still using the old version of the Facebook Business Extension plugin for OpenCart and unfortunately, versions 3.1.2 and below of the extension have been deprecated and support for them has ceased.

Do download the latest version from OpenCart marketplace or from the GitHub releases and follow the installation guide in this repository to uninstall the old version and install the latest version.

**Comment by KonstantinGOT** [comment]
> 

Understood! Question we will need to update php for this new pluging ?

**Comment by yao-tx** [comment]
@KonstantinGOT 

Yes, the minimum PHP version requirement is 7.3.
