### ISSUE TITLE
[Feature Request] Skip facebook ads account when connect to Facebook

### ISSUE THREAD

**Issue by huiyang** [facebookincubator/Facebook-For-OpenCart#601]
**FBE plugin version**
4.1.1

**Is your feature request related to a problem? Please describe.**
Cannot connect to Facebook due to Facebook Ads account in bad standing.

**Describe the solution you'd like**
May i skip to connect to Facebook ads account while i just need to sync products to catalogue?

**Screenshot for the issue**
![image](https://user-images.githubusercontent.com/517651/144594102-3a4d7da9-002f-42bc-b49a-437adaf41663.png)

Thanks.

**Comment by yao-tx** [comment]
Hi @huiyang 

Although we've never personally tried it before, you could try manually setting up for catalog feed synchronisation through your Facebook Business Commerce Manager with the extension's catalog feed URL. The following is the format of the feed URL:

For OpenCart 2.0.x to 2.2.x:
https://{your-domain}/index.php?route=module/facebook_business/genFeed

For OpenCart 2.3.x and 3.x and above:
https://{your-domain}/index.php?route=extension/module/facebook_business/genFeed

where {your-domain} is your OpenCart store URL (please do not include the curly brackets). i.e. If your OpenCart store URL is https://www.example.com/, then your catalog feed URL (for OpenCart 2.3.x and 3.x and above) should be https://www.example.com/index.php?route=extension/module/facebook_business/genFeed.

Do test it out first by visiting the URL mentioned above, and check if a .csv file containing your OpenCart Products Catalogue downloads automatically. If the a .csv file downloads automatically and the contents are correct, you should be able to manually use the URL to setup synchronisation of your catalog through the Commerce Manager.

**Comment by huiyang** [comment]
thanks for your reply, it is seem working now.
