### ISSUE TITLE
Facebook Upload via module - issues with descripton 

### ISSUE THREAD

**Issue by KonstantinGOT** [facebookincubator/Facebook-For-OpenCart#603]
Hi everyone

I have an opencart 2.3 and there is a issue with upload of some products the error comes out as description
<img width="1197" alt="Screen Shot 2021-12-12 at 11 32 29" src="https://user-images.githubusercontent.com/50840258/145726762-c262f903-de6e-459d-aaaf-2cbe29915ab2.png">

lets take for example one of the products with this description issue here is the link - https://satorisan.ru/chacrona-fog

I checked the product in admin panel  and i have description there   in the product .
<img width="1162" alt="Screen Shot 2021-12-12 at 11 35 38" src="https://user-images.githubusercontent.com/50840258/145726874-d06e3b1a-0986-4c04-9ec8-e748e54f96d9.png">

I have 128 products in total and all of them are done in same way but for some reason 23 of them gets rejected for the description error that i actually have 
 What can i do about it?

**Comment by yao-tx** [comment]
Hi @KonstantinGOT 

That does seem strange. Do reach out to us via our [helpdesk](https://marketinsg.zendesk.com) for assistance.

**Comment by KonstantinGOT** [comment]
> Hi @KonstantinGOT
> 
> That does seem strange. Do reach out to us via our [helpdesk](https://marketinsg.zendesk.com) for assistance.

sure, thanks
