### ISSUE TITLE
This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

### ISSUE THREAD

**Issue by cartbinder** [facebookincubator/Facebook-For-OpenCart#617]
Without doing any changes. When click manage settings buttton, it takes to a page and it is displayed:

"This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.
![Log in with Facebook](https://user-images.githubusercontent.com/17376201/167283062-ae6231bf-7273-456a-829b-6d5830d4e56f.png)
"

**Comment by yao-tx** [comment]
Hi Pavan,

We're currently experiencing some technical issues with the extension and are in the process of trying to get them resolved. We will update you again when it has been resolved.

In the meantime, we apologise for any inconveniences caused.

**Comment by yao-tx** [comment]
Hi @cartbinder 

The technical issue has been resolved. You should be able to connect to your Facebook Business account now.
