### ISSUE TITLE
Can't uncheck cookie bar

### ISSUE THREAD

**Issue by Erikas013** [facebookincubator/Facebook-For-OpenCart#63]
Hi,

I installed the latest version of extension, but I can't uncheck cookie bar, no button for save

**Comment by shue249** [comment]
Thank you for your feedback. The settings will be auto-saved when you uncheck the option, hence we did not provide the save button.

Can you uncheck the cookie bar option and then check your web store to verify that the cookie bar is no longer present.

**Comment by Erikas013** [comment]
Uncheck not working :) When refresh page it check anyway. Maybe this setting are in mysql and I can do it with it?

**Comment by shue249** [comment]
@Erikas013 Can you do a hard refresh of your browser to remove away the old cached files? If you complete this step and still is unable to save the cookie bar settings, can you share any error messages that appear on the developer panel console log?

![image](https://user-images.githubusercontent.com/11957585/48873903-6af14000-ee2b-11e8-8e0f-ae4cc086218d.png)

**Comment by Erikas013** [comment]
Error: WARNINGS
Products Are Missing From Your Catalogs
Retargeting ads can't run for 1 out of 1 product views on this page, because the products people have viewed are missing from your catalogs.Learn more
Investigate in Catalog Manager

Cookie bar checkbox work now

**Comment by shue249** [comment]
@Erikas013 Thank you for your feedback. Can we ask for you to help us create a new ticket for the catalog warning. Also can you provide us your webstore URL.

We will proceed to close off this ticket on the cookie bar unable to be unchecked.
