### ISSUE TITLE
About installing the updated version

### ISSUE THREAD

**Issue by i3kevin** [facebookincubator/Facebook-For-OpenCart#64]
I am now to update to the newest version to fix the 'freegeoip.net/shutdown' bug which caused google error. 
Do I have to delete the original facebook extension in my admin panel or I will just have to install the newest version once again and it will automatically cover the files?

**Comment by shue249** [comment]
@i3kevin To upgrade the facebook extension plugin, access the modifications, select the plugin and click on Delete icon to remove the old version. Then follow the same installation process to re-install the plugin via zip file and click on the refresh button.

**Comment by shue249** [comment]
I will be closing off this ticket, but feel free to open it if you encounter any problems.
