### ISSUE TITLE
Catalog issue

### ISSUE THREAD

**Issue by Erikas013** [facebookincubator/Facebook-For-OpenCart#67]
Error: WARNINGS
Products Are Missing From Your Catalogs
Retargeting ads can't run for 1 out of 1 product views on this page, because the products people have viewed are missing from your catalogs.Learn more
Investigate in Catalog Manager
site: beyou.lt

**Comment by shue249** [comment]
@Erikas013 Thank you for your feedback. We see that the initial sync of products to FB is not working. There are no products in the catalog.

Can we understand how many products are in your website?

**Comment by shue249** [comment]
@Erikas013 Like to follow up on this. We will like to help you to debug this further. Is there anyway that you can provide to us the error log file from the Facebook Ads Extension?

![image](https://user-images.githubusercontent.com/11957585/49770976-ee62ca80-fd21-11e8-9b05-db8ad1811aed.png)

**Comment by shue249** [comment]
@Erikas013 We will proceed to close out this ticket, but pls feel free to reach to us if you need any further questions
