### ISSUE TITLE
How Change Currency?

### ISSUE THREAD

**Issue by trsistemas** [facebookincubator/Facebook-For-OpenCart#68]
All base prioces are in USD but the frontend th currency is ARS Pesos Argentinos, how can i change to Facebook extension use ARS and not USD?

**Comment by shue249** [comment]
@trsistemas Thank you for your feedback!

Here are the steps to setup the correct currency for Facebook Ads Extension.

![image](https://user-images.githubusercontent.com/11957585/49049453-ff87e380-f219-11e8-9eb3-30d3558146c3.png)

![image](https://user-images.githubusercontent.com/11957585/49049557-6e653c80-f21a-11e8-8c20-61cb33072928.png)

**Comment by shue249** [comment]
We will proceed to close this ticket, but feel free to re-open the ticket again if you need more help.

**Comment by trsistemas** [comment]
Thanks shue249, but this not my issue, my problem is how i configure this extension use the currency i choose, sorry my english...

**Comment by shue249** [comment]
@trsistemas No apologies needed, perhaps I wasnt clear myself too.

There are 2 places where the currency is being used - catalog and pixel.

1. For the catalog, we use the currency selected on your OpenCart settings as the currency for the product prices. (see the screenshot on my earlier post). If you check the products on Facebook catalog, it will reflect the same currency on your OpenCart settings.

2. For the pixel, it depends on the currency selected on the website. We will use the selected currency as the currency in the website.
![image](https://user-images.githubusercontent.com/11957585/49050553-e03f8500-f21e-11e8-9e7b-1d9144664eb5.png)

**Comment by trsistemas** [comment]
Thanks again, i use the same extension and the currency is ARS, for the frontend i disable the other currencies, we use the USD internally because our PESO vs DOLLAR change all time, our cost is in USD (backend) and or sale price is in ARS (frontend).
