### ISSUE TITLE
Cannot install extension with different admin name

### ISSUE THREAD

**Issue by jwestlake** [facebookincubator/Facebook-For-OpenCart#69]
Hi all,

Found this page searching for help with the OC FB extension.  Trying to install on 2.3.0.2 with different admin directory name, but getting nowhere.  Opened the .zip, changed the upload/admin dir to match mine, searched all files for anything with "admin/" and changed it as well, but still cannot install via the Extensions Installer.  After making my changes and re-zipping, I get the error "Directory containing files to be uploaded could not be found."

I tried installing manually by uploading the "upload" dir contents, but this doesn't work either.  When I try to edit the extension in "Modules", I get the error "Page not found".

No errors appearing in error.log file.

Not sure what else to try here.  Does anyone have any other ideas?

Thanks!

**Comment by shue249** [comment]
@jwestlake Thank you for your feedback! As we need the admin folder to make modifications to the core plugin files during the plugin installation, I am afraid just manually uploading the files will not work. Can i suggest the following:

1. Rename the folder on your opencart server back to "admin" name
2. Install our plugin using the original plugin zip file (do not use the one that you re-zip as the rezip file may have a sub level folder https://github.com/facebookincubator/Facebook-For-OpenCart/issues/62)
3. Click on the refresh button on the Modifications module
4. Access Facebook Ads Extension module
5. Click on Get Started to start the installation
6. Rename the admin folder back to the different naming

Let us know if you are encountering any problems in the steps above and which step it fail.

**Comment by jwestlake** [comment]
Hey @shue249,

Thanks for the reply.  I went ahead and made that change, though now I have a problem with the admin language files.  I have an English-US plugin installed where my language directory/code is "en-us", and the plugin is looking for "english".  I tried uploading the files to my "en-us" directory, but it still seems to be hardcoded to "english".  Is there any way I can change this?  Sounds like the two plugins won't work together if one is "en-us" and one is "english"...

Thanks!

Jason

**Comment by jwestlake** [comment]
@shue249 - 

Ok, so I grepped for "english" in all files, changed those to "en-us", then repackaged the .zip as in your link above.  This now installed, but then I was getting errors when accessing the extension panel.

There are problems with the installation of the Facebook Ads Extension.


```
We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders.

<MyStorePath>/system//library
<MyStorePath>/catalog//controller/extension
<MyStorePath>/catalog//view/javascript
<MyStorePath>/catalog//view/theme/css
<MyStorePath>/catalog//view/theme

Please uninstall and reinstall the Facebook Ads Extension after correcting the above 1 step.
```

I manually copied the files from the "upload" in the zip to the server in the appropriate locations and everything finally came up in the module.  I was able to run through the Pixel setup wizard, and looks like everything went through properly there.

However, now I get a "Page not found" error when accessing the Extensions > Modules > Facebook Ads Extension > Edit.  How can I find out what else is missing?

**Comment by shue249** [comment]
@jwestlake Thanks for the feedback. The plugin should be able to support for both english and en-us as we ensure both sets of folders are updated accordingly. Let us double check again on this for future users of the plugin.

After completing the Facebook Ads Extension setup flow (Pixel setup wizard), you should be all set. There is no more further setup required. There is no action required from " Extensions > Modules > Facebook Ads Extension > Edit", hence you are getting the Page not found error.

What is your web URL? When you accessed the website, does pixelhelper show up the pixels? PixelHelper is a chrome extension developed by Facebook to check if the pixels are firing from the website.

**Comment by jwestlake** [comment]
@shue249 -

Oh, well that makes me feel better then. :-)  I saw a message after setting up the module that said something about editing the extension, which is why I went there.  Glad to hear it's not needed!

Our store is https://shop.jwestlake.com.  Just grabbed PixelHelper.  Got a green check, so looks like we're up and running.

Thanks for the replies!  I think we're good to go for now.

**Comment by shue249** [comment]
@jwestlake Thanks for the feedback. Your website looks good. We will proceed to close off the ticket, but feel free to reach out if you have any further questions.
