### ISSUE TITLE
Products Pending Approval being Sync'ed with Facebook Page Store!

### ISSUE THREAD

**Issue by theglobalartisans** [facebookincubator/Facebook-For-OpenCart#7]
Hi - we have successfully installed and setup the facebook ad extension on our store - opencart version 2.1.0.2 and everything works fine except for one thing - we have a multi-vendor vqMOD product extension enabled on our store (rendering us as multi-vendor website) and this extension allows us to hold every submission by individual vendor on our store to be placed in a state called "Pending Approval". this state is not equal to "ENABLED" and hence we were very surprised to see that products in pending approval state are also being posted to facebook page store. 

i think the logic that this extension uses for synchronizing between opencart and facebook page store is that the product is not disbled hence it MUST be enabled and hence synchronize. how do we change this so that only products which are ENABLED get synchronized and the rest are not, whatever their state might be.

**Comment by shue249** [comment]
Thank you for your feedback!

Pls help me to understand this correctly. In your use case, there is a additional 3rd party extension on your store, which allows products to be in an additional state known as "Pending Approval". You want to products which are in "Pending Approval" to be excluded from the Page Shop.

Can I understand what is the name of this 3rd party extension. We need to understand more on the code complexity to assess if we can support for this plugin. Or if we can offer alternative solutions.

**Comment by shue249** [comment]
@theglobalartisans We will be closing out this ticket. Feel free to reach to us if you have further questions.
