### ISSUE TITLE
error if clicked from the product tag link oc. 3.0.2.0

### ISSUE THREAD

**Issue by herrysuhe** [facebookincubator/Facebook-For-OpenCart#70]
i have install on my site (oc 3.0.2.0)
i have one error on search page tag : https://elysianastore.com/search?tag=bajutiduranak

PHP Notice: Undefined index: search in /home/k2285254/public_html/elysianastore.com/catalog/controller/extension/facebookeventparameters.php on line 305

**Comment by shue249** [comment]
@herrysuhe Thank you for the feedback. Let us look into this.

**Comment by shue249** [comment]
@herrysuhe We have released a new version 2.1.3 to address this issue. You can either download from OpenCart or from here https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3.

We will close out the ticket, but feel free to let us know if there's further questions.
