### ISSUE TITLE
Not synchronized product option

### ISSUE THREAD

**Issue by tuananh8127** [facebookincubator/Facebook-For-OpenCart#73]
Hello. My product has optional attributes that are not synchronized with the product on the fanpage.

**Comment by shue249** [comment]
Thank you for your feedback. Can we understand what is your website URL?

**Comment by shue249** [comment]
@tuananh8127 At the moment we are not supporting the optional attributes to the Facebook shop as it is not fully compatible. 

We will close out this ticket, but pls feel free to open up a new ticket if you have any further questios.
