### ISSUE TITLE
Failure - facebook upload not created, sync all products using feed

### ISSUE THREAD

**Issue by Akbarkz** [facebookincubator/Facebook-For-OpenCart#74]
My website has around 30k products. I'm getting error "Failure - facebook upload not created, sync all products using feed" 
Facebook Ads Extension version = 2.1.2
 OpenCart version = 3.0.2.0
 PHP version = 7.1.14

**Comment by Akbarkz** [comment]
Its working great now.
Deleted all cache including mod cache.
Deleted facebook settings from db.
Re-installed two three times and its working fine now.
I think for store with large number of products we need to wait some time for the module to create feed and upload.

**Comment by shue249** [comment]
@Akbarkz Thanks for the feedback! As you mentioned, for large catalogs, the system will need some time to create the feed file.

**Comment by ihos1** [comment]
How long did you wait? We have 17,000 items, we have been waiting for 5 days. But all the same Failure - facebook feed not created, access product module

**Comment by Akbarkz** [comment]
We waited for a night . I worked well but yesterday we tried to re sync
again but no success till now
