### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by fgi2006** [facebookincubator/Facebook-For-OpenCart#77]
My log

MOD: Facebook Ads Extension
CODE: public function index() {
LINE: 22

FILE: admin/controller/common/dashboard.php
CODE: public function index() {
LINE: 25

FILE: admin/view/template/common/dashboard.tpl
CODE: <?php if ($error_install) { ?>
LINE: 20
CODE: return $product_id;
LINE: 917
CODE: public function index() {
LINE: 27
CODE: $this->model_catalog_product->addProduct($this->request->post);
LINE: 64
CODE: $this->model_catalog_product->editProduct($this->request->get['product_id'], $this->request->post);
LINE: 138
CODE: if (isset($this->request->post['selected']) && $this->validateDelete()) {
LINE: 211
CODE: protected function getList() {
LINE: 335
CODE: $url = '';
LINE: 73
LINE: 152
LINE: 233
LINE: 296
LINE: 421
LINE: 608
LINE: 660
LINE: 890
CODE: <?php if ($error_warning) { ?>
LINE: 29
CODE: <?php
LINE: 6
CODE: <?php
LINE: 6

FILE: catalog/controller/api/order.php
CODE: $this->model_checkout_order->addOrderHistory($json['order_id'], $order_status_id);
LINE: 361
CODE: $this->model_checkout_order->editOrder($order_id, $order_data);
LINE: 699
CODE: $this->model_checkout_order->addOrderHistory($order_id, $order_status_id);
LINE: 717
CODE: class ModelCheckoutOrder extends Model
LINE: 8
CODE: public function index()
LINE: 18

FILE: catalog/view/theme/default/template/common/header.tpl
CODE: </head>
LINE: 124

FILE: catalog/view/theme/oct_luxury/template/common/header.tpl
CODE: </head>
LINE: 799

FILE: catalog/view/theme/default/template/product/product.tpl
CODE: <?php echo $footer; ?>
LINE: 605

FILE: catalog/view/theme/oct_luxury/template/product/product.tpl
CODE: <?php echo $footer; ?>
LINE: 1265
CODE: public function index()
LINE: 12

FILE: admin/language/en-gb/common/dashboard.php
CODE: <?php
LINE: 6

FILE: admin/language/ru-ru/common/dashboard.php
CODE: <?php
LINE: 6

FILE: system/config/catalog.php
CODE: $_['action_event'] = array(
LINE: 62

FILE: catalog/controller/common/maintenance.php
CODE: public function index() {
LINE: 20

**Comment by adisius** [comment]
Same here, when trying to continue install and configuration, the admin page says "Page not found". Any ideas?

**Comment by shue249** [comment]
@fgi2006 , @adisius Thank you for your feedback. To setup the Facebook Ads Extension, pls follow the video link here - https://drive.google.com/open?id=1JPXQ0mS1pGk2Bat9RV02vYNdbRfCLP9r

I believe you are getting the Page not found error when you click on the Edit button on the module page. There is no need to do this.

We will be closing out this ticket, but pls feel free to open up a new ticket if you still encounter any problems.
