### ISSUE TITLE
Problem with Facebook Ads Extension

### ISSUE THREAD

**Issue by ssii-bur** [facebookincubator/Facebook-For-OpenCart#79]
Hi, we have a problem with the instalation of this extension.

![boceto](https://user-images.githubusercontent.com/46023038/50282142-17860800-0452-11e9-977f-b1c203322e6b.jpg)

What is the error?

Best regards

**Comment by shue249** [comment]
@ssii-bur Thank you for your feedback. We need to copy some new files to your server, but your server folder does not have the write access permission, hence we are unable to do this. Can you give the write access permission (775) to the admin, catalog and system folders on your OpenCart server. Pls see this link for more information https://github.com/facebookincubator/Facebook-For-OpenCart/issues/60

**Comment by shue249** [comment]
@ssii-bur We hope the solution helped you. We will be closing out the ticket, but pls feel free to create a new ticket if you have any further questions.
