### ISSUE TITLE
Error Log says..."Undefined index: product_id in  .../catalog/controller/extension/facebookproduct.php on line 28

### ISSUE THREAD

**Issue by HunKiat** [facebookincubator/Facebook-For-OpenCart#80]
2018-12-22 16:21:30 - PHP Notice:  Undefined index: product_id in /opt/bitnami/apps/opencart/htdocs/catalog/controller/extension/facebookproduct.php on line 28

This lines so often in the Maintainance Error Logs. I don't think it is syncing well with FB Pixel. 
What can I do?

**Comment by shue249** [comment]
@HunKiat Thank you for your feedback. Can we know what is your store website URL?

**Comment by HunKiat** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} https://www.bumwear.com                                                                                                                                                                        Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: 29 December 2018 15:54To: Facebook-For-OpenCart@noreply.github.comReply to: reply@reply.github.comCc: hunkiat@gmail.com; mention@noreply.github.comSubject: Re: [facebookincubator/Facebook-For-OpenCart] Error Log says..."Undefined index: product_id in .../catalog/controller/extension/facebookproduct.php on line 28 (#80)  @HunKiat Thank you for your feedback. Can we know what is your store website URL?

**Comment by shue249** [comment]
@HunKiat Thank you for your feedback. We found there is an issue of the AddToCart event not firing properly from the product details page, due to the error in the log. 

We will look into this and update you soonest when we have the fix.

**Comment by shue249** [comment]
@HunKiat 
We have released a latest version of the plugin, v2.1.4 and can be downloaded from OpenCart marketplace or our github. The new version will resolve the issue with "Undefined index". You can verify this by going to your product details page and adding products to cart. You should be able to see the AddToCart pixel fired.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.4

We will close out this ticket for now, but pls do reach to us if you still have any further questions or issues.
