### ISSUE TITLE
Purchase and InitiateCheckout pixel events not fired 

### ISSUE THREAD

**Issue by shue249** [facebookincubator/Facebook-For-OpenCart#82]
Posting on behalf of papke88

@shue249 Just tried updated extension, looks like it works fine, just cant track the pixel on success page, the pixel helper do not show it. Can you check it?

Success page is here
cr7shop.lt/atsiskaitymas-sekmingas

also cant see the pixel "checkout initianed"

**Comment by papke88** [comment]
Hello @shue249 , any news omn this issue?

**Comment by shue249** [comment]
@papke88 Apologies for the late reply. Can we understand if you are using any 3rd party checkout modules? Our pixel event for InitiateCheckout and Purchase is supporting the default OpenCart checkout module.

**Comment by papke88** [comment]
We are using only default ones!

Regards,
Rokas V.

**Comment by shue249** [comment]
@papke88 I see that your checkout and thank you URL is different from the OpenCart default ones. In the default URL, it will follow something like "index.php?route=checkout/checkout".

Are you using any SEO mapping to change the checkout and payment URL on your website?

![image](https://user-images.githubusercontent.com/11957585/50722145-6b0c7d00-1105-11e9-94a7-42ea1ca1d0d7.png)

**Comment by papke88** [comment]
Yes of course, we use seo tool for friendly urls. Thats very important and most of well made sites use only clean seo urls.. 

Regards,
Rokas V.

**Comment by papke88** [comment]
Hello @shue249, can i get a fix for this problem?

**Comment by shue249** [comment]
@papke88 We will look into this. Can I understand how do you use the seo tool to setup the friendly URLs, so I am not familiar with this SEO tool.

**Comment by papke88** [comment]
We use this extension:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=9486&filter_search=Complete%20SEO%20Package <https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=9486&filter_search=Complete%20SEO%20Package>

There you can check demo. (go to seo editor > param url)




Regars,
Rokas V.

**Comment by papke88** [comment]
hello @shue249 , any news on this issue?

**Comment by shue249** [comment]
@papke88 Apologies for the late reply. As it is a 3rd party extension, we may need more time to figure how best to support this feature.

In the meantime, you may want to try to make some changes on our plugin code to be able to send in the events. However, that will require you to have access to development skills. Will you be open to that?

**Comment by papke88** [comment]
Yes sure write me in which files and what to change, thanks

Regards,
Rokas V.

**Comment by papke88** [comment]
@shue249 i am waiting for your directions, thanks!

**Comment by shue249** [comment]
@papke88 Can you try putting in the below code lines to this file at line 188 on your server.
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L188

Code lines to be added:

    $uri = $_SERVER['REQUEST_URI'];
    if (strcmp($uri, '/atsiskaitymas') == 0) {
      $facebook_pixel_event_params_fae = $this->getPurchaseEventParameters();
    }
    if (strcmp($uri, '/atsiskaitymas-sekmingas') == 0) {
      $facebook_pixel_event_params_fae =
          $this->getInitiateCheckoutEventParameters();
    }

After adding the changes, you can try to make  a mock purchase and verify if the InitiateCheckout and Purchase events are successfully fired on your website using the PixelHelper.

**Comment by papke88** [comment]
@shue249 hello, added the code using your directions, but pixels are not fired... you  can check cr7shop.lt/atsiskaitymas-sekmingas

**Comment by shue249** [comment]
@papke88 Apologies for the delay. We are still checking on this, pls do give us more time and will update you soonest.

**Comment by papke88** [comment]
@shue249 ok thanks, hope to get the solution soon, we cant advertise without pixels on those pages

**Comment by papke88** [comment]
@shue249 hello, any news on this issue?

**Comment by shue249** [comment]
@papke88 Thank you for the patience and apologies for the delay. 

We have some initial findings and we want to cross-check with your configuration setup to verify if the findings tally. We like to understand more on how you do the configuration on the SEO editor. Will you be able to share screenshots of your SEO configuration. Please remove away any sensitive information from the screenshot.

In particular, we are looking for the below sample examples for the absolute URL and common page URL. Apart from these 2 settings, are you using any other settings and can you share these settings with us?
![image](https://user-images.githubusercontent.com/11957585/52158874-c0718500-26d7-11e9-8cd1-4aee751b470c.png)
![image](https://user-images.githubusercontent.com/11957585/52158895-09c1d480-26d8-11e9-8736-5e9b098b0f84.png)

**Comment by papke88** [comment]
Hello @shue249 , here are the screen shots of common page url settings for both LT and US language on the site. Do you need anything else?
<img width="1180" alt="screen shot 2019-02-02 at 10 37 36" src="https://user-images.githubusercontent.com/44572066/52162040-b733e880-26d6-11e9-89ae-ddd7a5b29d34.png">
<img width="1059" alt="screen shot 2019-02-02 at 10 37 18" src="https://user-images.githubusercontent.com/44572066/52162041-b7cc7f00-26d6-11e9-8873-3ce6595e80a2.png">

**Comment by papke88** [comment]
all other settings is default ones, nothing special there that could effect your module i think... the main thing that affects your module i think is friendly urls...

**Comment by papke88** [comment]
Thank you for your anwers. Interesting, i guess se could switch to absolute but can you explain the difference between absolute and common urls? Does it make difference to SEO?

Regards,
Rokas V.

**Comment by shue249** [comment]
@papke88 As we are not the developers for the SEO editor plugin, we are not in the best position to be able to explain the differences between the absolute and common URLs. Perhaps you may want to check in with the developers to understand the differences. Off the hand from their plugin site, it offers a very high level explanation. 
![image](https://user-images.githubusercontent.com/11957585/52171582-29213600-279a-11e9-9c64-03c60fe12d46.png)

To the best of my understanding, both absolute and common urls should work in the same way for your use case. However, it may be good to double confirm with the developers to be sure.

From SEO side, I will say it does not matter to them. For SEOs, only the url string matters. They do not care how the implementation code looks like, ie be it common url or absolute url or some other implementation methods..

**Comment by shue249** [comment]
@papke88 
We have released a latest version of the plugin, v2.1.4 and can be downloaded from OpenCart marketplace or our github. The new version will resolve the issue with SEO URL.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.4

We will close out this ticket for now, but pls do reach to us if you still have any further questions or issues.

**Comment by papke88** [comment]
Thanks!

Regards,
Rokas V.

**Comment by garbinmarcelo** [comment]
Hi, I have version 3.0.3.1 (Brasil 1.2.4), with this issue of not registering the checkout and purchase part in the Facebook pixel. Installing this Facebook extension will solve it? Any suggestion? Thanks

**Comment by yao-tx** [comment]
Hi @garbinmarcelo 

Facebook Business Extension plugin for OpenCart versions 3.1.2 and below has been deprecated and support will not be provided for those versions. That being said, if you are only having issues with Checkout and Purchase Pixel Events, it is usually caused by custom checkout extensions causing the FB plugin to be unable to register the Checkout and Purchase Events.

Adjustments to the extension will have to be made to accommodate custom checkout extensions.
