### ISSUE TITLE
Messenger chat language

### ISSUE THREAD

**Issue by magixrys** [facebookincubator/Facebook-For-OpenCart#83]
Hello, I have activated facebook chat - messenger and I want to translate "Hi! How can we help you? ....." in my own language. Which file should I edit? I cannot find it.

**Comment by shue249** [comment]
@magixrys We have released a latest version 2.1.5 which provides you the feature to customise the Messenger chat plugin on the locale, welcome greeting message and the theme colour. You can view the setup on this video guide - https://drive.google.com/open?id=1XubpAUFYw6m7lB9A8RqrdOPq3IjEQvIq

You can download the latest plugin from OpenCart marketplace or our github.
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.5

We will be closing out this issue. Feel free to reach to us if you have any further questions.
