### ISSUE TITLE
reopen #33

### ISSUE THREAD

**Issue by reginamor** [facebookincubator/Facebook-For-OpenCart#85]
i still having the problem of the topic #33 and i can't reopen the issue.
Thank you

**Comment by shue249** [comment]
@reginamor Thank you for the feedback and apologies for missing out on your previous comment. When you download the latest plugin from our github or OpenCart, is it as a zip file? If not, did you re-zip the file yourself? 

If you have to re-zip the file, most likely the zip procedure is incorrect, resulting in a sub-folder inside the zip file. Can you take a look at this thread if the solution works for you https://github.com/facebookincubator/Facebook-For-OpenCart/issues/62

**Comment by shue249** [comment]
@reginamor I will close off this ticket, but pls feel free to reach out to us if you are still encountering any problems.
