### ISSUE TITLE
Updating Extension Issue

### ISSUE THREAD

**Issue by ryanstacey** [facebookincubator/Facebook-For-OpenCart#86]
I'm having trouble figuring out how to update the extension to the latest version. There no uninstall feature so how do I update it?

**Comment by shue249** [comment]
@ryanstacey Thank you for the feedback. To uninstall the previous version of the plugin, you need to delete the current version. And then re-install the new version of the plugin.

![image](https://user-images.githubusercontent.com/11957585/50719886-f40fbe00-10dd-11e9-9d88-19ff446143c9.png)

We will proceed to close this ticket, pls feel free to create a new ticket if you have any further questions.
