### ISSUE TITLE
reopen #26

### ISSUE THREAD

**Issue by slaventiy92** [facebookincubator/Facebook-For-OpenCart#88]
HI @shue249 I installed the latest version of the module, see that created the feed file on the hosting (175607 products, 421 MB of csv filesize), but the products were not uploaded to facebook. I attach a log file: _tehnobox.com.ua/facebook_ads_extension_log.zip

**Comment by slaventiy92** [comment]
And in error.log often repeats this error: 
`PHP Notice:  Undefined index: filter_category_id in /home/thnbx/public_html/catalog/controller/extension/facebookeventparameters.php on line 397`

**Comment by shue249** [comment]
@slaventiy92 Apologies for the late reply. Based on my initial assessment, I believe your server hit a timeout when generating the initial product catalog feed file, and probably the feed file you are seeing on your server contains only partial of all the products. Where can I download a copy of your log file for me to better understand the problem?

**Comment by slaventiy92** [comment]
@shue249 [tehnobox_error_logs.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2780829/tehnobox_error_logs.zip)

**Comment by shue249** [comment]
@slaventiy92 I looked at the file. Our plugin was attempting to create the feed file for 178892 products. From your feedback on the feed file generated, there are 175607 products which means the database is unable to handle the product load for the last 3k products before crashing.

I see from https://github.com/facebookincubator/Facebook-For-OpenCart/issues/90 that you have managed to upload a set of products to Facebook. Did you do anything to reduce the number of products? 

I can suggest for you to look at changing the products no longer in use to Disabled as our plugin will disregard all disabled products and they will not be synced to Facebook. This will help to reduce the number of products for your server to generate and reduce the chance of crash.

![image](https://user-images.githubusercontent.com/11957585/51562893-dc01b200-1ec5-11e9-982c-0e034b49e648.png)

**Comment by shue249** [comment]
@slaventiy92  We have released a latest version 2.1.5 which fixes the error of "Undefined index: filter_category_id"

You can download the latest plugin from OpenCart marketplace or our github.
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.5

We also like to circle back on the catalog sync. Are you able to successfully sync the initial product catalog to Facebook after disabling some of the unused products?

**Comment by shue249** [comment]
Closing out this ticket. Feel free to reach to us if you have further questions.
