### ISSUE TITLE
Manual resync crashes webserver

### ISSUE THREAD

**Issue by maxdmtrv** [facebookincubator/Facebook-For-OpenCart#89]
I'm running Opencart on a quad core VPS (4 х 2600 MHz) and 8GB RAM.

Resync of 150 products takes about 8 mins. During this time my website becomes unresponsive and later nginx crashes with error 504.

Facebook Ads Extension version = 2.1.3
OpenCart version = 2.3.0.2.3
PHP version = 7.1.17

**Comment by shue249** [comment]
Thank you for the feedback. We are aware of this limitation and is looking at ways to improve the experience. We will share with you any updates soonest.

**Comment by G0dzzilla** [comment]
I have the same problem unresponsive during sync. 
Resync of 8000 products takes forever.

Follow my setup:
Facebook Ads Extension version = 2.1.8
Duo core VPS and 8GB RAM.
OpenCart version = 2.1.0.2
PHP version = 7.0.33

**Comment by shue249** [comment]
@G0dzzilla There are 2 things you can check.
1. Download the log file of Facebook Ads Extension plugin. From the log file you may be able to trace what happened during the initial catalog sync

2. To help mitigate large catalogs, we queries the database products in batches of 100. There could be a chance of Mysql database out of memory. You can take a look at this section to see if it helps - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog.

**Comment by shue249** [comment]
@maxdmtrv , @G0dzzilla We have released a new version of the plugin - 2.1.10. We greatly improved the performance of the Resync products feature in Facebook Business Extension module. You can use this function to re-sync your products from Opencart to facebook catalog. The catalog will remain the same.

We will be closing out the ticket, feel free to reach to us if you have any further questions.
