### ISSUE TITLE
Permission Denied! for opencart 2.3.0.2

### ISSUE THREAD

**Issue by Khnaz35** [facebookincubator/Facebook-For-OpenCart#92]
Hi i have download the extension from Facebook and install it. After a successful installation i'm getting the error for "Permission Denied!
 Permission Denied!
You do not have permission to access this page, please refer to your system administrator."
The funniest thing is that i'm login as **Top Administrator**  when i went to add the user group there are not files like facebook/facebookextensions to grant access or modify , i try to given access & modification  to all install modules but not use full.
![image](https://user-images.githubusercontent.com/43812103/52163256-88d7fc80-271a-11e9-8f76-9c7369c1c7c8.png)

![image](https://user-images.githubusercontent.com/43812103/52163273-c046a900-271a-11e9-8395-5da3ef8c7f4d.png)

**Comment by shue249** [comment]
@Khnaz35 The permission setting is extension/facebookadsextension. Can you try to see if this setting is available on your server. (See below screenshot)

![image](https://user-images.githubusercontent.com/11957585/52165348-b2088500-273a-11e9-86e5-39857394cf2d.png)

Our plugin will automatically give the Access and Modify permission to the "Administrator" user group when the plugin is installed. This "Administrator" user group is the default one provided by OpenCart. In your case, as the name of the administrator is "Top Administrator" instead, this user group does not get the permission automatically.

Let us know if this works for you.

**Comment by Khnaz35** [comment]
@shue249 Thanks for your response i have look into setting but their is nothing like that as in your provided picture. 
See here from my Dashboard 
![facebook_ads_extension ocmod](https://user-images.githubusercontent.com/43812103/52174809-86d27400-27d4-11e9-9555-54c0a69650eb.png)

 i have downloaded the extension directly from Facebook. 
is it there are some file are missing in it? i had attached the zip for your reference.
[facebook_ads_extension.ocmod.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2825337/facebook_ads_extension.ocmod.zip)

Regards 
Ali

**Comment by shue249** [comment]
@Khnaz35 Thank you for your feedback. We have a newer version, v2.1.3, of the plugin and we are now in the progress of updating the plugin on Facebook. In the meantime, can you get this version here https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3. You need to remove away the current plugin version and install in the newer version.

**Comment by Khnaz35** [comment]
Hi @shue249 I followed your instructions and uninstall the previous version and installed V2.1.3, but unfortunately same problem still exist.  
![image](https://user-images.githubusercontent.com/43812103/52391022-46297200-2ad6-11e9-9e52-160e887f8e46.png)

![image](https://user-images.githubusercontent.com/43812103/52391042-57727e80-2ad6-11e9-8ce0-25c74c6abd9f.png)

This is the latest v 2.1.3 i downloaded from link which you refer 
[facebook_ads_extension.ocmod.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2839344/facebook_ads_extension.ocmod.zip)

**Comment by shue249** [comment]
@Khnaz35 Can you check if the admin, catalog and system folders on your OpenCart server have read+write folder permission recursively. We need to copy in some new files to your servers and if you are unable to see the permissions for the Facebook Ads Extension module on your server, it could be that the files are not copied over. After you give read+write permissions, uninstall the plugin and re-install back again.

You can refer to this post for more details. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/60

Specifically, you need to ensure that you can see these files on your server after the plugin is re-installed.

![image](https://user-images.githubusercontent.com/11957585/52489668-c8608600-2bfd-11e9-8d12-95864b39821b.png)

**Comment by shue249** [comment]
@Khnaz35 We will be closing out on this issue, but pls feel free to reach out to us if you have any further questions.

**Comment by Khnaz35** [comment]
Thanks for trying your best to resolve the issue anyway it doesn't help.  I have uploaded it via FTP and it's work
