### ISSUE TITLE
Pulling Wrong Product Price!

### ISSUE THREAD

**Issue by ryanstacey** [facebookincubator/Facebook-For-OpenCart#93]
I have special prices on most of my products within OpenCart. But when the extension uploads the products to Facebook catalog it takes the original price and not the special discounted price which is obviously what I want.
OC:
<img width="343" alt="screenshot 2019-02-02 at 8 17 16 pm" src="https://user-images.githubusercontent.com/44474887/52168885-bd05ea00-2727-11e9-8812-d302b3d0b27f.png">
FB:
<img width="190" alt="screenshot 2019-02-02 at 8 16 58 pm" src="https://user-images.githubusercontent.com/44474887/52168887-c1ca9e00-2727-11e9-8d8a-98b9a7e53fa2.png">

**Comment by burkoyuriy** [comment]
I have the same problem.
Version opencart 2.3.0.2
Version module 2.1.13

**Comment by burkoyuriy** [comment]
I got into the problem. My problem is not a problem. It turns out that the module promotional prices works well, but the discount does not count. This is definitely the right decision.

**Comment by shue249** [comment]
@burkoyuriy Thank you for the feedback. I am understanding that you have understand how our plugin sync the OpenCart product discounts to Facebook and you are able to resolve this problem.

Feel free to create a new ticket if you have any further questions.

**Comment by shue249** [comment]
@ryanstacey  We will be closing out this ticket. Feel free to reach to us if you have any further questions.
