### ISSUE TITLE
Cannot find page in Opencart v3.0.2.0

### ISSUE THREAD

**Issue by oguzhansari** [facebookincubator/Facebook-For-OpenCart#94]
Hi,
I use Opencart v3.0.2.0.
I'm entering the application page.
I get the page not found error.
![notfound](https://user-images.githubusercontent.com/13555457/52169346-9788d880-2747-11e9-926f-ce1fa91d91e2.JPG)

**Comment by shue249** [comment]
@oguzhansari Thank you for your feedback. Can you look at this post to see if the solution helps you. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/77

**Comment by shue249** [comment]
@oguzhansari Can you look at this video link to see if it helps you. 

https://drive.google.com/open?id=1V4Nu8nlmHX5ppKqsjcR-xR05Rozb7MKN
https://drive.google.com/open?id=1-ljN_pNcyZBbN2LoXtxwaJEy0dfnxAum
https://drive.google.com/open?id=1JPXQ0mS1pGk2Bat9RV02vYNdbRfCLP9r

There should be a Facebook Ads Extension menu on the left hand side

**Comment by shue249** [comment]
@oguzhansari We will be closing out this ticket. Feel free to reach to us if you have any further questions.
