### ISSUE TITLE
FACEBOOK crashing CP Panel

### ISSUE THREAD

**Issue by xrist0s29** [facebookincubator/Facebook-For-OpenCart#95]
Hello everyone. i am trying to install the facebook extention but whenever i do it my cp panel crashes.

It shows a "no page found" error when i click on my cp panel and the facebook plugin.

Here is my error log:

2019-02-02 20:55:59 - MOD: Modification Default
FILE: system/engine/action.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 39
FILE: system/engine/loader.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 20
LINE: 59
LINE: 80
LINE: 99
FILE: system/library/config.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 23
FILE: system/library/language.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 25
LINE: 31

Any tips?

**Comment by shue249** [comment]
@xrist0s29 Thank you for your feedback. We like to suggest 3 things.

1. We require the admin, catalog and system folders on your OpenCart to have write+read permission as we need to copy some files to your server. Pls refer to this post for more details - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/60

2. We want to share with you these installation videos. We like to suggest for you to follow the steps in these videos.
a. Step by step video guide for installing the Facebook Ads Extension https://drive.google.com/open?id=1V4Nu8nlmHX5ppKqsjcR-xR05Rozb7MKN
b. Additional installation step required for OpenCart v3.x https://drive.google.com/open?id=1-ljN_pNcyZBbN2LoXtxwaJEy0dfnxAum
c. Step by step video guide for setting up the Facebook Ads Extension https://drive.google.com/open?id=1JPXQ0mS1pGk2Bat9RV02vYNdbRfCLP9r
d. Step by step video guide for setting up permissions for Facebook Ads Extension https://drive.google.com/open?id=1JUwZPlUNIhFO7I8U0slbJSQNjyu4al_J

3. Can you share a screenshot of the cp panel which crashes?

**Comment by shue249** [comment]
@xrist0s29 We will be closing out this ticket. Feel free to reach to us again if you have any further questions.
