### ISSUE TITLE
GeoIp https problem

### ISSUE THREAD

**Issue by veliel** [facebookincubator/Facebook-For-OpenCart#97]
I am having the problem in the image bellow after installation of your extension
http://prntscr.com/mgle51

Opencart 2.3.0.2

**Comment by veliel** [comment]
Yes indeed I had an older version. I have downloaded my version from opencart store. That means your opencart store version dosn't include this fix please update it!

**Comment by shue249** [comment]
@veliel Thank you for your feedback.

The OpenCart store version is using this download URL - https://www.opencart.com/index.php?route=marketplace/download&extension_id=32336. We have checked and the version is the latest 2.1.3.

Earlier, we found that we have yet to update the version of the plugin on Facebook, resulting in Facebook still having a older version. This could be the reason why you are seeing the older version. We have fixed the problem.
