### ISSUE TITLE
Missing cookie bar DB field

### ISSUE THREAD

**Issue by andrejuseu** [facebookincubator/Facebook-For-OpenCart#98]
Hi,

So, my client was having problems with cookie bar (as all EU e-shops must have GDPR notice) then having his own notice.

The **Show cookie bar on store website** checkbox doesn't work, because there's no row in **oc_setting** are created as **facebook_enable_cookie_bar**.

If you encounter this problem, you need to run this SQL:

**ONLY IF YOU KNOW WHAT THIS CODE DOES!!!**

```sql
INSERT INTO `oc_setting`(`store_id`, `code`, `key`, `value`, `serialized`) VALUES (0, 'facebook','facebook_enable_cookie_bar', 'false', 0);
```

**Comment by shue249** [comment]
@andrejuseu Can we understand what is the version of the Facebook Ads Extension plugin and what is the version of your OpenCart.

**Comment by andrejuseu** [comment]
@shue249 

Opencart - 3.0.2.0
Facebook Ads Extension plugin - 2.1.3 (latest)

**Comment by shue249** [comment]
@andrejuseu Thank you for the feedback. Few suggestions.

1. Did you install a earlier version of the plugin and then update to the latest version? If so, can I suggest for your to look into this post. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/63

2. Does the mysql user has rights to insert/edit the data in the oc_setting table? Our plugin relies on the same mysql user used by the OpenCart backend to make changes to the database table. If the oc_setting table does not have the row data, it could mean that the mysql user is lacking the correct permissions.

3. If all else fails, you can rely on the SQL insert statement that you have provided in the first post. But you may want to change the 'false' to 'true' to show up the cookie bar.

INSERT INTO `oc_setting`(`store_id`, `code`, `key`, `value`, `serialized`) VALUES (0, 'facebook','facebook_enable_cookie_bar', '**true**', 0);

**Comment by andrejuseu** [comment]
@shue249 thank you for suggestions, but:

1. It's fresh 2.1.3 installation of extension.
2. If user didn't have MySQL rights - OC wouldn't work at all, so this is not a case.
3. By default cookie setting is set to TRUE, so EU shops will need a FALSE.

All settings that are needed for extension to work should be in install.php by default.

I didn't investigate more into this, but I think JS part is not sending first update, and it don't create needed setting. I you want, I can make full investigation in this.

**Comment by shue249** [comment]
@andrejuseu Thank you for the feedback. I want to share these suggestions, pls let me know if it makes sense.
1. Your client needs to disable our plugin's cookie bar as they have their own cookie bar in place.

2. Your client tried to uncheck the option to disable cookie bar but our plugin's cookie bar is still shown on the client's webstore.

If the above are correct, we may need more help/details from you to troubleshoot this further.
1. By default, we do not create the facebook_enable_cookie_bar setting in the database initially. If this setting is not present in the database, we will enable the cookie bar of our plugin.

2. When user disable the cookie bar on the Facebook Ads Extension, we will then insert in the setting via JS. Will you be able to help us verify the below steps for your client?
`select * from oc_setting where `code` = 'facebook' and `key` = 'facebook_enable_cookie_bar';`
![image](https://user-images.githubusercontent.com/11957585/52610206-27065800-2ebb-11e9-9c27-0c8d7c9dda2e.png)
![image](https://user-images.githubusercontent.com/11957585/52610187-0fc76a80-2ebb-11e9-8aa7-1eeac59ea900.png)
![image](https://user-images.githubusercontent.com/11957585/52610166-f3c3c900-2eba-11e9-9a34-d4fd3c2568a3.png)
![image](https://user-images.githubusercontent.com/11957585/52610217-3d141880-2ebb-11e9-97ed-f21bae02d45f.png)

**Comment by shue249** [comment]
@andrejuseu Like to follow up with you if you have any further feedback.

**Comment by shue249** [comment]
@andrejuseu we will be closing out this ticket, feel free to reach to us if you have any further questions.
