### ISSUE TITLE
Update for latest OpenCart version v3.0.3.1

### ISSUE THREAD

**Issue by saamani** [facebookincubator/Facebook-For-OpenCart#99]
Hi, will it support latest version 3.0.3.1 
I want to install it please suggest me kindly...
Or please update it kindly...

**Comment by shue249** [comment]
@saamani Thank you for the feedback. Let us look into this and get back to you soonest.

**Comment by shue249** [comment]
@saamani We have released a latest version 2.1.5 which we verified that our plugin is compatible with Opencart v3.0.3.1.

You can download the latest plugin from OpenCart marketplace or our github.
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.5

We will be closing out this issue. Feel free to reach to us if you have any further questions.
